### ISSUE TITLE
Support GitHub Windows Runners

### ISSUE THREAD

**Issue by anton-yurchenko** [infracost/infracost#101]
[GitHub documentation:](https://docs.github.com/en/actions/creating-actions/about-actions#docker-container-actions)
> Docker container actions can only execute on runners with a Linux operating system

There should be either two actions (windows/linux) or a JavaScript executed binary which will allow an action to be run from all support GitHub Runners.

**Comment by alikhajeh1** [comment]
We've not had issues with linux runners so going to close this issue
