### ISSUE TITLE
Post GitHub PR comments with Atlantis integration

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1020]
Our [current Atlantis integration](https://github.com/infracost/atlantis-demo/pull/6#issuecomment-795889174) outputs the CLI diff text at the end of the Atlantis output. That means it's tucked-away at the bottom of the expandable "Show Output" section, which is easy to miss.

It would be much better if we can post a PR comment like we do for GitHub Actions. Atlantis already has [GH tokens/configs](https://www.runatlantis.io/docs/server-configuration.html#flags) so ideally we could re-use those, but I'm not sure if we can access those. If not, I think we can ask users to set env variables instead.

This issue is for us to figure-out how we can do this for GitHub, we can create issues to work on GitLab et al after we ship this.

### Note for community
Please 👍 if you'd like to upvote this or receive updates.

**Comment by hassankhosseini** [comment]
User request: +1 on GitLab too.

**Comment by aliscott** [comment]
I've added an example of how you can post a separate Infracost comment as part of the Atlantis workflow with [compost](https://github.com/infracost/compost) here: https://github.com/infracost/infracost-atlantis/tree/master/examples.

**Comment by aliscott** [comment]
@alikhajeh1 should we close this issue in favor of the discussion here? https://github.com/infracost/infracost/discussions/1179

**Comment by alikhajeh1** [comment]
Yep - good catch.
