### ISSUE TITLE
Add support for AWS Transfer Family

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#1030]
Adding support for AWS Transfer family in both the product and also into the usage file.

Terraform resources:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_ssh_key
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_user
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_access

Pricing: https://aws.amazon.com/aws-transfer-family/pricing/

**Note for community:**
Please 👍 if you'd like to upvote this or receive updates.
See our contributing guide if you'd like to help with this issue!

**Comment by vdmgolub** [comment]
This has been merged to master and will go live with the next release.

**Comment by tim775** [comment]
@bourbonfgiles @robh007 @PatMyron 0.9.13 is released.  Thanks @vdmgolub!
