### ISSUE TITLE
Add support for AWS Cloudtrail.

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#1038]
Add support for AWS Cloudtrail in both the product and also into the usage file.

https://aws.amazon.com/cloudtrail/pricing/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

### `aws_cloudtrail`

Cost components:
* `Management events (additional copies)` - unit is `events`. Monthly quantity is defined in usage parameter `monthly_additional_management_events`. This cost component is only shown if the resource has an event selector with `include_management_events = true` or the usage parameter is set.
* `Data events` - unit is `events`. Monthly quantity is defined in usage parameter `monthly_data_events`. 
* `Insight events` - unit is `events`. Monthly quantity is defined in usage parameter `monthly_insight_events`. This cost component is only shown if an `insight_selector` is specified on the resource.

There are no free resources for CloudTrail.

**Comment by aliscott** [comment]
I've updated the description of this issue with the details discussed.

**Comment by vdmgolub** [comment]
@robh007 this is live in v0.9.16.
