### ISSUE TITLE
Skip 0-quantity lines in `infracost output`

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1047]
This is a follow-up from https://github.com/infracost/infracost/issues/929#issuecomment-934338954

### v0.9.10 behavior
Repro steps for v0.9.10:
```
update examples/terraform/infracost-usage.yml to set the lambda usage values to 0

infracost breakdown --path examples/terraform --usage-file examples/terraform/infracost-usage.yml --format json > out1.json

infracost output --path out1.json --format table # Notice how 0-cost lines are shown for Lambda, same happens in HTML format.
```

### Desired behavior

The `breakdown` command will not show 0-quantity lines in HTML and table formats, the `infracost output --format table|html` commands should do the same.

Repro steps:
```
update examples/terraform/infracost-usage.yml to set the lambda usage values to 0

build/infracost breakdown --path examples/terraform --usage-file examples/terraform/infracost-usage.yml # Notice how 0-quantity lines are not output (correct behavior)

build/infracost breakdown --path examples/terraform --usage-file examples/terraform/infracost-usage.yml --format > out.json

build/infracost output --path out.json --format table # Notice how lambda prices are shown, and the usage params don't seem to have applied
build/infracost output --path a.json --format html > out.html # Same thing happens as the above line
```

I expected to hidden lines - OR at the least similar behavior as v0.9.10 so it seems like there's a bug in the master branch too.

- [x] Also update https://github.com/infracost/docs/pull/99/files#diff-127ccf771949de22c36f72306c28f3f448853733f173a2f658d4d6f5464de803R37 as part of this

**Comment by tim775** [comment]
This works as desired for me in master and also the `cmd/output_test` shows it working ok: https://github.com/infracost/infracost/pull/1042/files#diff-c3a03a689d47c1177fd9acb84db5a1e46976449a39fb3e8f7630458b7d36bd86

Could you try again with latest master?  Theres a typo in your instructions above where `--format` isn't followed by  `json`:

> ```
> build/infracost breakdown --path examples/terraform --usage-file examples/terraform/infracost-usage.yml --format > out.json
> ```

**Comment by alikhajeh1** [comment]
@tim775 you're right, I'm not sure what I was doing wrong before. Thanks!
