### ISSUE TITLE
Support - AWS/Elasticache

### ISSUE THREAD

**Issue by anton-yurchenko** [infracost/infracost#105]
#### Placeholder Issue

I'll try to **PR** this in the coming days/weeks.

#### Additional Info

- [Pricing](https://aws.amazon.com/elasticache/pricing/)
- [Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster)

**Comment by alikhajeh1** [comment]
Added in https://github.com/infracost/infracost/pull/218
