### ISSUE TITLE
Add additional backup storage for AWS RDS

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1063]
Add a new usage-based cost component to the `aws_db_instance` resource:
* Name: Additional backup storage
* Unit: GB
* Usage key: `additional_backup_storage_gb`

AWS Pricing pages:
* https://aws.amazon.com/rds/aurora/pricing/?pg=pr&loc=1
* https://aws.amazon.com/rds/postgresql/pricing/?pg=pr&loc=3
* https://aws.amazon.com/rds/mysql/pricing/?pg=pr&loc=2
* https://aws.amazon.com/rds/mariadb/pricing/?pg=pr&loc=4
* https://aws.amazon.com/rds/oracle/pricing/?pg=pr&loc=5
* https://aws.amazon.com/rds/sqlserver/pricing/?pg=pr&loc=6

It seems to be a set $0.095 per GB for all DB types except for Aurora DBs where there are different charges per region.

**Comment by joshniec** [comment]
Hi @aliscott, I started to look into this. 

A few questions if you don't mind:
According to the documentation, AWS does not charge for backup storage for up to 100% of the provisioned database storage. This would obviously be something I would want to take into account. How would you suggest I accurately model these costs? 

I will not know how large the user's actual database is vs their total provisioned database storage. It could be that the user has a database using only 20GB of a 100GB, which would give them 5x backups (assuming sizes remain constant) before they see any backup storage related costs from AWS. Perhaps this additional output should provide projected storage costs if the user were to store backups equal to 200% of the provisioned database storage with a special note indicating that these are only estimated costs if database backups equaled 200% of the provisioned database storage amount. Related excerpt from the documentation:
> For example, if you have an active PostgreSQL instance with 500 GiB-month of provisioned database storage and an active MySQL DB instance with 200 GiB-month of provisioned database storage, we provide up to 700 GiB-month of backup storage at no additional charge. 

Additionally, according to the docs:
> Backup storage is allocated by region. Total backup storage space is equivalent to the sum of the storage for all backups in that region.
> ...
> There is no additional charge for backup storage up to 100% of your total database storage for a region

I will not have any insight into whether or not the user has other database instances provisioned in the same region. It could be that the other `aws_db_instance`'s exist in other directories or perhaps the user does not have IAM permissions to even see the other databases in their account (inside the same region). Thus, the total available additional backup storage they have available to them may be much larger than I would know about. Should this be something I consider or out of scope? 

Another possible worthy mention is the fact that if the database instance is terminated, AWS begins to bill $0.095 per GiB-month. I analyzing a directory where the database instance has or will be destroyed, I would want to account for backup storage costs equal to the total originally provisioned database storage amount. Do you think that is in scope here? 

Let me know if I am thinking about this too much and if I should only be working with the data that I have available to me [in the workspace/directory(s)] during runtime of `infracost`.

**Comment by aliscott** [comment]
Thanks for looking into this @joshniec!

Since it's not possible to tell the quantity from the Terraform code I think we should start with a usage-based cost component. That means we don't actually calculate the cost, we just show the user the price per unit of the additional backups. They can then fill out the [Infracost usage file](https://www.infracost.io/docs/usage_based_resources#infracost-usage-file) manually to add the quantity so they can see the cost. You can see an example of how we do this with the [`aws_mwaa_environment` resource's `additional_workers` value](https://github.com/infracost/infracost/blob/master/internal/resources/aws/mwaa_environment.go#L24-L28).

We have started experimenting with [pulling some usage data from CloudWatch](https://www.infracost.io/docs/usage_based_resources#fetch-from-cloudwatch), so in the future we can do that for this so we can show a cost based on the last 30 days of usage, but I think this is out of scope for this issue initially.

> Another possible worthy mention is the fact that if the database instance is terminated, AWS begins to bill $0.095 per GiB-month. I analyzing a directory where the database instance has or will be destroyed, I would want to account for backup storage costs equal to the total originally provisioned database storage amount. Do you think that is in scope here?

Interesting! I think this should be out of scope just now, but this makes me think about how we can detect things like this to warn the user in the future. I actually created this issue because we're seeing this in our own AWS account.

**Comment by alikhajeh1** [comment]
@joshniec would you like me to assign you the issue? (it helps the rest of the community know that someone is working on it to avoid duplicate effort)

**Comment by joshniec** [comment]
Sure! Happy holidays!

**Comment by alikhajeh1** [comment]
Thanks - you too!
![gify](https://user-images.githubusercontent.com/638577/143472332-403a6ae5-21c1-4387-8c0e-026d6cadb717.gif)
