### ISSUE TITLE
Improve Godoc support

### ISSUE THREAD

**Issue by hugorut** [infracost/infracost#1066]
Infracost has excellent documentation and contributor guidelines. However, it lacks detailed godoc support. I think enhancing godoc support would improve the contributor process, especially with new contributors. Here's my reasoning:

In general whenever I'm working with 3rd party sdks/packages I do a glance over the Readme and examples, but, I heavily rely on code documentation to inform me on how to use the package/lib. A good example of this in the `net/http` package:

```go
// RoundTripper is an interface representing the ability to execute a
// single HTTP transaction, obtaining the Response for a given Request.
//
// A RoundTripper must be safe for concurrent use by multiple
// goroutines.
type RoundTripper interface {
	// RoundTrip executes a single HTTP transaction, returning
	// a Response for the provided Request.
	//
	// RoundTrip should not attempt to interpret the response. In
	// particular, RoundTrip must return err == nil if it obtained
	// a response, regardless of the response's HTTP status code.
	// A non-nil err should be reserved for failure to obtain a
	// response. Similarly, RoundTrip should not attempt to
	// handle higher-level protocol details such as redirects,
	// authentication, or cookies.
	//
	// RoundTrip should not modify the request, except for
	// consuming and closing the Request's Body. RoundTrip may
	// read fields of the request in a separate goroutine. Callers
	// should not mutate or reuse the request until the Response's
	// Body has been closed.
	//
	// RoundTrip must always close the body, including on errors,
	// but depending on the implementation may do so in a separate
	// goroutine even after RoundTrip returns. This means that
	// callers wanting to reuse the body for subsequent requests
	// must arrange to wait for the Close call before doing so.
	//
	// The Request's URL and Header fields must be initialized.
	RoundTrip(*Request) (*Response, error)
}
```

After reading this code block I'm pretty confident in how I should implement a `http.RoundTripper` in my code and all it took was a *navigate to definition* in my code editor.

A concrete example of how improving godoc support could help contributors is with **new resource** additions. With this process, contributors deal with a number of different infracost  domain types that currently don't have any code documentation, e.g. `schema.Resource` :

```go
type Resource struct {
	Name              string
	CostComponents    []*CostComponent
	SubResources      []*Resource
	HourlyCost        *decimal.Decimal
	MonthlyCost       *decimal.Decimal
	IsSkipped         bool
	NoPrice           bool
	SkipMessage       string
	ResourceType      string
	Tags              map[string]string
	UsageSchema       []*UsageItem
	EstimateUsage     EstimateFunc
	EstimationSummary map[string]bool
}
```

Adding some documentation to some of the fields here could be invaluable for new contributors learning what the different parts of a `Resource` is and what they need to set explicitly. 

For example, new contributors coming to this struct might have the following questions: 

- It's not immediately obvious what `Tags` are and if they're required for valid output?
- Should I explicitly set `SkipMessage` if the `IsSkipped` field is `true`? Where does `IsSkipped` affect (output/breakdown/e.t.c)?
- Does adding `NoPrice` skip a resource from the output, and if so why use that over `IsSkipped` ?
- Do I need both `HourlyCost` & `MonthlyCost` ?
- When should I use `EstimateUsage` and what information should that return? (although I realise that the actual type of `EstimateFunc` does have docs)
- What's the difference between `CostComponents` and `SubResources` ? When should I use one over the other and how does this directly affect resource outputs?

Just to name a few. All these questions could be sorted with some doc blocks directly in the code.

Now I realise that adding code comments can be a bit of a chore. Especially on a codebase that's already the size of infracost. So I thought it best to open this issue to discuss the merits of adding these. It might be that after discussion it just doesn't warrant the effort that it would take to implement. 

I would love to see more godoc implementation across the codebase, but I realise not every engineer navigates code this way.

If we do decide that adding more in-depth comments would be worth our time, it might be best to prioritise which areas/structures in the codebase would have the most impact and tackle those first. From my initial forays into the codebase I think these areas would benefit from more explicit commments:

1. `schema.Resource`
2. `schema.CostComponent`
3. `schema.UsageItem`
4. `resources.PopulateArgsWithUsage`
5. `resources.CoreResource`

With these implemented that would pretty much cover the add new resource flow.

**Comment by alikhajeh1** [comment]
@hugorut any thoughts on what the next step for this could be? or does resourcegen already handle this?

**Comment by hugorut** [comment]
@alikhajeh1 I think as a team we've agreed to support more comments moving forward. Additionally, as you've mentioned `resourcegen` encourages contributors to write `godoc` out the box. The rest of the codebase we can slowly iterate on when we're refactoring/editing files. It doesn't have to be a big bang approach. So, with that said I think we can close this issue.

**Comment by alikhajeh1** [comment]
Thanks @hugorut!
