### ISSUE TITLE
Add support for Azure MSSQL Server

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#1107]
Add support for MSSQL server on MS Azure

Terraform: 
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server

Azure pricing page: https://azure.microsoft.com/en-us/pricing/details/azure-sql-database/single/

**Comment by alikhajeh1** [comment]
See https://github.com/infracost/infracost/issues/1138
