### ISSUE TITLE
Shell completion improvements

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1118]
- Add Fig.io integration: https://fig.io/docs/guides/autocomplete-for-teams
- Could `$SHELL` be used to automatically choose the shell when not specified? If not, then running `infracost completion` should show the help text as well as the existing error message. In the same way that `infracost diff` does.

**Comment by brendanfalk** [comment]
I presume you want the Fig integration to be fully automated. We recommend creating a GH action that runs on push to main that deep merges the spec with the existing one then pushed to withfig/autocomplete

Tagging @fedeci who has been working on this with us and can hopefully help :)

please ping me if you need any help brendan AT fig DOT io

**Comment by alikhajeh1** [comment]
That's very cool, we use GH actions already in this repo so that would be sweet.

**Comment by fedeci** [comment]
I have opened a first PR containing the fig integration code for cobra and I will follow up soon with the gh action to automatically push to the autocomplete repo.
