### ISSUE TITLE
Add support for AWS RDS

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#112]
User request to add AWS RDS instances support: https://aws.amazon.com/rds/pricing/

We currently support aws_rds_cluster_instance and aws_rds_cluster. Expand the list to include more (Terraform currently supported RDS below):

<img width="265" alt="Screen Shot 2020-09-15 at 4 09 45 PM" src="https://user-images.githubusercontent.com/1238825/93229053-12acd000-f76e-11ea-9eca-ebab2b4e1959.png">

**Comment by hassankhosseini** [comment]
User has requested aws_db_instance as priority.

**Comment by alikhajeh1** [comment]
@hassankhosseini as mentioned in https://www.infracost.io/docs/supported_resources, `aws_db_instance` is supported. Is there an issue with it? https://github.com/infracost/infracost/issues/84#issuecomment-692910352 might help make things clearer for users.

**Comment by hassankhosseini** [comment]
Will reach back out to user to see what the issue is. Cheers

**Comment by alikhajeh1** [comment]
@hassankhosseini I've assigned the issue to you for now as we're not sure what the issue is.

**Comment by hassankhosseini** [comment]
Thanks - lets close this issue for now. Will open up another issue once we get requests for specific resources that are missing. Cheers
