### ISSUE TITLE
Following resoruces are skipped from cost estimation

### ISSUE THREAD

**Issue by RimashMohomed** [infracost/infracost#1129]
I have executed below command to estimate the cost, below resources are skipped from estimation
-  aws_dynamodb_table_item
-  aws_ebs_default_kms_key

**Comment by alikhajeh1** [comment]
Thanks for reporting this @RimashMohomed! I sent a [PR](https://github.com/infracost/infracost/pull/1128/files) just now, I marked `aws_dynamodb_table_item` as free as we already model the costs against the `aws_dynamodb_table` resource. `aws_ebs_default_kms_key` also looks free as it only refers to the `aws_kms_key` (which is already a supported resource). This'll go out in release v0.9.14, probably late this week or next week.
