### ISSUE TITLE
infracost output: number of projects with no cost changes instead of actual paths

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1132]
The `infracost output --format github-comment` format outputs the list of projects that have no cost estimate changes. This can create a long line of projects for mono repos, so instead should we output just the count of projects in the comment, and the CLI output can be expanded to see the details?

💰 Infracost estimate: **monthly cost will not change**
<table>
  <thead>
    <td>Project</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>All projects</td>
      <td align="right">$1,234</td>
      <td align="right">$1,234</td>
      <td>$0</td>
    </tr>
  </tbody>
</table>

The following projects have no cost estimate changes: very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1, very/long/path/to/my/project/1

Changes to:
8 project have no cost estimate changes.
<details>
<summary><strong>Infracost output</strong></summary>

```
details here
```
</details>

**Comment by alikhajeh1** [comment]
@aliscott is this merged into master?

**Comment by aliscott** [comment]
@alikhajeh1 yes this will go out out in v0.9.14 (either tomorrow or Monday).

**Comment by tim775** [comment]
@PatMyron @jrmash This is now live in 0.9.14
