### ISSUE TITLE
Add these to supported resources 

### ISSUE THREAD

**Issue by dsfrederic** [infracost/infracost#1134]
```
  ∙ 2 x azurerm_data_factory
  ∙ 2 x azurerm_storage_account
  ∙ 1 x azurerm_sql_active_directory_administrator
  ∙ 1 x azurerm_sql_database
  ∙ 1 x azurerm_storage_account_network_rules
```

**Comment by alikhajeh1** [comment]
@dsfrederic thanks for creating this! I added a few tickets so we can track these individually as we work on them, please watch them for updates.

azurerm_data_factory > https://github.com/infracost/infracost/issues/1137
azurerm_storage_account / azurerm_storage_account_network_rules > https://github.com/infracost/infracost/issues/951 
azurerm_sql_database / azurerm_sql_active_directory_administrator > https://github.com/infracost/infracost/issues/1138
