### ISSUE TITLE
Add support for Azure Data Factory

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1137]
Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory and the other `azurerm_data_factory*` resources
Pricing page: https://azure.microsoft.com/en-us/pricing/details/data-factory/data-pipeline/

## Paid resources

- `azurerm_data_factory`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Read/Write operations` | `50k entities` | `monthly_read_write_operation_entities` | |
  | `Monitoring operations` | `50k entities` | `monthly_monitoring_operation_entities` | |

- `azurerm_data_factory_integration_runtime_azure`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Compute ([Instance type], [Number of cores] cores)` | `vCore-hours` | | `HourlyQuantity` x cores |
  | `Orchestration` | `1k runs` | `monthly_orchestration_runs` | |
  | `Data movement activity` | `hours` | | `HourlyQuantity` |
  | `Pipeline activity` | `hours` | | `HourlyQuantity` |
  | `External pipeline activity` | `hours` | | `HourlyQuantity` |

- `azurerm_data_factory_integration_runtime_azure_ssis`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Compute ([Instance type <with license>], [Number of instances] instance[s])` | `hours` | | `HourlyQuantity` x intances |

- `azurerm_data_factory_integration_runtime_managed`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Compute ([Instance type <with license>], [Number of instances] instance[s])` | `hours` | | `HourlyQuantity` x intances |
  | `Orchestration` | `1k runs` | `monthly_orchestration_runs` | |
  | `Data movement activity` | `hours` | | `HourlyQuantity` |
  | `Pipeline activity` | `hours` | | `HourlyQuantity` |
  | `External pipeline activity` | `hours` | | `HourlyQuantity` |

- `azurerm_data_factory_integration_runtime_self_hosted`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Orchestration` | `1k runs` | `monthly_orchestration_runs` | |
  | `Data movement activity` | `hours` | | `HourlyQuantity` |
  | `Pipeline activity` | `hours` | | `HourlyQuantity` |
  | `External pipeline activity` | `hours` | | `HourlyQuantity` |

## Free resources

- `azurerm_data_factory_custom_dataset`
- `azurerm_data_factory_data_flow`
- `azurerm_data_factory_dataset_azure_blob`
- `azurerm_data_factory_dataset_binary`
- `azurerm_data_factory_dataset_cosmosdb_sqlapi`
- `azurerm_data_factory_dataset_delimited_text`
- `azurerm_data_factory_dataset_http`
- `azurerm_data_factory_dataset_json`
- `azurerm_data_factory_dataset_mysql`
- `azurerm_data_factory_dataset_parquet`
- `azurerm_data_factory_dataset_postgresql`
- `azurerm_data_factory_dataset_snowflake`
- `azurerm_data_factory_dataset_sql_server_table`
- `azurerm_data_factory_linked_custom_service`
- `azurerm_data_factory_linked_service_azure_blob_storage`
- `azurerm_data_factory_linked_service_azure_databricks`
- `azurerm_data_factory_linked_service_azure_file_storage`
- `azurerm_data_factory_linked_service_azure_function`
- `azurerm_data_factory_linked_service_azure_search`
- `azurerm_data_factory_linked_service_azure_sql_database`
- `azurerm_data_factory_linked_service_azure_table_storage`
- `azurerm_data_factory_linked_service_cosmosdb`
- `azurerm_data_factory_linked_service_cosmosdb_mongoapi`
- `azurerm_data_factory_linked_service_data_lake_storage_gen2`
- `azurerm_data_factory_linked_service_key_vault`
- `azurerm_data_factory_linked_service_kusto`
- `azurerm_data_factory_linked_service_mysql`
- `azurerm_data_factory_linked_service_odata`
- `azurerm_data_factory_linked_service_odbc`
- `azurerm_data_factory_linked_service_postgresql`
- `azurerm_data_factory_linked_service_sftp`
- `azurerm_data_factory_linked_service_snowflake`
- `azurerm_data_factory_linked_service_sql_server`
- `azurerm_data_factory_linked_service_synapse`
- `azurerm_data_factory_linked_service_web`
- `azurerm_data_factory_managed_private_endpoint`
- `azurerm_data_factory_pipeline`
- `azurerm_data_factory_trigger_blob_event`
- `azurerm_data_factory_trigger_custom_event`
- `azurerm_data_factory_trigger_schedule`
- `azurerm_data_factory_tumbling_window`

**Comment by vdmgolub** [comment]
This resource will go live with the next release this week.
