### ISSUE TITLE
Odd behavior when Terraform 'target' flag is used

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1152]
A user has reported this issue. 

User: 
We've had to do some builds with `-target` set for terraform, and Infracost has reported cost decreases consistently, I would expect a cost decrease on the first build with a `-target`, but then future runs report the same decrease. I'm sure there's something I don't understand about it, and it's not a big deal. Just the only thing I could think to raise with you :)

Me: 
Trying to understand the process you went through better:
1. you run `terraform plan -target="my_resource"` and you see a cost estimate comment showing a cost decrease. Were you expecting a cost decrease because of the change to my_resource or something else was being modified in the TF project?
2. You make changes to my_resource, and the comment is updated (or a new comment is posted?) showing the same cost decrease. But you didn’t expect to see this cost decrease comment?

    Or are you seeing cost decrease comments even after the my_resource change was applied? But you expected to see no cost diff when re-running with -target=my_resource as the change has already been applied.

User:
1. expecting to see a cost decrease because we're now running with -target, yes
2. The cost decrease persist across several later PRs as well
3. Yes we saw the cost decrease after the change was applied with TF

**Comment by aliscott** [comment]
The fix has now been released in v0.9.15.
