### ISSUE TITLE
`Terragrunt` invalid character '\x1b' looking for beginning of value

### ISSUE THREAD

**Issue by terrych0u** [infracost/infracost#1174]
while I'm trying to run `infracost breakdown/diff --path .`, It will show the following error on my terminal,
not sure what happened or what I'm missing.

```
Detected Terragrunt directory at .
  ✖ Running terragrunt run-all terragrunt-info
Error: invalid character '\x1b' looking for beginning of value
```

version: 0.9.14

**Comment by aliscott** [comment]
Thanks for reporting this. Can you run with `--log-level=debug` and add the logs here?

Are you using Terragrunt? If so:
1. What version of Terragrunt?
2. What is the output when you run `terragrunt run-all terragrunt-info` in that directory?

**Comment by terrych0u** [comment]
Hi @aliscott 
thanks for quick reply, here is my result:

--log-level=debug
```
time="2021-12-03T18:06:05+08:00" level=info msg="Detected Terragrunt directory at ."
time="2021-12-03T18:06:05+08:00" level=info msg="starting: Running terragrunt run-all terragrunt-info"
time="2021-12-03T18:06:05+08:00" level=info msg="Running command: /usr/local/bin/terragrunt run-all --terragrunt-ignore-external-dependencies terragrunt-info"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform msg="\x1b[0;32m[INFO] Getting version from tgenv-version-name\x1b[0;39m"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform msg="\x1b[0;32m[INFO] TGENV_VERSION is 0.35.10\x1b[0;39m"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform msg="time=2021-12-03T18:06:05+08:00 level=info msg=The stack at <my-tf-code-folder> will be processed in the following order for command terragrunt-info:"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform msg="Group 1"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform msg="- Module <my-tf-code-folder>"
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform
time="2021-12-03T18:06:05+08:00" level=debug binary=terraform
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="{"
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"ConfigPath\": \"<my-tf-code-folder>/terragrunt.hcl\","
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"DownloadDir\": \"<my-tf-code-folder>/.terragrunt-cache\","
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"IamRole\": \"\","
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"TerraformBinary\": \"terraform\","
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"TerraformCommand\": \"terragrunt-info\","
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="  \"WorkingDir\": \"<my-tf-code-folder>\""
time="2021-12-03T18:06:07+08:00" level=debug binary=terraform msg="}"
Error: invalid character '\x1b' looking for beginning of value
```


terragrunt version: `0.35.10`（the newest version `0.35.13` still have same error）


terragrunt run-all terragrunt-info
```
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.35.10
INFO[0000] The stack at <my-tf-code-folder> will be processed in the following order for command terragrunt-info:
Group 1
- Module <my-tf-code-folder>

{
  "ConfigPath": "<my-tf-code-folder>/terragrunt.hcl",
  "DownloadDir": "<my-tf-code-folder>/.terragrunt-cache",
  "IamRole": "",
  "TerraformBinary": "terraform",
  "TerraformCommand": "terragrunt-info",
  "WorkingDir": "<my-tf-code-folder>"
}
```

**Comment by aliscott** [comment]
Thanks @terrych0u, looks like it's an issue with us parsing the `terragrunt run-all terragrunt-info` output in certain cases. @tim775's going to dive in and fix it/see if there's a workaround in the meantime.

**Comment by tim775** [comment]
@terrych0u It seems like the stderr and stdout from terragrunt are getting mixed together.  What envinroment are you running in (operating system, shell, etc...)?

**Comment by terrych0u** [comment]
@aliscott Thank you for being help
@tim775  Hi, I'm using Macbook Pro M1 with OS 12.0.1, and my shell is `fish-shell` , but I have been also tried to using `bash`, and still got the same error

**Comment by tim775** [comment]
It looks like the additional log messages `tgenv` prints are sent to stdout: https://github.com/cunymatthieu/tgenv/blob/master/libexec/tgenv-exec#L20

Could you try running without tgenv and confirm that fixes the problem?

FWIW, tgenv installed with `brew install tgenv` has the extra logging removed for some reason and seems to work fine with infracost.

**Comment by terrych0u** [comment]
@tim775 
Thanks for the help,
I switch to using `terragrunt` directly without `tgenv`, and it works for me.

I'm wondering is possible to support `tgenv` ?

**Comment by alikhajeh1** [comment]
I don't suppose we could do something similar to https://github.com/infracost/infracost/pull/1146/files as the output doesn't follow a parse-able pattern.

I guess https://github.com/cunymatthieu/tgenv/pull/13 and https://github.com/cunymatthieu/tgenv/pull/12 are the issues. Those PRs have been open for a while but not merged. https://github.com/cunymatthieu/tgenv/issues/19 makes me think that `tgenv` is being maintained and suggests https://github.com/warrensbox/tgswitch as an alternative. @terrych0u I'm wondering if you're tried that before?

**Comment by terrych0u** [comment]
@alikhajeh1 

Thank you, I will try to switch to using `tgswitch`, it looks like also fit what I need.

Again, Thank you for the team support, appreciate it!! :)

**Comment by alikhajeh1** [comment]
Thanks! Once you get a chance to try it, maybe add a comment here letting the rest of the community know if it worked ok - that helps the next community member who hits this issue :)

**Comment by terrych0u** [comment]
@alikhajeh1 
I have been tried to use `tgswitch`, it works well with `infracost`, although it has a small drawback.（it doesn't support adding `.terragroun-version` at the root folder, you need to put it into every tf code folder.）

In the end, I'm switching to using another version of `tgenv`,  and everything works perfectly. :)
here is the link: 
https://github.com/taosmountain/tgenv

**Comment by alikhajeh1** [comment]
@terrych0u thanks for the update! Just FYI that @tim775 made [a change](https://github.com/infracost/infracost/pull/1190/files) to Infracost v0.9.15 (released ~1h ago) - can you possibly do a quick test of that version with the old `cunymatthieu/tgenv` to see if that works ok too? It seemed like a simple change so @tim775 did that to save future tgenv users from debugging pain.

**Comment by terrych0u** [comment]
@alikhajeh1 
I'm confrimed the `v0.9.15` version works well with `cunymatthieu/tgenv` and `taosmountain/tgenv`.
Again, thanks for everything :D
