### ISSUE TITLE
Make links in CLI output simpler to read

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1175]
The current blue links are sometimes not easy to read, e.g. see the first screenshot from a user vs the second screenshot from my terminal (iTerm2):

![image](https://user-images.githubusercontent.com/638577/144635984-7ff5f334-b07a-433e-9e0d-4d1c2b22aa4e.png)

![Screen Shot 2021-12-03 at 7 17 55 PM](https://user-images.githubusercontent.com/638577/144636188-c01e185d-c4eb-4ad8-bfbc-0a8cd8b40fee.png)

## Note for community

Please 👍 if you'd like to upvote this or receive updates.

**Comment by vdmgolub** [comment]
@alikhajeh1 What if we use underlined styling instead of the colors?
![image](https://user-images.githubusercontent.com/87082/155324322-0c577c96-3440-499f-893c-36a2c4a18b87.png)

**Comment by alikhajeh1** [comment]
LGTM! thank you

**Comment by alikhajeh1** [comment]
@emocharnik, @penja and @PatMyron just FYI that as of [v0.9.19](https://github.com/infracost/infracost/releases), released today, the link colors are white and bold, can you please try that and let us know if that helped?

**Comment by emocharnik** [comment]
thanks, @alikhajeh1!
