### ISSUE TITLE
Token too long error when using tfdir and tfplan options

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#118]
A user with 1K+ resources sent me this error, they're using `macOS 10.15.6` and downloaded the latest version of infracost from homebrew.

```
infracost --tfdir=. --tfplan=plan.save                                                                   4s
INFO Running command: /usr/local/bin/terraform show -json plan.save
ERROR Error while reading from Writer: bufio.Scanner: token too long
signal: broken pipe
```

@aliscott mentioned he fixed a similar issue but maybe that was only for the --tfjson option?

**Comment by aliscott** [comment]
Looks like this is related to https://github.com/sirupsen/logrus/issues/564.
