### ISSUE TITLE
Composable GitLab CI Templates

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1183]
For GitHub, we recently switched from our old [infracost-gh-actions](https://github.com/infracost/infracost-gh-action) repo to our new [actions](https://github.com/infracost/actions/) repo. We'd like to create a similar experience for GitLab users. We need to:
1. [x] Create a new `infracost output --format gitlab-comment` format (similar to the existing `github-comment`)
2. [x] Use our new open source project, [Compost](https://github.com/infracost/compost), which will detect [GitLab CI env vars](https://github.com/infracost/compost/blob/23fc7410c9855846d898b3aa86cb8ee78736922b/src/detect/gitlabCi.ts#L10-L13) and use those to post/update merge request comments.
3. [x] The `infracost/infracost` Docker image is quite large as it contains multiple versions of Terraform, and the latest version of Terragrunt. We'll create new smaller image (`infracost/infracost:ci-v0.9`?) that just has the Infracost and Compost CLIs.
4. [x] Develop examples, similar to our GitHub actions [examples](https://github.com/infracost/actions/)

```sh
# Steps in GitLab CI:

# Install Infracost, Terraform/Terragrunt

# Run Infracost commands
infracost breakdown --format json --out-file infracost.json --path my/terraform
infracost output --path infracost.json --format diff --out-file infracost-diff.txt # can become `gitlab-comment` once we have that

# Post merge request comment
compost autodetect update --body-file=infracost-diff.txt

# Do other required stuff with infracost.json, e.g. policy checks or post to Slack
```

**Comment by aliscott** [comment]
I've put in a PR for adding a GitLab comment output format (https://github.com/infracost/infracost/pull/1198), which we can then use to build more composable GitLab CI integrations. This will go live in v0.9.15 of the CLI. Initially this GitLab comment is the same as our GitHub on, so it will look like this:

<img width="979" alt="Screenshot 2021-12-13 at 16 27 12" src="https://user-images.githubusercontent.com/158824/145962901-56c67b57-1b91-4a78-8692-c75f15f40f18.png">

GitLab has better markdown features so there's definitely opportunity to improve this.

**Comment by alikhajeh1** [comment]
This is now live! See https://gitlab.com/infracost/infracost-gitlab-ci
