### ISSUE TITLE
Detect Terraform plan files in current directory

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1201]
A user has a GitHub action which uses Terragrunt ([action.yml](https://gist.github.com/aliscott/860b4ef7852376758c50815bb09f21d1)). The plan files are generated using `terragrunt run-all plan -out terraform.tfplan`. When Infracost runs it detects terragrunt and re-runs the `terragrunt run-all plan` which is slow (from the user: "our goal is to speed up infracost run since it adds 2x terragrunt run time to pipeline").

**Option 1:**

Autodetect any plan files in the current directory. For this we would have to work out:
1. How do we detect a plan file? Do we need a name pattern to be passed as a hint, or do we read each file and check if it's a plan.
2. How many directories deep do we check?
3. What precedence do we set for detecting plan files vs code director.

**Option 2**

Support glob patterns in the `--path` flag for `infracost breakdown` so the user can pass something like `--path=path/to/all/**/**.tfplan`.

**Workaround**

@jgrumboe suggested the following workaround for just now for generating a config file on the fly:

```bash
#!/usr/bin/env bash

cfgfile="/tmp/infracost.yml"

# write the infracost config file header
echo -e "version: 0.1\n\nprojects:\n" > $cfgfile

# Loop through plans and create Infracost config file
planfiles=($(find . -name "terraform.tfplan" | tr '\n' ' '))
for planfile in "${planfiles[@]}"; do
  echo "Adding $planfile to infracost config";
  echo "  - path: $planfile" >> $cfgfile
done

# export config file name to Github env
# use it in the next step as env.infracost_configfile
echo "infracost_configfile=$cfgfile" >> $GITHUB_ENV
```

**Comment by alikhajeh1** [comment]
To the users who upvoted this issue: given the new [Infracost v0.10](https://www.infracost.io/docs/guides/v0.10_migration/) that parses HCL code and [works with Terragrunt](https://www.infracost.io/docs/features/terragrunt/) is this issue still needed? if so, why?

**Comment by alikhajeh1** [comment]
Going to close this as I've not heard from users that need it
