### ISSUE TITLE
Show price for resources with no cost

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#121]
According to `Level 1 support` of https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md we should make all currently existing resources compatible with these requirements.

Resources:
- [ ] aws_alb
- [ ] aws_db_instance
- [ ] aws_docdb_cluster_instance
- [ ] aws_ecs_service
- [ ] aws_elb
- [ ] aws_lambda_function
- [ ] aws_lb
- [ ] aws_rds_cluster_instance
- [ ] aws_elasticsearch_domain
- [x] aws_dynamodb_table
- [x] aws_nat_gateway
- [x] aws_instance (https://github.com/infracost/infracost/pull/126, https://github.com/infracost/infracost/pull/129)
- [ ] aws_ebs_snapshot (https://github.com/infracost/infracost/pull/143)
- [ ] aws_ebs_snapshot_copy (https://github.com/infracost/infracost/pull/143)
- [ ] aws_ebs_volume (https://github.com/infracost/infracost/pull/143)
- [ ] aws_autoscaling_group (https://github.com/infracost/infracost/pull/142)

**Comment by sinabakh** [comment]
The question is shoule we list all possible costs or just the main required costs. Take Pay Per Request DynamoDB for instance, it has 3 main cost components : Read/Write units and storage price, one can't use this service without utilizing all these three components. But there are some additional components like backup storage, shall we add 0 cost components for them also?

2. Do we need to show 0 cost components for resources missing in terraform and covered in infracost terraform plugin? Like most pay per request components?

**Comment by alikhajeh1** [comment]
1. yeah I think that would be good, @aliscott did something similar for `aws_instance`, which I think we can mark as done in this issue list.
2. I wouldn't work on the infracost terraform plugin until we know users want it and will use it. Despite pushing users for feedback on that, I've gotten very few replies, and one strong rejection (the user saw estimates as dead/stale-code that needs to be removed after the service is deployed).

**Comment by sinabakh** [comment]
> What I think is there might be no point in showing the 0 costs for the resources we can't support.

There is value in developers understanding **what are the cost components of this resource** and **how much is the price of each component**, even if the cost shows 0 (since it's usage-based).

It took me ~1h to understand the pricing of ECS Fargate and I had to spin stuff up and read docs to see if the default 20GB docker disk cost money or was free... `infracost` takes that 1h to 1min, that's the base value it provides.

_Originally posted by @alikhajeh1 in https://github.com/infracost/infracost/pull/133#issuecomment-702831824_

**Comment by sinabakh** [comment]
No changes for `aws_alb`

**Comment by sinabakh** [comment]
@alikhajeh1 @aliscott I'm checking the resources pricing page one by one to see if we might have a change for level 1 support but it takes me days to complete. It would be great if you can tell which resources need change(if you know any).

**Comment by alikhajeh1** [comment]
@sinabakh I re-ordered this list a bit, I'm leaning towards us adding support for new resources that users are requesting so I think we can pause work on this issue just now.

**Comment by alikhajeh1** [comment]
Going to close this issue as some of these are already done and the remaining ones are being prioritized based on user feedback going forward.
