### ISSUE TITLE
`aws_elasticache_replication_group.cluster_mode` is present in non clustered aws_elasticache_replication_group state

### ISSUE THREAD

**Issue by hugorut** [infracost/infracost#1213]
When applying a `aws_elasticache_replication_group` in non clustered mode terraforms uses [number_cache_clusters](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#number_cache_clusters) to specify replication nodes.

However after applying terraform, the state adds the `cluster_mode` block to the resulting state. e.g:

```hcl

resource "aws_elasticache_replication_group" "non-cluster" {
  replication_group_description = "This Replication Group"
  replication_group_id          = "tf-rep-group-2"

  engine = "redis"

  node_type             = "cache.r5.4xlarge"
  number_cache_clusters = 3
}

```

results in something like so:

```hcl
resource "aws_elasticache_replication_group" "non-cluster" {
  replication_group_description = "This Replication Group"
  replication_group_id          = "tf-rep-group-2"

  engine = "redis"

  node_type             = "cache.r5.4xlarge"
  number_cache_clusters = 3
  
  cluster_enabled               = false
  cluster_mode {
      num_node_groups         = 1
      replicas_per_node_group = 1
  }
}

```

note the `cluster_enabled` and `cluster_mode` additions. This causes problems with cmds such as infracost diff as infracost uses the `cluster_mode` block and overrides the cost meaning it doesn't pick up on price changes if users have changed `number_cache_clusters` flag.

**Comment by alikhajeh1** [comment]
@hugorut thanks for creating this! Can you possibly also add any details of new cost components or units - or is it just a quantity that we need to multiply by?

So far I've:
- added the "needs details" label
- removed that label after details are added to the issue description.
- set the project of the issue to Main so show the community that it's something that we'd like help with sooner rather than later (the details make a big difference to the community being able to pick it up).

**Comment by hugorut** [comment]
@alikhajeh1 I was actually a bit quick to jump on this into an enhancement - it actually seems we do handle the `number_cache_clusters` in `aws_elasticache_replication_group` but it seems this feature isn't being picked up by the user. I'm going to rename the title and mark as a bug and ask for further details of their terraform file to replicate.

**Comment by vdmgolub** [comment]
This is live in v0.9.16.
