### ISSUE TITLE
Support for Terraform CDK

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1219]
How could Infracost be used with https://github.com/hashicorp/terraform-cdk?

One user mentioned that "the CDK supports provisioning infra with Terraform resources through the CDK but not natively with CDK only. So one will need to change their IaC from native CDK provisioning to using CDK-with-Terraform, I hope I'm not mistaken."

### Community notes

Would be great to hear from anyone who has tried using Infracost with CDK, or has ideas on how this could be done.

Please 👍 if you'd like to upvote for this feature.

**Comment by rirze** [comment]
Want to chime in on this-- the first feature that needs to be developed would be support for JSON Terraform files, since that is the only output the CDK for Terraform supports. 

I don't see any major barriers to using infracost once that is implemented.

**Comment by alikhajeh1** [comment]
@rirze have you tried running `infracost breakdown --path /path/to/tf/dir` where `dir` has `.tf.json` files? We [fixed an issue](https://github.com/infracost/infracost/issues/801) a while ago to enable that for non-CDK projects. Wondering if that helps at all.

**Comment by alikhajeh1** [comment]
Has anyone tried this on their CDK for TF projects?
```
cdktf synth
infracost breakdown --path cdktf.out/stacks/mystack/
```

I tried it on a small test project and it worked ok.

**Comment by alikhajeh1** [comment]
See [here](https://www.infracost.io/docs/features/cli_commands/#cdk-for-terraform) for brief docs on this. Please create new issues if you run into issues with CDK for TF support!
