### ISSUE TITLE
Automatic supported resources docs generation

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#123]
We need to be able to generate the contents of https://www.infracost.io/docs/supported_resources automatically.

**Comment by sinabakh** [comment]
My own idea is to change resource registry from `string->func` to `string->struct`:
```Go
var someResourceRegistry := RegistryItem{
  Name: "aws_alb",
  Aliases: []string{"aws_lb"},
  rFunc: ...
}

var someOtherResourceRegistry := RegistryItem{
  Name: "aws_ecs_service",
  Notes: "Fargate on-demand only.",
  rFunc: ....
}

```

**Comment by alikhajeh1** [comment]
LGTM, @aliscott any thoughts?

**Comment by aliscott** [comment]
Another option is having a `Notes` attribute on the `schema.Resource` and `schema.CostComponent` types. Will we ever want notes at cost component level (I'm not sure we will)?

**Comment by alikhajeh1** [comment]
@aliscott I was thinking of notes as succinct, human-readable, and for our docs; so Resource level notes should be enough as we can include mention any components that require highlighting.

**Comment by sinabakh** [comment]
The only problem I can think of is how the doc generator is going to get the resource object? Currently, we need to feed a resource schema to our resource functions so they can return a Resource object. So it wouldn't be as easy as traversing some lists.
Anyway, it might be possible to pass some dummy resource schema to get a Resource with just notes field.

**Comment by aliscott** [comment]
> The only problem I can think of is

Good point - let's keep it simple and go with your initial suggestion.
