### ISSUE TITLE
Add support for Bitbucket Server

### ISSUE THREAD

**Issue by wahlfeld10x** [infracost/infracost#1231]
As per title

**Comment by wahlfeld10x** [comment]
This work is complete, however, I'm having trouble pushing code to Github... it feels related to my organisation's security configuration i.e. Zscaler. Will get back to you.

**Comment by hugorut** [comment]
@wahlfeld10x thanks for opening this. Just a quick thought - you have created a fork of the repo and are pushing to that instead of trying to push to the main `infracost/infracost` repo. Most likely there's something else going on here but just wanted to make sure! Reach out if you need any help

**Comment by wahlfeld10x** [comment]
Yeah trying to push to https://github.com/wahlfeld10x/infracost but getting all sorts of weird errors that suggest something is getting in the way. e.g.
```
ssh -T git@github.com
[1]    26796 killed     ssh -T git@github.com
```
```
git push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.85 KiB | 1.85 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
```
```
gh repo clone wahlfeld10x/infracost
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit status 128
```
```
git clone git@github.com:wahlfeld10x/infracost.git                                            
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```
```
git push                                              
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by hugorut** [comment]
hmm this is weird. Are you sure there's nothing funky going on in your `.gitconfig`. It might be that your machine is re-writing urls to use https and is causing access errors?

Regarding bitbucket server support, are you editing the `diff.sh` script in the repo. Just a heads up, we're migrating away from this bash script in favour of a more composable approach. Using a new tool we've developed called [compost](https://github.com/infracost/compost). Rather rely on the master bash script we now `output` formats for different CI systems with the `breakdown` cmd and then post a diff using a `compost` wrapper. You can check out how it works with github here: https://github.com/infracost/actions.

This new composable approach isn't currently supported by bitbucket. There's an open issue here: https://github.com/infracost/infracost/issues/1173 to capture some requirements. Please vote on this if this is something that you want.

**Comment by wahlfeld10x** [comment]
I confirmed that we do currently block pushing to Github at the moment, but this will be changed in the future.

Also, yes, I did update the diff.sh script -- I'll have a look at compost instead. I suspect by the time I'm able to contribute anything you may already be using compost anyway.

**Comment by hugorut** [comment]
@wahlfeld10x, ah right, makes sense. Thanks for all the efforts so far. Taking a peek at your https://github.com/infracost/infracost/issues/1173#issuecomment-1005219898 this addition to the `diff.sh` looks promising and I wouldn't want all your hard work to go to waste. What you could do to get around the github access problem is manually edit https://github.com/wahlfeld10x/infracost/blob/master/scripts/ci/diff.sh directly using the **github website** - adding your additions. Then goto https://github.com/infracost/infracost/compare/master...wahlfeld10x:master to send a pull request from your fork, again using the **github website**. Alternatively, if that proves too much hassle I can open a PR with your changes and get your 👀 s on it for review. I don't want to deprive you of those all important contributor credits though - so maybe the manual addition would be the best idea!

**Comment by wahlfeld10x** [comment]
Thanks, that worked, I've created a draft PR for now as I'm in discussion with my organisation about this contribution.

**Comment by alikhajeh1** [comment]
Thanks @wahlfeld10x - I'm going to close this issue as the PR is merged so the diff script has that change.
Also, as mentioned [here](https://github.com/infracost/infracost/issues/1173#issuecomment-1036649757), we're adding support for this in `infracost comment bitbucket` too :)
