### ISSUE TITLE
certificate signed by unknown authority issue introduced in v0.9.15

### ISSUE THREAD

**Issue by rickardosmith** [infracost/infracost#1238]
I get the following printed to console when running version 0.9.15
```powershell
Detected Terraform directory at .
  ✔ Checking for cached plan... found
✖ Calculating monthly cost estimate


Error: Error sending API request: Post "https://pricing.api.infracost.io/graphql": x509: certificate signed by unknown authority
```

When I downgraded to version 0.9.14, the tool runs as expected
```powershell
Detected Terraform directory at .
  ✔ Checking for cached plan... found

✔ Calculating monthly cost estimate


Update: A new version of Infracost is available: v0.9.14 → v0.9.15
  Go to https://www.infracost.io/docs/update for instructions     

Running in "."

Summary: {
  "totalDetectedResources": 8,
  "totalSupportedResources": 1,
  "totalUnsupportedResources": 0,
  "totalUsageBasedResources": 1,
  "totalNoPriceResources": 7,
  "unsupportedResourceCounts": {},
  "noPriceResourceCounts": {
    "aws_internet_gateway": 1,
    "aws_network_interface": 1,
    "aws_route_table": 1,
    "aws_route_table_association": 1,
    "aws_security_group": 1,
    "aws_subnet": 1,
    "aws_vpc": 1
  }
}

Total Monthly Cost:        8.392 USD
Total Monthly Cost (diff): 8.392 USD
```

**Additional information**:
- I was running with version 0.9.5 at first, then upgraded version 0.9.15, noticed the error, then downgraded to version 0.9.14
- System info:
```
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by tim775** [comment]
Thanks for the issue.  I'm not able to reproduce on my dev machine so I'm spinning up a windows box in the cloud.  

If you have a chance could you see if setting `infracost configure set tls_insecure_skip_verify false` is a work-around?

**Comment by tim775** [comment]
I was able to reproduce on windows, and confirm that `.\infracost configure set tls_insecure_skip_verify true` is a work-around.

**Comment by tim775** [comment]
I guess there is a long-standing issue where the golang doesn't know how to load system certs on windows: https://github.com/golang/go/issues/16736.

**Comment by rickardosmith** [comment]
> 

@tim775 confirming that the workaround does work in my environment.

Thank you for addressing so quickly.  Looking forward to the fix added in the next release (fingers-crossed)

**Comment by vdmgolub** [comment]
@rickardosmith this is live in v0.9.16.
