### ISSUE TITLE
Add support for Azure monitor diagnostic setting

### ISSUE THREAD

**Issue by tomatwoodliquidx** [infracost/infracost#1252]
Terraform Resource: azurerm_monitor_diagnostic_setting

**Comment by alikhajeh1** [comment]
@tomatwoodliquidx thanks for creating these! We'll try to get to them as soon as possible. If you'd like to work on any of them, we'd be more than happy to help too. Our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) gives you a rough idea of what this involves.

**Comment by tomatwoodliquidx** [comment]
@alikhajeh1 Thanks for sending along!  Will definitely contribute if that helps the process along.  I know how it can be difficult with a lean team!  Infracost is great too!  If you ever want to do a call, I can provide some ideas for paid add-on featurea that would help your team out!  Let me know.

I am back at the office Jan 11 and will add more detail with these tickets and give a try at submitting some items.

**Comment by alikhajeh1** [comment]
Thanks @tomatwoodliquidx! A call to discuss that is also appreciated, my email is ali.hosseini@infracost.io.
@aliscott / @tim775 can you possibly add details to this or one of the other @tomatwoodliquidx issues in the next week to make it easier for him to start contributing?

**Comment by alikhajeh1** [comment]
@tomatwoodliquidx just checking if you have time to chat about your ideas on paid add-on features. We're holding our [first community call](https://github.com/infracost/infracost/issues/1353) next week - that would also be a good place to chat.

**Comment by tim775** [comment]
@tomatwoodliquidx I'm looking into adding coverage for diagnostic setting (finally!) and I'm wondering if you could help me understand the billing model a little better?  From reading the docs it seems that there aren't any costs directly attached to the `azurerm_monitor_diagnostic_setting` resource.  Instead, setting one of these up results in ingest costs on the target eventhub, storage account, or log analytics workspace.  Does that sound right?

**Comment by tim775** [comment]
This will go live in the 0.10.19 release

**Comment by tim775** [comment]
@tomatwoodliquidx this is live in 0.10.19
