### ISSUE TITLE
Add support for Azure storage container

### ISSUE THREAD

**Issue by tomatwoodliquidx** [infracost/infracost#1257]
Terraform resource: azurerm_storage_container

This is like not having coverage for an AWS S3 bucket....  Can this be prioritized as very high?

**Comment by aliscott** [comment]
Thanks @tomatwoodliquidx. We support certain storage options for the `azurerm_storage_account` resource. Would you expect a cost to also show on the `azurerm_storage_container` resource and if so which prices do you think should apply?

**Comment by aliscott** [comment]
@tomatwoodliquidx I was looking at prioritizing this and wondered if you had any thoughts on the prices that should be added to this resource?

**Comment by vdmgolub** [comment]
After some research it seems like "storage container" represents a "folder" in Storage Account. Here's how it's represented in [this article](https://www.serverless360.com/azure-storage-account):
![image](https://user-images.githubusercontent.com/87082/160288963-a2a00aa1-725a-4ffe-b90c-71a5da79c35c.png)

As far as I understand, the existence of a container is free, however Azure bills operations with them, like listing or creating. The storage account resource already calculates the costs for such operations and supports a usage-based parameters: https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L992, the pricing is for 10k operations, but the prices are available for only certain storage options.

Apparently, on `terraform apply` containers are created that induces costs, but it would be a one-off operation (not monthly based). So I'm not sure if we should introduce such cost component for this resource. We could also introduce a `List operations (10k)` cost component with a usage-based parameter, specifying how many operations this particular container expects. But it may create double-spending issue as the parent storage account resource also includes such operations.

Alternatively, we could calculate the number of defined resources and maybe show their creation cost on storage account resource (which is more concise, but doesn't exclude the double-spending issue mentioned above).

@tomatwoodliquidx Do you have any thoughts on it? Are you able to see the billing details for these resources?

**Comment by vdmgolub** [comment]
This resource has been added as free, `azurerm_storage_account` has cost components related to operations with containers. It will go live with the next release.

**Comment by vdmgolub** [comment]
@tomatwoodliquidx This is live with v0.9.21! Thank you for creating the issue! :)
