### ISSUE TITLE
Duplicate resources in supported resources docs

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#127]
Some resources such as `aws_alb / aws_alb` appear twice in https://github.com/infracost/infracost/blob/master/docs/generated/supported_resources.md

**Comment by sinabakh** [comment]
@alikhajeh1 So the problem is with a tweak I added in resource registry:
```go
for _, registryItem := range aws.ResourceRegistry {
	resourceRegistryMap[registryItem.Name] = registryItem
	for _, alias := range registryItem.Aliases {
		resourceRegistryMap[alias] = registryItem
	}
}
```
I simply add a duplicate resource with the alias name, so the question is whether the alias name is a valid name for terraform or not? and if users can freely choose between the aliases?
* If no, we can remove the duplicated resources.
* If yes, we may need to have a flag or sth to indicate the resource is just a duplicate of another resource.

**Comment by aliscott** [comment]
@sinabakh yeah the alias name is a valid Terraform name. It's only one case though, so one thought is to keep it simple and not have aliases's at all. We can just have separate `GetLBRegistryItem` and `GetALBRegistryItem` functions, and list them as separate line items in the `supported_resources.md` file. What do you think?

**Comment by sinabakh** [comment]
If it's not a recurring situation and there are just few exceptions I agree with you. Will fix it.
