### ISSUE TITLE
Add support for AWS Glue resources

### ISSUE THREAD

**Issue by moreandres** [infracost/infracost#1272]
Hi! It would be nice to support AWS Glue resources. In particular, `aws_glue_job` are serverless and run multiple executors which are costly. Thanks!

```
∙ 31 weren't estimated, report them in https://github.com/infracost/infracost:
  ∙ 14 x aws_glue_crawler
  ∙ 11 x aws_glue_job
  ∙ 4 x aws_glue_trigger
  ∙ 1 x aws_glue_catalog_database
  ∙ 1 x aws_glue_workflow
```

**Comment by alikhajeh1** [comment]
@moreandres thanks for creating this! We'll try to get to them as soon as possible. If you'd like to work on any of them, we'd be more than happy to help too. Our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) gives you a rough idea of what this involves.

**Comment by vdmgolub** [comment]
@moreandres This is live with v0.9.21! Thank you for creating the issue! :)
