### ISSUE TITLE
Support for vultr cloud

### ISSUE THREAD

**Issue by AliSajid** [infracost/infracost#1276]
### Discussed in https://github.com/infracost/infracost/discussions/1275

<div type='discussions-op-text'>

<sup>Originally posted by **AliSajid** January  8, 2022</sup>
Hi,

This is borne out of personal annoyance but what do you guys think about supporting other smaller cloud providers? I really want to use [Vultr](vultr.com).

I'd be willing to create the entire thing as they have a verified terraform provider and provide an API for pricing as well.</div>

**Comment by alikhajeh1** [comment]
Going to close this as we're tracking the discussion on https://github.com/infracost/cloud-pricing-api/issues/12 and Slack :)
