### ISSUE TITLE
Do best-effort on fetch from CloudWatch permission issues

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1279]
Using the [fetch from CloudWatch](https://www.infracost.io/docs/features/usage_based_resources/#fetch-from-cloudwatch) feature fails if the user does not have the `ListBucketMetricsConfigurations` permission. However, we could continue to fetch the rest of the metrics as things like the storage GB don't need that permission as far as I remember.

**Comment by aliscott** [comment]
Fixed by https://github.com/infracost/infracost/pull/1368 and will be released in v0.9.18.

**Comment by vdmgolub** [comment]
This is live in v0.9.18.
