### ISSUE TITLE
Migrate Remaining AWS Resources

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#1288]
Here are the steps to migrate a resource:
1. Pull latest changes from my `refactor-migration-t1` branch.
2. Set the var `SINGLE_RESOURCE_NAME` in `cmd/migrator/main.go` to the resource filename.
3. Run `go run cmd/migrator/main.go`, the resource file would be edited and a new resource file will be created in `internal/resources/aws`
4. All things that the script was unable to migrate are changed to the `UNKNOWN` keyword. There might even be need for logic changes.
5. Read the old logic and code and try to fix things as smoothly as possible.
6. Create a separate PR for your changes.

Important notes:
1. Let me know if you had any idea that the script could make things easier
2. Don't push resources on the aforementioned branch
3. Please sync the branch with the master whenever a migration pr is merged to master
4. There are cases where resources are dependent on each other, in these cases please convert all of them in one place

**Comment by sinabakh** [comment]
Here's a list of remaining resources:
- [ ] internal/providers/terraform/aws/cloudfront_distribution.go
- [ ] internal/providers/terraform/aws/cloudwatch_metric_alarm.go
- [ ] internal/providers/terraform/aws/dx_connection.go
- [ ] internal/providers/terraform/aws/dx_gateway_association.go
- [ ] internal/providers/terraform/aws/ebs_snapshot.go
- [ ] internal/providers/terraform/aws/ebs_snapshot_copy.go
- [ ] internal/providers/terraform/aws/ec2_transit_gateway_peering_attachment.go
- [ ] internal/providers/terraform/aws/ec2_transit_gateway_vpc_attachment.go
- [ ] internal/providers/terraform/aws/ecs_service.go
- [ ] internal/providers/terraform/aws/efs_file_system.go
- [ ] internal/providers/terraform/aws/elasticache_cluster.go
- [ ] internal/providers/terraform/aws/elasticache_replication_group.go
- [ ] internal/providers/terraform/aws/kinesis_firehose_delivery_stream.go
- [ ] internal/providers/terraform/aws/neptune_cluster_snapshot.go
- [ ] internal/providers/terraform/aws/route53_record.go
- [ ] internal/providers/terraform/aws/route53_resolver_endpoint.go
- [ ] internal/providers/terraform/aws/vpc_endpoint.go
- [ ] internal/providers/terraform/aws/waf_web_acl.go
- [ ] internal/providers/terraform/aws/wafv2_web_acl.go

**Comment by sinabakh** [comment]
@aliscott I suggest you start with `cloudwatch_metric_alarm` it seems easier than others for start.

**Comment by sinabakh** [comment]
I'll do:
- [ ] internal/providers/terraform/aws/waf_web_acl.go
- [ ] internal/providers/terraform/aws/wafv2_web_acl.go

**Comment by vdmgolub** [comment]
I'll do:
- [ ] internal/providers/terraform/aws/cloudfront_distribution.go
- [ ] internal/providers/terraform/aws/cloudwatch_metric_alarm.go

**Comment by aliscott** [comment]
@sinabakh this is awesome 😄! I set myself a time limit of 30 mins to see how many I could get done and managed to knock out 3 with these steps. Having the `UNKNOWN` blocks made this super simple.

I took some notes of things I noticed while going through it:

1. Should any resource structs that don't have usage parameters be non-pointers? This is what we have for the ones we did manually like `s3_bucket` and `eks_node_group` and I think it might be good to reduce possibilities of nil ptrs.
2. Should we use `strVal(r.X)` instead of `*r.X` to reduce nil ptr possibilities?
3. The `GetX` registry functions aren't renamed to `getX` in `registry.go` automatically - easy enough to fix up manually though.
4. `MonthlyDataProcessedGb` -> `MonthlyDataProcessedGB` (and other occurrences of `Gb` in the resource structs) . We can fix this up once all the migrations are done.

**Comment by sinabakh** [comment]
@aliscott 
1. I remember I thought about it and there were some technical difficulties that I can't remember right now. Give me some time to give it another thought to see if that's possible.
2. I think that's possible, need some investigation though.
3. Yeah, I think doing it manually will consume more time than all the manual edits combined :))
4. I didn't understand. It's pretty easy to transform `Gb` to `GB`, is it what you mean?


For the first 2 comments, I think we would need another migrator script for already migrated ones. So I will give it enough time for thoughts to be sure what is the best solution

**Comment by aliscott** [comment]
I think 1 & 2 should be fairly quick to do manually either way, and 3 is easy to do as we're going through the changes.

For 4 yeah exactly, but we can just search through afterwards and find and replace `Gb` -> `GB`.

**Comment by sinabakh** [comment]
Fixed 4, working on 1,2. They require some changes in the script.

**Comment by aliscott** [comment]
Thanks @sinabakh  I will pause https://github.com/infracost/infracost/pull/1302 for just now and move back to working on the list above.

For 1 it might be more complicated than I first thought. There's some resources that we want optional attributes for that aren't usage params, i.e. any count attribute that defaults to a non-zero value (for example https://github.com/infracost/infracost/blob/cleanup-resource-migrations/internal/resources/aws/elasticsearch_domain.go#L13-L31).

**Comment by sinabakh** [comment]
Fixed 1 with some hacks, remember to pull the latest changes.

**Comment by sinabakh** [comment]
I'll finish it.
