### ISSUE TITLE
Resources not estimated: aws_appautoscaling_policy & aws_appautoscaling_target

### ISSUE THREAD

**Issue by matthewnessworthy** [infracost/infracost#1294]
Hi,
The following resources are not estimated by infracost:

* aws_appautoscaling_policy
* aws_appautoscaling_target

## Community note

Please 👍 if you need this. Also let us know if you'd like to work on it, we'd be happy to help you!

**Comment by alikhajeh1** [comment]
Thanks @matthewnessworthy! It looks like we can use the aws_appautoscaling_target min/max and scalable_dimension to calculate a cost range. This is something that @sashman had mentioned a while ago too. We don't yet support a cost range, so I'm wondering if we should use target_value until then? What do you think?

I think we also need https://github.com/infracost/infracost/issues/849 before we can work on this as we need to lookup all aws_appautoscaling_* resources whilst processing the target resources.

**Comment by alikhajeh1** [comment]
@matthewnessworthy we're going to work on this soon, https://github.com/infracost/infracost/issues/440 is the issue to watch for updates
