### ISSUE TITLE
Please add linux-arm64 binary

### ISSUE THREAD

**Issue by timogoosen** [infracost/infracost#1317]
Could you please add a linux-arm64 binary.
This would be really useful.
For now I will just compile from source.
Thanks

**Comment by aliscott** [comment]
Thanks @timogoosen, sorry we should have done this earlier. I've added https://github.com/infracost/infracost/pull/1318 so this should start from the next release.

**Comment by timogoosen** [comment]
Thanks @aliscott

**Comment by vdmgolub** [comment]
This is live in v0.9.18. You can find the binaries here, we released an ARM64 version as well: https://github.com/infracost/infracost/releases/tag/v0.9.18.
