### ISSUE TITLE
Option to disable updated version notification

### ISSUE THREAD

**Issue by ryan-dyer-sp** [infracost/infracost#1319]
It would be great if there was an option to disable the updated version notification.  We have PRs where infracost is invoked over 2k times.  This results in a lot of notifications that the CLI has been updated that we dont care about.  If there is a way to disable this notification, it would go along way for CI purposes.

Thanks!

**Comment by aliscott** [comment]
Hi @ryan-dyer-sp you can do this by setting `INFRACOST_SKIP_UPDATE_CHECK=true` (https://www.infracost.io/docs/integrations/environment_variables/#infracost_skip_update_check)
