### ISSUE TITLE
Skip Infracost Data Resource

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#132]
In the resources list, the infracost's own data resource is also counted. We need to ignore it.

**Comment by alikhajeh1** [comment]
@sinabakh this only impacts users that use the infracost terraform provider, right?

**Comment by sinabakh** [comment]
@alikhajeh1 Yes

**Comment by sinabakh** [comment]
It seems to be fixed in master branch, my branch was releatively old. `stripInfracostResources` function takes care of it but I couldn't track the commit in which it was added.
Anyway, closing it since it seems to be invalid now.
