### ISSUE TITLE
Migrate Remaining Google Resources

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#1320]
Change the `PROVIDER` and `PROVIDER_TF` to `google` in the migrator script.

Here's a list of remaining resources:
- [x] internal/providers/terraform/google/compute_address.go @sinabakh 
- [x] internal/providers/terraform/google/compute_disk.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_external_vpn_gateway.go @sinabakh 
- [x] internal/providers/terraform/google/compute_forwarding_rule.go @sinabakh 
- [x] internal/providers/terraform/google/compute_ha_vpn_gateway.go @sinabakh 
- [x] internal/providers/terraform/google/compute_image.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_instance.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_instance_group_manager.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_machine_image.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_region_instance_group_manager.go @vdmgolub 
- [x] internal/providers/terraform/google/compute_snapshot.go @vdmgolub
- [x] internal/providers/terraform/google/compute_target_grpc_proxy.go @sinabakh 
- [x] internal/providers/terraform/google/compute_vpn_gateway.go @sinabakh 
- [x] internal/providers/terraform/google/container_cluster.go @vdmgolub 
- [x] internal/providers/terraform/google/container_node_pool.go @vdmgolub 
- [x] internal/providers/terraform/google/container_registry.go @sinabakh 
- [x] internal/providers/terraform/google/kms_crypto_key.go @sinabakh
- [x] internal/providers/terraform/google/logging_billing_account_bucket_config.go
- [x] internal/providers/terraform/google/logging_billing_account_sink.go
- [x] internal/providers/terraform/google/logging_folder_bucket_config.go
- [x] internal/providers/terraform/google/logging_folder_sink.go
- [x] internal/providers/terraform/google/logging_organization_bucket_config.go
- [x] internal/providers/terraform/google/logging_organization_sink.go
- [x] internal/providers/terraform/google/logging_project_bucket_config.go
- [x] internal/providers/terraform/google/logging_project_sink.go
- [x] internal/providers/terraform/google/network_egress_internal.go
- [x] internal/providers/terraform/google/sql_database_instance.go
- [x] internal/providers/terraform/google/storage_bucket.go @sinabakh

**Comment by sinabakh** [comment]
I think google resources are all done. I will check for missed resources. Thanks you @vdmgolub for your help with complex resources.

**Comment by alikhajeh1** [comment]
@sinabakh amazing! Feel free to close this issue after you've checked

**Comment by sinabakh** [comment]
All google resources seem to be migrated successfully.
