### ISSUE TITLE
Add arm64 Docker image 

### ISSUE THREAD

**Issue by jeremy-ke** [infracost/infracost#1321]
Hey guys,

Recently implemented infracost into some Github Actions and it works great! It's now a part of our terraform audit process.

That being said, I was wondering if an arm64 version of the infracost binary/docker image could be added to the possible releases? We're currently running our GitHub workflow on some self-hosted GitHub runners, and it would be a nice bonus to be able to run Infracost on AWS Graviton instances.

Thank you!

**Comment by alikhajeh1** [comment]
Hey @jeremy-ke - thanks! We just merged https://github.com/infracost/infracost/pull/1318 earlier today but it's not released yet. I've not used GH Actions with self-hosted runners, do you need an arm64 binary so you can bake it into your self-hosted OS image, or are you using the infracost/actions/setup task (which probably needs to be [updated](https://github.com/infracost/actions/blob/master/setup/src/index.ts) to support arm64 too)?

@aliscott could we add that as a release asset to v0.9.17 manually to unblock people? Seems like we can add release assets in GH using the edit button.
Also, do we also need to add the `linux-arm64` to the `make release` task?
Should we add windows at the same time?

**Comment by aliscott** [comment]
Good idea, I've added the linux-arm64 and windows-arm64 builds to the latest release (https://github.com/infracost/infracost/releases/tag/v0.9.17) and updated our release pipeline so these will be added going forward.

I've also created a PR for the linux/arm64 docker images. It's more difficult to update the current images, so at the moment this will start from the next release (https://github.com/infracost/infracost/pull/1322)

**Comment by jeremy-ke** [comment]
> Hey @jeremy-ke - thanks! We just merged #1318 earlier today but it's not released yet. I've not used GH Actions with self-hosted runners, do you need an arm64 binary so you can bake it into your self-hosted OS image, or are you using the infracost/actions/setup task (which probably needs to be [updated](https://github.com/infracost/actions/blob/master/setup/src/index.ts) to support arm64 too)?

Thanks so much!

Either the arm64 binary or the `infracost/actions/setup` task is great, I think either works in our context. We've just used the GitHub actions setup task for now.

**Comment by jeremy-ke** [comment]
@aliscott thanks for the quick turnaround! I'll check sometime in the next few days and report back

**Comment by jeremy-ke** [comment]
@aliscott arm64 `infracost/actions/setup@v1` github action works! thanks so much.

**Comment by aliscott** [comment]
The linux-arm64 Docker image is going to take a bit more work, so wasn't released as wasn't released as part of v0.9.18. I think we need to look into the dependencies we build in the Docker image and make sure they will work with this as well.

**Comment by alikhajeh1** [comment]
@jeremy-ke, @puzzledvacuum and @timogoosen we now [release](https://github.com/infracost/infracost/releases) ARM64 binaries for MacOS, Linux and Windows. Is it ok if I close this issue or do you need docker images too?

**Comment by jeremy-ke** [comment]
good to close @alikhajeh1. thank you so much for supporting it!

**Comment by alikhajeh1** [comment]
@jeremy-ke great - thanks!

**Comment by hilariocoelho** [comment]
> @jeremy-ke, @puzzledvacuum and @timogoosen we now [release](https://github.com/infracost/infracost/releases) ARM64 binaries for MacOS, Linux and Windows. Is it ok if I close this issue or do you need docker images too?

is it possible to also build docker images? this issue was about building docker images for arm64 but was closed after just building binaries
