### ISSUE TITLE
Infracost February community call

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1353]
### Join the first Infracost community call!
We're open to discuss any topic related to Infracost and cloud costs. You can also share your adoption challenges and successes. We'll share the latest product news.

### When
Wednesday 16 February 2022, 08:30 PST = 11:30 EST = 16:30 GMT

### Where
Zoom meeting: https://us06web.zoom.us/j/99421485564
Meeting ID: 994 2148 5564
(this meeting requires a Zoom account for joining, sign up for free on Zoom if you do not have an account)

### Calendar invites
Add this [public calendar](https://calendar.google.com/calendar/embed?src=c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com) to see upcoming event details.
  - Google Calendar: Use this email address `c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com` to [subscribe](https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Cadd-using-an-email-address).
  - iCal format: Use `https://calendar.google.com/calendar/ical/c_fvdtkbmdrqc17m1bmvlhiksb4k%40group.calendar.google.com/public/basic.ics` for other applications.

### Action required
- React with a 👍 - if you intend to join (RSVP)
- Add any topic that you think should be discussed as a comment in this issue.
- Upvote existing comments/topics.

**Comment by sbibow** [comment]
One thing I would like to hear your opinion about is #616 and how to expand infracost to also allow custom prices (especially for these on-prem resources).
It is kinda similar to #796, as in companies having internal prices for the operation and monitoring that comes from an operational team.
Maybe a single solution can be found for both enhancements.

**Comment by alikhajeh1** [comment]
Going to close this - I'll create a new issue for the next call in March (not sure when yet) - we'll advertise it well in advance.
