### ISSUE TITLE
Add support for `google_service_networking_connection` resource

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1360]
Terraform resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_connection

**Comment by torbendury** [comment]
The connection itself as a resource is not creating any costs for users. The standard pricing for ingress/egress traffic applies.

**Comment by tim775** [comment]
@torbendury Thanks for the issue!  This will go live in v0.9.21.

**Comment by vdmgolub** [comment]
@torbendury This is live with v0.9.21! Thank you! :)
