### ISSUE TITLE
Add support for RDS reserved instance charges 

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#1373]
[AWS DB Instance](https://github.com/infracost/infracost/blob/master/internal/resources/aws/db_instance.go) and [AWS RDS Cluster Instance](https://github.com/infracost/infracost/blob/master/internal/resources/aws/rds_cluster_instance.go) should be updated to support a usage param for reservered instance charges that saw way [EC2 Instance](https://github.com/infracost/infracost/blob/master/internal/resources/aws/instance.go) does.

**Comment by robh007** [comment]
I'll have a look at this @tim775 unless someone else is looking at it.

**Comment by aliscott** [comment]
Thanks @robh007 🙏

**Comment by robh007** [comment]
@tim775 @aliscott - Unless I'm missing something, RDS resources appear to support reserved instances via usage params.

**Comment by alikhajeh1** [comment]
@robh007 good catch! I think we just need to update [this example](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L303) with the same params as [here](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L318-L319) and test that both work.

We can also add a sentence to the Notes column of [this file](https://github.com/infracost/docs/blob/master/docs/supported_resources/aws.md) for RDS to say "Reserved instance settings can be set in the [usage file](https://github.com/infracost/docs/blob/master/docs/features/usage_based_resources)."

**Comment by robh007** [comment]
Thanks @alikhajeh1  I'll get a PR for the changes you've mentioned above.

**Comment by robh007** [comment]
I think this can be closed as the `aws_rds_cluster` resource doesn't support Reserved instances. This resource is for Serverless Aurora or used in conjuntion with `aws_rds_cluster_instance` or `db_instance` which both support Reserved instances via the usage file.

**Comment by alikhajeh1** [comment]
ah yes - thanks!
