### ISSUE TITLE
Cleaner / reduced output

### ISSUE THREAD

**Issue by ryan-dyer-sp** [infracost/infracost#1380]
Am requesting that the output from infracost be cleaner or reduced.  Our use case is that we run infracost with PRs which contain multiple terragrunt projects.  This in turn runs multiple(sometimes dozens) infracost breakdowns and outputs.  

For the breakdown it would be nice if there was a way to only output errors. 
```
> infracost breakdown --no-color --format json --out-file cost.json --path . --log-level error >/dev/null

Output saved to cost.json
```
Why is this being output to stderr?  Why it it being output at all if I'm specifying log-level error?  This is not an error.

Secondly the output:
```
> infracost output --no-color --path cost.json --format diff
──────────────────────────────────

The following projects have no cost estimate changes: develop/logging/us-east-1/apps
Run infracost breakdown to see their full breakdown.

──────────────────────────────────
9 cloud resources were detected, rerun with --show-skipped to see details:
∙ 5 were estimated, 3 include usage-based costs, see https://infracost.io/usage-file
∙ 4 were free

Add cost estimates to your pull requests: https://infracost.io/cicd
```
In this case there are no changes.  This is a lot of output to tell us 0 changes.  Can we please get some sort of reduced output single line option when there are 0 changes.  

Also I understand the various helper lines in this output. However in a CICD scenario, none of this is useful and is just spam.
* Run infracost breakdown to see their full breakdown.
* Add cost estimates to your pull requests: https://infracost.io/cicd
* <empty/newlines>

**Comment by ryan-dyer-sp** [comment]
#1. Thanks
#2. We do not use any of the formats other than text.  Though this is part of our CICD pipeline, its ran through atlantis.  I'm not sure how well atlantis will take to receiving bitbucket text, or more accurately how well bitbucket will respond to bitbucket markup within a code block.  My guess is it will just end up displaying all the markup, which is not what we want either.  I'll play around with it though and see if there is a better format which will work.

**Comment by alikhajeh1** [comment]
#2: Depending on what version of Atlantis you're using, you can get Infracost to post a separate comment to Bitbucket using [this](https://github.com/infracost/infracost-atlantis) and the [`infracost comment bitbucket`](https://www.infracost.io/docs/features/cli_commands/#bitbucket) command. 

We literally released the final docs PRs for this 10mins ago in v0.9.18, see [this for screenshots](https://github.com/infracost/infracost/pull/1363#discussion_r803880215). @vdmgolub tested those with Bitbucket Cloud and Server and tried various things to make them look as nice as he could but as you say, the collapsed sections aren't supported by Bitbucket yet so it's not as nice as github. Please let us know how it goes as we'd be happy to iterate on this.

**Comment by ryan-dyer-sp** [comment]
Awesome.  Will play around with the new comment functionality tomorrow and let you know.  TYVM!

**Comment by ryan-dyer-sp** [comment]
Was able to use the new infracost comment bitbucket functionality within atlantis to output a single comment as part of a post_workflow_hook.  This worked great to minimize the output from infracost when having multiple projects/breakdowns.

Thanks!

**Comment by aliscott** [comment]
>  we didn't want those log lines to go to stdout as that would make the JSON file invalid. So I think we went with putting those in stderr. @aliscott did I remember that right?

Yeah that's the reasoning, but @ryan-dyer-sp has a great point - we shouldn't be outputting this if the log-level is set. I've sent a PR to fix this case going forward: https://github.com/infracost/infracost/pull/1383

**Comment by aliscott** [comment]
> @aliscott thanks for the PR, should we also hide the line "Run infracost breakdown to see their full breakdown" in CI?

I don't have a strong opinion about this. Do we see a need for CI users to dig into why there's no changes if they're not expecting it?

**Comment by alikhajeh1** [comment]
@aliscott fair point. I'll close this issue for now but we can keep discussing it if @ryan-dyer-sp has a strong opinion on it. I'll also look out in case other users complain about spam in CI.

**Comment by guidodobboletta** [comment]
It would be nice to add a way on which the `github-comment` format be edited. I'd love to have the `Infracost output` be changed to either HTML for easier reading on the PR if you want to get the detailed output or using the `table` format instead.

**Comment by alikhajeh1** [comment]
@guidodobboletta have you tried enabling https://www.infracost.io/docs/features/share_links/? This results in the bottom of the `Infracost output` section to have a link ([example](https://dashboard.infracost.io/share/deaczrvclzv9z8yf76dex0t4dpxx9buj)), which shows a diff and table tab. Perhaps when share links are enabled, the whole words "Infracost output" should just be a link to the report?

**Comment by guidodobboletta** [comment]
That looks pretty cool but I wish we had that as part of the PR. It seems to me a pretty big security concern making core parts of the infrastructure readable on the public internet

**Comment by alikhajeh1** [comment]
Thanks! The link has a token that's generated using the API key, so it's similar to a pre-authenticated S3 download link, but I understand your concern. Our longer term plan is to have a signup flow for the dashboard so these links could go behind that.
