### ISSUE TITLE
Update CircleCI Orb readme to describe the new CI Docker images and `infracost comment`

### ISSUE THREAD

**Issue by oeuftete** [infracost/infracost#1381]
We need to update https://github.com/infracost/infracost-orb to describe or link to [this](https://www.infracost.io/docs/integrations/cicd/#my-cicd-system-isnt-supported), as we're no longer maintaining the old diff.sh script.

--- 

Original issue description:

I'd like to have terraform 1.1 available in the latest docker image in order to integrate infracost into our CI workflow using the CircleCI Orb.  Without it, I get failures related to [the new `moved` syntax](https://www.terraform.io/language/modules/develop/refactoring).  Happy to put up a PR if there aren't reasons not to add this!

```text
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /workspace/.terraform/output-dev/tfplan
time="2022-02-17T02:22:03Z" level=info msg="Detected Terraform plan file at /workspace/.terraform/output-dev/tfplan"
time="2022-02-17T02:22:04Z" level=info msg="Starting: Running terraform show"

Error: terraform show failed: exit status 1

  Terraform command failed with:
    Error: Unsupported block type
      on foo.tf line 25:
      (source code not available)
    Blocks of type "moved" are not expected here.
    Error: Unsupported block type
      on foo.tf line 37:
      (source code not available)
    Blocks of type "moved" are not expected here.
```

**Comment by alikhajeh1** [comment]
Hi @oeuftete - we're in the process of moving away from our old approach (that relied on the TF CLI being baked into the Infracost docker image and running the diff.sh script). We haven't had a chance to update our CircleCI Orb yet, but the other CI/CD integrations have been updated to use this approach - can you possibly try this and let us know if it works ok?

1. Use our new [CI Docker images](https://www.infracost.io/docs/integrations/cicd/#docker-images)
2. Generate a Terraform plan JSON file using the official Terraform image (this enables you to use any version of TF)
3. Use the Terraform plan JSON file as follows:
```
infracost breakdown --path terraform_plan.json --format json --out-file infracost.json
infracost comment github --path infracost.json # or infracost comment bitbucket
```

[Our GitLab CI integration](https://gitlab.com/infracost/infracost-gitlab-ci) does this, here are the docs for the `infracost comment` command - do you use github or bitbucket?
- https://www.infracost.io/docs/features/cli_commands/#circleci-with-github
- https://www.infracost.io/docs/features/cli_commands/#circleci-with-bitbucket

**Comment by oeuftete** [comment]
@alikhajeh1 Thanks for the prompt response, I appreciate it.  I jumped the gun a bit, and noticed I wasn't converting the plan from binary to json using the old approach, so I do have it working now.  But I'll try the new approach (we're using github).

**Comment by alikhajeh1** [comment]
@oeuftete awesome! When you get the chance to try it, I'd appreciate it if you let me know if the new approach worked for you too.

Ok if I update this issue's title/desc a bit so it reminds us to update the CircleCI Orb readme to describe the new method?

**Comment by oeuftete** [comment]
> @oeuftete awesome! When you get the chance to try it, I'd appreciate it if you let me know if the new approach worked for you too.

New approach worked great.

> Ok if I update this issue's title/desc a bit so it reminds us to update the CircleCI Orb readme to describe the new method?

For sure.

Thanks again for the assistance, @alikhajeh1 .

**Comment by alikhajeh1** [comment]
@oeuftete that's great! I updated [this docs section](https://www.infracost.io/docs/integrations/cicd/#my-cicd-system-isnt-supported) with the above details.

**Comment by alikhajeh1** [comment]
@oeuftete can you please take a quick look at https://github.com/infracost/infracost-circleci and let us know what you think? @aliscott decided to JEDI this GH issue instead of linking to the docs and letting users figure-out the rest (JEDI = Just Effing Do It 😄)
