### ISSUE TITLE
Azure Dedicated App Service Plan with Function App Bug

### ISSUE THREAD

**Issue by t-dever** [infracost/infracost#1384]
It is still possible to use "dedicated" app service hosting plans such as "PremiumV2" (P1v2) for azure functions. Currently Infracost is skipping the App Service Plan pricing if it's being used for a function app. Because it is expecting an "EP" plan (example EP1)

Current Outcome:
Skips calculating cost for function.

- "Skipping resource azurerm_function_app.app. Could not find a way to get its cost components from the resource or usage file."

Skips calculating cost for app service plan.
- "Hiding cost with no usage: azurerm_app_service_plan.app_service_plan 'Instance usage (P1v2)'"

Expected Outcome:
If an App Service plan is deployed with "PremiumV2" and azure function is using the app service plan then infracost should calculate the price of the App Service plan not the price of the Functions.

Example Terraform:

```terraform
resource "azurerm_app_service_plan" "app_service_plan" {
  name                = var.app_service_plan_name
  resource_group_name = "resource-group"
  location            = "location"
  kind                = "linux"
  reserved            = true

  sku {
    tier = "PremiumV2"
    size = "P1v2"
  }
}
```

```terraform
resource "azurerm_function_app" "app" {
  name                       = "test-app"
  resource_group_name        = "resource-group"
  location                   = "location
  app_service_plan_id        = azurerm_app_service_plan.app_service_plan.id
  os_type                    = "linux"
  version                    = "~4"
  https_only                 = true
}
```

**Comment by tim775** [comment]
@t-dever Thanks for the issue, could you try setting the capacity for the `azurerm_app_service_plan` and let me know if that gives you the expected cost:
```
sku {
    tier = "PremiumV2"
    size = "P1v2"
    capacity = 1
  }
```

Our code currently defaults to capacity=0 if it is not set which is why it's not showing any charges.  I guess this should default to 1?  I don't see anywhere in the azure docs where they explicitly say what the default capacity is.

**Comment by vdmgolub** [comment]
Thank you for reporting the issue! We updated the resource default capacity to be 1. This will be out with the next release.
