### ISSUE TITLE
Commenting for Bitbucket Server is broken

### ISSUE THREAD

**Issue by lazzurs** [infracost/infracost#1396]
The new support for commenting in Bitbucket Server is broken. Right now the URL that is built for the API only works with the Bitbucket 2.0 API that is used in Bitbucket cloud.

In 2.0 the path to pull requests uses "pullrequests" in the URL but for the 1.0 API it uses "pull-requests".

Link to 1.0 API:
https://docs.atlassian.com/bitbucket-server/rest/7.20.0/bitbucket-rest.html#idp332

Link to 2.0 API:
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-pull-request-id-comments-post

There are two lines where this needs to be fixed.
https://github.com/infracost/infracost/blob/master/internal/comment/bitbucket.go#L171
https://github.com/infracost/infracost/blob/master/internal/comment/bitbucket.go#L239

**Comment by vdmgolub** [comment]
@lazzurs Hello! Thank you for creating the issue! Does it fail for you? By default the command works with Bitbucket Cloud, if you want to use it with Bitbucket Server, you need to provide `--bitbucket-server-url` flag with the URL of your server.

The code you mentioned is for Bitbucket Cloud, but this file also has a dedicated Bitbucket Server handler and it uses v1 API: https://github.com/infracost/infracost/blob/master/internal/comment/bitbucket.go#L648.

Here's where it decides which one to use: https://github.com/infracost/infracost/blob/master/internal/comment/bitbucket.go#L137.

**Comment by lazzurs** [comment]
Yes it does fail for me. I tried switching over to the new support and found I was getting 500 errors back from the server.

When I had a further look into it as you can see from the documentation links above I found the issue with pullrequests vs pull-requests in the API versions.

I have submitted a PR which should allow support for both API versions to work.

**Comment by lazzurs** [comment]
Oh, so looking at the first link you posted that is interesting...maybe this is my bad in understanding the code.

**Comment by vdmgolub** [comment]
May I ask you how you use it with your Bitbucket Server? What is your full comment command? We mention the `--bitbucket-server-url` in the command's help and briefly in our docs https://www.infracost.io/docs/features/cli_commands/#bitbucket, so we might need to make it more discoverable :) Or there might be an issue with the URL detection.

**Comment by vdmgolub** [comment]
BTW, you can also join our community [Slack](https://www.infracost.io/community-chat) if this is an easier way to discuss the issue :)

**Comment by lazzurs** [comment]
I have joined the community Slack.

**Comment by lazzurs** [comment]
On further investigation this is because of lack of unicode support.

Manually trying to add the same comment Infracost is doing cause a similar failed.

## 💰 Infracost estimate: **monthly cost will not change** <- did not work and caused an error

## Infracost estimate: **monthly cost will not change** <- worked without error.

On further investigation this is not the only time this has come up with Bitbucket server.

https://github.com/renovatebot/renovate/issues/6424 <- another project with the same issue.

For now until Bitbucket Server is out of support it would be best to remove any emoji from being used with Bitbucket Server comments. I would suggest other servers should keep the emoji as it looks good.

**Comment by vdmgolub** [comment]
Thank you for reporting and fixing the issue! This is merged and will go live in the next release.

**Comment by tim775** [comment]
@lazzurs This is live in v0.9.19.  Thanks!
