### ISSUE TITLE
Add support - AWS/DocumentDB

### ISSUE THREAD

**Issue by SiahaanBernard** [infracost/infracost#140]
### Placeholder Issue
I'll try to work on this issue.
### Additional Info:
- [Pricing](https://aws.amazon.com/documentdb/pricing/)
- [Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster)

**Comment by alikhajeh1** [comment]
@SiahaanBernard thanks for creating this issue and offering to work on it. Have you seen https://www.infracost.io/docs/supported_resources/ ? Infracost already supports `aws_docdb_cluster_instance`, and I might be missing something but `aws_docdb_cluster` itself has no cost, the `aws_docdb_cluster_instance` does.

**Comment by SiahaanBernard** [comment]
Ah my bad. You are correct. Closing this issue.
