### ISSUE TITLE
Disable progress bar for CI/CD pipeline usage

### ISSUE THREAD

**Issue by torbendury** [infracost/infracost#1403]
Hello everyone,

first of all thanks for this great tool!

We baked it into our CI/CD pipelines so we can directly see cost changes when running Terraform, but the progress "text" is somehow cluttering the outputs. I'd like to keep it as clean as possible and hide such things.

**Expected:** I don't see the progress output when I don't want it

**Actual:** I see something like this:

```bash
Detected Terraform plan JSON file at /tmp/state.kCsuFt


  ⠋ Extracting only cost-related params from terraform 

  ⠙ Extracting only cost-related params from terraform 

  ⠹ Extracting only cost-related params from terraform 

  ⠸ Extracting only cost-related params from terraform 

  ⠼ Extracting only cost-related params from terraform 

  ⠴ Extracting only cost-related params from terraform 

  ⠦ Extracting only cost-related params from terraform 

  ⠧ Extracting only cost-related params from terraform 

  ⠇ Extracting only cost-related params from terraform 

  ⠏ Extracting only cost-related params from terraform 

  ⠋ Extracting only cost-related params from terraform 
  ✔ Extracting only cost-related params from terraform


  ⠋ Retrieving cloud prices to calculate costs 

  ⠙ Retrieving cloud prices to calculate costs 

  ⠹ Retrieving cloud prices to calculate costs 

  ⠸ Retrieving cloud prices to calculate costs 

  ⠼ Retrieving cloud prices to calculate costs 

  ⠴ Retrieving cloud prices to calculate costs 

  ⠦ Retrieving cloud prices to calculate costs 

  ⠧ Retrieving cloud prices to calculate costs 

  ⠇ Retrieving cloud prices to calculate costs 

  ⠏ Retrieving cloud prices to calculate costs 

  ⠼ Retrieving cloud prices to calculate costs 

  ⠴ Retrieving cloud prices to calculate costs 

  ⠦ Retrieving cloud prices to calculate costs 
  ✔ Retrieving cloud prices to calculate costs
```

This might be a nice and fancy thing for running `infracost` manually from a local terminal where this can be displayed correctly, but e.g. Jenkins is not capable of this.

**Comment by aliscott** [comment]
@torbendury if you set the log level then it should turn these spinners off. You can do this by setting the env var `INFRACOST_LOG_LEVEL=info` or passing the flag `--log-level=info`. Let me know if that works for you.

**Comment by torbendury** [comment]
hey @aliscott thank you for the answer. I experimented a bit and `--log-level=error` did the trick for me (there were some info/warnings that were not relevant for us).

As an info for everyone else: The log level provided by @aliscott already turns of the spinners.
