### ISSUE TITLE
Resource to support: `aws_elastic_beanstalk_environment`

### ISSUE THREAD

**Issue by lukeadams84** [infracost/infracost#1410]
Please can you add support for `aws_elastic_beanstalk_environment`

**Comment by alikhajeh1** [comment]
Thanks @lukeadams84! The community has helped us add a lot of resource mappings so please let us know if you have time to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#adding-new-resources) and we can add the cost component details to make it easier for you to contribute.

**Comment by lukeadams84** [comment]
I have had a look at some of your documentation, elastic beanstalk looks a little complicated because of the way it wraps multiple resource types. It will involve iterating through the settings variables in terraform in order to identify instance size, asg min nodes and so on.

**Comment by hugorut** [comment]
Thanks to @lukeadams84 a fix for this has been merged to master and will be out in the `v.0.9.20` release

**Comment by hugorut** [comment]
hey @lukeadams84  this has now been released as part of the [v.0.9.20](https://github.com/infracost/infracost/releases/tag/v0.9.20) release. Thanks for all your hard work.
