### ISSUE TITLE
Add a `terraform-init-flags` flag

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1413]
Previous discussion:
* https://github.com/infracost/infracost/issues/953
* https://github.com/infracost/infracost/pull/1172#issuecomment-984893767

Infracost has a method of passing custom flags for when Infracost runs `terraform plan`, but it doesn't support passing custom flags to `terraform init`.

This will be useful for users who
1. Want to auto-upgrade modules using `terraform init -upgrade`
2. Pass a custom backend config using `terraform init -backend-config=path`

**Comment by alikhajeh1** [comment]
@gudylf just FYI that this was released in v0.9.21 recently. `infracost breakdown` and `diff` can be run with a new `--terraform-init-flags` option:
```
infracost breakdown --path path/to/code \
    --terraform-init-flags "-upgrade=true" \
    --terraform-plan-flags "-var-file=my.tfvars"
```
