### ISSUE TITLE
HCL Parsing doesn't report `azurerm_app_service_plan`

### ISSUE THREAD

**Issue by bgrainger** [infracost/infracost#1433]
I just tried the new `infracost breakdown --path=. --terraform-parse-hcl`. It is so much faster! 🎉

However, it didn't report my `azurerm_app_service_plan` resource, so it omitted $229.95 of costs. The rest of the output was identical though.

Here's the end of the output from regular `infracost breakdown`:

```
[ 31 lines skipped]
 module.XXX.azurerm_application_insights.this

 +- Data ingested                                                             Monthly cost depends on usage: $2.30 per GB


 module.XXX.azurerm_app_service_plan.service_plan

 +- Instance usage (P1v3)                                                                    730  hours
         $229.95


 OVERALL TOTAL
         $455.87
----------------------------------
23 cloud resources were detected, rerun with --show-skipped to see details:
· 5 were estimated, 4 include usage-based costs, see https://infracost.io/usage-file
· 11 weren't estimated, report them in https://github.com/infracost/infracost
· 7 were free
```

Here's the end of the output from `infracost breakdown --terraform-parse-hcl` (the beginning lines are the same):

```
[ 31 lines skipped ]
 module.XXX.azurerm_application_insights.this

 +- Data ingested                                                             Monthly cost depends on usage: $2.30 per GB


 OVERALL TOTAL
         $225.92
----------------------------------
23 cloud resources were detected, rerun with --show-skipped to see details:
· 5 were estimated, 4 include usage-based costs, see https://infracost.io/usage-file
· 11 weren't estimated, report them in https://github.com/infracost/infracost
· 7 were free
```

As you can see, the `module.XXX.azurerm_app_service_plan.service_plan` resource is entirely missing when using `--terraform-parse-hcl`.

**Comment by tim775** [comment]
@bgrainger Thanks for the report, this is exactly the kind of thing we're hoping the community can help us find!  Is there any chance you could send a sanitized tf project with the issue so we can reproduce it?

**Comment by bgrainger** [comment]
Here's a file that reproduces the problem:

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.98"
    }
  }

  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}

  subscription_id = "[redacted]"
}

resource "azurerm_resource_group" "this" {
  name     = "Issue1433"
  location = "westus2"
}

resource "azurerm_app_service_plan" "this" {
  name                = "issue1433-plan"
  location            = resource.azurerm_resource_group.this.location
  resource_group_name = resource.azurerm_resource_group.this.name

  sku {
    tier = "PremiumV3"
    size = "P1v3"
    # capacity = 1
  }
}
```

Without `capacity = 1` (an optional property, and I assume `1` is the default), `--terraform-parse-hcl` calculates a monthly cost of $0.00.

**Comment by vdmgolub** [comment]
@bgrainger Thank you for the provided example! We're working on resolving this.

**Comment by vdmgolub** [comment]
@bgrainger Both terraform plan and HCL parsing result in empty estimate if `capacity` is omitted. We updated the resource to have a default capacity 1 if the attribute is not set (#1435). It will go out with the next release. Until then setting `capacity = 1` should be able to unblock you. We'll notify when it is live. Thank you for reporting the issue!

**Comment by vdmgolub** [comment]
@bgrainger If that's okay, I'm going to close this issue for now. We'll notify when a new release is out, so you'll receive a notification.
