### ISSUE TITLE
Dashboard projects list is missing the project

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1439]
From Slack: I'm trying to set up usage-based resource reporting to the Dashboard. I'm seeing reports upload, but there are a few issues. The command I run is:
`INFRACOST_ENABLE_DASHBOARD=true infracost breakdown --path spacelift.plan.json --sync-usage-file --usage-file /tmp/ignore1.yml`
The usage file doesn't exist, so all data should be fresh.
Infracost runs and prints a final line:
Share this cost estimate: https://dashboard.infracost.io/share/<redacted>
This link takes me to the dashboard where I can view the data with usage information attached. Yay! :raised_hands:
However, the report doesn't appear in my project list
The project appears and there are multiple reports with similar timestamps, but they don't contain usage data

**Comment by aliscott** [comment]
I'm not able to reproduce this. Do you have a screenshot or reproduction steps?

**Comment by alexjurkiewicz** [comment]
Sorry, I went to get screenshots and the data is in both places now! I
probably misreported this -- sorry, you can close.

**Comment by aliscott** [comment]
Thanks @alexjurkiewicz 🙏 ! Let us know if you see this again.
