### ISSUE TITLE
Automatically expire share links

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1441]
From Slack: I would like [links](https://www.infracost.io/docs/features/share_links/) to expire after a few days before testing this further. It doesn't feel great to create public web pages with cost data, even if they are unlisted. as mvp, just knowing the information will eventually vanish is fine. I don't imagine we'd use reports after 7 days right now. long-term, I guess I'd like reports to exist forever but only be accessible to people in my org.

### Proposed solution
Expire links automatically after 7 days.

**Comment by hugorut** [comment]
I'd be more for having these behind a login.

**Comment by vdmgolub** [comment]
Login functionality and public link are different features, and in a long run I think we need to support both. Having the reports behind the login requires org's different team members to have an account in Infracost.

**Comment by hugorut** [comment]
> Having the reports behind the login requires org's different team members to have an account in Infracost.

@vdmgolub I think this is advantageous and a better solution. I really don't like these public links.

**Comment by vdmgolub** [comment]
I totally agree, but it's a big commitment with time and effort (and existing users migration). The share links are already released and can help our users today. We'll get to the accounts eventually, but right now we can make the links more usable with the expiration timer.

We either can default it to a specific number (7 days for example), or introduce `infracost configure set share_link_expiration_days 7` option.

**Comment by hugorut** [comment]
Yup agree that in the short term this could be beneficial to existing users.

**Comment by alexjurkiewicz** [comment]
For my purposes, having any non-infinite expiry is going to be reassuring.
I don't care if it's 7 or 30 days (I'd prefer 7). Customising the number is
unimportant.  As Hugo says, I wouldn't want to use public links in the
long-term.

**Comment by vdmgolub** [comment]
@alexjurkiewicz Thanks!

Until we have something for this in place, and you'd like to try the share links feature, you can reach out to us and we will invalidate the links for you.

**Comment by alikhajeh1** [comment]
Going to close this issue as most users are moving to using [Infracost Cloud](https://www.infracost.io/docs/infracost_cloud/get_started/) to [share](https://www.infracost.io/docs/infracost_cloud/key_concepts/#team-management) access to all runs with their teams. That gives them control over who sees what.
