### ISSUE TITLE
Disable "Add cost estimates to your pull requests: https://infracost.io/cicd" output

### ISSUE THREAD

**Issue by VasseurLaurent** [infracost/infracost#1459]
Hello everyone, 

Like written in this issue, I would to know if it is possible to disable the output : `Add cost estimates to your pull requests: https://infracost.io/cicd` when I am launching infracost from my computer. 

Of course, I know that this output is disabled when infracost is launched in a CI/CD. 
I saw in this [issue](https://github.com/infracost/infracost/issues/1380) that you added this output to let people knows that adding infracost `comments` in CI/CD was possible, but it would be great to be able to disable it when we want to launch infracost from computers (like during the development of a new module or new infra).

An environment variable such as `INFRACOST_SKIP_CI_MESSAGE` would be great (same idea as `INFRACOST_SKIP_UPDATE_CHECK` for updates)

Have a nice day !

**Comment by aliscott** [comment]
Thanks @VasseurLaurent 🙏 . @alikhajeh1 what do you think of the env variable for this or an alternative suggestion?

**Comment by vdmgolub** [comment]
@VasseurLaurent This message is removed in scope of #1477 which is merged to master. It will go live with the next release. We'll notify when it's out. Thank you for reporting! :)

**Comment by vdmgolub** [comment]
@VasseurLaurent This fix is live with v0.9.21! Thank you! :)
