### ISSUE TITLE
Tell the user when there is no .tf file to estimate cost

### ISSUE THREAD

**Issue by akhan4u** [infracost/infracost#146]
Hi Team,

I have noticed one issue after setting the Infracost API key, that infracost is not complaining about the .tf file not being present at my current location. However, If I am running it at the place where .tf files are present it will present me with the cost estimate. 

![Infracost_Error](https://i.ibb.co/gdTpKxf/infracost.png)

Not sure, Is infracost making an API call and generating some error logs at the server side when there is no .tf file?
```
infracost
error loading resources: error loading resources: error generating terraform execution plan: exit status 1
```
Instead of the above error, I  think it should tell the user that you don't have any terraform files in the current location.

**Comment by aliscott** [comment]
Thank you @akhan4u! I've added some changes to improve error handling in #147 and it covers this issue. This has now been released in v0.6.2.
