### ISSUE TITLE
Custom integration support for infracost 

### ISSUE THREAD

**Issue by Zheaoli** [infracost/infracost#1497]
Hello all,

I'm using infracost now, but now we have got some issues:

1. We use an IM named Lark now, we want to add message sending support for this IM software.
2. We want to collect all the pricing diff data to our self-hosted database.

So if there is any possibility to support custom integration/plugins for infracost?

### Note for community
Please 👍 if you'd like to upvote this or receive updates.

**Comment by vdmgolub** [comment]
@Zheaoli Hello! It's a great question! Infracost currently has several integrations with services like Env0 or Spacelift ([integrations list](https://www.infracost.io/docs/integrations/cicd/) may be a source of examples), and CLI supports a dedicated Slack format output.

However, there is no an out-of-the-box solution for Lark. But it is possible to run Infracost, get its output in JSON format, extract data and prepare a message via tools like `jq` and send it to Lark API via curl. For example, we use curl to send a Slack message: https://github.com/infracost/actions/tree/master/examples/slack. It looks like Lark's API allows to do that: https://open.larksuite.com/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/create_json.

With regards to the diff data collection, `infracost diff --format json --out-file diff.json` flags may help with collecting data as files, but you'll have to process it manually. This will require custom code from your side.

**Comment by Zheaoli** [comment]
@vdmgolub Wow thanks for your paticence.

I think for right now processing the output JSON by myself is the best way. For the future, I think maybe supporting custom plugin would be a good choice!

**Comment by vdmgolub** [comment]
@Zheaoli You're very welcome! :) To be honest, I've discovered about Lark today from you :D. There are too many tools and services nowadays, it's hard to keep up 😅. Slack seems to be the most popular IM right now. We rely on our open source community to bring the use cases that we don't know about and together evolve the functionality.

It seems like adding an Infracost bot/plugin for Lark may be a great opportunity for such contribution :).

Our [docs](https://www.infracost.io/docs/) should help explaining different options/flags, but feel free to ask here on GitHub or join our [community Slack](https://www.infracost.io/community-chat) where community may help too. :)

**Comment by Zheaoli** [comment]
If the community would like to add Lark as official support IM. I'm glad to make a PR for it !

**Comment by alikhajeh1** [comment]
Thanks @Zheaoli! I added a "Note for community" to the issue description so we can get more input from the community.

Regarding your second point ("We want to collect all the pricing diff data to our self-hosted database"), I've spoken with other users who are storing the [Infracost JSON](https://www.infracost.io/docs/features/cli_commands/#combined-output-formats) in their own DB to analyze things later (`diff`/`breakdown`/`output` all produce the same JSON format) - so that's a good approach, keep going :) This is something we plan to build in the future as part of our product to provide visibility dashboards but when we get to that, we'll chat with you to learn more (I'm not sure when that'll be yet).

**Comment by alikhajeh1** [comment]
Hi @Zheaoli - we recently [released v0.10](https://www.infracost.io/docs/guides/v0.10_migration/) and are now focusing on the dashboard, I'd love to show you some wireframes and get your feedback. Can you please email me (ali.hosseini@infracost.io) some dates/times that work for a call? I'm in the US Pacific timezone so my evenings should be your day time.
