### ISSUE TITLE
Add support for azurerm_virtual_wan and related ressources

### ISSUE THREAD

**Issue by matthieupetite** [infracost/infracost#1501]
# Context

In our landing zone we use the Azure Virtual Wan as a base component to deploy our connectivity landing zone. That resources is very important because it's now the main component to enable the connectivity in the Cloud Adoption Framework developed by MS. Unfortunatly the component is not quoted yet with infracost even if it's quite expensive and has a major impact in the global price. The other think is that the azure calculator give a price but for more than one ressources such as 

- azurerm_virtual_wan
- azurerm_virtual_hub
- azurerm_virtual_hub_connection
- azurerm_virtual_bgp_connection
- azurerm_firewall or third party connection

And all the connection resources such as the vpn gateway, the express route gateway, ...

# Azure pricing calculator sample 

![image](https://user-images.githubusercontent.com/4076681/160379772-ed812ac4-a5d6-4b93-80fd-b4be6ea55610.png)

# Price list associate with virtual wan

|   service   | productFamily |                                 ?column?                                 |                                 ?column?                                 | ?column?
|-------------|---------------|--------------------------------------------------------------------------|--------------------------------------------------------------------------|----------
| Virtual WAN | Networking    | App Gateway Unit                                                         | App Gateway Unit                                                         |
| Virtual WAN | Networking    | ExpressRoute Additional Scale Unit                                       | ExpressRoute Additional Scale Unit                                       |
| Virtual WAN | Networking    | ExpressRoute Connection Unit                                             | ExpressRoute Connection Unit                                             |
| Virtual WAN | Networking    | ExpressRoute Scale Unit                                                  | ExpressRoute Scale Unit                                                  |
| Virtual WAN | Networking    | Hub to Hub Transfer                                                      | Hub to Hub Transfer                                                      |
| Virtual WAN | Networking    | NVA Infrastructure Unit                                                  | NVA Infrastructure Unit                                                  |
| Virtual WAN | Networking    | Routing Infrastructure Unit                                              | Routing Infrastructure Unit                                              |
| Virtual WAN | Networking    | Standard Hub                                                             | Data Processed                                                           |
| Virtual WAN | Networking    | Standard Hub                                                             | Standard Hub                                                             |
| Virtual WAN | Networking    | Standard Hub with Firewall policies for Third party security provider(s) | Data Processed                                                           |
| Virtual WAN | Networking    | Standard Hub with Firewall policies for Third party security provider(s) | Standard Hub with Firewall policies for Third party security provider(s) |
| Virtual WAN | Networking    | VPN P2S Connection Unit                                                  | VPN P2S Connection Unit                                                  |
| Virtual WAN | Networking    | VPN P2S Scale Unit                                                       | VPN P2S Scale Unit                                                       |
| Virtual WAN | Networking    | VPN Policy Unit                                                          | VPN Policy Unit                                                          |
| Virtual WAN | Networking    | VPN S2S Connection Unit                                                  | VPN S2S Connection Unit                                                  |
| Virtual WAN | Networking    | VPN S2S Scale Unit                                                       | VPN S2S Scale Unit                                                       |

# Question 

I plan to work on that to add the support of the virtual wan on infracost but I definitly need some advice on what is the good strategy regarding the PR associated with the component and how we can manage to add it with avoiding the BIG FAT Feature pattern ;)

**Comment by hugorut** [comment]
Hi @matthieupetite , thanks for raising this. We did actually have a user already request WAN support. The closed issue is here: https://github.com/infracost/infracost/issues/910 . WAN support was resolved as part of https://github.com/infracost/infracost/pull/1189. This change includes a lot of what you mentioned above, so I'm keen to understand what's missing from your perspective. Thanks!

**Comment by matthieupetite** [comment]
Hello It s a bit confusing to see thé wvan as a free resource cause if you add it in the calculator without any connections there is a price

**Comment by matthieupetite** [comment]
For sure you can close the issue and thanks for your light on that point. I will try to run infracost on our landing zone that use a vwan an try to monitor the pricing related to our component and try to find out if there is delta between the calculator price and what infracost shows. It problably will show an epsilon, on the other hand I will let you know...

**Comment by hugorut** [comment]
Perfect thanks @matthieupetite , much appreciated 

![](https://media.giphy.com/media/7aBE32jCr6lOhtuE9v/giphy.gif)

**Comment by spotakash** [comment]
Just For your information, vWAN has running cost associated with `azurerm_virtual_hub`. Which has not been picked up

![image](https://user-images.githubusercontent.com/7689697/190122735-b1101593-fad1-410d-8c23-93532bcc46d2.png)

Another issue, I found that it does not detect cost associated with multi-subscription deployment scenario example: deployed Landing Zone where different component are running under different subscription, yet part of single deployment code.

**Comment by spotakash** [comment]
I am trying to use this module to deploy Azure LandingZone which allow us to deploy different part of Landing Zone into different subscription. You may refer [guidance here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Provider-Configuration#multi-subscription-deployment).

Please refer `azurerm_virtual_hub `and `vWAN `code block for [module here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Virtual-WAN-Resources-With-Custom-Settings#maintf)

Just FYI, when I ran infacost, it could only detect one subscription of deployment (not entire landscape as module running different component across different subscriptions). 
![image](https://user-images.githubusercontent.com/7689697/190863839-b91cb338-cf6f-4f42-ae24-e7d673cfac41.png)


As enterprise operates across multiple subscription (with linked resource), it will be great if Infracost can detect it end to end cost mapped to subscription in single execution.

**Comment by spotakash** [comment]
@hugorut i have provided information, sample and repo. Is there any update?

**Comment by hugorut** [comment]
@spotakash the problem you are having seems to be related to the third-party module you are using. Infracost displays a "Data processed" pricing for `azurerm_virtual_hub` if it can detect that this resource has been used. From the example output you've posted, it seems we don't pick that up. I suspect this is because the third-party module your using has some complexities within it that Infracost is struggling with. I'd recommend switching to our plan JSON method of providing cost estimates, as this will negate having to parse this complex module. This can be done using cmds like this:

```
cd path/to/code

terraform init
terraform plan -out tfplan.binary
terraform show -json tfplan.binary > plan.json

infracost breakdown --path plan.json
```

I'd also state that you should have [usage estimates](https://www.infracost.io/docs/features/usage_based_resources/) properly defined to avoid seeing lines such as "Monthly cost depends..."

If this doesn't resolve your problem, I'd suggest opening a dedicated issue highlighting your third-party module usage and expected outputs. However, just to set expectations, we have a large backlog of resource improvements to tackle and this is unlikely to get resolved in the near term. If you want a faster solution to your problem, we're always [open to contributions.](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md)
