### ISSUE TITLE
User defined project names (`--project-name` and `name` in config-file)

### ISSUE THREAD

**Issue by syphernl** [infracost/infracost#1535]
It would be nice if we could add a `name` parameter to the list of projects to provide a "friendly name".
Instead of printing `src/something/something/staging-plan.json` it should then print the provided name instead (e.g. `staging`).

**Comment by aliscott** [comment]
Thanks @syphernl, I think this is a good idea.

I can think of two edge cases we should consider before adding this.
1. Terraform users with multiple workspaces. Currently we name these `path/to/code (workspace name)`. I think we could do a similar thing with the friendly name and append the workspace in brackets.
2. Terragrunt users. if they specify the root project path we split that into multiple projects, so we should work out how to identify those. Maybe we could do a similar thing to the above and add the relative path in brackets after.

cc'ing @alikhajeh1 because I know he's had thoughts about this in the past.

**Comment by alikhajeh1** [comment]
It seems like there are two different problems:
1. Users that run Infracost with specific paths want to provide a `name` (what @syphernl needs, also [this issue](https://github.com/infracost/infracost/issues/1440)).
2. Users that run Infracost with a directory that has multiple projects (e.g. Terragrunt, or [parsing HCL](https://www.infracost.io/docs/guides/advanced_usage/#parsing-hcl-experimental) and pointing to a mono-repo root dir) might want to provide a `name_prefix` (e.g. `ApplicationX`, instead of `src/something/something/app_x`). We could then make the name "ApplicationX (prod)".

If users provide `name` and `name_prefix`, the CLI could error and explain the two options.

**Comment by alexjurkiewicz** [comment]
I'm not sure I totally understand the proposed feature 😅  I think you are proposing a `-name` argument we can give to Infracost to tell it what "project" to associate the cost report with, which is used to link multiple reports so we can track cost over time and so on. If so, that sounds perfect for us!

To recap our use case:
- We have a monorepo containing multiple Terraform configurations. Example path: `terraform/product1/fooservice/main.tf`
- Each configuration will deploy to many environments using different backend configuration (all as the `default` Terraform workspace). Example envs: dev, prod.
- Each deployment has a friendly name in our Terraform deployment platform (Spacelift). Example name: `product1-fooservice-prod`
- In the CI environment that runs Infracost, we know this friendly name (so we can provide it as an arg when running `infracost`). In the git repo itself, we don't know that name (so it can't be read from an in-repo config file).

Hope this helps.

**Comment by aliscott** [comment]
Thanks for the use-case details @alexjurkiewicz 🙏. The proposal is to add a `name` key to projects in the [infracost.yml config file](https://www.infracost.io/docs/features/config_file/#usage) which will then be shown in the `Project: ` part of the output.

For your use-case it seems like a `--name` or `--project-name` flag would be more useful if I'm understanding correctly?

**Comment by alexjurkiewicz** [comment]
Yes, it would be!

**Comment by aliscott** [comment]
> If users provide name and name_prefix, the CLI could error and explain the two options.

@alikhajeh1 how would this work in a user provided `name` for a Terragrunt/multi-workspace project instead of `name_prefix`?

**Comment by alikhajeh1** [comment]
@aliscott I can think of three options:
1. Users only provide a `name` param, and if we detect Terragrunt/multi-workspace project, we automatically add the dir/workspace in brackets to the name. This seems nice but I worry that it'll confuse API users if the name set by them doesn't match the name returned by our future API.
2. We detect/error on terragrunt/multi-workspace, and tell users to use `name_prefix` so they understand that we'll be adding something else to the name.
3. Users only provide `name_prefix`, and we set `project.name` to `name_prefix (+ our logic to add dir/workspace)`. If there is no Terragrunt/multi-workspace, we set name to name_prefix.

I kinda like option 3 as users only provide one thing, and it's clear that we can add stuff to that thing.

**Comment by alikhajeh1** [comment]
We plan to work on this in June, the proposed changes are as follows. Feel free to leave a comment if this does/does not work for your use case!

## Proposed changes

- Add the optional `--project-name` flag to `infracost breakdown` and `infracost diff`
    - This shouldn’t break the diff functionality as that uses the metadata section internally too, but we need to test it.
- Add `name` to the config-file. That means if users want different names for multi-project runs, they can define the name on a per-project basis.
- Changes to the Infracost JSON format:
    - all `projects.name` in the JSON file get the project name that users set. We fallback to the existing project name logic if that's not provided, but exclude the workspace/subpath that we currently put in brackets as we’ll add that separately into the metadata.
    - `projects.metadata` gets these new keys if available:
        - `path` stays as is.
        - add new `terraformModulePath` that has the relative path of the directory being run for mono repos, or terragrunt module for terragrunt projects.
        - add a new `terraformWorkspace` that's set when the `---terraform-workspace` flag or `terraform_workspace` config-file value is set.
- In our table, diff, HTML, and comment (summary table) output formats, project names would be displayed as`project.name (terraformModulePath)` , e.g. running `--project-name=infra` in a mono repo would result in “infra (dev)” and “infra (prod)”.

Example JSON and CLI output:

```jsx
$ cd infracost/infracost/examples/terragrunt
$ infracost breakdown --path . --format json

## With --project-name=infra:

### JSON becomes:
projects:
    "name": "infra",
      "metadata": {
        "terraformModulePath": "prod",
        "path": "/Users/ali/src/infracost/infracost/examples/terragrunt/prod",
        "type": "terragrunt_dir",
        "vcsRepoUrl": "git@github.com:infracost/infracost.git",
        "vcsSubPath": "examples/terragrunt/prod"
      },

    "name": "infra",
      "metadata": {
        "terraformModulePath": "dev",
        "path": "/Users/ali/src/infracost/infracost/examples/terragrunt/dev",
        "type": "terragrunt_dir",
        "vcsRepoUrl": "git@github.com:infracost/infracost.git",
        "vcsSubPath": "examples/terragrunt/dev"
      },

### Output becomes:

The table, diff, HTML, and comment (summary table) output formats would show these projects:
- infra (prod)
- infra (dev)

## Without --project-name:

### JSON becomes:
projects:
    "name": "infracost/infracost/examples/terragrunt",
      "metadata": {
        "terraformModulePath": "prod",
        "path": "/Users/ali/src/infracost/infracost/examples/terragrunt/prod",
        "type": "terragrunt_dir",
        "vcsRepoUrl": "git@github.com:infracost/infracost.git",
        "vcsSubPath": "examples/terragrunt/prod"
      },

    "name": "infracost/infracost/examples/terragrunt",
      "metadata": {
        "terraformModulePath": "dev",
        "path": "/Users/ali/src/infracost/infracost/examples/terragrunt/dev",
        "type": "terragrunt_dir",
        "vcsRepoUrl": "git@github.com:infracost/infracost.git",
        "vcsSubPath": "examples/terragrunt/dev"
      },

### Output becomes:
The table, diff, HTML, and comment (summary table) output formats would show these projects:
- infracost/infracost/examples/terragrunt (prod)
- infracost/infracost/examples/terragrunt (dev)
```

**Comment by alexjurkiewicz** [comment]
Thanks Ali! Here's what I understand:

It looks like we can define a "project name prefix", but the full project name also includes a suffix which is the "relative path of the directory being run for mono repos, or terragrunt module for terragrunt projects". So the project name is like `$project_name ($repo_path)`.

This is borderline unusable for our case, unfortunately. The short reason why is that our projects are identified by arbitrary project name and arbitrary environment name - and the repo path is not necessarily related to either.

Here's some background on how we use Terraform:

* We don't use Terragrunt at all
* Some of our Terraform is in monorepos (repo: `orgname/terraform`, paths: `src/product1/serviceA`), some is in single-purpose repos (repo: `orgname/newmicroservice`, paths: `terraform/`)
* Generally, we use the same Terraform configuration to deploy multiple environments (dev, prod). To do this we don't use Terraform workspaces. We just init with different backend configs. eg: `terraform init -backend-config backends/dev.tfvars`
* The project names we want are a copy of the stack name when we deploy the Terraform Configuration in our Terraform SaaS (Spacelift, Terraform Cloud). These project names have been set arbitrarily by us.

Given our structure, the project name is not something Infracost can derive for us. We want full control over setting it. For example, we'd use the following project names:

* product1-serviceA-prod (repo: `orgname/terraform`, subdir:  `terraform/product1/serviceA`, env: `prod`)
* product2-serviceF-dev (repo: `orgname/serviceF`, subdir: `terraform`, env: `dev`)

I get the sense you really want auto-detection logic. I explained that we want full control over project names in my earlier comment and you haven't gone with that approach. It's not my product and I'm not offended by your product decisions, but I can't see how any autodetection of project name is going to suit us. We want to use the same name as our Terraform SaaS, and those names are arbitrary.

**Comment by alikhajeh1** [comment]
@alexjurkiewicz thanks for the detailed feedback! I should have made it clearer that using `--project-name` gives you full control of the project name that's displayed in the dashboard so it'll match the stack name.

I don't think you have any Infracost runs that result in multiple project outputs, e.g. running infracost on a mono repo or [terragrunt](https://github.com/infracost/infracost/tree/master/examples/terragrunt), right? If so, the exact project name you pass-in will also be shown in all CLI output formats in addition to the dashboard: table, diff, HTML, and comment (summary table).

#### Multi-project runs (e.g. mono repo or terragrunt)

The tricky case we're trying to solve with the automated project name post-fix, that is only add in the CLI output formats (not dashboard), is this:
User runs `infracost breakdown --path examples/terragrunt --project-name my-project` using [this example](https://github.com/infracost/infracost/tree/master/examples/terragrunt) (you can try it). In this case, the dashboard will group both dev and prod projects as "my-project" since that's what the user asked for. If you click on that project's runs in the dashboard, you'll see the results of both dev and prod, in the same way you would in the PR comment summary table (shown below). If we don't add the post-fix, the table shows the row "my-project" twice and it's not possible for the user to distinguish them. Does that make sense? Maybe there's a better way to handle that though? 

<table>
  <thead>
    <td>Project</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>my-project (dev)</td>
      <td align="right">$1,444</td>
      <td align="right">$1,000</td>
      <td>+$260 (-10%)</td>
    </tr>
    <tr>
      <td>my-project (prod)</td>
      <td align="right">$1,444</td>
      <td align="right">$1,704</td>
      <td>+$260 (+18%)</td>
    </tr>
  </tbody>
</table>

**Comment by alexjurkiewicz** [comment]
Thanks for the info. Ok great, it sounds like we are aligned 😊

You are right, we only run infracost on a single project at a time. In fact
we will continue to run it after creating a plan for PRs in Spacelift.

Looking forward to this feature!!

**Comment by alikhajeh1** [comment]
Great - thanks for the ack!

**Comment by aliscott** [comment]
> The tricky case we're trying to solve with the automated project name post-fix, that is only add in the CLI output formats (not dashboard)

I think what we should do here is recognize the differentiating information and put it in brackets. For examples, for Terragrunt projects and Terraform monorepos the differentiating information is the sub-path, for a multi-workspace project its the Terraform workspace. So for these cases we can have the table output like below. One edge case might be if there's multiple plan JSON files assigned to the same project for a run, but for this case I think we can still just show that in brackets.

**When multiple sub-paths are specified or detected for Terragrunt/Terraform mono-repo:**

<table>
  <thead>
    <td>Project</td>
    <td>Path</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>my-project</td>
      <td>dev</td>
      <td align="right">$1,444</td>
      <td align="right">$1,000</td>
      <td>+$260 (-10%)</td>
    </tr>
    <tr>
      <td>my-project</td>
      <td>prod</td>
      <td align="right">$1,444</td>
      <td align="right">$1,704</td>
      <td>+$260 (+18%)</td>
    </tr>
  </tbody>
</table>

**When multiple Terraform workspaces are specified:**

<table>
  <thead>
    <td>Project</td>
    <td>Workspace</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>my-project</td>
      <td>dev</td>
      <td align="right">$1,444</td>
      <td align="right">$1,000</td>
      <td>+$260 (-10%)</td>
    </tr>
    <tr>
      <td>my-project</td>
      <td>prod</td>
      <td align="right">$1,444</td>
      <td align="right">$1,704</td>
      <td>+$260 (+18%)</td>
    </tr>
  </tbody>
</table>

**When multiple plan JSONs are specified:**

<table>
  <thead>
    <td>Project</td>
    <td>Path</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>my-project</td>
      <td>/truncated/path/…/to/dev/plan.json</td>
      <td align="right">$1,444</td>
      <td align="right">$1,000</td>
      <td>+$260 (-10%)</td>
    </tr>
    <tr>
      <td>my-project</td>
      <td>/truncated/path/…/to/prod/plan.json</td>
      <td align="right">$1,444</td>
      <td align="right">$1,704</td>
      <td>+$260 (+18%)</td>
    </tr>
  </tbody>
</table>

@alikhajeh1 If we do this, though we'll want the to make the breakdown and diff txt output consistent, so maybe we'd just need to put the differentiating information in brackets after the project name for those, e.g:

```
Project: infracost/infra (path: dev)

# or

Project: infracost/infra (workspace: prod)
```

**Comment by tim775** [comment]
Would it make sense to include the user defined `--project-name` in the json metadata?  It might be nice so there is an understanding of where it came from.

**Comment by tim775** [comment]
@alikhajeh1 Currently project.name in the json format is sort of a "friendly display name" derived from the metadata fields.  For instance, this metadata: 
```
      "metadata": {
        "path": "./cmd/infracost/testdata/",
        "type": "terraform_dir",
        "vcsRepoUrl": "git@github.com:infracost/infracost.git",
        "vcsSubPath": "cmd/infracost/testdata",
        "terraformWorkspace": "myworkspace"
      },
``` 
would result in the project name 
```
"name": "infracost/infracost/cmd/infracost/testdata (myworkspace)"
```

If we put the user defined name in project.name directly, it might not be clear where the name came from and it is potentially a little less friendly (since it won't include workspace info).

**Comment by alikhajeh1** [comment]
I'd keep it simple and use project.name as the thing users define (and if they don't define it we auto-generate it). Longer term we might have IDs or tags or other fields to distinguish things.

**Comment by alikhajeh1** [comment]
@syphernl, @alexjurkiewicz and @sunnyoswalcro FYI the `--project-name` flag is live for `infracost breakdown` and `infracost diff`, see the [docs here](https://www.infracost.io/docs/infracost_cloud/key_concepts/#projects). This works with the CLI, PR comments and project names in Infracost Cloud (our new SaaS product). Can you please try it and let me know if that solves your use-case?
