### ISSUE TITLE
Add free resources feature

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#154]
In complex resources, there are tons of additional resources like iam policies and ... which have no cost but fill the skipped resources warning. It would be great if we can add a free resource concept.

**Comment by aliscott** [comment]
@sinabakh at the moment we can do this with the NoCost field. See https://github.com/infracost/infracost/blob/110d91f8edde971b88967188b21d739bad4e0748/internal/providers/terraform/aws/ecs_service.go#L22-L27 for an example.

I'm happy for a better approach to be added if we want.

**Comment by sinabakh** [comment]
Seems solid, I was not aware of this feature. I'll check the skipped resources logic to see if sth is missing there.

**Comment by aliscott** [comment]
@sinabakh I hope you don't mind me keeping this open. I've been thinking about this a little more and think we could have a much better/light-weight approach. We had one user have `89 out of 95 resources` show as unsupported where most of them are free resources (IAM policies, security groups, etc).

I think we could very quickly build a string array of free terraform resource types and exclude them. What do you think?

**Comment by sinabakh** [comment]
@aliscott I think the general approach is so clean, but creating files and functions to return a single no cost component might take a while (although I think it might be cleaner). For now, we can work on some sort of tricks in our registry so we can provide an array of free resources.
It's a trade off between speed and clean code. I think we can choose speed for now, if you agree I will work on it today but it would be great if you can provide the resources that you are aware of which are free.

**Comment by aliscott** [comment]
Yeah I think an array will be easier to maintain going forward.

Known free resources:
 * aws_iam_*
 * aws_security_group*
 * null_resource
