### ISSUE TITLE
Visual Studio Code extension

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1546]
Following-up from the Infracost CLI's ability to [parse HCL directly](https://www.infracost.io/blog/jun-2022-update/), we'd like to develop a VS Code extension to show costs as Terraform projects or modules are being developed. Engineers could then get cost visibility as early as possible, to make better design decisions, and avoid rework/surprises at the pull request stage. 

**Note for community**
Please 👍 if you'd like to upvote this or receive updates.

**Comment by hugorut** [comment]
We're excited to announce that we've published our first version of the Infracost VSCode extension 🎉 ⌨️. Here's a shiny gif to show you the initial release in action!

![cost-webview](https://user-images.githubusercontent.com/6455139/176232623-52973c34-b2d0-4726-bff5-b80d90b63d40.gif)

I'm going to close this issue now this is implemented. You can find more information about the extension on the dedicated [vscode-infracost repository](https://github.com/infracost/vscode-infracost).
