### ISSUE TITLE
Support environment variables or additional command line args for `infracost register`

### ISSUE THREAD

**Issue by ctodd-cb** [infracost/infracost#1547]
I'm trying to add this to our CI which runs through a custom container where I don't have interactive access to the command line. I'd also prefer not to store a pre-existing API key in the project code. Would it be possible to support additional variables for `Name`, `email` and the `see the docs` option?

**Comment by alikhajeh1** [comment]
@ctodd-cb great question! Infracost API keys are designed to be per-team or per-org, as long-term as we plan to add API key management and multi-user features via a dashboard. Infracost users normally add them to CI/CD env vars (e.g. GitHub and GitLab env vars), or fetch them from AWS KMS, Vault etc and pass them into CI/CD via env vars, `docker run -e "INFRACOST_API_KEY=xxxxx"`.

**Comment by ctodd-cb** [comment]
Ok, if this is by design, I can respect that. I will modify this to populate at runtime

**Comment by alikhajeh1** [comment]
Thanks @ctodd-cb! We need to document that in a clearer manner on our side. Here's [another example](https://github.com/jenkins-infra/pipeline-library/blob/cfb070c79c2fac2ea4dece20e476ce1bad18c2b8/vars/terraform.groovy#L117-L118) from today of a user passing in the API key via Jenkins creds.
