### ISSUE TITLE
April community call - take 2

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1549]
### April Infracost community call topics
We're going to cover the following topics (5mins each):
1. Quick intros
2. Overview of Open Policy Agent and how it [works with Infracost](https://www.infracost.io/docs/features/cost_policies/)
3. Fun issues we're running into as we [parse HCL](https://www.infracost.io/docs/features/cli_commands/#option-3-parse-hcl-directly) to generate cost estimates
4. How [Jenkins](https://github.com/infracost/infracost-jenkins/) and [CircleCI](https://github.com/infracost/infracost-jenkins/) users can integrate Infracost. We'll also go over how [other CI/CD systems](https://www.infracost.io/docs/integrations/cicd/#my-cicd-system-isnt-supported) can integrate with Infracost.
5. https://github.com/infracost/infracost/issues/43
6. Any other topic that you'd like to discuss.

We'll share the meeting recording afterwards.

### When
Wed 13 April 2022, 11:00 PST = 14:00 EST = 19:00 GMT

### Where
Zoom meeting: https://us06web.zoom.us/j/99421485564 
Meeting ID: 994 2148 5564
(this meeting requires a Zoom account for joining, sign up for free on Zoom if you do not have an account)

### Calendar invites
- Google Calendar: go to this [public calendar](https://calendar.google.com/calendar/embed?src=c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com), click on the community call > Copy to my calendar. Alternatively use the email address `c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com` to [subscribe](https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Cadd-using-an-email-address).

- iCal format: Use `https://calendar.google.com/calendar/ical/c_fvdtkbmdrqc17m1bmvlhiksb4k%40group.calendar.google.com/public/basic.ics` for other applications.

**Comment by PatMyron** [comment]
Are these meetings recorded? Interested in HCL parsing, but probably won't be free then

**Comment by alikhajeh1** [comment]
@PatMyron great idea! We'll record it and share the link here afterwards.

**Comment by alikhajeh1** [comment]
Here's the recording of the call: https://youtu.be/14FhZfmAbcM

Apologies to @sinabakh and others who dialed in at the wrong time - I messed-up the timezone conversions 🤦 

Looking forward to seeing y'all at the [May call](https://github.com/infracost/infracost/issues/1562).
