### ISSUE TITLE
Calculate cost for on-demand instances which are not always on

### ISSUE THREAD

**Issue by DeltaWhy** [infracost/infracost#1556]
My company uses a lot of EC2 instances which only run during business hours and are stopped otherwise. Would it be possible to add an 'hours per month' or 'percent usage per month' field to the usage file to account for this use case?

For instance, we might estimate costs based on 180 hours per month rather than 730 for the instances, but the disk subresources are still charged at the full monthly rate (since we're stopping rather than terminating the instances).

**Comment by alikhajeh1** [comment]
@DeltaWhy great idea - I've heard this a few times from users so thanks for creating the issue! If you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md), this seems like a good first issue:
1. Add `monthly_hours` to the [example usage file](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L202) (we have this for some of the other resources too).
2. Add the above param to [this](https://github.com/infracost/infracost/blob/master/internal/resources/aws/instance.go#L18)
3. change [this](https://github.com/infracost/infracost/blob/master/internal/resources/aws/instance.go#L172) to `MonthlyQuantity` and use the param. The param should default to 730 so the existing behavior continues to work if users don't define the usage param (I suppose we should also validate the param is >0 and <= 730).
4. Review the other `HourlyQuantity` mentions in the instance.go file above and see if they should use the same param or, if they should remain as 730 (e.g. do users pay for the Inference accelerator when the instance is stopped?) - if needed we can also help with this by reviewing the AWS EC2 pricing page.

Semi-related to the above change could be to also update the Azure and Google instance resources so instances are consistent across the providers. 

Unrelated to this GH issue, this feature'll enable us to get feedback from AWS RDS and other resource users to see if the same thing is needed for those resources.

**Comment by alikhajeh1** [comment]
@hugorut plz close this after v0.10.8 is live as it looks like it's being released as part of that.
