### ISSUE TITLE
Is there any estimation to include Oracle (OCI) as a provider?

### ISSUE THREAD

**Issue by paolajuarezgomez** [infracost/infracost#1557]

**Comment by hugorut** [comment]
Hi @paolajuarezgomez, Infracost does not yet support OCI. We have an open issue here: https://github.com/infracost/infracost/issues/911 which you can 👍 to help us prioritise this in our backlog. I'm closing this issue to avoid confusion with https://github.com/infracost/infracost/issues/911. Have a great day.
