### ISSUE TITLE
Azure china resources are free

### ISSUE THREAD

**Issue by NunoAMFerreira** [infracost/infracost#1559]
When running a infracost breakdown or diff with resources on "chinaeast2" location the cost is $0.0

### Breakdown
![image](https://user-images.githubusercontent.com/22886997/163014712-2580f372-0750-4eb9-989d-79c0dbba75c0.png)

### Diff
![image](https://user-images.githubusercontent.com/22886997/163014813-c6594a0b-445d-40b2-acd9-60c1560630a5.png)

**Comment by vdmgolub** [comment]
@NunoAMFerreira Hello! I looked through our cloud pricing API and I couldn't find any SKUs for this region. As we download the prices from Azure's API, I would assume that they don't share anything for the region. Do you have any examples (maybe pricing calculator) where you can see it in Azure docs?

FYI, these are the regions we have right now: `China`, `Zone 1 (China)`, `chinaeast3` and `chinanorth3`.

**Comment by NunoAMFerreira** [comment]
Hi @vdmgolub ,

Theres some information here https://www.azure.cn/en-us/pricing/details/virtual-machines

Since we are using mostly "chinaeast2" is there any workaround for this? Besides changing the config.tf (using sed)

**Comment by alikhajeh1** [comment]
@NunoAMFerreira I'm wondering if you can help us? [This thread](https://social.msdn.microsoft.com/Forums/en-US/5b6cf25a-0485-48a1-8f41-19de06aa3acb/azure-china-api-for-china-cloud-pricing-data) mentions that users with access to Azure China should be able to fetch the prices. I looked at the [link](https://www.azure.cn/en-us/pricing/details/virtual-machines) you sent but it's not using any JSON APIs as far as I can see - [this](https://github.com/infracost/cloud-pricing-api/blob/master/src/scrapers/azureRetail.ts#L9) is the URL we hit to download the other Azure prices. Maybe you can create a support ticket using your Azure China account to ask for the equivalent URL for China price JSON? (Like @vdmgolub, I couldn't find any docs for it). That's the URL we need long term to support this properly in Azure (last year, an AWS China user helped the community pave the way).

**Comment by NunoAMFerreira** [comment]
@alikhajeh1 Hi,
I'll contact msft support. 
Once i've more information i'll update you guys. Thanks

**Comment by NunoAMFerreira** [comment]
I just spoke with our msft support, they will check why they have China East 3 on the retail prices api and not China East 2 since it's operated by the same company 21Vianet. 
Also there's a possibility of using another API that shows "our real" prices (with discounts). Is there a way of using it if we deploy Infracost internally?

**Comment by vdmgolub** [comment]
Currently cloud-pricing-api scrapes data from the link Ali mentioned ([link](https://github.com/infracost/cloud-pricing-api/blob/master/src/scrapers/azureRetail.ts#L9)) and we expect a particular format from there. It is not possible to include additional APIs out of the box, unfortunately. However, if the format from that another API is similar, I guess you could try to fork the cloud-pricing-api repo and adjust the URL and run the scraper. The discounted prices is the topic we've seen to pop up several times already, but Infracost doesn't support this at the moment.

**Comment by NunoAMFerreira** [comment]
I'm checking with msft if they will make china east 2 available on the retail prices api. Thanks

**Comment by alikhajeh1** [comment]
@NunoAMFerreira did you ever hear back from MSFT support about China East 2 prices?

btw, custom price discounts (e.g. for Azure EA discounts) are live in [Infracost Cloud](https://www.infracost.io/docs/infracost_cloud/get_started/): https://www.infracost.io/docs/infracost_cloud/custom_price_books/

**Comment by alikhajeh1** [comment]
Going to close this due to lack of info from MS, feel free to re-open if someone finds out more!
