### ISSUE TITLE
Argument --tfflags does not work on brew installed package version 0.6.1

### ISSUE THREAD

**Issue by jamengual** [infracost/infracost#156]
Looks like the readme point to new options released in 0.6.2.

This does not work on version 0.6.1:

infracost --tfdir /path/to/code --tfflags "-var-file=myvars.tf"

It will be ideal to note that on the readme

**Comment by alikhajeh1** [comment]
@jamengual thanks for reporting this, we're starting to use https://www.conventionalcommits.org and want to auto-generate a changelog based on that, there's also an automated check-for-updates feature in-flight as we're releasing versions often given the early nature of the project.

**Comment by jamengual** [comment]
No problem, and thanks for the response

**Comment by alikhajeh1** [comment]
@jamengual the automated check-for-updates feature is live so I'm going to close this issue as we expect users'll upgrade more often, `brew upgrade infracost`...
