### ISSUE TITLE
May community call

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1562]
### Recording of the call

https://youtu.be/iZgavKe9aZU

### May Infracost community call topics

We're going to cover the following topics (5mins each):
- Quick intros
- The new Get Started guide, including the `--terraform-parse-hcl` flag, and `infracost diff --compare-to`
- How [Jenkins](https://github.com/infracost/infracost-jenkins/) and [CircleCI](https://github.com/infracost/infracost-jenkins/) users can integrate Infracost. We'll also go over how [other CI/CD systems](https://www.infracost.io/docs/integrations/cicd/#my-cicd-system-isnt-supported) can integrate with Infracost.
- Any other topic that you'd like to discuss.

### When
Thu 12 May 2022, 10:00 Los Angeles (PDT) = 13:00 New York (EDT) = 19:00 Berlin (CEST), [convert to your timezone](https://www.timeanddate.com/worldclock/converter.html?iso=20220512T170000&p1=137&p2=179&p3=37)

### Where
Zoom meeting: https://us06web.zoom.us/j/99421485564 
Meeting ID: 994 2148 5564
(this meeting requires a Zoom account for joining, sign up for free on Zoom if you do not have an account)

### Calendar invites
- Google Calendar: go to this [public calendar](https://calendar.google.com/calendar/embed?src=c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com), click on the community call > Copy to my calendar. Alternatively use the email address `c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com` to [subscribe](https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Cadd-using-an-email-address).

- iCal format: Use `https://calendar.google.com/calendar/ical/c_fvdtkbmdrqc17m1bmvlhiksb4k%40group.calendar.google.com/public/basic.ics` for other applications.

**Comment by agardnerIT** [comment]
I'd be happy to demo what I have so far with the Keptn integration. Count me in.

**Comment by alikhajeh1** [comment]
I put the record on YouTube: https://www.youtube.com/watch?v=iZgavKe9aZU 

The next call will be on Wed 8 June: https://github.com/infracost/infracost/issues/1649
