### ISSUE TITLE
Envrionment variable to set the usage file

### ISSUE THREAD

**Issue by emocharnik** [infracost/infracost#1578]
We are very interested in a [a usage file](https://www.infracost.io/docs/features/usage_based_resources/) feature. Currently, the breakdown command supports specifying it as a parameter. It brings additional complexity to our CI pipeline, as we try to use the same Terraform code for different environments (dev/qa/prod). And obviously, different environments produce different usage. 

So to make things simpler, we would like to specify the usage file as an environment variable, e.g. `INFRACOST_USAGE_FILE`.

Current approach
-----------------
```bash
infracost breakdown --sync-usage-file --usage-file infracost-usage.yml --path /code
```

Proposed solution
------------------
```bash
export INFRACOST_USAGE_FILE=infracost-dev-usage.yml # exported before the CI started

... # CI has started and pre-calculation operations are done here
infracost breakdown --sync-usage-file --path /code
.... # post-calculate operations are done here and CI finished
```

**Comment by alikhajeh1** [comment]
@emocharnik I might be missing something but could this also be achieved right now by passing in the file name to the flag via an env var:
`infracost breakdown --sync-usage-file --usage-file $INFRACOST_USAGE_FILE --path /code`

That way the env var value can be set at run-time but the above command stays the same.

**Comment by emocharnik** [comment]
@alikhajeh1 but not all workflows have the usage specified

**Comment by alikhajeh1** [comment]
@emocharnik tru dat! So then something like this is needed:
```
if [ -n "$INFRACOST_USAGE_FILE" ]; then
   infracost breakdown --sync-usage-file --usage-file $INFRACOST_USAGE_FILE --path /code
else
  infracost breakdown --sync-usage-file --usage-file /tmp/ignore.yml --path /code # The /tmp/ignore.yml is a trick I've shown a few users, it lets them get the usage-data from CloudWatch if available but not have to create a file in advance or check-it into git
fi
```
