### ISSUE TITLE
Add support for azure iot hub devices

### ISSUE THREAD

**Issue by craigbryson** [infracost/infracost#1616]
Add estimation support for `azurerm_iothub` resources, e.g. from here: https://azure.microsoft.com/en-us/pricing/details/iot-hub/

Each SKU has a defined limit of messages per day per hub unit - so estimating this resource based solely on hub unit capacity should be sufficient - this is what the Azure pricing calculator does.

---

### Cost details

Paid resources:

- `azurerm_iothub`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `IoT hub` | `units` |  | `MonthlyQuantity`, the price is multiplied by the number of units from `sku.capacity`. `sku.name` defines the tier. If value is `F1` the resource is free |

- `azurerm_iothub_dps`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Device provisioning` | `1k operations` | `monthly_operations`  | `MonthlyQuantity`, the price is multiplied by the number of units from `sku.capacity`. NB: the CPAPI price is for 1k operations.  |

CPAPI query fo reference: `select * from products where "vendorName" = 'azure' and service = 'IoT Hub' and region = 'westus'`. `S1 Operations` meterName defines price for `azurerm_iothub_dps` cost component.

Free resources:

- `azurerm_iothub_certificate`
- `azurerm_iothub_consumer_group`
- `azurerm_iothub_dps_certificate`
- `azurerm_iothub_dps_shared_access_policy`
- `azurerm_iothub_shared_access_policy`

---

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by vdmgolub** [comment]
@craigbryson Hello! Thank you for creating the issue!

Our first step is to update the issue description with the details of what Cost Components are related to service. Here's an example how it can look like: https://github.com/infracost/infracost/issues/1038. I'd assume you already have some context around these resources, so maybe you'll be able to add them here. [This guide](https://github.com/infracost/infracost/blob/master/contributing/resource_mapping_guide.md) can help defining the cost components.

And we also have a dedicated guide how to add new resources: [guide](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md).

Please let us know if you need any help with that. We have a [community Slack](https://www.infracost.io/community-chat) for easier communication. :)

**Comment by craigbryson** [comment]
Thanks @vdmgolub and apologies I didn't realise there was a process - i will update the issue now

**Comment by vdmgolub** [comment]
No worries at all and thank you! We don't have a proper process in place yet, but we try to get some cost details in the issue as a help if anybody from the community decides to contribute.

**Comment by vdmgolub** [comment]
According to TF registry there are the following resources:

Paid resources:

- `azurerm_iothub`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `IoT hub` | `units` |  | `MonthlyQuantity`, the price is multiplied by the number of units from `sku.capacity`. `sku.name` defines the tier. If value is `F1` the resource is free |

- `azurerm_iothub_dps`

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Device provisioning` | `1k operations` | `monthly_operations`  | `MonthlyQuantity`, the price is multiplied by the number of units from `sku.capacity`. NB: the CPAPI price is for 1k operations.  |

CPAPI query fo reference: `select * from products where "vendorName" = 'azure' and service = 'IoT Hub' and region = 'westus'`. `S1 Operations` meterName defines price for `azurerm_iothub_dps` cost component.


Free resources:

- `azurerm_iothub_certificate`
- `azurerm_iothub_consumer_group`
- `azurerm_iothub_dps_certificate`
- `azurerm_iothub_dps_shared_access_policy`
- `azurerm_iothub_shared_access_policy`

@craigbryson Thank you! Here's what I ended up with. Does it look right to you? If yes, I'm going to update the issue description for better visibility and add a note for a community.

**Comment by craigbryson** [comment]
Yes that looks right - sorry i didnt add `azurerm_iothub_dps` as its a separate resource and we don't use it currently but it would make sense to add support for

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by vdmgolub** [comment]
Hey @deepto98! Sure thing, thank you! I'll assign it to you :) Here's a guide how to add new resources: [guide](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md). If you have any questions you can also join our [community Slack](https://www.infracost.io/community-chat) for easier communication. :)

**Comment by sawyerw-mastery** [comment]
@deepto98 are you still working on this? I picked it up without realizing you were working on it. I *think* I'm about done with it.

@craigbryson for the `azurerm_iothub_dps`, I see that the `sku` allows a `capacity` to be set however, I don't see in the Azure portal where you can scale DPS. Do you know if it's possible to scale DPS?

**Comment by craigbryson** [comment]
@sawyerw-mastery - I don't know if that's possible sorry, I cant see any docs for capacity and we currently have 1

**Comment by alikhajeh1** [comment]
Thanks @sawyerw-mastery!
