### ISSUE TITLE
Add support for AWS EC2 Dedicated Instances

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1623]
Main TF resource: [aws_ec2_host](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_host)
Pricing: https://aws.amazon.com/ec2/pricing/dedicated-instances/

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by caimeq** [comment]
This can add significant cost depending on pricing and instance that is used. 
It would be a big help in furthering insights into the costs associated with planned, and existing, infrastructure

**Comment by jgrumboe** [comment]
Would also be needed to support Mac pricing, see #2103

**Comment by robh007** [comment]
I've started this @alikhajeh1

**Comment by alikhajeh1** [comment]
Thanks @robh007!

**Comment by jgrumboe** [comment]
😮 That was a quick one @robh007! 🎉

**Comment by vdmgolub** [comment]
Thank you @robh007! This will go out with the next release. ❤️

**Comment by aliscott** [comment]
@caimeq, @ribeiroh, @tylerd-canva, @pathway27, @olebedev, @edaily, @jgrumboe this has now been released in v0.10.14. Thank you for contributing this @robh007 🙏.
