### ISSUE TITLE
GCP MemoryStore Redis cost is in-accurate

### ISSUE THREAD

**Issue by pansingh-qt** [infracost/infracost#1625]
Actual GCP Cost:

![image](https://user-images.githubusercontent.com/55705323/167103072-d8da3cf8-e965-4b8a-ae1d-27ac75eeaa01.png)

Cost Projected by infracost:
![image](https://user-images.githubusercontent.com/55705323/167104016-434d2bf2-1190-4caa-a786-c6d402143811.png)

As you notice actual estimated cost for this instance is      $127.75/month , however infracost only showing $0.14/month.
It seems it is ignoring the instance cost and considering cost of memory only.

**Comment by vdmgolub** [comment]
@pansingh-qt Hi! Thank you for reporting the issue! We fixed the bug in #1627 and it's in master now. It should go live with the next release.
