### ISSUE TITLE
--sync-usage-file can't read metrics because it needs to assume a role

### ISSUE THREAD

**Issue by erhudy** [infracost/infracost#1638]
Infracost is a great tool and it's come in very handy for us. While integrating it into our pipelines, I observed that `--sync-usage-file` wasn't working; it would report 0/1 resources synced. I reran the command with debug logs and saw that it was being denied access to read the necessary metrics from CloudWatch.

I then figured out what was wrong; in our deployment model, Terragrunt/Terraform start as a user that can only assume the deployer role in a particular account, and that deployer role is the one with all the privileges. In Terragrunt we specify this with `iam_role`, in raw Terraform it would be with `assume_role` in the provider configuration block. I think this problem would be fixed if I could specify a role ARN to be assumed before Infracost attempts to get the usage data.

I'd be happy to contribute this back if this sounds like a reasonable request to you. Thanks for all your work on Infracost!

**Comment by aliscott** [comment]
@erhudy thanks for reporting this. To help me understand this better could you help me understand what a solution for this could look like?

For getting the credentials for syncing usage we currently just use whatever is in the default AWS credential provider chain. In the meantime would doing something like this work?

```sh
aws sts assume-role --role-arn <arn> --role-session-name <session name>
# extract the AccessKeyId, SecretAccessKey and SessionToken

export AWS_ACCESS_KEY_ID=<AccessKeyId>
export AWS_SECRET_ACCESS_KEY=<SecretAccessKey>
export AWS_SESSION_TOKEN=<SessionToken>

infracost breakdown ...
```

**Comment by erhudy** [comment]
Hi, yeah, you're correct. My credential provider chain was subtly mangled in a way that Terragrunt was compensating for but Infracost didn't know what to do with it. Once I fixed that, Infracost was able to pull the metrics as expected. I'll close this out.

**Comment by alikhajeh1** [comment]
Thanks @erhudy! I just pushed a [docs change](https://github.com/infracost/docs/commit/fc75fc86234fb54d54f2c951b88cb7dfbb899c94) to [this page](https://www.infracost.io/docs/features/usage_based_resources/#fetch-from-cloudwatch) - does that make it clearer? Any other things we should mention?

Also, we're looking for community members who can give us 20mins to help with a usability test of the new `--terraform-parse-hcl` and `--compare-to` features. It'll be a Zoom call where we watch/take notes of issues you run into whilst you follow the [Get Started](https://www.infracost.io/docs/) page. If you have time this/next week, plz email ali.hosseini@infracost.io 🙇
