### ISSUE TITLE
infracost ignoring log level and being too noisy 

### ISSUE THREAD

**Issue by Element20Three** [infracost/infracost#1650]
Despite using flag --log-level  = "info" or when using env variable INFRACOST_LOG_LEVEL=info, the following output still displays

```
bash-5.1$ echo $INFRACOST_LOG_LEVEL
info
bash-5.1$ infracost breakdown --path=TEST --format=json --log-level=info
time="2022-05-12T18:43:53Z" level=info msg="Detected Terraform plan file at test"
time="2022-05-12T18:43:53Z" level=info msg="Starting: Running terraform show"
time="2022-05-12T18:44:02Z" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-05-12T18:44:10Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-12T18:44:15Z" level=warning msg="No products found for module.event_store_notifications_dev.aws_sns_topic.bucket_sns_topic[3] Kinesis Firehose notifications, using 0.00"
time="2022-05-12T18:44:15Z" level=warning msg="No products found for module.event_store_notifications_dev.aws_sns_topic.bucket_sns_topic[3] Mobile Push notifications, using 0.00"
```

**Comment by tim775** [comment]
Hi, setting `--log-level` sets the _minimum_ level of logs that will be displayed.  The order of precedence for log messages is `trace, debug, info, warn, error, fatal`.  So setting `--log-level=info` will show `info, warn, error, fatal` messages, but not `trace, debug`.

To surpess the warning messages you could set `--log-level=error`, but that will also surpress the `info` messages.

For what it's worth, #1633 corrects the issue that causes the the warning you're seeing.  That fix will go live in our next release.

**Comment by Element20Three** [comment]
> error

Thanks for the reply! I think setting it to error is fine for now then. At least until the newest release comes out.
