### ISSUE TITLE
GCE resource references should work automatically with `self_link`

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#1652]
From [this discussion](https://github.com/infracost/infracost/pull/1645#discussion_r872457081) in #1645, all GCE resources contain a `self_link`.  We should support these `self_link` references, similar to [how we support `arn` references for AWS resources](https://github.com/infracost/infracost/blob/bcf2c70062a51acc104ef849100461de846335f5/internal/providers/terraform/parser.go#L415-L451).

**Comment by golgeek** [comment]
I kinda feel it's my fault you had to create this issue and I already have the code opened, so I might go ahead and tacle this one if that's OK with you guys.

**Comment by tim775** [comment]
Go for it!
