### ISSUE TITLE
Fix cost for scratch disks in google_compute_region_instance_group_manager and google_compute_instance_group_manager

### ISSUE THREAD

**Issue by golgeek** [infracost/infracost#1654]
In `google_compute_region_instance_group_manager` and `google_compute_instance_group_manager`, local scratch disks (`local-ssd`) are currently identified as `Standard provisioned storage (pd-standard)` instead of `Local SSD provisioned storage`.

Below is one reproductible example.

## Example
**Terraform code:**

```terraform
provider "google" {
  credentials = "{\"type\":\"service_account\"}"
  region      = "us-central1"
}

resource "google_compute_instance_template" "appserver" {
  name = "appserver-template"

  machine_type = "f1-micro"

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
  }

  disk {
    source_image = "debian-cloud/debian-9"
    boot         = true
    disk_type    = "pd-ssd"
    disk_size_gb = "375"
  }

  disk {
    interface    = "NVME"
    type         = "SCRATCH"
    disk_type    = "local-ssd"
    disk_size_gb = "375"
  }

  guest_accelerator {
    type  = "nvidia-tesla-k80"
    count = 2
  }
}

resource "google_compute_instance_group_manager" "default" {
  name = "default"

  base_instance_name = "app"
  zone               = "us-central1-a"

  version {
    instance_template = google_compute_instance_template.appserver.id
  }

  target_size = 4
}
```

**Expected result:** The `google_compute_instance_group_manager` resource should show a `Local SSD provisioned storage` quantity of 1,500 GB for a price of $120.00.

**Actual result:** The `google_compute_instance_group_manager` resource shows a `Standard provisioned storage (pd-standard)` quantity of 1,500 GB for a price of $60.00.

**Comment by tim775** [comment]
Thanks again @golgeek, you're on a roll.  Do you have any interest in working on this one before I open it up to the community?  First step would probably be to add `local-ssd` and `pd-standard` disks to the instance template used in the [instance group manager test](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/testdata/compute_instance_group_manager_test/compute_instance_group_manager_test.tf).

**Comment by golgeek** [comment]
> Thanks again @golgeek, you're on a roll. Do you have any interest in working on this one before I open it up to the community? First step would probably be to add `local-ssd` and `pd-standard` disks to the instance template used in the [instance group manager test](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/testdata/compute_instance_group_manager_test/compute_instance_group_manager_test.tf).

I actually already opened #1655 to close this one :)

**Comment by tim775** [comment]
Haha, you already fixed it.  I can't keep up!  🚀

**Comment by hugorut** [comment]
@golgeek thanks for your contributions! This is now live as part of the [v0.10](https://github.com/infracost/infracost/releases/tag/v0.10.0) release
