### ISSUE TITLE
Use TF_ env vars for TFC

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1659]
When `TF_WORKSPACE`, `TF_CLOUD_ORGANIZATION` or `TF_CLOUD_HOSTNAME` are set, we should use them as fallbacks if `INFRACOST_TERRAFORM_WORKSPACE`, `INFRACOST_TERRAFORM_CLOUD_TOKEN`​ and `INFRACOST_TERRAFORM_CLOUD_HOST​` are not set.

As part of this issue, the precedence order mentioned in [this](https://www.infracost.io/docs/features/environment_variables/) and [this](https://www.infracost.io/docs/features/config_file/#precedence) page should be updated to:
1. CLI flags (run infracost --help to see them)
2. INFRACOST_ environment variables
3. [Config file](https://www.infracost.io/docs/features/config_file/) 
4. TF_ environment variables

**Comment by aliscott** [comment]
What was the origin of this issue?

I see `TF_WORKSPACE` in the [Terraform docs here](https://www.terraform.io/cli/config/environment-variables), but I don't see any for the host or the token or the organization (not sure why we need this anyway?).

As a side note, we already support the `TF_CLI_CONFIG_FILE` env variable for reading the token from that file.

**Comment by alikhajeh1** [comment]
@aliscott The origin of the issue was a user who had set `TF_WORKSPACE` and expected Infracost to pick it up, so maybe that's all we need to support. We can ignore the other 2, I saw them mentioned in https://github.com/hashicorp/terraform/releases/tag/v1.2.0-rc1

**Comment by aliscott** [comment]
@dyordsabuzo I've got a potential fix for the `TF_WORKSPACE` env var - but just to make sure it fixes your original issue, do you remember what error you were seeing?

**Comment by dyordsabuzo** [comment]
I dont remember exactly the error message and I can't seem to recreate it but it was prompting that I need to use the `--terraform-workspace` flag even with TF_WORKSPACE defined.

**Comment by dyordsabuzo** [comment]
Got it!
![image](https://user-images.githubusercontent.com/2220268/169161682-9458263c-71a2-4747-94fa-9c72bac08de3.png)

It works if I run without `--terraform-parse-hcl`.

**Comment by aliscott** [comment]
Thanks @dyordsabuzo!

**Comment by hugorut** [comment]
This has been fixed and released as part of [v0.10](https://github.com/infracost/infracost/releases/tag/v0.10.0).
