### ISSUE TITLE
Add Support for Azure azurerm_virtual_network_peering

### ISSUE THREAD

**Issue by Joerg-L** [infracost/infracost#1671]
Peering of Azure Networks is highly used in Hub/Spoke Concept and Microsoft Cloud Adoption Framework.
So it would be very usefull to include that in the calculation too.
Thanks

---

### Cost details

Paid resource:

`azurerm_virtual_network_peering`
- TF registry: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_peering
- Azure pricing: https://azure.microsoft.com/en-us/pricing/details/virtual-network/
- Cost components:

  | Name | Units | Usage param | Notes |
  | ---- | ----- | ----------- | ----- |
  | `Inbound data transfer` | `GB` | `monthly_inbound_data_transfer_gb` float | |
  | `Outbound data transfer` | `GB` | `monthly_outbound_data_transfer_gb` float | |

---

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by vdmgolub** [comment]
@Joerg-L Hi! Thank you for creating the issue!

Our first step is to update the issue description with the details of what Cost Components are related to service. Here's an example how it can look like: https://github.com/infracost/infracost/issues/1038. I'd assume you already have some context around these resources, so maybe you'll be able to add them here. After a quick look into cloud prices and Azure pricing calculator it seems like there are two cost components for Egress and Ingress traffic, and the prices depend if they are within one region or inter-region. Does it sound right to you? [This guide](https://github.com/infracost/infracost/blob/master/contributing/resource_mapping_guide.md) can help defining the cost components.

And we also have a dedicated guide how to add new resources: [guide](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md).

Please let us know if you need any help with that. We have a [community Slack](https://www.infracost.io/community-chat) for easier communication. :)

**Comment by Joerg-L** [comment]
@vdmgolub Hi!
Thanks a lot for your feedback, and sorry for additional work. That's my first request of that kind.

You are completely right with your analysis of the cost components

Cost Components

- `Inbound data transfer` with `GB` as unit per use
- `Outbound data transfer` with `GB` as unit per use
- Price depends if traffic is within same region or globally (3 zones + gov)

As described in the [Hub-and-spoke network topology](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology) and the [Landing Zone Concept](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/ready) of the Microsoft Cloud Adoption Framework, the usage of vnet peering is highly recommendet and best-practice. Even if that is  "per Use" calculation, having that in minde and plan the costs is really use full.

**Comment by vdmgolub** [comment]
This is merged to master and will go live with the next release. Big thanks to @sawyerw-mastery for the contribution!

**Comment by hugorut** [comment]
This is now live in the [v0.10.8](https://github.com/infracost/infracost/releases/tag/v0.10.8) release. Thanks again @sawyerw-mastery  ❤️
