### ISSUE TITLE
Move the output.Root struct in an package that can be imported

### ISSUE THREAD

**Issue by golgeek** [infracost/infracost#1684]
I'm working on integrating `infracost` in one of our internal tools, and was planning on parsing the JSON output.
As the tool I'm working on is also written in Golang, my intent was to `json.Unmarshal` the output into the `Root` struct from the `output` package you maintain. But this package is `internal` hence cannot be imported. 

As you already export this schema as JSON (using https://github.com/invopop/jsonschema), I'm not sure why you chose not to expose a public package with this struct, but it would greatly simplify the use from another Golang code.

**Comment by hugorut** [comment]
Hi, @golgeek thanks for raising this. Our current stance is that we don't export any functionality outside of the `internal` package. Infracost internals are geared towards being consumed as a CLI. Once we start exporting packages and allowing other developers to consume Infracost as an SDK, we introduce complexity in designing and releasing Infracost.

I understand that you're just asking for a relatively trivial type to export. However, adding this will inevitably lead to other consumers asking for more to be included. We want to properly think about the API and which components make sense for us to export before we make changes like this.

Right now, we're focused on making the CLI the best it can possibly be, so exposing public interfaces isn't something we'd consider in the near term. That doesn't mean that we'll extract certain things out of the application to libraries and SDKs in the future. It just means that it's not a priority for us. If you're looking to consume the JSON output, I recommend copying over the `Root` structs to your application. Alternatively, pasting the JSON output into something like https://mholt.github.io/json-to-go/ should also be sufficient.

I'm going to close this issue and probably raise another issue which will be a more generic "SDK support" issue which people can watch/ 👍  if they're interested in future developments towards this end.

**Comment by hugorut** [comment]
sdk issue opened here: https://github.com/infracost/infracost/issues/1685

**Comment by golgeek** [comment]
Hi @hugorut; thanks for your very detailed answer.
I completely get why an SDK is not your priority at the moment, and I'll duplicate the struct!

**Comment by alikhajeh1** [comment]
@golgeek just FYI that https://github.com/infracost/infracost/discussions/1278 has ideas on changes we're thinking about for the JSON format. Feel free to comment on it as you dig more into our JSON
