### ISSUE TITLE
Add support for AWS Global Accelerator

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#1690]
Add support for AWS Global Accelerator.

Terraform resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/globalaccelerator_accelerator
AWS Pricing page: https://aws.amazon.com/global-accelerator/pricing/

---
Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by tim775** [comment]
Thanks @carmeloriolo!  A good first step is to take a look at the pricing model and figure out what pricing components will be needed.   You can then comment here with the details to get some feedback.  ([Here's an example I did a while ago](https://github.com/infracost/infracost/issues/638#issuecomment-860879859)).
