### ISSUE TITLE
Make `infracost comment` errors easier to debug

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1693]
I've seen a few user CI/CD pipelines fail on `infracost comment` due to errors from the source control server. The Infracost CLI's error messages aren't [easy to debug](https://github.com/infracost/infracost/issues/1691#issuecomment-1139698472).

### Proposal
1. Update the `infracost comment` command so server-side errors include the URL what was called, which makes it easier to spot issues such as an env var not being set or the wrong server domain being used. The error should also make it clear that the Infracost comment was generated by the CLI but the request to the server failed. It might be useful to log the HTTP request without any tokens/secrets.
2. See if we can catch 403s and send users to the following links. If that's too complicated we can create a generic `infracost comment` troubleshooting section in https://www.infracost.io/docs/troubleshooting/ and send users there from all `comment` errors.
gitlab: https://gitlab.com/infracost/infracost-gitlab-ci#403-error-when-posting-to-gitlab
github: https://github.com/infracost/actions/#permissions-issue
azure-repos: https://github.com/infracost/infracost-azure-devops#403-error-when-posting-to-azure-repo

### Useful curls to test token permission issues

GitLab (2 users needed this):
```
export GITLAB_TOKEN=xxxx

curl -X POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --data-urlencode "body=test1" \
    https://gitlab.com/api/v4/projects/my-org%2my-group%2my-infra-repo/merge_requests/123/notes

Where:
- my-org%2my-group%2my-infra-repo  is your repo name in form namespace/project name with encoded slash character.
- 123  is merge request number

```

Bitbucket (2 users needed this):
```
export BITBUCKET_REPO=xxx/xxx
export BITBUCKET_TOKEN=uuu:xxx
export BITBUCKET_COMMIT=xxxxx

curl \
-H 'Accept: application/json' \
-u $BITBUCKET_TOKEN \
https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO/commit/$BITBUCKET_COMMIT
```

Azure DevOps (1 user ran into this):
https://github.com/infracost/infracost/issues/1699#issuecomment-1143174323

---
Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by tim775** [comment]
The improved error message was added in #1785.  It will go live in the next release.
