### ISSUE TITLE
v0.10: Error: Error parsing JSON file: invalid character '\x1b' looking for beginning of value

### ISSUE THREAD

**Issue by Joerg-L** [infracost/infracost#1699]
We are using `infracost breakdown --config-file ./infracost.yml --show-skipped --out-file=/tmp/infracost.json` with `INFRACOST_CURRENCY = EUR` as environment setting in an Azure Devops Pipeline to generate the cost estimation.

In addition, we are using
```         
infracost comment azure-repos \
             --path /tmp/infracost.json \
             --azure-access-token $(System.AccessToken) \
             --pull-request $(System.PullRequest.PullRequestId) \
             --repo-url $(Build.Repository.Uri) \
             --behavior update
```
To add the comment to the pull request.

With v0.10 we receive the error:
`Error: Error parsing JSON file: invalid character '\x1b' looking for beginning of value`

Please let us know, how to solve the issue.

**Comment by hugorut** [comment]
Hey @Joerg-L 👋 , I believe this is because the breakdown format is not valid JSON. Could you try changing the `breakdown` command to use `--format json` flag, i.e:

```
infracost breakdown --config-file ./infracost.yml --show-skipped --out-file=/tmp/infracost.json --format json
```

and see if this helps

**Comment by Joerg-L** [comment]
@hugorut 
Thanks for the hint. I will check it tomorrow. 
Looks like that that setting was not required in former release and therefor we did not use it

**Comment by hugorut** [comment]
hmm, the weird thing is that this has always been required if you pass the output to `infracost comment` so I'm unsure how this was working before.

**Comment by Joerg-L** [comment]
@hugorut I don't have a clue, how ever that was the reason why wee receive the error.

We are now facing the error `Error: Error creating comment: 403 Forbidden` what is a little bit surprising as the permission on the repo is, as it should be
![2022-06-01 08_34_44-Window](https://user-images.githubusercontent.com/25051496/171342501-fbbecdef-f680-4184-8319-6c768718f4bb.png)

**Comment by Joerg-L** [comment]
@hugorut 
okay, I have identified the root cause

From [Azure Documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken)

the usage must look like this

```
- script: |
    infracost comment azure-repos \
      --path /tmp/infracost.json \
      --azure-access-token $SYSTEM_ACCESSTOKEN \
      --pull-request $(System.PullRequest.PullRequestId) \
      --repo-url $(Build.Repository.Uri) \
      --behavior new
  displayName: Post Infracost comment
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

**Comment by hugorut** [comment]
hey @Joerg-L I don't believe this is correct. We use `$(System.AccessToken)` directly in our [example repo](https://dev.azure.com/infracost/base/_git/azure-devops-repo-demo?path=/azure-pipelines.yml) pipeline and it works fine. Has this resolved your issue though?

**Comment by Joerg-L** [comment]
Hey @hugorut 
Yes, it has resolved my issue with 443 and the comments are now posted at the pull request.

I don't know what the reason is because I'm very sure that on our first steps to integrate it in our pipeline we just use your approch from the documentation.

**Comment by hugorut** [comment]
Ok great @Joerg-L , I'll update the FAQ/troubleshooting section to include your env approach. Thanks 👍
