### ISSUE TITLE
Apply flat discounts to Infracost (e.g. AWS EDP or Azure EA discounts)

### ISSUE THREAD

**Issue by patrickhisshion-okta** [infracost/infracost#1725]
Feature Request: Apply a flat discount rate to the infracost output.

#### Request for feedback
- Which of the following [3 options](https://github.com/infracost/infracost/issues/1725#issuecomment-1147817410) do you need?
- 👍 if you'd like to upvote this or receive updates.

**Comment by lindu-dd** [comment]
Option 1 will be sufficient for now.

**Comment by HoLengZai** [comment]
Will it work on a self-hosted model too as discounted contracts could be sensitive?

**Comment by alikhajeh1** [comment]
Hi everyone, option 1, that we discussed is now live on [Infracost Cloud](https://www.infracost.io/docs/infracost_cloud/get_started/) 🎉 You can define the percentage discounts that should be applied for AWS, Azure and Google, see [the docs](https://www.infracost.io/docs/infracost_cloud/custom_price_books/) for more information - feel free to email me at ali.hosseini@infracost.io if you need more help with custom prices.
