### ISSUE TITLE
Versions > 0.9.22 upgrade `k8s.io/client-go` package to v10.0.0+incompatible 

### ISSUE THREAD

**Issue by prajjwaldimri** [infracost/infracost#1729]
For some reason, if I try to install any version of infracost > v0.9.22, it upgrades the k8s.io/client-go package in my `go.mod` file to `v10.0.0+incompatible` which then breaks the `go mod tidy` command.
```
go: upgraded k8s.io/client-go v0.23.4 => v10.0.0+incompatible
```

If I try to run `go get k8s.io/client-go@latest` it downgrades infracost to v0.9.22. What might be causing this issue? Thanks

The already installed version of k8s.io/client-go was v0.23.4

**Comment by aliscott** [comment]
Thanks @prajjwaldimri. What command are you using to install Infracost? Are you doing local development with it or are you wanting a binary?

**Comment by prajjwaldimri** [comment]
@aliscott Using simple `github.com/infracost/infracost` to install. Doing local dev with it.

**Comment by prajjwaldimri** [comment]
BTW, on further analysis, I don't think we can use it as a package in our project. @aliscott Can infracost be used from inside another Go project? Or is it limited to CLI only? Thanks

**Comment by aliscott** [comment]
@prajjwaldimri yeah currently Infracost can only be consumed as a CLI so we don't export any functionality outside of the internal package. Once we start exporting packages and allowing other developers to consume Infracost as an SDK, we introduce complexity in designing and releasing Infracost, so it's not something we are doing at the moment.

We have [this issue](https://github.com/infracost/infracost/issues/1685) you can follow/thumbs up for supporting consuming Infracost as a package to get notified of any updates.

**Comment by prajjwaldimri** [comment]
Cool. Thanks @aliscott 😃 for helping out.

**Comment by aliscott** [comment]
@prajjwaldimri no problem 🙏. Out of interest what are you looking to develop with it?

**Comment by prajjwaldimri** [comment]
Take a look @ https://www.argonaut.dev/ 
We were thinking of using Infracost to provide cost estimation of infrastructure changes to our users.

**Comment by alikhajeh1** [comment]
@prajjwaldimri this is what I share with others who want to integrate with Infracost:
Use separate API keys for users, e.g. ask your users to signup for their own Infracost API key and enter that in the settings page of your product/app/tool. This approach is used by other partners including HashiCorp and Spacelift who ask their users to signup for their own Infracost API keys and add that to their settings. That'll enable those users to upgrade their Infracost accounts to use other hosted services that we'll offer in the future, it'll also enable them to rotate their API keys etc.
