### ISSUE TITLE
Can we get a macOS Universal Binary build?

### ISSUE THREAD

**Issue by skyzyx** [infracost/infracost#1732]
Can we get a Universal Binary (possible with the latest GoReleaser) for macOS?

**Comment by aliscott** [comment]
We don't currently use GoReleaser, but I think we'd be open to using GoReleaser for this. What's the main use-case for Universal Binaries - I've not heard much about them before? Happy to accept contributions for this as well.

**Comment by skyzyx** [comment]
It allows a single binary to run on multiple CPU architectures. Like Intel and Apple Silicon. No Rosetta required.

It’s possible to use some esoteric commands to do it on the terminal, but GoReleaser just makes it really easy.

**Comment by aliscott** [comment]
👍 thanks, if it helps in the meantime we offer builds for both archs on OS X. We have an [install script](https://github.com/infracost/infracost/blob/master/scripts/install.sh) as well that will download the correct one and verifies the SHA. It can be called with:
```sh
curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
```

**Comment by alikhajeh1** [comment]
Going to close this as there doesn't seem to be much demand from other users about it - feel free to re-open if you disagree
