### ISSUE TITLE
Infracost v0.10.0 does not resolve EnvVar, but terragrunt does: Call to function "get_env" failed: EnvVarNotFound

### ISSUE THREAD

**Issue by andrejskuidins** [infracost/infracost#1742]
**Two log files from pipeline below:**

$ echo $LOCALS
locals_dev.hcl
\\$ KST=\\$(aws sts assume-role --role-arn \\${SERVICE_ROLE_ARN} --role-session-name "deployment-${CI_PROJECT_NAME}" --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]' --output text)
\\$ export AWS_ACCESS_KEY_ID=$(echo $KST | cut -d" " -f1)
\\$ export AWS_SECRET_ACCESS_KEY=$(echo $KST | cut -d" " -f2)
\\$ export AWS_SESSION_TOKEN=$(echo $KST | cut -d" " -f3)
\\$ export AWS_SECURITY_TOKEN=$(echo $KST | cut -d" " -f3)
\\$ infracost breakdown --path=\\${TF_ROOT} --format=json --out-file=${TF_ROOT}/infracost.json
time="2022-06-10T12:52:38Z" level=info msg="Detected Terragrunt directory at /builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure"
Error: Error processing module at '/builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of /builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure. Underlying error: /builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure/terragrunt.hcl:2,14-22: Error in function call; Call to function "get_env" failed: EnvVarNotFound: Required environment variable LOCALS - not found.
Update: A new version of Infracost is available: v0.10.0+2-ga2[34](https://gitlab.com/1nce-tech/miscellaneous/central-monitoring-infrastructure/-/jobs/2574392874#L34)9c60 → v0.10.2
$ curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
Cleaning up file based variables
00:01
ERROR: Job failed: command terminated with exit code 1

**terragrunt command in the same pipeline:**
$ terragrunt run-all plan -out=$PLAN
time=2022-06-10T12:51:56Z level=info msg=The stack at /builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure will be processed in the following order for command plan:
Group 1
\\- Module /builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure
aws_iam_role.cm-dev: Refreshing state... [id=eks-cluster-cm-dev]
...
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Saving cache for successful job
00:11
Creating cache test-non_protected...
/builds/4zRYsKjG/0/1nce-tech/miscellaneous/central-monitoring-infrastructure/.terragrunt-cache: found 107 matching files and directories 
No URL provided, cache will be not uploaded to shared cache server. Cache will be stored only locally. 
Created cache
Cleaning up file based variables
00:00
Job succeeded

**My terragrunt.hcl:**
locals {
   varfile = get_env("LOCALS")
   monitor = read_terragrunt_config("${local.varfile}")

   bucket  = "${local.monitor.locals.cluster_id}-\\${local.monitor.locals.region}"
   dynamo  = "${local.monitor.locals.cluster_id}-\\${local.monitor.locals.region}"
   tfpath  = "infra/terraform.tfstate"
}

**Comment by andrejskuidins** [comment]
Sorry, I did not noticed first these two bugs:
https://github.com/infracost/infracost/issues/1695
https://github.com/infracost/infracost/issues/1728

Seems to be working with:
--terraform-force-cli

**Comment by aliscott** [comment]
Thanks for adding details 🙏! Yeah this seems to be the same as https://github.com/infracost/infracost/issues/1728, so hopefully we'll get that into a patch release soon. Will close this issue for just now.
