### ISSUE TITLE
Add repo, commit and pull request metadata to Infracost JSON output

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1753]
Some users are storing the [Infracost JSON output](https://www.infracost.io/docs/features/cli_commands/#examples) in a central database so they can build visibility dashboards (e.g. pull requests that increased or decreased costs the most) and also have an audit trail of cost estimate changes.

We're going to add the following metadata so users can close the loop and have a full audit trail from cost estimates to repos, commits and pull requests.

```text
"projects": [
  {
    # See https://github.com/infracost/infracost/issues/1535 for how to define this
    "name": "my project",
    
    "metadata": {
      "path": ".",
      "type": "terraform_dir",
      # This use to be the git address, we're fixing it so it's the actual repo URL
      "vcsRepoUrl": "https://github.com/infracost/example-terraform",
      "vcsSubPath": sub directory or module of the project "examples/terraform",

      ### Fields we're planning to add:

      "infracostCommand": can be "breakdown" or "diff" so it's clear how the JSON file was generated

      "branch": name of the branch that was used to generate the estimate
      "commit": long commit SHA of the branch that was used to generate the estimate
      "commitAuthorName": git author name of the commit
      "commitAuthorEmail:" git email of author of commit
      "commitTimestamp": timestamp of the commit
      "commitMessage": the commit message
      
      ### The following will initially be populated for GitHub Action and GitLab CI:

      "vcsProvider": name of the VCS provider (github, gitlab, azure_repos, bitbucket)
      "vcsBaseBranch": name of the base branch that the pull request is being merged into
      "vcsPullRequestTitle": name of the pull request
      "vcsPullRequestUrl": link to the pull request
      "vcsPullRequestAuthor": name of the person who opened the pull request, this is probably the same as commitAuthor most of the time but it's helpful to see this if they're different
      "vcsPipelineRunId": a way to differentiate pipelines that are run withing one PR
```

#### Note for community
- Are there any other metadata you need?
- 👍 or subscribe if you'd like to receive updates on this.

**Comment by aliscott** [comment]
> vcsPullRequestName

Can we use `vcsPullRequestTitle` instead since GitHub and GitLab call it title?

**Comment by hugorut** [comment]
This has been implemented for local `git` setups and GitHub and Gitlab CI systems. This will be live in the coming 0.10.4 release

**Comment by hugorut** [comment]
These additional metadata fields are live in the [`v0.10.5`](https://github.com/infracost/infracost/releases) version of Infracost. CI-specific data is limited to GitHub actions and Gitlab CI. Support for additional CI systems will be added soon.
