### ISSUE TITLE
Add support for azurerm_linux_web_app and azurerm_windows_web_app

### ISSUE THREAD

**Issue by uneti-max** [infracost/infracost#1767]
azurerm_app_service [is being deprecated](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service) in favor of

[azurerm_linux_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) and [azurerm_windows_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app) which are not currently supported.

Using [This page](https://azure.microsoft.com/en-us/pricing/details/app-service/linux/) as a source for prices

Cost Components seem to be:
`Instance Tier` - which corresponds to the virtual machine instance family hosting the app-service environment
`Instance Type` - a specific virtual machine size / spec which includes `Number of cores`, `Amount of RAM`, and `Storage amount`

App service has a free-tier instance type called `F1`

Prices are `Hourly` and include stopped instances

**Comment by vdmgolub** [comment]
Hi @uneti-max! Thank you for creating the issue! 

Our first step is usually to update the issue description with the details of what Cost Components are related to service. Here's an example how it can look like: https://github.com/infracost/infracost/issues/1038. I'd assume you already have some context around these resources, so maybe you'll be able to add them here. [This guide](https://github.com/infracost/infracost/blob/master/contributing/resource_mapping_guide.md) can help defining the cost components.
