### ISSUE TITLE
IP ranges for whitelist

### ISSUE THREAD

**Issue by mnhat3896** [infracost/infracost#1772]
Hi team :wave:
I need some help with our whitelist!
We are setting a whitelist IPs egress, here are our IPs

- "3.130.210.19/32",
- "3.20.213.154/32",
- "3.138.59.242/32",
- "3.23.123.206/32",
- "3.137.75.3/32",
- "18.216.2.173/32"

The problem is when I do a terraform plan I met this error
`
Error sending API request: Post "https://pricing.api.infracost.io/graphql": dial tcp 18.119.20.46:443: i/o timeout
time="2022-06-21T03:48:55Z" level=warning msg="Error reporting CLI error: Error sending API request: Post \"https://pricing.api.infracost.io/event\": dial tcp 18.119.20.46:443: i/o timeout"
`
If I do a check here https://www.whatsmydns.net/#A/pricing.api.infracost.io, these are worldwide IP

- pricing.api.infracost.io. 60 IN A 3.129.181.56
- pricing.api.infracost.io. 60 IN A 3.137.134.78
- pricing.api.infracost.io. 60 IN A 3.23.123.206

Of course, you can see that 18.119.20.46 is not in our whitelist, so my question is what is the best way to filter? If there is an IP range could you please give me that?

Thank you in advance!

**Comment by alikhajeh1** [comment]
@mnhat3896 are you using Terraform Enterprise Run Tasks by any chance? I ask as another user asked us a similar question and that service uses our hosted services in addition to the Cloud Pricing API that you mentioned above.

**Comment by mnhat3896** [comment]
@alikhajeh1 thank you for the quick response
our version is v0.9.17. we are not using TF Enterprise. we are also not self-hosting the Cloud Pricing API

**Comment by alikhajeh1** [comment]
Thanks - that's helpful. Can you also run `dig pricing.api.infracost.io` from the server you're running the CLI to see if the response matches https://www.whatsmydns.net/#A/pricing.api.infracost.io? That'll confirm that there's no funny stuff going on with DNS lookups on your side.

Whilst we don't have fixed IPs yet (we use AWS/EKS for our hosted services), but we'll see what we can do to unblock you :)

**Comment by mnhat3896** [comment]
well, I don't have permission to do that on the server where the CLI running, but it guess it same as https://www.whatsmydns.net/#A/pricing.api.infracost.io result because one of my colleague run success the terraform plan this morning, me neither. So I think there is something wrong with the DNS resolve, somehow it can't recognize these worldwide CDN yesterday. 
- 3.23.123.206
- 3.137.134.78
- 3.129.181.56

a small thing that we did dig [pricing.api.infracost.io](http://pricing.api.infracost.io/) in our different local and the result is different like these
```
➜  ~ host [pricing.api.infracost.io](http://pricing.api.infracost.io/)
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 3.137.134.78
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 3.129.181.56
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 3.23.123.206

host [pricing.api.infracost.io](http://pricing.api.infracost.io/)                     
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 18.119.20.46
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 18.224.198.88
[pricing.api.infracost.io](http://pricing.api.infracost.io/) has address 18.119.48.50
```

**Comment by alikhajeh1** [comment]
@mnhat3896 hmm you might be right, that smells like a DNS resolution issue on your side. When you run `dig pricing.api.infracost.io | grep SERVER` what do you see as your upstream DNS server? 

You can also run `dig pricing.api.infracost.io @8.8.8.8` to force the DNS lookup to use Google's 8.8.8.8 but I consistently get the [3 that whatsmydns.net](https://www.whatsmydns.net/#A/pricing.api.infracost.io) shows regardless of my DNS server.

I assume you've been using Infracost for months since 0.9.17 is from Jan 2022, did this issue start happening randomly recently? or do you now need to whitelist IPs due to other internal changes?

**Comment by mnhat3896** [comment]
@alikhajeh1 
on my local
```
➜  / dig pricing.api.infracost.io | grep SERVER
;; SERVER: 127.0.0.53#53(127.0.0.53)
```
and yes `dig pricing.api.infracost.io @8.8.8.8` is the same as [whatsmydns.net](https://www.whatsmydns.net/#A/pricing.api.infracost.io)

This issue is rarely happening, the last time is 2 months ago. if this happens again I'll check deeper in the next time since now it backed to work 3 days ago. 
Thank you for your support :pray:

**Comment by alikhajeh1** [comment]
Thanks @mnhat3896! Sure, we're happy to help :)
