### ISSUE TITLE
Support JSON files as Terraform var-file

### ISSUE THREAD

**Issue by pacorreia** [infracost/infracost#1773]
Team,

Please consider supporting JSON files as Terraform input files.

Terraform already supports that as per documenation [here](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files)

This would allow me to start using Infracost on top of source code instead of relying on Terraform JSON plans

**Comment by alikhajeh1** [comment]
@pacorreia great! @hugorut and @aliscott just FYI on this, I don't think it requires a CLI interface change so hopefully it's a fairly straightforward change?

**Comment by pacorreia** [comment]
count me on to help test it 👌

**Comment by pacorreia** [comment]
Just want to share that found this tool written in GO that can do HCL  to JSON a vice-versa, thought it might help:

https://github.com/gorpher/hcl2json

**Comment by hugorut** [comment]
hey @pacorreia, this should be a simple fix we just don't have it on the roadmap atm. Let me bring it up at our grooming meeting on Thursday and hopefully we can get it into the next release.

**Comment by pacorreia** [comment]
That would be very cool indeed 😊

A terça, 5/07/2022, 17:47, Hugo Rut ***@***.***> escreveu:

**Comment by hugorut** [comment]
@pacorreia this has now been fixed and is merged into master awaiting the next release. I'll ping here to let you know when it's live.

**Comment by pacorreia** [comment]
@hugorut will be glad to test asap and give a shout out 😊

**Comment by pacorreia** [comment]
Just saw it, already testing it, great work not only with this, but with other features!
