### ISSUE TITLE
Output file is not generated after the latest updates.

### ISSUE THREAD

**Issue by dgokcin** [infracost/infracost#1776]
Helloo

I noticed that although this command works really fast after, `infracost breakdown --path=terragrunt/app \ --format=json \ --out-file=infracost_base.json`  no infracost_base.json file is generated. 

Am I missing anything?

**Comment by hugorut** [comment]
@dgokcin I'm guessing you got this working?

**Comment by dgokcin** [comment]
@hugorut yes, my bad 🙃 it is working great!
