### ISSUE TITLE
Support fetching region from AWS profile

### ISSUE THREAD

**Issue by hugorut** [infracost/infracost#1779]
Infracost HCL parses the AWS `region` where provided in the `aws` Terraform provider block. e.g:

```
provider "aws" {
  region = "us-east-1"
}
```

However many users instead choose to dynamically set the `region` from the AWS profile.  For example:

```
provider "aws" {
  profile  = "myprofile"
}
```
```
# ~/.aws/credentials

[profile myprofile]
region=us-east-1
```

---
Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by alikhajeh1** [comment]
I'm closing this issue in favor https://github.com/infracost/infracost/issues/1796 as that describes a more generic way of solving this problem. @exoemay feel free to comment on the new issue with your preference.
