### ISSUE TITLE
Long Bitbucket comments

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1783]
## Problem

As shown in the following screenshot, Bitbucket does not support collapsible sections in pull request comments so the comment can become too big if the diff has more than a few changes.

<img width="1062" alt="Screen Shot 2022-06-27 at 3 07 47 PM" src="https://user-images.githubusercontent.com/638577/176044186-5405147d-92e2-481c-99ea-93c1292fb993.png">

### 1. Ask Bitbucket to support collapsible sections

GitHub, GitLab and Azure Repos all support collapsible sections in pull request comments. If you're a Bitbucket user, please consider commenting on [this feature request](https://jira.atlassian.com/browse/BCLOUD-15185?focusedCommentId=2253944&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel) in Bitbucket so Infracost can do the same thing as GitHub/GitLab/Azure Repos.

### 2. Add `--summary-only` option to `infracost comment bitbucket`

This would result in the Infracost pull request comment to only have the top summary table. This is the simplest option but it means users don't have the diff, which is useful if the summary shows something that requires further investigation.

### 3. Similar to option 2 but with a share link

The [Infracost share link](https://www.infracost.io/docs/features/share_links/) feature could be used to generate a link to the diff, so there is always a summary table and a link to the details if `--summary-only` is used.

## Which option do you prefer?

Please add a comment with the option you prefer?.
Also 👍 if you'd like to upvote this or receive updates.

**Comment by pietrodellamore** [comment]
I would love to have the 2 option available ASAP. 

Thanks for the effort on improving it for Bitbucket users.

**Comment by exoemay** [comment]
To me option 2 would be preferrable as it gives the most flexibility. 
Putting a feature request for atlassian just means waiting on this for years to come.
Option 3 is fine as well, but (to me) only in addition to option 1. I don't think everyone wants to use the share links, so having more flexibility is always preferred.

Thanks!

**Comment by OscarBarrett** [comment]
FYI: this *may* now be possible using a fenced code block with `expand` as the language identifier. This is what Atlassian Rovo does for its Code Reviewer comments.
Though their renderer might not have great support for markdown within the expand block.

e.g.
```
Expand example 1.\n```expand\nDetails\n\nInner contents.\n```\n
Expand example 2.\n```expand\nSome Other Title for Details\n\nInner contents.\n```\n
Expand example 3.\n```expand\nDetails\n\n## Heading within expand block\n\nMore content.\n```\n
```

(With example 1 and 3 opened)
<img width="493" height="350" alt="Image" src="https://github.com/user-attachments/assets/a6f35279-1c57-46ee-9df6-13d37581caa5" />
