### ISSUE TITLE
Override cloud regions

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1796]
## Problem

See https://github.com/infracost/infracost/issues/1779 for an example where users need to specify a region manually. We've ran into this with other users, often when Infracost can't detect a region from the user's project and falls back to the pre-defined default we've hardcoded in the CLI code.

Questions:
1. Should users be able to define the default using the infracost [usage-file](https://www.infracost.io/docs/features/usage_based_resources/) or [config-file](https://www.infracost.io/docs/features/config_file/)? I lean towards the usage-file as that has other usage information, whereas config-file is used for multi-project runs. A config-file can reference multiple usage-files, so if we add it to the config-file, we'd probably need to have it as a per-project setting.

2. Should users be able to override the region, or set the default region that is used as a fallback? It seems like the main use-case is the latter, but being able to override the region might be helpful if users want to compare costs between regions in a given cloud vendor?

## Proposed solution

See [this comment](https://github.com/infracost/infracost/issues/1796#issuecomment-1172535690).

## Community note

Please add a comment with what you prefer.
Also, 👍 or subscribe to the issue for updates.

**Comment by exoemay** [comment]
We often deploy the same terraform code to multiple regions by changing the environment terraform runs in. Having an environment variable to set the region would be my preferred approach. But still, that can just be an additional override to setting it in a config file.

Something like: environment var -> config/usage file -> provider
where -> means an override.

This way we can use good defaults in provider or config and override per env var if required.

**Comment by alikhajeh1** [comment]
@exoemay great point! We already have [override/precedence](https://www.infracost.io/docs/features/environment_variables/) for env vars. So for this issue, we can pick the region based on this order:
1. `INFRACOST_AWS_REGION` env var (new env var we can add for this issue)
2. `aws-region` config/usage-file (same thing as above but in config/usage-file)
3. terraform provider
4. default fallback that is hard-coded in the Infracost CLI.

In the future, if the above env doesn't fully address the use-case, we can also add a `INFRACOST_AWS_DEFAULT_REGION` similar to how [AWS does](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).

**Comment by yellowhat** [comment]
That would be great.

Thanks

**Comment by gurpalw** [comment]
we have an .envrc file that sets the AWS_REGION, based on the directory. it would be good if there was an option that looked for this AWS_REGION or AWS_DEFAULT_REGION value when determining the region.

at the moment, infracost is unusable for us until this is fixed.

**Comment by pacorreia** [comment]
Let em add a use case scenario:

I have a multi-region setup wehere terraform iterates through a list of regions.
Several resources are created using for_each and indexed by region.

For dependency reasons, I always refer to resource locations using the the location property of a parent resource rather than using the region variable. So in my case I'm kaing it hard for infracost to get it.

What if we either:
- Allow overriding regions in the usage file
- Implement a terraform code annotation for infracost allowing us to pass directive to infracost
   -  e.g. `#INFRACOST#LOCATION#eastus#`
   - When infracost finds this would know that the resource desribed immediately after shuld use location eastus

**Comment by vdmgolub** [comment]
The new ENV vars were merged to master and will go out with the next release.

**Comment by alikhajeh1** [comment]
@vdmgolub can you possibly add a link to the docs PR so users who want to try it early can do it by setting the env vars and following [this](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#install) then [this](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#run) step?

**Comment by aliscott** [comment]
@carmeloriolo, @gurpalw, @noriko3, and @pacorreia this has now been released in v0.10.14. Thanks for all your ideas and input 🙏 -  the docs for it [can be found here](https://www.infracost.io/docs/features/environment_variables/#environment-variables-to-override-cloud-provider-region).
