### ISSUE TITLE
Breakdown command: Failed to load module err

### ISSUE THREAD

**Issue by kayman-mk** [infracost/infracost#1827]
Hi guys,

I am really excited to get a cost breakdown for my infrastructure, but `infracosts breakdown` struggels downloading one of my modules.

Error message
```
time="2022-07-06T18:42:51Z" level=warning parser=terraform_hcl msg="Failed to load module err: missing module with source 'registry.terraform.io/Hapag-Lloyd/bastion-host-ssm/aws Hapag-Lloyd/bastion-host-ssm/aws' -  try to 'terraform init' first"
```

`terraform init` ran before. Everything is fine and the module was downloaded.

```
Downloading registry.terraform.io/Hapag-Lloyd/bastion-host-ssm/aws 1.12.16 for bastion...
- bastion in .terraform/modules/bastion
```

Module source
```
module "bastion" {
  source  = "Hapag-Lloyd/bastion-host-ssm/aws"
  version = "1.12.16"

  # once per account. We have "prod" only
  count = var.environment == "prod" ? 1 : 0

  # removed the rest of the variable assignments
}
```

`modules.json` looks like (I removed many modules for privacy reasons)
```
{"Modules":[{"Key":"","Source":"","Dir":"."}
{"Key":"bastion","Source":"registry.terraform.io/Hapag-Lloyd/bastion-host-ssm/aws","Version":"1.12.16","Dir":".terraform/modules/bastion"}]}
```

`infracost` is called with the following command (I checked the variables, they contain valid values):
```
infracost breakdown --path=. \
                          --format=json \
                          --out-file=infracost-base.json \
                          --terraform-var-file configuration/prod.tfvars \
                          --terraform-var environment=prod \
                          --terraform-var service_name=$SERVICE_NAME \
                          --terraform-var aws_account_id=${AWS_ACCOUNT_ID}
```

Might be related to #1730

**Comment by alikhajeh1** [comment]
@kayman-mk it looks like you're using private registry modules (registry.terraform.io), right? If so, support for this is merged in master and will go live in v0.10.7 next week.

Can you possibly help us test it by:
1. `git clone git@github.com:infracost/infracost.git`
2. `cd infracost`
3. `make build` This is assuming golang is installed, if not do https://golang.org/doc/install first
4. Check if you have one of these [two steps](https://github.com/infracost/docs/pull/243/files#diff-16f3ed1775643c78c2d3f8935b6b91a7d0121f6e723d2d0f9269f56e45bb1daaR53-R55) setup so the CLI can download registry modules (that's the link to the docs for the upcoming v0.10.7).
5. `./build/infracost --path=. ...` # same as before
```

**Comment by kayman-mk** [comment]
Our bastion module is published in the public registry at Hashicorp. No private registry.

Will do the test tomorrow.

**Comment by kayman-mk** [comment]
I built the binary locally. Version number shown `Infracost v0.10.6+13-ga5415c2a`

- [x] Checked with `terraform init`
- [x] Checked without `terraform init`

Great job. Can't wait for the next release 😏

**Comment by kayman-mk** [comment]
Closing. Will be solved with the next release.

**Comment by alikhajeh1** [comment]
Awesome - thanks for helping us test this!
