### ISSUE TITLE
Allow users to self-host the Infracost API

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [infracost/infracost#1837]
Hi

We would love to use Infracost, but we would feel more at ease hosting our own Infracost API, instead of only only hosting the Cloud Pricing API and still being dependent on a remote API.

Could you please consider this?

Thanks

**Comment by hassankhosseini** [comment]
Hey, thanks for the issue. We had this running for a while before, but the pricing APIs from the cloud providers are hard to work with (they changed without notifications, pricing were missed / wrongly updated, and bulky downloads), so they kept breaking user's CI/CD systems as the pricing service failed. This is how we have solved these issues.

You can stop the weekly download job from running so you don't contact Infracost, but prices change quite regularly, and you will quickly be out of date.

Cheers!
