### ISSUE TITLE
Add terraspace support, fix variable inferred instance_type cost estimate

### ISSUE THREAD

**Issue by silasmahler** [infracost/infracost#1858]
I noticed that variables inferred by terraspace are not parsed correctly. 
E.g.  Having a cost estimate of an aws_instance like:
![image](https://user-images.githubusercontent.com/14834495/178933040-a6a7b6a3-5ecd-4e9d-a0d2-cc86dd926905.png)
because the instance type is coded like:
  `instance_type               = var.server_instance_type`.
where var.server_instance_type is a variable of terraspace. Basically a file in format: myenv.tfvars in tfvars directory. Other than that this is handled like normal terraform variables. 
If we set:
  `instance_type               = "t3a.large"`. explicitly the cost estimate becomes more realistic:
![image](https://user-images.githubusercontent.com/14834495/178933810-c74a7182-0426-4178-9038-23a64e29ef50.png)

As i noticed it also happened with other vars, e.g. for ebs configuration.

**Comment by hugorut** [comment]
Hi @silasmahler, this doesn't sound like a Terraspace issue but more a naming convention issue. I can see you've included screenshots from the VSCode extension, which uses a naive way to apply `tfvar` files at the moment. They need to use a specific naming convention: https://github.com/infracost/vscode-infracost#how-can-i-supply-input-variables-to-infracost-vscode-extension for more information.

If you want to use Infracost cli to read this tfvar file, you can point the `--terraform-var-file` flag to the location of this file. e.g.:

```
infracost breakdown --path to/my/infra --terraform-var-file myenv.tfvars
```

**Comment by silasmahler** [comment]
> @silasmahler can this issue be closed?

Yes, haven't tested it, but should be the case cause it uses normal var interpolation mechanisms of terraform. Other than that the dot-dir is interferring with terraspace caching, but I'd say this would be configurable. Maybe i'll test it out sometime.
