### ISSUE TITLE
Support for multiple paths.

### ISSUE THREAD

**Issue by netguino** [infracost/infracost#1860]
It would be great if the cli supported the inclusion of multiple `--path` flags. 

```
infracost breakdown --path foo --path bar
```

This currently results in only `bar` being evaluated. This would be a great solution that could solve this https://github.com/infracost/infracost/issues/1841

**Comment by alikhajeh1** [comment]
@netguino can you possibly share a bit more about how this would help? Could the [solution](https://github.com/infracost/infracost/issues/1841#issuecomment-1180571569) mentioned here be used? Alternatively, a [config-file](https://www.infracost.io/docs/features/config_file/) could be auto-generated with the project dirs that have changed, and run `infracost breakdown --config-file /tmp/changed-infracost.yml` etc, but that'll mean that the summary table won't show the total cost estimate for the project.

**Comment by alikhajeh1** [comment]
@netguino just FYI we merged [this](https://github.com/infracost/actions/blob/master/examples/using-cache/README.md) after testing/using it with other users, it seems to be helping them. Later this week, I'll publish a new github issue about an interface change we'd like to propose to make it easier to run infracost against a config-file, I'll tag you in that for feedback as we're leaning towards that approach vs having tons of flags. The idea being that the same config file can be used by the CLI, VSCode, CI/CD integrations (e.g. docker-compose.yml or docker-compose-dev.yml)

**Comment by netguino** [comment]
> @netguino can you possibly share a bit more about how this would help? Could the [solution](https://github.com/infracost/infracost/issues/1841#issuecomment-1180571569) mentioned here be used? Alternatively, a [config-file](https://www.infracost.io/docs/features/config_file/) could be auto-generated with the project dirs that have changed, and run `infracost breakdown --config-file /tmp/changed-infracost.yml` etc, but that'll mean that the summary table won't show the total cost estimate for the project.

I like the idea of calling infracost once. 

To me it's not so much about what can I do, but the fact that the tool lets me pass --path more than once, and it basically ignores the first instance. It shouldn't.
