### ISSUE TITLE
Consistent configuration options across flags, env vars and config-file

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1869]
### Problem
It can be confusing to tell which CLI option has to be configured using which method (e.g. env var vs flags).

Depending on the setting being changed, the Infracost CLI can be configured by:
- CLI flags (e.g. `infracost breakdown --project-name=blah`)
- [env vars](https://www.infracost.io/docs/features/environment_variables/)
- `infracost configure`
- [config-file](https://www.infracost.io/docs/features/config_file/)
- Infracost Cloud

The above list also describes the [precedence order](https://www.infracost.io/docs/features/config_file/#precedence).
 
### Proposed solution

Review settings to see if it makes sense for all settings to be supported in all methods. Atlantis does [something cool](https://www.runatlantis.io/docs/server-configuration.html#environment-variables) where all flags can be specified as env vars.

**Comment by aliscott** [comment]
While I like the idea of making these consistent, I'm not convinced it makes sense in all cases. Atlantis has one main top-level command so for their case it's more intuitive.

One thought is to think of the the different configuration options being at different levels and adding the config for each level that makes sense, i.e:

* `infracost configure` & env vars - machine-level config
* Infracost Cloud - org-level config
* config-file - project-level config
* CLI flags - command/run-level config

Some examples:
1. Log level makes sense to be at machine-level or command-level but not necessarily project level or org level.
2. Different commands have different flags, so does it make sense to have higher-level config options for these. For example `infracost diff` has `--compare-to`, so it might be confusing if `INFRACOST_COMPARE_TO` env var only applies to diff.
3. Different commands have overlapping flags. It would be confusing if `INFRACOST_OUT_FILE` is set and the `infracost breakdown`, `diff` and `output` commands' output all overwrite each other. Terraform has `TF_CLI_ARGS_<command_name>` env vars which might help with these two cases.

**Comment by alikhajeh1** [comment]
We've created https://github.com/infracost/infracost/issues/1959 with a proposal on how Infracost could be run in the future with a config file. I'm going this issue so we can continue the discussions there.
