### ISSUE TITLE
Show price of whole repository changes (proposal)

### ISSUE THREAD

**Issue by chapayevdauren** [infracost/infracost#188]
For example, we have terraform directories for production and staging
```
/my-project
     /production
          main.tf
     /staging
          main.tf
```
and I want show price changes for both of them. Will be nice if we can add like this feature?

**Comment by alikhajeh1** [comment]
@chapayevdauren thanks for creating this issue! Can you possibly provide more context about the use-case, e.g. a variable is being changed that impacts the cost in production and staging, and you'd like to see the cost estimate for both projects by running infracost once? There is also https://github.com/infracost/infracost/issues/90, would that help your use-case?

**Comment by chapayevdauren** [comment]
> e.g. a variable is being changed that impacts the cost in production and staging, and you'd like to see the cost estimate for both projects by running infracost once?

@alikhajeh1 yep
i.e. I have the following repository structure

```
/my-infrastructure-repository
      /project-1
           /production
                main.tf
           /staging
                main.tf
      /project-2
           /production
                main.tf
           /staging
                main.tf
       etc...
```
so I want to show price changes for each file

**Comment by alikhajeh1** [comment]
@chapayevdauren sorry for the delay! Can you please try the following bash script and see if it solves your use-case? It uses the [`infracost report`](https://www.infracost.io/docs/#report) command to produce table output in the terminal, and saves an HTML file (called report.html). You can customize it to only grep certain projects or exclude other things. The HTML report includes the file path so you should be able to identify the cost of `project-1-production`, `project-1-staging` etc in the output. Please let me know if this helps and I'll add it to the [scripts dir](https://github.com/infracost/infracost/tree/master/scripts).

```sh
#!/usr/bin/env bash

# Find all subfolders that have .tf files, but exclude "modules" folders, can be customized
tfprojects=$(find . -type f -name '*.tf' | sed -E 's|/[^/]+$||' | grep -v modules | sort -u)

# Run infracost on the folders individually
while IFS= read -r tfproject; do
  echo "Running infracost for $tfproject";
  cd $tfproject
  filename=$(echo $tfproject | sed 's:/:-:g' | cut -c3-)
  # TODO: customize to how you run infracost
  infracost --tfdir . --output json > "$filename-infracost-out.json"
  cd - > /dev/null
done <<< "$tfprojects"

# Run infracost report to merge the subfolder results
jsonfiles=$(find . -name "*-infracost-out.json")
infracost report --output html $(echo $jsonfiles | tr '\n' ' ') > report.html
infracost report --output table $(echo $jsonfiles | tr '\n' ' ')

# Remove temp json files
rm $(echo $jsonfiles | tr '\n' ' ')
```

**Comment by chapayevdauren** [comment]
@alikhajeh1 I will try

**Comment by alikhajeh1** [comment]
https://github.com/infracost/infracost/pull/321 closes this issue for now, we still have more work to do to simplify things for users with multiple TF projects but we can create new issues based on user requests.

**Comment by alikhajeh1** [comment]
@chapayevdauren did you get a chance to try [this](https://www.infracost.io/docs/report#bulk-run)? [This comment](https://github.com/infracost/infracost-gh-action/issues/16#issuecomment-767820083) got me thinking how your project structure could work in CI... would [this method](https://github.com/infracost/infracost-gh-action/issues/16#issuecomment-767828376) possibly work for you?
