### ISSUE TITLE
Add support for using a repo default config file automatically

### ISSUE THREAD

**Issue by LiamDeaconAntarcticaAM** [infracost/infracost#1899]
Many other tools (e.g. checkov, trunk, yamllint, etc.) search for the presence of a config file in specific location(s) and automatically use it if found. 

To the best of my knowledge there is not yet any such functionality. In my ideal situation I would like `infracost` to automatically check for a file such as `.infracost.yml` in the git repo root directory and use that as the default configuration when found. Users could still explicitly specify a config file at the command line should they wish to use a different config.

Having such as feature would help lower the barrier of adoption for users who wish to see infrastructure costs, but who did not set up the details (and do not care about them) within a given git repository themselves.

**Comment by alikhajeh1** [comment]
@LiamDeaconAntarcticaAM since an infra repo can have multiple workspaces/projects, I'm curious to hear your thoughts on having a top-level repo config-file vs per-directory config files, see [question 2](https://github.com/infracost/infracost/issues/1280#issuecomment-1013851153) in this comment for an example.

**Comment by alikhajeh1** [comment]
@LiamDeaconAntarcticaAM this issue influenced our thinking a lot :) We've created https://github.com/infracost/infracost/issues/1959 with a proposal on how Infracost could be run in the future with a config file. I'm going this issue so we can continue the discussions there.
