### ISSUE TITLE
Support for ECS and Fargate

### ISSUE THREAD

**Issue by lukeberry99** [infracost/infracost#19]
Hello,

I was wondering what would be involved in adding support for ECS (specifically Fargate) pricing - I'm not opposed to implementing this myself but a nudge in the right direction would be great.

Cheers!

**Comment by aliscott** [comment]
Sounds good, we will add support for this soon.

Fargate pricing can be calculated using the price for `aws_ecs_task_definition.{cpu,memory}` multiplied by `aws_ecs_service.desired_count`. I've created a ticket for adding Fargate spot pricing to the pricing API, so we can support spot pricing for this as well.

ECS with EC2 launch strategy is more complicated. This will involve us working out the instance count of the autoscaling group used as the capacity provider. This will depend on the usage of all the tasks in the cluster, the instance types used in the autoscaling group and the placement strategy.

@lukeberry99 a couple of questions:
1. Are you only using the Fargate launch strategy or both Fargate and EC2? Are you looking to compare them?
2. Are you using any spot pricing for either?

**Comment by aliscott** [comment]
ECS support with Fargate has now been added (https://github.com/infracost/infracost/pull/36) released. ECS support for EC2 launch type is more complicated. I have created separate issue to track that (https://github.com/infracost/infracost/issues/79)
