### ISSUE TITLE
Add VPC pricing

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#191]
We currently support `aws_nat_gateway` pricing, but we need to add pricing for the following VPC resources:

* AWS PrivateLink pricing (https://aws.amazon.com/privatelink/pricing/)
  * Terraform resource: `aws_vpc_endpoint
* AWS Site-to-Site VPN pricing (https://aws.amazon.com/vpn/pricing/)
  * Terraform resource: `aws_vpn_connection`
* AWS VPC traffic mirroring pricing (https://aws.amazon.com/vpc/pricing/)
  * Terraform resource: `ec2_traffic_mirror_session`

**Comment by robh007** [comment]
I'll take this one @aliscott @alikhajeh1, I've got a PR nearly ready to go for vpc_endpoint.

**Comment by robh007** [comment]
I'll also include Transit Gateway.

**Comment by alikhajeh1** [comment]
Fixed by https://github.com/infracost/infracost/pull/264, https://github.com/infracost/infracost/pull/265 and https://github.com/infracost/infracost/pull/266.
FYI @dawidmalina, this should be live tmrw in the next release of infracost (v0.7.8).
