### ISSUE TITLE
Add support for AWS Codebuild Project

### ISSUE THREAD

**Issue by SiahaanBernard** [infracost/infracost#193]
## Description
I would like to try to create PR for this. I think to calculate Codebuild porejct cost we can use similar approach on how lambda cost calculate, since both of them is usage-based pricing. We can use `monthly_build_minutes` as variable to define the usage duration of codebuild within a month in minutes metric. What do you think?

## Reference:
1. [Codebuild Pricing](https://aws.amazon.com/codebuild/pricing/)

**Comment by alikhajeh1** [comment]
@SiahaanBernard thanks for creating this issue. That sounds great!

For [level 1 support](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#level-1-support), it looks like `environment.type` and `environment.compute_type` in `codebuild_project` can be used to fetch the pricing (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project)

For level 2 support](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#level-2-support), what you propose makes sense.

I'd be happy to review the PRs :)

**Comment by ekifel** [comment]
Hello! I want to pick it up :)

**Comment by alikhajeh1** [comment]
@SiahaanBernard this will be released in next week's release, it was done in #390 thanks to @ekifel!
