### ISSUE TITLE
Error trying to use infracost comment with GHE

### ISSUE THREAD

**Issue by danielbmeireles** [infracost/infracost#1933]
Hello!

I am getting the following error during the posting of an infracost diff report in the PR's comment session:

```
Error: The pull request comment was generated successfully but could not be posted:
non-200 OK status code: 404 Not Found body: "{\"message\":\"Not Found\",\"documentation_url\":\"[https://docs.github.com/enterprise/3.3/rest\"}"](https://docs.github.com/enterprise/3.3/rest/%22%7D%22)

See https://infracost.io/docs/troubleshooting/#5-posting-comments for help.
```

I am using the following syntax (Azure Pipelines + GHE 3.3.7)

```
      - bash: |
          infracost comment github --path=$(Agent.TempDirectory)/infracost-diff.json \
                                   --github-token=${{ parameters.ghToken }} \
                                   --github-api-url="https://API_SERVER_ADDR/api/v3/" \
                                   --commit=$(Build.SourceVersion) \
                                   --repo=$(Build.Repository.Name) \
                                   --behavior=update
        displayName: Post Infracost comment
```

I have a PR opened and I am using a token with all scopes selected.

Do I need to add any extra parameters when using this command against a GHE instance?

**Comment by aliscott** [comment]
Hi @danielbmeireles, thanks for reporting. I don't have a GHE instance myself to test on just now, but looking at the code I wonder if it works if you pass `--github-api-url="https://API_SERVER_ADDR/api"` or `--github-api-url="https://API_SERVER_ADDR"`?

**Comment by danielbmeireles** [comment]
Presto!

```
--github-api-url="https://API_SERVER_ADDR/api"
```

Thank you so much for your help!

**Comment by aliscott** [comment]
Thanks @danielbmeireles. For now I've updated the docs here https://www.infracost.io/docs/features/cli_commands/#github for Azure Repos.
