### ISSUE TITLE
Support AWS Lambda tiered pricing

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1949]
AWS [announced support](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-lambda-tiered-pricing/) for tiered Lambda pricing. We should update the `aws_lambda_function` resource to support multiple tiers for the Duration cost component.

**Comment by hugorut** [comment]
Reopening this issue as https://github.com/infracost/infracost/pull/1950 did not add full support for tiered pricing

**Comment by robh007** [comment]
I can take a look at this @aliscott @hugorut

**Comment by aliscott** [comment]
This has now been released in v0.10.14. Thanks @robh007 🙏
