### ISSUE TITLE
Add support for Azure route table resources

### ISSUE THREAD

**Issue by lintaonz** [infracost/infracost#1953]
```hcl
∙ 8 are not supported yet, see https://infracost.io/requested-resources:
  ∙ 4 x azurerm_route_table
  ∙ 4 x azurerm_subnet_route_table_association
```
Both `azurerm_route_table` and `azurerm_subnet_route_table_association` are quite common for Azure networking. 

Could Infracost support them, please?

**Comment by davetustin** [comment]
I would also like this feature added.

∙ 3 are not supported yet, see https://infracost.io/requested-resources:
  ∙ 2 x azurerm_subnet_route_table_association
  ∙ 1 x azurerm_route

Thank you!
