### ISSUE TITLE
Project not properly split (using git-ssh and bitbucket)

### ISSUE THREAD

**Issue by tbugfinder** [infracost/infracost#1973]
Hello,

my remote is:
origin  ssh://git@bbserver.domain.com:7999/~first.second_domain.com/stack-project.git (fetch)
origin  ssh://git@bbserver.domain.com:7999/~first.second_domain.com/stack-project.git (push)

infracost translates this to the Project:
Project: 7999/~first

It would be better if the git repo would be displayed.

**Comment by tbugfinder** [comment]
IMHO, shortest approach would be „stack-project“, however if BB projects or forked repos should be considered then „“ is better.

**Comment by vdmgolub** [comment]
Awesome! Thank you! We'll work on a fix, so it makes in the next release.

**Comment by vdmgolub** [comment]
@tbugfinder Just letting you know that the fix is merged to master. It will go out with the next release. Thanks again for reporting the issue! 👍

**Comment by hugorut** [comment]
A fix for this issue is now live in the [v0.10.12](https://github.com/infracost/infracost/releases/tag/v0.10.12) release.
