### ISSUE TITLE
Add support for Azure Functions

### ISSUE THREAD

**Issue by kalyanaramansmart** [infracost/infracost#1991]
# Add support for Azure Functions. 

Azure Function is a serverless compute service that enables user to run event-triggered code without having to provision or manage infrastructure. They are analogous to AWS lambdas.

## Relevant Terraform resources

| resource name                | docs link                                                                                            | notes      |
|------------------------------|------------------------------------------------------------------------------------------------------|------------|
| azurerm_function_app         | https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app         | deprecated |
| azurerm_windows_function_app | https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app |            |
| azurerm_linux_function_app   | https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app   |            |

## Relevant pricing pages

https://azure.microsoft.com/en-gb/pricing/details/functions/

## Notes

As these are serverless functions they are usage-based, and priced per execution time and memory usage.

## Note/Request For Community

Please 👍 if you'd like to upvote this or see this feature coming up.

**Comment by hugorut** [comment]
hey @kalyanaramansmart, thanks for opening this issue. I've updated the issue description to cover generic  **Azure Functions**. From a quick search, it also looks like the original resource you requested `azurerm_function_app`, is deprecated in favour of the `linux` or `windows` specific resources. Would you still want to cover that resource knowing this?

We prioritize and work on resources based on 👍 and usage metrics. If you want to get ahead of our roadmap we're very welcoming to [contributions](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#adding-new-resources).

**Comment by kalyanaramansmart** [comment]
Thankyou @hugorut
