### ISSUE TITLE
Need An npm package for infracost 

### ISSUE THREAD

**Issue by kalyanaramansmart** [infracost/infracost#1996]
Hello Infracost Team,
  I need An Npm Package to estimate the price for the terraform without using the file passing the terraform file as a string to a function and then the function will return the price for the resources like that

**Comment by alikhajeh1** [comment]
@kalyanaramansmart can you possibly share more about what you're trying to achieve? what's the use-case? If you're trying to create an Infracost integration, please see [this doc](https://www.infracost.io/docs/integrations/third_party_integrations/#creating-an-integration).

**Comment by kalyanaramansmart** [comment]
I need a Package like the following code;


import {getCost} from infracost;

function getCostForTerraform(){


let terraformCode = `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}

# Create a VPC
resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
}`

let costResponse = await getCost(terraformCode);

}

//like this if i pass the terraform code as a string then the package will return the json cost  as response  i can use infracost without running a terminal / powershell

**Comment by alikhajeh1** [comment]
Thanks for adding more details, you can subscribe to [this issue](https://github.com/infracost/infracost/issues/1685) for updates.
