### ISSUE TITLE
Allow pass through of tf vars

### ISSUE THREAD

**Issue by sashman** [infracost/infracost#20]
```
infracost --tfdir examples/terraform
```

It's a nice to have for the above command to also accept the variables required for the terraform plan. For example:

```
infracost --tfdir examples/terraform -var key=value
```
or
```
infracost --tfdir examples/terraform --var-file my.tfvars
```

**Comment by aliscott** [comment]
Added `--tfflags` option in https://github.com/infracost/infracost/pull/147 which covers this use case.
