### ISSUE TITLE
infracost comment gitlab - 404

### ISSUE THREAD

**Issue by black-snow** [infracost/infracost#2055]
I followed [this](https://gitlab.com/infracost/infracost-gitlab-ci) but the job fails with

> time="2022-09-22T12:11:16Z" level=info msg="Estimate uploaded to organization 'xxx' in Infracost Cloud"
time="2022-09-22T12:11:16Z" level=info msg="Finding matching comments for tag infracost-comment"
time="2022-09-22T12:11:17Z" level=info msg="Found 0 matching comments"
time="2022-09-22T12:11:17Z" level=info msg="Creating new comment"
Error: The pull request comment was generated successfully but could not be posted:
Error creating comment: 404 Not Found
See https://infracost.io/docs/troubleshooting/#5-posting-comments for help.

Infracost-wise everything looks good so far
![grafik](https://user-images.githubusercontent.com/579733/191749891-b9cf5880-683f-4476-8564-b1358caba1ce.png)

Here's the debug output when I reproduce this locally:

```
[
{
  "currency": "USD",
  "enable_cloud_org": false,
  "file": "/app/internal/config/run_context.go:196",
  "func": "github.com/infracost/infracost/internal/config.(*RunContext).IsCloudEnabled",
  "is_cloud_enabled": false,
  "level": "debug",
  "msg": "IsCloudEnabled inferred from Config.EnabledDashboard",
  "sync_usage": false,
  "time": "2022-09-22T12:24:17Z"
},
{
  "currency": "USD",
  "enable_cloud_org": false,
  "file": "/app/cmd/infracost/main.go:251",
  "func": "main.loadCloudSettings",
  "level": "debug",
  "msg": "Successfully loaded settings from Infracost Cloud",
  "result": "{CloudEnabled:false}",
  "sync_usage": false,
  "time": "2022-09-22T12:24:17Z"
},
{
  "currency": "USD",
  "enable_cloud_org": false,
  "file": "/app/internal/config/run_context.go:196",
  "func": "github.com/infracost/infracost/internal/config.(*RunContext).IsCloudEnabled",
  "is_cloud_enabled": false,
  "level": "debug",
  "msg": "IsCloudEnabled inferred from Config.EnabledDashboard",
  "sync_usage": false,
  "time": "2022-09-22T12:24:17Z"
},
{
  "file": "/app/internal/comment/handler.go:99",
  "func": "github.com/infracost/infracost/internal/comment.(*CommentHandler).matchingComments",
  "level": "info",
  "msg": "Finding matching comments for tag infracost-comment",
  "time": "2022-09-22T12:24:17Z"
},
{
  "file": "/app/internal/comment/handler.go:109",
  "func": "github.com/infracost/infracost/internal/comment.(*CommentHandler).matchingComments",
  "level": "info",
  "msg": "Found 0 matching comments",
  "time": "2022-09-22T12:24:18Z"
},
{
  "file": "/app/internal/comment/handler.go:155",
  "func": "github.com/infracost/infracost/internal/comment.(*CommentHandler).UpdateComment",
  "level": "info",
  "msg": "Creating new comment",
  "time": "2022-09-22T12:24:18Z"
},
Error: The pull request comment was generated successfully but could not be posted:
Error creating comment: 404 Not Found

See https://infracost.io/docs/troubleshooting/#5-posting-comments for help.,
```

Image used: infracost/infracost:ci-0.10@sha256:488b5a249fa21dfb820bff13e734f2412bab067904eb6b716c32976aeb30d170

**Comment by vdmgolub** [comment]
@black-snow Hello! Thank you for creating the issue and providing the debug output! :)

The `infracost comment gitlab` performs two API requests to GitLab:
1. Check the existing comment on the merge request (using GitLab's GraphQL)
2. Post a new/update comment (using GitLab's REST API)

It seems like the first request worked fine as it showed 0 comments, but the second one failed with 404 status, which could mean it didn't find the target MR. This is odd because both requests use the same values.

Could you please try to make a manual cURL request described in our [troubleshooting guide](https://gitlab.com/infracost/infracost-gitlab-ci#http-403-error-when-posting-comments) to see if everything is in place:
```
export GITLAB_TOKEN=mytoken

# If you're not using GitLab.com, set this to your server URL
export CI_SERVER_URL=https://gitlab.com

# Your repo path in the form of namespace/project with encoded slash character. If your repo path has a group, try the curl with and without the group, e.g. also try my-org%2my-group%2my-repo
export CI_PROJECT_PATH=my-org%2my-repo

# Set this to your merge request ID
export CI_MERGE_REQUEST_IID=123

curl -i -X POST \
  --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
  --data-urlencode "body=testcomment" \
  $CI_SERVER_URL/api/v4/projects/$CI_PROJECT_PATH/merge_requests/$CI_MERGE_REQUEST_IID/notes
```

If everything is alright, it will create a new comment on MR. This would mean that something missing from the command in the pipeline.

**Comment by black-snow** [comment]
Thanks for the quick reply @vdmgolub !

The slash in `CI_PROJECT_PATH` should not be urlencoded.

```
HTTP/2 404
date: Fri, 23 Sep 2022 08:08:44 GMT
content-type: application/json
content-length: 25
cache-control: no-cache
content-security-policy: default-src 'none'
vary: Origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-request-id: f6cabf789568d36075e75849fbc642d6
x-runtime: 0.021685
strict-transport-security: max-age=31536000
referrer-policy: strict-origin-when-cross-origin
ratelimit-observed: 1
ratelimit-remaining: 1999
ratelimit-reset: 1663920584
ratelimit-resettime: Fri, 23 Sep 2022 08:09:44 GMT
ratelimit-limit: 2000
gitlab-lb: fe-22-lb-gprd
gitlab-sv: localhost
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=lYAMjUwcvcsJbFbvqnDKDzejRWJBrSXtVgWVGiyDv3ISPO8SMcMjfB3Z0wAIUlHYDBvLzEfpNACEhEIpjanF3W9C2usuXkc6sXEoSl7pb9dwh7C%2FaV%2F34KPGGYk%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 74f1cb4cdffdb7a3-AMS

{"error":"404 Not Found"}
```

**Comment by black-snow** [comment]
Tested again with a public test project - posting comments works there.

**Comment by black-snow** [comment]
I created a project access token with api scope but the guest role ... works with more privileged roles 🤦 
Maybe you could add a hint to the docs ;) @vdmgolub

**Comment by vdmgolub** [comment]
@black-snow Great job on solving this! 👏

We don't use GitLab's premium/ee features, so I guess the guest role was overlooked as it's not mentioned in their docs. Thanks for the tip! I'll play with their EE setup and update our docs 👍
