### ISSUE TITLE
Add support for AWS EKS

### ISSUE THREAD

**Issue by shomeprasanjit** [infracost/infracost#208]
Add support for AWS EKS
Pricing: https://aws.amazon.com/eks/pricing/
Resource: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster

**Comment by alikhajeh1** [comment]
@shomeprasanjit the PR for this is almost done (https://github.com/infracost/infracost/pull/206), it should make this week's release.
Closing this issue as it's a duplicate of https://github.com/infracost/infracost/issues/82
