### ISSUE TITLE
azurerm_managed_disk pricing at 0.00

### ISSUE THREAD

**Issue by megakid** [infracost/infracost#2101]
It seems the `azurerm_managed_disk` resource is not getting correct priced:

Our Premium LRS P40 disks cost £291.66 a month fixed, plus £15.29 per mount. See https://azure.microsoft.com/en-gb/pricing/details/managed-disks/

I see #588 but it doesnt' seem to be working for us.

```
time="2022-10-25T09:13:49Z" level=warning msg="No products found for azurerm_managed_disk.disk[\"disk6\"] Storage (P40), using 0.00"
time="2022-10-25T09:13:49Z" level=warning msg="No products found for azurerm_managed_disk.disk[\"disk7\"] Storage (P40), using 0.00"
time="2022-10-25T09:13:49Z" level=warning msg="No products found for azurerm_managed_disk.disk[\"disk8\"] Storage (P40), using 0.00"
time="2022-10-25T09:13:49Z" level=warning msg="No products found for os_disk Storage (P20), using 0.00"
time="2022-10-25T09:13:49Z" level=warning msg="No products found for module.custom_dns_zone.azurerm_private_dns_zone.custom_dns Hosted zone, using 0.00"
```

Running infracost v0.10.11 against the cloud API

**Comment by aliscott** [comment]
@megakid Azure made some changes recently to their pricing API. Are you able to try with v0.10.13 which should fix this issue?

**Comment by alikhajeh1** [comment]
Closing this issue as it seems to be fixed, https://azure.microsoft.com/en-gb/pricing/details/managed-disks/ shows $259.05 for the following resource, which matches to what the Infracost output is. The price per mount isn't covered just now, a new issue is needed to track that

```
resource "azurerm_managed_disk" "premium-LRS-P40" {
  name                = "premium"
  resource_group_name = "fake_resource_group"
  location            = "eastus"

  create_option        = "Empty"
  storage_account_type = "Premium_LRS"
  disk_size_gb = "2000"
}
```

```
 azurerm_managed_disk.premium-LRS-P40
 └─ Storage (P40, LRS)                                  1  months                         $259.05
```
