### ISSUE TITLE
Azure managed disk ignored when storage_account_type = "StandardSSD_ZRS"

### ISSUE THREAD

**Issue by Marcus-James-Adams** [infracost/infracost#2126]
Infracost v0.10.13

When storage types are set as StandardSSD_LRS, infracost reports storage costs correctly but if you change the type to "StandardSSD_ZRS" then the costs are ignored when hey should be 3xthe LRS cost.

This is both within azurerm_managed_disk and the OS disk created as part of azurerm_windows_virtual_machine

When the storage type is set as "StandardSSD_LRS" for both types of disks

```
Project: *******

 Name                                                          Monthly Qty  Unit                    Monthly Cost (GBP)

 azurerm_managed_disk.drive_e
 ├─ Storage (E50)                                                        1  months                             £292.54
 └─ Disk operations                                   Monthly cost depends on usage: £0.001731436 per 10k operations

 azurerm_managed_disk.drive_f
 ├─ Storage (E50)                                                        1  months                             £292.54
 └─ Disk operations                                   Monthly cost depends on usage: £0.001731436 per 10k operations

 azurerm_windows_virtual_machine.server
 ├─ Instance usage (pay as you go, Standard_E2ds_v5)                   730  hours                              £164.95
 └─ os_disk
    ├─ Storage (E15)                                                     1  months                              £18.28
    └─ Disk operations                                Monthly cost depends on usage: £0.001731436 per 10k operations

 OVERALL TOTAL (GBP)                                                                                           £768.32
```
When the storage type is set as "StandardSSD_ZRS" for both types of disks

```
Project: *******

 Name                                                 Monthly Qty  Unit   Monthly Cost (GBP)

 azurerm_windows_virtual_machine.server
 ├─ Instance usage (pay as you go, Standard_E2ds_v5)          730  hours             £165.90

 OVERALL TOTAL (GBP)                                                                 £165.90
```

**Comment by hugorut** [comment]
Hey @Marcus-James-Adams, thanks for raising this. Yes, looking at the code for `azurerm_managed_disk` we don't currently support `ZRS` disk types. I think this is something we could accomodate quite easily by the looks of it. However, just to set your expectations, we have a lot of other high priority issues in our backlog. So we might not get to this that quickly. If you want this quicker than our current roadmap, feel free to dive in and raise a PR ❤️

**Comment by grixxie** [comment]
hey @hugorut I'm going to try to get this one sorted as my first contribution. How do I add this to the project board?

**Comment by alikhajeh1** [comment]
I think this was fixed by https://github.com/infracost/infracost/pull/2153
