### ISSUE TITLE
Add support for AWS KMS

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#213]
AWS pricing: https://aws.amazon.com/kms/pricing/
Terraform resources: `aws_kms*`

**Comment by sashman** [comment]
yo @alikhajeh1 can take this one on please?

**Comment by alikhajeh1** [comment]
@sashman thanks! I assigned it to you. If you notice duplicated costComponents/resources between the new new stuff you're adding, it might make sense to put them in a function in one of the resources and call it from the other ones. e.g. https://github.com/infracost/infracost/pull/222/files#diff-08ef288af65faeed6959c5e5d903167df115ae5fd0df2621b341c53f35856276R39 and https://github.com/infracost/infracost/pull/222/files#diff-c8fe718baaa1eb2eaade38039c21e6dea3927a01142b43143dd3be3f09b12be3R33
