### ISSUE TITLE
Infracost failing on dir with empty TF files

### ISSUE THREAD

**Issue by orbitz** [infracost/infracost#2186]
We have a directory that has tf files in it but they are empty.  Terraform handles this fine, however infracost gives the error:

> Error: No valid terraform files found given path, try a different directory

**Comment by hugorut** [comment]
Hey @orbitz, what is your use case for this? And what would you like as the expected behaviour here? For me, failing makes sense here. Infracost cannot provide cost estimates for a project without Terraform resources, so it doesn't make a lot of sense to run in this directory.

**Comment by orbitz** [comment]
I think the expected behaviour is that the cost of this directory is 0.  Terraform can plan this fine (it says there are no changes).  It makes sense to me that if Terraform can plan it, infracost should evaluate it successfully as well.

Does Infracost fail if a plan file has no changes in it?

**Comment by hugorut** [comment]
I'm afraid I disagree with you. I think failing is expected behaviour as `--path` autodetection is not the same as parsing a plan. There are various things we need to consider in this scenario, which impact other users' expected behaviour, e.g. multi-project. Infracost is not a 1-1 mapping with the functionality of Terraform, and we deviate quite significantly from it with our CLIs behaviour.

What is your use case for having a blank Terraform project and running Infracost on it? If you explain perhaps I can give you a workaround.

**Comment by orbitz** [comment]
Maybe I have a less sophisticated view of Infracost, but an empty TF files seems to be an valid Terraform file, and Terraform parses it fine.  Why is an empty TF file any different from one with just null resources, which Infracost handles fine?

The use case I have is that we have an algorithm for detecting which directories have Terraform files in them and then we explicitly run Infracost on each directory that we have detected.

**Comment by hugorut** [comment]
Ok, @orbitz, thanks for explaining your use case. So Infracost is different in that we autodetect projects, unlike terraform. i.e. `terraform plan` in a top-level multi-project will fail with "No configuration files", but Infracost will traverse directories to try and build a list of projects. In certain scenarios, users require the exit code "No valid terraform files found given path" to apply different logic.

With your approach, I'd recommend that you either alter your algorithm to do the same thing as infracost (files with no resources are not valid) or use `infracost --path` to autodetect those projects for you.

I'm going to close this issue for now, as based on the discussion, I don't think it's something we'll be looking to change soon. That being said, we might reopen this in the future if we decide to make a breaking change to the interface.

**Comment by orbitz** [comment]
hey @hugorut , I'm still not quite sure how to address this on my side.  I use infracost by creating a config.yml with all of my projects in it.  If there are empty TF files in one of those projects, it fails.  The error message is also insufficient to determine which project failed.  I want to do infracost runs with the config.yml so I can perform a breakdown and a diff.  Perhaps I don't understand the proper usage of infracost, is there a better way to accomplish this?

**Comment by hugorut** [comment]
You have two options:

1. modify the script that builds the infracost config.yml file not to include the invalid projects
2. switch to using the `--path` project auto-detection functionality, this will ignore any invalid projects and only include the projects that actually include valid Terraform root modules

**Comment by orbitz** [comment]
Does Infracost specify what an invalid project is so I can replicate that logic?  I guess I'm still unclear on why an empty `.tf` file is not valid.

**Comment by orbitz** [comment]
Would it be possible to put the path that failed in the error message?  Currently the error message and logging are on stdout and stderr which, depending on how infracost is run, one cannot depend on being juxtaposed in the console output.  Having the path in the error message would help in debugging what's happening.
