### ISSUE TITLE
Support Terraform Cloud's Remote Execution Mode

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#221]
Due to [this Terraform issue](https://github.com/hashicorp/terraform/issues/22779), it's not possible for `infracost --tfdir /path/to/code` to get the plan json, and users are faced with this:
```
$ infracost --tfdir /path/to/code
  ✔ Running terraform init
  ✖ Running terraform plan

  Terraform command failed with:
    Error: Saving a generated plan is currently not supported
    The "remote" backend does not support saving the generated execution plan
    locally at this time.

Error running terraform plan: exit status 1
```

It's somewhat annoying that the Terraform CLI doesn't support this but there is a way to get the [plan JSON](https://www.terraform.io/docs/cloud/api/plans.html#retrieve-the-json-execution-plan) from the Terraform Cloud API. Assuming that the Terraform code folder has `*.auto.tfvars` with any [required variables](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence), we can:

```
export TF_WORKSPACE=dev
export TERRAFORM_API_HOST=https://app.terraform.io
# The following must be a user or team token per Terraform docs, the json-output endpoint cannot be accessed with organization tokens
export TERRAFORM_API_TOKEN=xxx 


plan_path=$(terraform plan | grep -o '/runs/.*')/plan
echo $plan_path
# /runs/run-xxxxx/plan

plan_json_path=$(curl -H "Authorization: Bearer $TERRAFORM_API_TOKEN" $TERRAFORM_API_HOST/api/v2/runs/run-xxxxx/plan | jq '.data.links["json-output"]')
echo $plan
# /api/v2/plans/plan-xxxxx/json-output

curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/vnd.api+json" -L $TERRAFORM_API_HOST/api/v2/plans/plan-xxxxx/json-output > plan.json 


infracost --tfjson plan.json
  ✔ Calculating costs

  NAME                                 MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST

  aws_dynamodb_table.api_keys
  ├─ Write capacity unit (WCU)               3,650  WCU-hours  0.0007       0.0033        2.3725
   ...
```

Infracost can detect this error and tell users to set the 3 required env vars, then rerun `infracost --tfdir /path/to/code` so it can do the above dance to get the plan. Doing that would fix [this GH Actions issue](https://github.com/infracost/infracost-gh-action/issues/9) and mean users don't need to init or set AWS creds.

**Comment by alikhajeh1** [comment]
This has been fixed in [v0.7.9](https://github.com/infracost/infracost/releases/tag/v0.7.9).

@holzro and @tovbinm sorry it took us a while to get to this, we were semi-hoping that Terraform would fix the issue but didn't see any updates. Anyhow, please see https://www.infracost.io/docs/#terraform-cloud-users for the docs and feel free to add a comment here with any issues or ping me on (Slack)[https://www.infracost.io/community-chat].

**Comment by tovbinm** [comment]
@aliscott @alikhajeh1 thanks for adding this!!

Are there any changes required in https://github.com/infracost/infracost-gh-action as well?

**Comment by alikhajeh1** [comment]
@tovbinm nope, https://github.com/infracost/infracost-gh-action uses the [latest version](https://github.com/infracost/infracost-gh-action/blob/master/action.yml#L38) of the infracost docker image so it gets all the goodness automatically. You should only need to set the 2 envs mentioned in https://github.com/infracost/infracost-gh-action/issues/9#issuecomment-746749321 (sorry I should have mentioned those here too). 

We think using `latest` in CI works best for now as we're releasing very often, but it's something to be mindful of for the future as things mature.

**Comment by alikhajeh1** [comment]
FYI we renamed TERRAFORM_CLOUD_API_TOKEN to TERRAFORM_CLOUD_TOKEN. https://www.infracost.io/docs/#terraform-cloud-users has been updated.
