### ISSUE TITLE
New parallelism overloads Terraform Cloud private registry API (HTTP 429)

### ISSUE THREAD

**Issue by jgrumboe** [infracost/infracost#2227]
After upgrading to infracost 0.10.16 I sometimes get HTTP 429 "Too Many Requests" when running a breakdown for a monorepo where infracost would find 13 projects.
Rerunning infracost breakdown helps.

**Comment by hugorut** [comment]
Thanks @jgrumboe, according to the docs these apis have a rate limit of 30 requests per second: https://developer.hashicorp.com/terraform/cloud-docs/api-docs. It seems like we might need to introduce a distributed request counter to make sure we don't go over these limits across goroutines.

**Comment by hugorut** [comment]
A workaround for other users who encounter this issue would be to set `INFRACOST_PARALLELISM=1` before running infracost.

**Comment by alikhajeh1** [comment]
@jgrumboe did `INFRACOST_PARALLELISM=1` help? You can also try 2, 3, 4... if 1 was too slow.

**Comment by jgrumboe** [comment]
Yes, running it in the terminal `INFRACOST_PARALLELISM` helps.
But how to use it with vscode-infracost?

**Comment by alikhajeh1** [comment]
@jgrumboe does https://stackoverflow.com/a/60403290 work? I know that's not ideal, so I'll keep this issue open so we can figure-out how to handle the 429s and slow down/retry the calls.
