### ISSUE TITLE
Wrong pricing azure application gateway v2

### ISSUE THREAD

**Issue by Arend-melissant** [infracost/infracost#2277]
Two problems here:

1) pricing of CU is completely off, this is calculated per hour, but should be calculated per month
2) when you do not set capacity on the sku (optional if you use autoscaling), there is no price for the application gateway, it seems that the capacity is multiplying the usage cost (so capacity=2 means 1460 hours of application gateway costs) , but this should impact the CU cost of (1)

**Comment by aliscott** [comment]
Thanks for reporting @Arend-melissant 🙏  We will look at getting a fix out in the next release (sometime this week).
