### ISSUE TITLE
AWS RDS instances with `gp3` storage marked as having `io1`

### ISSUE THREAD

**Issue by elisiariocouto** [infracost/infracost#2284]
Hello everyone.

We moved a bunch of RDS instances to `gp3` and unfortunately the instances are being marked by Infracost as having `io1` storage. You can see here what the terraform state has:
```
$ terraform state show module.<redacted>.aws_db_instance.db_instance | grep -e storage -e instance -e iops
# module.<redacted>.aws_db_instance.db_instance:
resource "aws_db_instance" "db_instance" {
    allocated_storage                     = 30
    custom_iam_instance_profile           = ""
    instance_class                        = "db.t4g.small"
    iops                                  = 3000
    max_allocated_storage                 = 0
    storage_encrypted                     = false
    storage_throughput                    = 125
    storage_type                          = "gp3"
```

And this is the output from infracost:
<img width="945" alt="Screenshot 2023-02-08 at 16 11 41" src="https://user-images.githubusercontent.com/818914/217586128-bb7cdad9-8b7a-4cb7-b804-9283be33d4e3.png">

I think the issue is in here https://github.com/infracost/infracost/blob/master/internal/resources/aws/db_instance.go#L119, this part of the code says that if it has `iopsValue` greater than zero it must have an `io1` storage type, which is not the case when using `gp3`.

Related to #536

**Comment by aliscott** [comment]
@elisiariocouto this has now been released in [v0.10.21](https://github.com/infracost/infracost/releases/tag/v0.10.21).

cc'ing everyone who upvoted: @joaorua, @ElMiTu, @limaseabra, @pedro3692, @rasta-rocket, @bart-braidwell, and @osousa.
