### ISSUE TITLE
Can infracost help/work when engineer makes manual adjustments via aws console? If yes, please help us with document which is helpful for us.

### ISSUE THREAD

**Issue by Aarti-Rode** [infracost/infracost#2288]

**Comment by hugorut** [comment]
@Aarti-Rode I'm struggling to understand what are your requirements. Perhaps you can give me more insight into your use case, what are you looking Infracost to help you with?

Infracost generates cost estimates by parsing HCL or a Terraform Plan JSON. This means we can detect resource drift (manual changes made outside of terraform) only if they are detected in the Terraform Plan JSON. This is normally resources that you've provisioned in Terraform and then have changed in the console. For everything else (e.g. resources manually created in the console) you'll need to connect Infracost Cloud to your cloud provider to fetch "actual costs". This is a early access feature which is only available in our paid product. You can read [more about it here](https://www.infracost.io/docs/infracost_cloud/actual_costs/).

**Comment by alikhajeh1** [comment]
Closing this as we discussed this on Slack too.

**Comment by Aarti-Rode** [comment]
Hi @hugorut Thank you above details.

Could you please help me with some details?

As per the above documents we need to send you some details about CUR, S3 bucket, ORGNIZATION_IDetc, then you will enable this Actual Costs feature for us. 
Is it nothing but we need to upgrade Infracost cloud?
What are the subscription plan are available on monthly or yearly basis?
How much time will it take to enable this feature?

**Comment by hugorut** [comment]
this conversation has been moved to slack
