### ISSUE TITLE
Add support for Azure EventGrid

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#2303]
Azure pricing page: https://azure.microsoft.com/en-us/pricing/details/event-grid/#pricing

**Comment by hugorut** [comment]
Support for Azure Event Grid has been merged into the master branch and will be included in the next release. If you are using the [GitHub app](https://www.infracost.io/docs/integrations/github_app/) integration, Azure Event Grid support should already be available.

**Comment by aliscott** [comment]
@jaredbrogan, @davisowb this has now been released in [v0.10.21](https://github.com/infracost/infracost/releases/tag/v0.10.21).
