### ISSUE TITLE
Option --show-all-project is missing from CLI documentation

### ISSUE THREAD

**Issue by mloskot** [infracost/infracost#2313]
The `--show-all-projects` was added in https://github.com/infracost/infracost/pull/2087 but that PR does not contain any documentation.

The option is not described in https://www.infracost.io/docs/features/cli_commands

It would be helpful if it is described there.

By the way, it would be nice if https://www.infracost.io/doc offered a complete CLI commands reference. The only form of CLI reference available is `infracost --help`.

**Comment by alikhajeh1** [comment]
Thanks @mloskot - I'll update the docs.

**Comment by alikhajeh1** [comment]
Done in https://github.com/infracost/docs/pull/405
