### ISSUE TITLE
Add support for GCP IP Address

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#232]
Pricing details: https://cloud.google.com/vpc/network-pricing#ipaddress
Terraform resource: google_compute_address

It might help to study the infracost/internal/providers/terraform/aws/eip.go file before adding this.

**Comment by sinabakh** [comment]
The pricing depends on whether the IP is assigned to an instance or not but the assignment is done in vm's resource:
```
resource "google_compute_address" "static" {
  name = "ipv4-address"
}

resource "google_compute_instance" "instance_with_ip" {
  name         = "vm-instance"
  machine_type = "f1-micro"
  zone         = "us-central1-a"

  network_interface {
    network = "default"
    access_config {
      nat_ip = google_compute_address.static.address
    }
  }
}
```
As far as I know, there's no easy way to get this info in our current structure. Any thoughts?

**Comment by alikhajeh1** [comment]
@sinabakh you're right, we've discussed having a reverse-lookup but only the AWS/GCP EIPs need it so far, so we didn't think it was important to do yet. Please check the logic in `infracost/internal/providers/terraform/aws/eip.go` as I think we can do the similar thing here, i.e. go with the estimation on a best-effort basis, and note that I called the component name `IP address (if unused)` in that file to make it clear.
