### ISSUE TITLE
Add support for Azure Web Apps

### ISSUE THREAD

**Issue by Scott-Emberson** [infracost/infracost#2329]
Support for Azure Web Apps
Terraform Resource: `azurerm_windows_web_app` 
Terraform Documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app
Azure Pricing: https://azure.microsoft.com/en-gb/pricing/details/app-service/windows/

**Comment by pacorreia** [comment]
And azurerm_linux_web_app as well!

**Comment by hassankhosseini** [comment]
@alikhajeh1 @aliscott - let's add these to be groomed please 🚀

**Comment by hugorut** [comment]
hey @Scott-Emberson and @pacorreia , a fix for this is in master and will go out with the next release. I'll ping you here when it's available. If either of you are using the GH app, these resources should already be available.

**Comment by tim775** [comment]
This is live in v0.10.19
