### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool's node_count should have a higher precedence over min_count

### ISSUE THREAD

**Issue by vdmgolub** [infracost/infracost#2371]
Changing the resource from
```tf
resource "azurerm_kubernetes_cluster_node_pool" "node_pools" {
  name             = "npw1ph"
  node_count       = 1
  min_count        = 1
  max_count        = 3
  ...
}
```
to 
```tf
resource "azurerm_kubernetes_cluster_node_pool" "node_pools" {
  name             = "npw1ph"
  node_count       = 1
  min_count        = 0
  max_count        = 3
  ...
}
```

produces the following diff:
```
~ module.aks_windows_node_pool.azurerm_kubernetes_cluster_node_pool.node_pools[1]
  -£98.71 (£98.71 → £0.00)
    ~ Instance usage (pay as you go, Standard_E2as_v5)
      -£79.25 (£79.25 → £0.00)
    ~ os_disk
        ~ Storage (P10, LRS)
          -£19.47 (£19.47 → £0.00)
```

However, the `node_count`'s value `1` should be used.

Fix: update [this logic](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/kubernetes_cluster_node_pool.go#L32) to ignore anything less than `min_count`. However, `node_count` should take higher precedence over `min_count`.

This issue was discovered here: https://github.com/infracost/infracost/discussions/2368

**Comment by mloskot** [comment]
I can confirm the note in https://github.com/infracost/infracost/issues/2371#issuecomment-1479691945 
Windows-based node pools in my AKS cluster are configured with `node_count=1` and `min_count=0` and `max_count` between 5 and 10.

**Comment by mloskot** [comment]
Would there be any update on this one?

**Comment by tim775** [comment]
Hi @mloskot, it's on our current sprint so it _should_ go out in the next release.  We'll post here when that is certain.

**Comment by aliscott** [comment]
Fixed in #2494. We'll close this when the fix is released.

**Comment by aliscott** [comment]
@mloskot this has now been released in [v0.10.23](https://github.com/infracost/infracost/releases/tag/v0.10.23)!

**Comment by mloskot** [comment]
@aliscott  Awesome, thank you! I'll report back as soon as I have a chance to test it.

**Comment by mloskot** [comment]
I'm happy to confirm the #2494 fix as for the zero initial nodes input:

```
  node_count       = 1
  min_count        = 0
  max_count        = 3
```

the estimates are now more accurate:

```
+ module.aks_windows_node_pool.azurerm_kubernetes_cluster_node_pool.node_pools[2]
  +£147
    + Instance usage (Windows, pay as you go, Standard_E2as_v5)
      +£128
    + os_disk   
        + Storage (P10, LRS)
          +£19
```
