### ISSUE TITLE
Add support for GCP resources

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#24]

**Comment by rottenbytes** [comment]
As you mentionned on twitter here are the resources I'd like to see first : 
- google_bigquery_dataset
- google_compute_address
- google_compute_disk
- google_compute_forwarding_rule
- google_compute_global_address
- google_compute_global_forwarding_rule
- google_compute_health_check
- google_compute_instance
- google_compute_region_backend_service
- google_compute_router
- google_compute_router_nat
- google_compute_target_http_proxy
- google_compute_target_https_proxy
- google_compute_url_map
- google_compute_vpn_gateway
- google_compute_vpn_tunnel
- google_container_cluster
- google_logging_metric
- google_monitoring_alert_policy
- google_pubsub_topic
- google_redis_instance
- google_storage_bucket

Thanks for your work 👍

**Comment by alikhajeh1** [comment]
Terraform cloud's cost estimation feature supports:

- google_compute_instance
- google_compute_disk
- google_sql_database_instance

**Comment by alikhajeh1** [comment]
Initial support for Google Cloud was added in v0.7.3, released yesterday 🎉 GCP pricing had become quite complicated since we last worked on this stuff years ago so it took longer than expected. We've added support for `google_compute_instance` and `google_compute_disk` as mentioned in the [docs](https://www.infracost.io/docs/supported_resources#google-cloud-platform-gcp).

This GH issue has quite a lot of likes and a long list of resources so it's not super-easy to see what resource should be added next - feel free to add a comment here with your needs, or ideally, create new GH issues on a per-resource basis. I'll keep this issue open for another week or so.

**Comment by rottenbytes** [comment]
Works fine !

**Comment by alikhajeh1** [comment]
Heads-up: since this issue was closed in Nov, we've found our Google groove and are adding new GCP resources like there is no tomorrow :shipit: [Upgrade](https://www.infracost.io/docs/#1-install-infracost) to the latest version (v0.7.20) to see the [14 resources](https://www.infracost.io/docs/supported_resources/#google-cloud-platform-gcp) that are now supported. 

Also, plz 👍 the [open issues](https://github.com/infracost/infracost/issues?q=is%3Aissue+is%3Aopen+Google) or create new ones to help us better prioritize.
