### ISSUE TITLE
Can not get local modules

### ISSUE THREAD

**Issue by ashishbista** [infracost/infracost#2470]
I can't get it working for Terragrunt paths. I'm getting the below error:

```
        "warnings": [
          {
            "code": 4,
            "message": "Error loading Terraform modules: could not load modules for path .infracost/.terragrunt-cache/KHviaXDu9Xq4b8PBMl32dUFFlsw/weIDhs7nU8caTiToOgKDEpso7_I failed to inspect module path ../../../../modules/cloud_vpn diag: Failed to read module directory: Module directory ../../../../modules/cloud_vpn does not exist or cannot be read.",
            "data": null
          }
        ]
```

`../../../../modules/cloud_vpn` is accessible from `.infracost/.terragrunt-cache/KHviaXDu9Xq4b8PBMl32dUFFlsw/weIDhs7nU8caTiToOgKDEpso7_I `. 

But, it has kept the path in the terraform file the as it is.

```
cat main.tf

module "cloud_vpn" {
  source           = "../../../../../../../../modules/cloud_vpn"
```

So, `terraform init` fails here because `"../../../../../../../../modules/cloud_vpn"` is not accessible. Is it supposed to change ` source = "../../../../../../../../modules/cloud_vpn"` to  `source = "../../../../modules/cloud_vpn"`?

Let me know if you need more details.

**Comment by aliscott** [comment]
@ashishbista thanks for reporting. Can you please provide the following information?
1. The exact `infracost` command you are running.
2. An example of the Terragrunt code that is causing this issue.

If there's any relevant log lines as well that would be helpful. You can get these by running with `--log-level=debug`.

**Comment by aliscott** [comment]
@ashishbista do you have any more details as per above?

**Comment by aliscott** [comment]
Closing this issue. @ashishbista if you have more details as per above please re-open 🙏 .
