### ISSUE TITLE
EC2 instance cost missing with Elastic Beanstalk and Launch configurations

### ISSUE THREAD

**Issue by dmitriyklyuzov** [infracost/infracost#2497]
When specifying the instance type using an Elastic Beanstalk setting (looks like support for EB was added in #1411), Infracost CLI warns:
```
No products found for aws_launch_configuration Instance usage (Linux/UNIX, on-demand, ), using 0.00
```
Note that the third argument (instance type) is missing even though it is specified using a setting in the "aws:autoscaling:launchconfiguration" namespace using the "InstanceType" parameter.

### How to reproduce the issue:

```
resource "aws_elastic_beanstalk_environment" "this" {
  name        = "tf-test-name"
  application = "test-app"

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "InstanceType"
    value     = "t3a.xlarge"
  }
}
```

and run `infracost breakdown --path .` 

### Expected result:
Infracost includes the cost of the EC2 instance(s) in the total

### Actual result:
Infracost is unable to include the cost of the EC2 instance(s) in the total even though the instance type persists and shows up correctly in the AWS Console in the Elastic Beanstalk Environment, Auto Scaling Group, and Launch Configuration.

Please let me know if there's a different/proper way to do this. Thanks!

**Comment by aliscott** [comment]
Thanks for the details @dmitriyklyuzov 🙏 . I've added this to our next sprint so should get this fixed soon.

**Comment by aliscott** [comment]
@dmitriyklyuzov this is now released in [v0.10.24](https://github.com/infracost/infracost/releases/tag/v0.10.24).

**Comment by dmitriyklyuzov** [comment]
@aliscott great! I confirm this is working on my end. Thank you!

**Comment by aliscott** [comment]
Thanks for confirming @dmitriyklyuzov 🙏🙏
