### ISSUE TITLE
Add support for AWS Systems Manager's Parameter Store

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#251]
**Resource details:**
 - Resource name: AWS Systems Manager's Parameter Store (used to store/access config data, e.g. DB creds) 
 - Link to pricing information: https://aws.amazon.com/systems-manager/pricing/ ONLY the Parameter Store pricing
 - Terraform resources: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter

The parameter store is an interesting resource to add as it's often used in stacks for credentials management.

**Comment by robh007** [comment]
I'll take this one @alikhajeh1 if that's ok.

**Comment by alikhajeh1** [comment]
@syphernl just FYI that support for aws_ssm_parameter and aws_ssm_activation was just released in v0.7.15 (I noticed you +1'd the `aws_cloudfront_distribution` resource too, that was released in the last version but I forgot to move [the ticket](https://github.com/infracost/infracost/issues/230) to released).
