### ISSUE TITLE
Support AWS aws_kinesis_stream

### ISSUE THREAD

**Issue by bartelemi** [infracost/infracost#2510]
As per the title - it would be amazing if we could add support for this new resource.

## references.
https://aws.amazon.com/kinesis/data-streams/pricing/

**Comment by ktasper** [comment]
I am happy to attempt to work on this.

**Comment by alikhajeh1** [comment]
Thanks @ktasper! The contributing guide should help you get started, any questions ping here or the Slack #contributors channel :)
