### ISSUE TITLE
Error: assignment to entry in nil map (v0.10.23)

### ISSUE THREAD

**Issue by dong-chiu** [infracost/infracost#2524]
C:\Codebase\***api>infracost breakdown --path .
Evaluating Terraform directory at .
  ✔ Downloading Terraform modules
  ✔ Evaluating Terraform directory
  ✔ Retrieving cloud prices to calculate costs

Project: ***/***api/build
Module path: build

Errors:
  assignment to entry in nil map
goroutine 80 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/infracost/infracost/internal/hcl.(*Parser).ParseDirectory.func1()
        /home/runner/work/infracost/infracost/internal/hcl/parser.go:289 +0x74
panic({0x20152e0, 0x2b37ec0})
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateProvider(0xc000649330?, 0xc00050ac80, 0xc00032a0b7?)
        /home/runner/work/infracost/infracost/internal/hcl/evaluator.go:730 +0x1a6
github.com/infracost/infracost/internal/hcl.(*Evaluator).getValuesByBlockType(0xc00069a000, {0x255bd14, 0x8})
        /home/runner/work/infracost/infracost/internal/hcl/evaluator.go:683 +0xe11
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateStep(0xc00069a000, 0x1?)
        /home/runner/work/infracost/infracost/internal/hcl/evaluator.go:283 +0x17e
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluate(0xc00069a000, {0x0?, 0x0?, 0x0?})
        /home/runner/work/infracost/infracost/internal/hcl/evaluator.go:253 +0x7c
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc00069a000)
        /home/runner/work/infracost/infracost/internal/hcl/evaluator.go:213 +0x118
github.com/infracost/infracost/internal/hcl.(*Parser).ParseDirectory(0xc000d5c210)
        /home/runner/work/infracost/infracost/internal/hcl/parser.go:350 +0x5df
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).Modules.func1()
        /home/runner/work/infracost/infracost/internal/providers/terraform/hcl_provider.go:344 +0x188
created by github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).Modules
        /home/runner/work/infracost/infracost/internal/providers/terraform/hcl_provider.go:334 +0x1f5

 OVERALL TOTAL       $0.00
──────────────────────────────────
No cloud resources were detected

**Comment by aliscott** [comment]
Thanks for reporting @dong-chiu. This has been fixed in https://github.com/infracost/infracost/pull/2522 and released in [v0.10.24](https://github.com/infracost/infracost/releases/tag/v0.10.24).
