### ISSUE TITLE
Non-linux AWS EC2 AMIs, e.g. Windows and marketplace items

### ISSUE THREAD

**Issue by ztmr** [infracost/infracost#26]
Is there any way to support instances based on marketplace AMIs? These are typically the most expensive ones so it would be nice to see the "subscription" cost along with the EC2 compute itself.

Not sure how feasible is this with the current approach where you seem to be caching the AWS pricelist separately on your website.

**Comment by aliscott** [comment]
The AWS bulk price API has pricing support for some configurations. For example it gives the following prices for an m3.large instance in us-east-1:

Linux: $0.133/hr
Linux + SQL Web: $0.202/hr
Linux + SQL Std: $0.614/hr

Windows (bring your own license): $0.133/hr
Windows: $0.259/hr
Windows + SQL Web: $0.367/hr
Windows + SQL Standard: $0.704/hr

RHEL: $0.193/hr
SUSE: $0.233/hr

I've been looking at adding support for these options, which will require somehow mapping the AMI to the price in the cloud-pricing-api.

For other marketplace AMIs, I'm not sure yet how this could be done. From what I can tell AWS doesn't have an API for these prices, so maybe the only option is scraping.

@ztmr are there any particular AMIs you're interested in this supporting?

**Comment by ztmr** [comment]
The problem is that the AMIs can change in time -- it is per region, per product version, even if the AMI is used to build a custom AMI derived from the official one, etc.

I think these two things can be useful:
- find if we can detect whether the instance uses a marketplace product and indicate it in the cost table (as extra line that indicates as unknown "extra" cost)
- the user would review all of these unknown costs and specify the product price in a config file that will be loaded next time infracost is run

Not sure if the first one is possible though.

**Comment by alikhajeh1** [comment]
@ztmr we've released [v0.7.12](https://github.com/infracost/infracost/releases/tag/v0.7.12) (also available on homebrew) that enables users to specify usage estimates for things like S3 or Lambda, as well as the operating system for aws_instances (windows, suse, rhel). Users can now pass `--usage-file /path/to/infracost-usage.yml`, see [this example](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L51-L52), and [docs here](https://www.infracost.io/docs/usage_based_resources).

Going to close this issue, feel free to add feedback here or on the [community Slack channel](https://www.infracost.io/community-chat). New issues can be created if "Windows (bring your own license)", or the SQL-based AMIs are needed so we can add those too.

**Comment by alikhajeh1** [comment]
@ztmr if there was a way to find any additional costs that apply to AMIs by using the AWS creds (that Terraform has) to make an `aws ec2 describe-images` call, would you want that to happen automatically when you run Infracost?

**Comment by ztmr** [comment]
@alikhajeh1 that would be great!

**Comment by alikhajeh1** [comment]
@ztmr great, feel free to watch https://github.com/infracost/infracost/issues/778 for updates :)

**Comment by alikhajeh1** [comment]
@ztmr in the recently released [v0.9.9](https://www.infracost.io/docs/#1-install-infracost), we released a feature that attempts to detect the OS as one of `linux`, `windows`, `suse`, `rhel` based on the response of [EC2DescribeOS](https://github.com/infracost/infracost/pull/967/files#diff-f4c655b4695ecd87dfbe5622e121083f60c59c95c9a3c3d9117d87c64bb1dd67R10-R26). This works for the following Terraform resources: `aws_instance`, `aws_autoscaling_group` and `aws_eks_node_group`. Can you possibly try that and let us know if it works for your use-case as I'm not sure if marketplace AMIs are returned using the same codes.
