### ISSUE TITLE
Add support for Google's GKE

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#267]
- Resource name: Google GKE
 - Link to pricing information: https://cloud.google.com/kubernetes-engine#section-10
 - Terraform resources: google_container*

**Comment by aliscott** [comment]
Closed by https://github.com/infracost/infracost/pull/370.

**Comment by alikhajeh1** [comment]
@bappr and @Yinabled FYI this is now available in the newly released v0.7.16 version
