### ISSUE TITLE
Add support for AWS CloudHSM

### ISSUE THREAD

**Issue by macbutch** [infracost/infracost#2714]
Please consider adding support for AWS CloudHSMs in both the product and also into the usage file. These are relatively expensive resources and we want to make sure we flag their creation.

Terraform resources:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_cluster
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_hsm

Pricing: https://aws.amazon.com/cloudhsm/pricing/

Example pricing: $1.45/hr in Oregon and $1.59/hr in London. 

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by aliscott** [comment]
@macbutch this resource has now been added. It's available now if you're using Infracost Cloud's native applications. Otherwise it will be released in the next release of the Infracost CLI.

**Comment by macbutch** [comment]
Thank you, @aliscott!

**Comment by aliscott** [comment]
@macbutch thank you 🙏! Sorry for the delayed update on this but it was released in [v0.10.32](https://github.com/infracost/infracost/releases/tag/v0.10.32)

**Comment by macbutch** [comment]
Thanks @aliscott
