### ISSUE TITLE
Cannot refine an unknown value of an unknown type

### ISSUE THREAD

**Issue by hugorut** [infracost/infracost#2730]
With `0.10.30` release the `hashicorp/hcl` library was updated to `2.17.0` which introduces a known regression around the new concept of refinements. This bug was fixed by downgrading the version to `2.16.2`, and will go out with the `0.10.31` release. The `hcl` library also has updates that will resolve this issue with `2.18.0` version and `cty` version `1.14.1`. We should look to update to these stable versions in the near future.

**Comment by aliscott** [comment]
This is now released in [v0.10.31](https://github.com/infracost/infracost/releases/tag/v0.10.31).
