### ISSUE TITLE
Skip init if it has already run

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#274]
**Description**
Currently `terraform init` is run each time infracost is run when using `--tfdir`. This is done to ensure the correct providers are installed.

With terraform 13.x this was okay because the providers were cached, but in terraform 14.x the providers are no longer cached and are reinstalled every time (See https://github.com/hashicorp/terraform/issues/27099 and https://github.com/hashicorp/terraform/issues/27155).

This means that running infracost is slow because every time it is redownloading the providers. We should detect if init has already been run and skip it if that is the case. The trade-off is that we will show an error if the plugins need updated.

**Comment by sinabakh** [comment]
I would like to give it a try but I'm not a terraform's advanced user so it would be great if you could give me some ideas about how I can tackle this issue.

**Comment by aliscott** [comment]
@sinabakh I can think of 3 options:

1. Simple check if `.terraform` dir exists
   *  We had this before (https://github.com/infracost/infracost/commit/985075d3d534a5de65fbc5559b3f9fa79ef5496f#diff-72a6035a570221d6612b04b5[…]c4efc7935dc1a972bb3a9ee55d7a4)
   * It doesn't detect if init needs to be re-run due to updated providers/modules
  
 2.  The same as this (https://github.com/gruntwork-io/terragrunt/blob/bfc313da5695195fae47ca8282e3f2732360b1e4/cli/cli_app.go#L736)
     * Also don't think this works if providers/modules need to be updated
     * Seems like fairly complicated logic
     
 3. When running the plan and show stages, check if it errors on `Error: Initialization required`. If it does, then we run init and re-run the plan/show.
     * Sort of similar to how we detect if we need to run a remote plan here: https://github.com/infracost/infracost/blob/master/internal/providers/terraform/provider.go#L247-L252
     * This will work even if providers/modules need updated.
     * If we go for this we probably want to still output a spinner line to the user to say that it's running init at this stage.
     
I think I'm leaning towards number 3 because it seems the most robust and not too difficult to implement. What do you think?

**Comment by alikhajeh1** [comment]
@mjad-dazn just FYI that this is now available in the newly released 0.7.16 version
