### ISSUE TITLE
Make resource registry more dynamic

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#276]
The current resource registry was the best one we could come up with but it has a major short-coming. There is a central file for resources that we need to call a function to append it to the registry. Here is a simplified version of such case:

`terraform/google/registry.go`:
```go
package google

import "github.com/infracost/infracost/internal/schema"

var ResourceRegistry []*schema.RegistryItem = []*schema.RegistryItem{
	GetComputeAddressRegistryItem(),
}

...
```

`terraform/google/compute_address.go`:
```go
package google

import (
	"github.com/infracost/infracost/internal/schema"
)

func GetComputeAddressRegistryItem() *schema.RegistryItem {
	return &schema.RegistryItem{
		Name:                "google_compute_address",
		RFunc:               NewComputeAddress,
		ReferenceAttributes: []string{},
	}
}

...
```

Although it's relatively clean, it needs developers to touch a shared file, and there's always merge conflicts.

There's another alternative that I missed in our initial implementation of registry and it's the `init()` function in go-lang.
In a nut-shell, we can refactor the codes as:

`terraform/google/registry.go`:
```go
package google

import "github.com/infracost/infracost/internal/schema"

var ResourceRegistry []*schema.RegistryItem = []*schema.RegistryItem{}
...
```

```go
package google

import (
	"github.com/infracost/infracost/internal/schema"
)

func init() {
	ResourceRegistry = append(ResourceRegistry, GetComputeAddressRegistryItem())
}

func GetComputeAddressRegistryItem() *schema.RegistryItem {
	return &schema.RegistryItem{
		Name:                "google_compute_address",
		RFunc:               NewComputeAddress,
		ReferenceAttributes: []string{},
	}
}

...
```
This way, developers have to just touch their feature related files (we can do the same thing to free resources).
What do you think @aliscott and @alikhajeh1 ?
If you agree I can work on the refactorization.

**Comment by aliscott** [comment]
@sinabakh can we simplify it to something like this?

```go
func init() {
	registerResource(&schema.RegistryItem{
		Name:                "google_compute_address",
		RFunc:               NewComputeAddress,
		ReferenceAttributes: []string{},
	})
}
```

**Comment by sinabakh** [comment]
@aliscott For sure, it's more elegant.

**Comment by alikhajeh1** [comment]
The merge conflicts haven't been an big issue since we moved to list the resources alphabetically in them. Should we close this issue? Seems like we're making bigger changes to how we model resources anyway...

**Comment by sinabakh** [comment]
Yeah, I personally think it's also more cleaner from a software point of view. The init model discussed here causes unpredictable code executions.
