### ISSUE TITLE
Where did the helm chart for self hosted infracost go?

### ISSUE THREAD

**Issue by Shocktrooper** [infracost/infracost#2763]
As the title states I am looking for the helm charts for self hosted infracost.  I had a weekly job running to update the deployment and it spontaneously started to fail looking for a chart download

**Comment by ToxicWar** [comment]
I'm experiencing the same problem with my experiment with the self-hosted Infracost instance. 

It appears that the repositories related to the Self-Hosted Cloud Pricing API have been made "hidden".

Is there any policy change?
As it appears Self-Hosted option is now under Infracost Enterprise pricing: https://www.infracost.io/pricing/

**Comment by z0rc** [comment]
Personally I wouldn't tolerate such move from company. I'm scarping away infracost from my pipelines.

**Comment by hassankhosseini** [comment]
Hi folks. which companies are you deploying this for? We might already have commercial agreements in place, so we can go through that to get you access. The self-hosting has moved into our paid tiers. You can use our hosted pricing service for free up to 1,000 runs. Usage packs can also be purchased. Please email me on hello@infracost and I'll respond. Cheers

**Comment by Shocktrooper** [comment]
Yeah im also going to remove this from my infra as well.  We are not going to be evaluating for enterprise with SAAS since we have airgapped networks and do not want to send data to a third party like this. On top of their appearing to be no obvious communication to the community about this. Its more of a rug pull since the product is "open source" but you can't actually run it in self hosted now.  Mind as well be closed source at this point because OS developers can't even benefit from contributing now themselves.

**Comment by theodiem** [comment]
I like how the change was communicated ...  like .. one day repos are deleted, not even worth a mention on their own blog about the "small" change that is removing a feature from the free tier to the enterprise. Not even leaving behind the old repos with older version .. you know just in case. "Oh, now is it broken? now pay".
Very easy to not recommend/use anymore.

**Comment by OwlInSpace** [comment]
What are some good alternatives? Seems like "open source" is a PR term now

**Comment by Shocktrooper** [comment]
Could just fork this project and start with an alternative. It's the Apache 2.0 license. Could go the way of Open TF if anyone wanted.

**Comment by theodiem** [comment]
> Could just fork this project and start with an alternative. It's the Apache 2.0 license. Could go the way of Open TF if anyone wanted.

With the repos removed, unless someone re-uploads them to have as starting point.
Replicating their API server so the vscode extension can be used is just asking them to change terms of the extension suddently (which they seems good at).

**Comment by mongrelion** [comment]
@theodiem what are the names of the original repos that disappeared? there are websites that archive everything publicly available on Github. That might be a starting point.

**Comment by Invincibear** [comment]
@mongrelion looks like it was https://github.com/infracost/helm-charts
I also found this, might be what we're looking for? https://github.com/artemvang/helm-charts-infracost/tree/master

**Comment by 13567436138** [comment]
what is going on
