### ISSUE TITLE
Add support for Bitbucket pipelines [CI]

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#277]
Adding support for users who want to integrate Infracost into their CI pipeline, and are using Bitbucket's pipelines.
https://bitbucket.org/product/features/pipelines

**Comment by alikhajeh1** [comment]
@4mation-kyeates and @mhmdio just FYI that we've updated the integrations to support Bitbucket Pipelines: https://www.infracost.io/docs/integrations#bitbucket-pipelines 

Please ping here or https://www.infracost.io/community-chat if there are any issues and I'd be happy to help.
