### ISSUE TITLE
Add support for Azure DNS Private Resolver

### ISSUE THREAD

**Issue by ewencodes** [infracost/infracost#2778]
Hi,
I'm currently working on a school project and I notice that `azurerm_private_dns_resolver_inbound_endpoint`, `azurerm_private_dns_resolver_outbound_endpoint` and `azurerm_private_dns_resolver_dns_forwarding_ruleset` are not supported by infracost.

Princing details : https://azure.microsoft.com/en-us/pricing/details/dns/
Azure Calculator screenshot :
<img width="1274" alt="image" src="https://github.com/infracost/infracost/assets/46159873/2cacc63e-a961-4085-abcd-4623b8f5f970">

I'm planning to implement this on the codebase.

**Comment by ewencodes** [comment]
I don't know if it's a mistake but these resources are Azure resources @aliscott 😄

**Comment by aliscott** [comment]
Haha oops, thanks @ewencodes 😅
