### ISSUE TITLE
Sign up with Google is failing - "Access blocked: infracost.io has not completed the Google verification process"

### ISSUE THREAD

**Issue by kalpanachinnappan** [infracost/infracost#2788]
I am trying out Infracost and following [Step #2 here](https://www.infracost.io/docs/#2-get-api-key) - "Get API key". 
I attempted to sign up with my Google account, but it failed with the following:

> Access blocked: infracost.io has not completed the Google verification process

![Screenshot 2023-12-12 at 8 13 13 PM](https://github.com/infracost/infracost/assets/118010469/65ea077c-5539-4211-bbe9-71c7f436c470)

**Comment by alikhajeh1** [comment]
@kalpanachinnappan thanks for reporting this, we'll take a look soon!

**Comment by aliscott** [comment]
@kalpanachinnappan this should be resolved now. Can you please try again and reopen this if it still isn't working?
