### ISSUE TITLE
guest_accelerator.type 'nvidia-l4' is not supported

### ISSUE THREAD

**Issue by himekifee** [infracost/infracost#2797]
My projects used a l4 GPU in a g2-standard-4. The debug output gives the following.
```
{
  "currency": "USD",
  "enable_cloud_org": false,
  "file": "github.com/infracost/infracost/internal/resources/google/compute_cost_component_helpers.go:416",
  "func": "github.com/infracost/infracost/internal/resources/google.guestAcceleratorCostComponent",
  "level": "debug",
  "msg": "skipping cost component because guest_accelerator.type 'nvidia-l4' is not supported",
  "sync_usage": false,
  "time": "2023-12-19T19:52:35Z"
}
```

**Comment by alikhajeh1** [comment]
Thanks for reporting this! I had a quick look and my guess is that https://github.com/infracost/infracost/blob/master/internal/resources/google/compute_cost_component_helpers.go#L396-L414 needs to be updated

**Comment by himekifee** [comment]
Hi, any update on this? I imagine it won't be a big change but rather just an easy config modification.

**Comment by vdmgolub** [comment]
@himekifee Hi! I've created a PR with the fix. Could you please confirm that the estimate looks correct for `g2-standard-4` with 1 GPU [here](https://github.com/infracost/infracost/pull/2883/files#diff-6cfc5866c7fdf53694fc6805a47be241781307911d8fcbc6c5e03b6ca313bfe3R40-R43). I've never used that kind of instances, and Google calculator doesn't help me much. Thanks!

**Comment by vdmgolub** [comment]
@himekifee The fix is merged to the master. We'll let you know when the new CLI release that includes it is live. Thanks again for reporting the issue! :)
