### ISSUE TITLE
Add support for terraform cloud with remote execution mode

### ISSUE THREAD

**Issue by oasys** [infracost/infracost#281]
infracost does not appear to work with terraform cloud workspaces in _remote execution mode_.   If I test with a workspace in _local_ mode, it works fine, but that removes much of the value of TFC for us.

I suspect that is more of a limitation of TFC at this time, but would be happy to use this tool if there were a way to make it work.

```bash
$ export TERRAFORM_CLOUD_API_TOKEN=<removed>
$ infracost  --log-level debug
time="2020-12-18T10:18:11-05:00" level=info msg="starting: Running terraform init"
time="2020-12-18T10:18:11-05:00" level=info msg="Running command: /usr/local/bin/terraform init -input=false -no-color"
time="2020-12-18T10:18:11-05:00" level=debug binary=terraform msg="Initializing modules..."
time="2020-12-18T10:18:11-05:00" level=debug binary=terraform
time="2020-12-18T10:18:11-05:00" level=debug binary=terraform msg="Initializing the backend..."
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="Initializing provider plugins..."
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="- terraform.io/builtin/terraform is built in to Terraform"
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="- Reusing previous version of hashicorp/tls from the dependency lock file"
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="- Reusing previous version of hashicorp/aws from the dependency lock file"
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="- Using hashicorp/tls v3.0.0 from the shared cache directory"
time="2020-12-18T10:18:13-05:00" level=debug binary=terraform msg="- Using hashicorp/aws v3.11.0 from the shared cache directory"
time="2020-12-18T10:18:14-05:00" level=debug binary=terraform
time="2020-12-18T10:18:14-05:00" level=debug binary=terraform msg="Terraform has been successfully initialized!"
time="2020-12-18T10:18:14-05:00" level=info msg="starting: Running terraform plan"
time="2020-12-18T10:18:14-05:00" level=info msg="Running command: /usr/local/bin/terraform plan -input=false -lock=false -no-color -out=/var/folders/m4/qbt28cpx3fqfdnb6_nd1bdph0000gn/T/tfplan244846605"
time="2020-12-18T10:18:15-05:00" level=error binary=terraform
time="2020-12-18T10:18:15-05:00" level=error binary=terraform msg="Error: Saving a generated plan is currently not supported"
time="2020-12-18T10:18:15-05:00" level=error binary=terraform
time="2020-12-18T10:18:15-05:00" level=error binary=terraform msg="The \"remote\" backend does not support saving the generated execution plan"
time="2020-12-18T10:18:15-05:00" level=error binary=terraform msg="locally at this time."
time="2020-12-18T10:18:15-05:00" level=error binary=terraform
time="2020-12-18T10:18:15-05:00" level=info msg="Continuing with Terraform Remote Execution Mode"

Please set your TERRAFORM_CLOUD_API_TOKEN environment variable.
It seems like Terraform Cloud's Remote Execution Mode is being used.
Create a Team or User API Token in the Terraform Cloud dashboard and set this environment variable.

Error running terraform plan: No Terraform Cloud API Token is set
$ infracost  --version
Infracost v0.7.10
Terraform v0.14.2
```

**Comment by hassankhosseini** [comment]
Hey @oasys ! Ah, sorry - and I just emailed you saying its fixed. Apologies. @aliscott / @alikhajeh1 can you take a look please. Cheers!

**Comment by alikhajeh1** [comment]
@oasys please try `export TERRAFORM_CLOUD_TOKEN=<removed>`
We renamed the env var between 0.7.9 and 0.7.10 and updated [the docs](https://www.infracost.io/docs/#terraform-cloud-users) but forgot to update the error message in the code, we pushed a fix to master just now. 

Sorry about that. Plz lmk if that helps.

**Comment by oasys** [comment]
Thanks, that was it!

I've  submitted #[282] to fix this.

**Comment by alikhajeh1** [comment]
@oasys thanks for the PR! Were you running this on your local machine or on CI? On local machines `TERRAFORM_CLOUD_TOKEN` should not have been needed as infracost tries to use your Terraform CLI config file.

**Comment by oasys** [comment]
I was running infracost on my local machine against a terraform repo that is configured to use a remote workspace.   I believe this use case needs an API token, as the plan output isn't available/downloadable using the terraform cli currently.   As I said earlier, if I run against a remote workspace using "local" execution mode, it works fine without the token.

**Comment by alikhajeh1** [comment]
@oasys understood, we changed infracost in v0.7.10 to make the API call to terraform cloud to fetch the plan (as you mentioned the terraform CLI doesn't support that so we had to work around it, it wasn't fun). Plz lmk if it worked ok without that env?

**Comment by oasys** [comment]
In this use case, the `TERRAFORM_CLOUD_TOKEN` env was required.  Otherwise, I received the original error above.  Thanks for your work.  I look forward to support for more resource types!

**Comment by alikhajeh1** [comment]
@oasys great, just to help us debug future issues, can you please let me know if your laptop has either of these files (I don't want/need to see what's inside, just that they exist or not)?
`~/.terraform.rc` or `~/.terraform.d/credentials.tfrc.json` ?

**Comment by oasys** [comment]
I have neither of those, but I do have a `~/.terraformrc`.  (From looking at the [docs](https://www.terraform.io/docs/commands/cli-config.html), `terraform.rc` is the name for the terraform config file on Windows only.)

**Comment by alikhajeh1** [comment]
@aliscott seems like we should check `~/.terraformrc` too?
