### ISSUE TITLE
Dockerfile installs infracost/compost npm dependency which contains vulnerability

### ISSUE THREAD

**Issue by nbrys** [infracost/infracost#2863]
The dockerfile for infracost installs the infracost/compost npm dependency:

https://github.com/infracost/infracost/blob/master/Dockerfile.ci#L32

The latest version of this npm contains a vulnerability:

HIGH Vulnerability found in non-os package type (npm) - /usr/local/lib/node_modules/@infracost/compost/node_modules/octokit/package.json (fixed in: 3.1.2)(GHSA-pwfr-8pq7-x9qv - https://github.com/advisories/GHSA-pwfr-8pq7-x9qv)

Since this NPM is depricated, is it still needed?

**Comment by alikhajeh1** [comment]
Thanks @nbrys - it's not needed and you can remove it from your dockerfile if you like - we'll be removing it from the docker image in the v0.11 images.
