### ISSUE TITLE
Show unknown price for unsupported resources

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#29]
It seems the unsupported resources are not shown in the report.
I think it's more suitable if the report shows such resources with some "Unknown price" flag. This way users can better track their resources in the report.
Here is a rough idea of this feature:
```
   NAME                             QUANTITY  UNIT        PRICE PER UNIT  HOURLY COST      MONTHLY COST

   unknown_resource                 ?           ?               ?           ?                   ?

    

   OVERALL TOTAL                       0.0000        0.0000
```

**Comment by sashman** [comment]
@aliscott @alikhajeh1 The label added for "coming soon" can be re-used here https://github.com/aliscott/infracost/blob/1d456c43999a04c06b579d89b38c8bdd96689322/pkg/resource/resource.go#L50

**Comment by alikhajeh1** [comment]
Closing this as it's covered by the discussions in https://github.com/infracost/infracost/issues/84 so we can track it there.
