### ISSUE TITLE
Improve the experience for Windows users

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#293]
There are a few issues with windows users:
1. Test/update the windows installation steps and docs. We might need to update teh `.github/workflows/create-release.yml` file too.
2. The CLI color output is messed-up, they have to use `--no-color`.
3. The spinner chars are messed-up.
4. During `infracost register` user typing is messed-up. The red-cross and green-tick were not working ok on windows.

**Comment by alikhajeh1** [comment]
Closing this as we've addressed some of these issues in recent versions, people can open new issues for specific ones that we should look at

**Comment by PatMyron** [comment]
worth building / unit testing on Mac / Windows in addition to Linux?
https://github.com/infracost/infracost/blob/70456d08b21a43fce7716e366c7c1b893b8cd3d6/.github/workflows/go.yml#L11-L13

**Comment by alikhajeh1** [comment]
Good point! Maybe we should start with ensuring the CLI runs ok on those with something like https://github.com/infracost/infracost/blob/master/.github/workflows/go.yml#L33-L39 ?

**Comment by PatMyron** [comment]
@alikhajeh1 tried seeing if either OS would already pass with no changes to add to the build, but both Windows and Mac look like they'd need some changes to get building in Github Actions

**Comment by alikhajeh1** [comment]
huh, that's odd as we have a makefile that builds the .exe. Any clues in the logs?
