### ISSUE TITLE
Add support for AWS gp3 volume types

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#296]
AWS released the gp3 volume types for [EBS](https://aws.amazon.com/ebs/pricing/), I haven't checked other products yet. Terraform is adding it, e.g. https://github.com/hashicorp/terraform-provider-aws/issues/16514

We need to follow the Terraform issues/PRs for this and see which resources support gp3 so we can update infracost.

**Comment by dawidmalina** [comment]
Would be good to add this as AWS Compute Optimizer started to propose gp3 as a recommended option.

**Comment by alikhajeh1** [comment]
Thanks for the heads-up @dawidmalina! [This comment](https://github.com/hashicorp/terraform-provider-aws/issues/16514#issuecomment-762893090) mentions Terraform's AWS provider is going to support gp3 this week.
This issue is on our [project board](https://github.com/infracost/infracost/projects/2) so we'll get to it as soon as we have bandwidth. Stay tuned :)

**Comment by sinabakh** [comment]
I'll give it a shot.

**Comment by alikhajeh1** [comment]
@sinabakh https://aws.amazon.com/ebs/pricing/ mentions GP3 volume types have Storage, IOPS and Throughput. I don't see the last one in https://github.com/infracost/infracost/pull/452 so just wondering if that also needs to be added? or am I missing something?

**Comment by sinabakh** [comment]
It seems I missed them. I Will work on it in the coming week If no one does it sooner.

**Comment by alikhajeh1** [comment]
Closing this issue as https://github.com/infracost/infracost/issues/536 has details of what's left.
