### ISSUE TITLE
Running infracost in screen outputs odd chars

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#304]
**Description**
Run `screen` then `infracost --tfdir examples/terraform` and notice the following:
<img width="770" alt="screenshot" src="https://user-images.githubusercontent.com/638577/103416179-69071880-4b7d-11eb-88ad-3d353fa86cae.png">

```
  ✔ Calculating cost estimate
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
  NAME                                         MONTHLY QTY  UNIT         PRICE   HOURLY COST  MONTHLY COST
WWWWWWWWWWWWWWWWWWWWWWWWWWW
  aws_instance.web_app
  ├─ Linux/UNIX usage (on-demand, m5.4xlarge)          730  hours        0.7680       0.7680      560.6400
```

**Which version did it happen in (run `infracost --version`):**
Infracost v0.7.11
Terraform v0.14.3
Linux and macOS

**Comment by alikhajeh1** [comment]
This is also happening in the Intelli J IDE

**Comment by netguino** [comment]
I have experienced this in urxvt with version `Infracost v0.7.17`.


The W's seem to come from the bottom, then clean up the screen upwards.

![image](https://user-images.githubusercontent.com/2894061/107431066-cd9d8780-6ada-11eb-87a6-f4f5532fe124.png)

**Comment by netguino** [comment]
The W's seem to depend on how far down the terminal the prompt starts at, here is another example with --no-color:

![image](https://user-images.githubusercontent.com/2894061/107431628-9085c500-6adb-11eb-8eae-ae3177b8aa91.png)

**Comment by vladkosarev** [comment]
I see this in urxvt but xterm works fine.

**Comment by sinabakh** [comment]
I'm taking a look at it to see if I can find the culprit.

**Comment by alikhajeh1** [comment]
Thanks @sinabakh! https://github.com/briandowns/spinner/issues/110 might be interested to checkout (we use that package as mentioned in #737 too)

**Comment by sinabakh** [comment]
The master branch seems to no longer have the problem. Bumping the `spinner` from 1.12 to 1.13 in [this](https://github.com/infracost/infracost/commit/12a4603fa276e4b210e92d90d6b2793a45ebe37c) commit solved the issue.
