### ISSUE TITLE
Changes in tfvars aren't properly detected in github app

### ISSUE THREAD

**Issue by endakelly** [infracost/infracost#3089]
We have a structure in most of our github repos like this:
```
./components/<component-name>/<terraform tf files e.g. main.tf>
./environments/stg/stg.tfvars
```

The tfvars files may contain values that create more infrastructure or scale existing infrastructure e.g.
```
vm_scale_sets = {
  scale_set_1 = {
    instances  = 2
  }
  scale_set_2 = {
    instances  = 2
  }
}
```

If I change the tfvars to scale up the instances or add a new scale set like the below, the github app doesn't detect any changes and doesn't post a comment. The CLI does detect the changes.

```
vm_scale_sets = {
  scale_set_1 = {
    instances  = 2
  }
  scale_set_2 = {
    instances  = 4
  }
  scale_set_3 = {
    instances  = 2
  }
}
```

We have another repo that has the tfvars and the tf files at the same level and changes are picked up fine.

**Comment by aliscott** [comment]
@endakelly my initial thought is the [Infracost config](https://www.infracost.io/docs/features/config_file/) for your repo isn't properly detecting the structure. If you email support@infracost.io with your Infracost org ID and repo name I can have a quick look and see what the issue is.

**Comment by endakelly** [comment]
I've reached out to support and will update here if I get this sorted so someone looking at this can see the fix.
