### ISSUE TITLE
aws ebs unit price is not correct

### ISSUE THREAD

**Issue by KaimingWan** [infracost/infracost#3090]
Part result of `infracost brewakdown`

 aws_instance.server[0]                                                                      
 ├─ Instance usage (Linux/UNIX, on-demand, r6i.large)           730  hours          $89.03   
 ├─ EC2 detailed monitoring                                       7  metrics         $1.93   
 ├─ root_block_device                                                                        
 │  └─ Storage (general purpose SSD, gp3)                        64  GB              $4.69   
 └─ ebs_block_device[0]                                                                      
    └─ Storage (general purpose SSD, gp3)                     2,048  GB            $150.24   

Actually 2048GB EBS gp3 monthly price is more than 800 USD

**Comment by alikhajeh1** [comment]
@KaimingWan thanks for creating the issue. In `us-east-1`, EBS gp3 is $0.08/GB-month x 2048 = $163.84. Which region are you using? Can you please share the Terraform HCL code snippet that generated the above cost estimate so we can reproduce it and investigate?

**Comment by KaimingWan** [comment]
@alikhajeh1 Thank you for your response. The $800 USD figure is inaccurate. I recalculated the price for the cn-northwest-1 region. The unit price is `¥ 0.5312 per GB-month of provisioned storage`, and based on the exchange rate, this price should be reasonable.

**Comment by alikhajeh1** [comment]
@KaimingWan thanks for confirming, so I'll close this issue. Just FYI I tested it as follows using your numbers (0.5312 x 2048 = 1.1K CNY), which matches given that we use exchange rates to convert USD to CNY.

```
# main.tf
provider "aws" {
  region                      = "cn-northwest-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "my_web_app" {
  ami           = "ami-005e54dee72cc1d00"
  instance_type = "m3.xlarge"
  root_block_device {
    volume_size = 2048
    volume_type="gp3"
  }
}
```

```
$ INFRACOST_CURRENCY=CNY infracost breakdown --path .

>  └─ root_block_device
    └─ Storage (general purpose SSD, gp3)       2,048  GB                           1,087.90 CNY
```
