### ISSUE TITLE
infracost comment gitlab ...: sh: command:: not found

### ISSUE THREAD

**Issue by Gilk260** [infracost/infracost#3106]
All goes as expected when using:
```sh
infracost comment gitlab --gitlab-server-url https://git.my_comp.org \
                         --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \
                         --merge-request $PULL_NUM \
                         --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \
                         --gitlab-token $GITLAB_TOKEN \
                         --behavior new
```
The comment is shown in the comment section, but the pipeline returns an error and when I look in the logs I have this:
```sh
2024-06-10T15:46:08Z INFO Creating new comment
2024-06-10T15:46:08Z INFO Created new comment: https://git.my_comp.org/hello-world/-/merge_requests/1#note_174376
Comment posted to GitLab

Update: A new version of Infracost is available: v0.10.36 → v0.10.37
  $ curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
sh: command:: not found
```

I can see I don't have the last version and I doubt this is the error, but if you think so I could ask to bump the new version on the docker image.

**Comment by vdmgolub** [comment]
Hi @Gilk260! Thanks for opening the issue. It looks odd. The `infracost comment` command ran successfully (hence the "Comment posted to GitLab" message). By default, CLI doesn't attempt to download a new version.

To fix the issue you could specify `INFRACOST_SKIP_UPDATE_CHECK=true` to skip the check. Can you try this and see if the error goes away?

**Comment by Gilk260** [comment]
Ok, sorry, finally the error comes from the `post_workflow_hooks` of `atlantis` very sorry to have open this issue

**Comment by vdmgolub** [comment]
No problem. Glad you figure it out :) 👍
