### ISSUE TITLE
Add support for Google Cloud Functions

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#311]
Resource name: Google Cloud Functions
Pricing page: https://cloud.google.com/functions#section-15

**Comment by ekifel** [comment]
Hello! Can I do this if nobody minds?

**Comment by alikhajeh1** [comment]
@ruanmartinelli we just released this in v0.7.20 🎉 ([install docs](https://www.infracost.io/docs/#installation)), it would be great to hear your thoughts about how infracost handles [usage-based resource](https://www.infracost.io/docs/usage_based_resources) such as Cloud Functions, e.g. using [this](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L187-L190).
