### ISSUE TITLE
Add the ability to customize API endpoints for remote backends

### ISSUE THREAD

**Issue by jeanbaptistebeck** [infracost/infracost#312]
Terraform CLI doesn't have support for retrieving locally a plan ran remotely, so Infracost has to call the remote backend API. Right now Infracost supports Terraform Cloud endpoints, but there is a need to make the API endpoint configurable to offer support for other remote backends, which may have slightly different endpoints.

Example: The Terraform Cloud API endpoint to retrieve plans ran remotely is `/api/v2/plans/:id`, when in the Scalr API it is `/api/iacp/v3/plans/:id`

**Comment by alikhajeh1** [comment]
@jeanbaptistebeck plz add a comment here once the Scalr API supports fetching json plans and I'll re-prioritize this.

**Comment by alikhajeh1** [comment]
Going to close this as we're going to help Scalr integrate so we can tackle this as part of that work if required.
