### ISSUE TITLE
`--tfflags` does not work with multiple `-var-file` options

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#313]
Thanks to bruceedge on Reddit for reporting this.

> The only gotcha was that the "--tfflags" arg doesn't understand repeated uses of "-var-file...", so one has to append all var-files into one big one and pass that in.

**Comment by aliscott** [comment]
I've been unable to reproduce this with infracost v0.7.11 and terraform v0.14.2 using the command:
```
infracost  --tfflags='-var-file=x.tfvars -var-file=y.tfvars'
```
Variables from both files are used as expected.

**Comment by alikhajeh1** [comment]
Should this be closed? it can be re-opened when we have more details or reproduction steps.
