### ISSUE TITLE
Terragrunt is re-running initialization for plan and show steps

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#317]
When using `TERRAFORM_BINARY=terragrunt` the terraform initialization is run 3 times: during the `init`, `plan` and `show` stages.

This means infracost takes a long time to complete. This has more of an effect now that terraform 14.x  will download the required providers each time (#274).

**Comment by notnmeyer** [comment]
what terragrunt version? based on when you submitted this, you might be describing a bug fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.27.0

> Fix a bug with Terragrunt always re-running init.

**Comment by aliscott** [comment]
Thanks @notnmeyer you are spot on 😄! Have tested with terragrunt v0.27.0 and this is resolved.

**Comment by alikhajeh1** [comment]
I sent a [PR](https://github.com/infracost/infracost/pull/353/files) to update the Terragrunt version we ship in the infracost docker image. @notnmeyer if you use that docker image (it's mostly used for CI integrations), do you think there is a need for multiple terragrunt versions in the dockerfile? (we do [this](https://github.com/infracost/infracost/blob/master/Dockerfile#L17) for terraform versions, which is similar to what Atlantis does in their image).

**Comment by notnmeyer** [comment]
i dont use the image, but i'm familiar with how Terragrunt and Atlantis play together. what youre doing looks like what i'd expect. for the most part, the specific TG version doesnt matter much to me.

**Comment by alikhajeh1** [comment]
@notnmeyer thanks for the feedback! I'll keep bumping up the infracost image to use latest version of TG until someone screams at me then :)
