### ISSUE TITLE
AWS VPC Endpoint pricing tiers are wrong

### ISSUE THREAD

**Issue by jamescnowell** [infracost/infracost#3228]
The current configuration has tiers set at 1000GB and 4000GB:
https://github.com/infracost/infracost/blob/38e888cfc56a42fcc2603ea4eee65350482b8202/internal/resources/aws/vpc_endpoint.go#L70

The correct configuration should be 1000000GB (1PB) and 5000000GB (5PB) as documented here: https://aws.amazon.com/privatelink/pricing/

**Comment by jamescnowell** [comment]
I am working on a fix for this now.

**Comment by aliscott** [comment]
@jamescnowell thanks 🙏  this has been released in [v0.10.40](https://github.com/infracost/infracost/releases/tag/v0.10.40)
