### ISSUE TITLE
Cost for AWS PrivateLink VPC Endpoint not per AZ

### ISSUE THREAD

**Issue by icereed** [infracost/infracost#327]
Thank you first of all for this awesome tool!

We are testing it and we noticed one potential bug:
When counting the PrivateLink VPC Endpoint it does not include the amount of AZs this endpoint would be instantiated.
So it shows me it will cost 730 hours for my endpoint with the pricing of https://aws.amazon.com/privatelink/pricing/.
However, it is instantiated in two AZs and hence is costing me 2*730h of usage.

Any idea how I can reflect this in infracost?

It was first originally introduced with #264.

Many thanks in advance!

**Comment by alikhajeh1** [comment]
@icereed thank you for reporting the issue! I'm struggling to find a way to detect the number of AZs for the vpc_endpoint from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint, any ideas? Would we be able to tell if we follow the `service_name` link, fetch that resource's AZ, then count the total number of unique AZs that refer to the vpc_endpoint?

@robh007 cc'in you in case you have any ideas too.

**Comment by robh007** [comment]
Yea it needs to count the subnets that the resource is deployed into. It's not AZ specific, albeit you'll more than likely deploy different subnets into separate AZs. I can take a look later.

**Comment by alikhajeh1** [comment]
Thanks @robh007! I've assigned it to you in case you have time to dig deeper, please let us know if we need to make changes to enable the lookups.

**Comment by alikhajeh1** [comment]
This will ship in v0.7.13, this should be released on Sunday.

**Comment by alikhajeh1** [comment]
@icereed I think I saw a comment on the PR mentioning you'd prefer a patch release so you can test it? 
Here you are https://github.com/infracost/infracost/releases/tag/v0.7.13 :)
BTW, if your project has a lot of resources, it would be good to hear your feedback on how long it took for infracost to run (my email is ali@infracost.io if you prefer that).

**Comment by icereed** [comment]
I will immediately test it. We are still in the evaluation phase of this tooling. In the end we plan to scan resources of over 50 AWS accounts. But this will take some months to integrate for us. For this current fix I may be able to deliver feedback in a few hours.

**Comment by alikhajeh1** [comment]
@icereed thank you! That's awesome - happy to help with any issues.

**Comment by icereed** [comment]
I can confirm it works now as expected 🎉

**Comment by alikhajeh1** [comment]
@icereed great! Thanks for the quick turnaround.

**Comment by alikhajeh1** [comment]
> In the end we plan to scan resources of over 50 AWS accounts. 

@icereed just FYI that in v0.7.15 (that we just released), users with big projects should see infracost run much faster as we've parallelized the Cloud Pricing API calls. Would be good to know if that makes a difference for you.
