### ISSUE TITLE
trouble with windows installation

### ISSUE THREAD

**Issue by copmir** [infracost/infracost#339]
Hi, 
I downloaded the infracost-windows-amd64.tar.gz file but when i unzip it (with tar -xvzf ), i find a  simply infracost-windows-amd64 file not an .exe file.

Can you please help me ( maybe i was wrong something)?
Many thanks

**Comment by alikhajeh1** [comment]
@copmir sorry about that, I just updated our docs with the following instructions, can you please let me know if this works ok for you?

Download and unzip the [latest release](https://github.com/infracost/infracost/releases/latest/download/infracost-windows-amd64.tar.gz). Rename the file `infracost-windows-amd64` to `infracost.exe`, then run it from the Command Prompt or Powershell using `.\infracost.exe --no-color` alongside other required flags/commands (color output has a bug we need to fix on Windows). You should also move the exe file to a folder that is in your `PATH` [environment variable](https://stackoverflow.com/questions/1618280/where-can-i-set-path-to-make-exe-on-windows), e.g. `C:\Windows`.

**Comment by copmir** [comment]
Yes, it works now! 

thanks a lot
