### ISSUE TITLE
[Feature Request] Support for S3 storage

### ISSUE THREAD

**Issue by javatarz** [infracost/infracost#34]
Storage prices are dependent on the region (which is available in terraform), the amount of data being stored (which isn't available in terraform) and the storage tier (which is available in terraform)

Can we add a `.infracost.config` or something to the repository to mention the rough volume of data in different S3 paths (which should help project costs based on different storage tiers) or is there another way you recommend?

I'm asking because I'd like to take a shot at implementing this. It's my first time in golang so any guidelines I should read up before contributing will be quite helpful.

**Comment by aliscott** [comment]
@javatarz thank you. I've been thinking about the best way add usage-based pricing. I've detailed one option in https://github.com/aliscott/infracost/issues/35 that I'm wanting to get feedback on. Please let me know what you think, and if you have any further ideas.

Initially what we can do is add the prices, but not usage costs for any resource we detect in the Terraform (example in https://github.com/aliscott/infracost/issues/25) so at least users are aware of what resources might have costs. Would this be useful initially?

We've also setup a [Discord chat](https://discord.com/invite/Cu9ftEg) to discuss this sort of thing if you're interested.

**Comment by javatarz** [comment]
Sounds good. I've just started working on this. It's my first contribution. I'll jump on to discord in case I have any questions 😄

**Comment by alikhajeh1** [comment]
@javatarz v0.7.0 of infracost (released just now) has S3 costs, feel free to take it for a spin and let us know what you think: https://www.infracost.io/docs/#installation
