### ISSUE TITLE
Gateway type VPC Endpoint is not supported

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#342]
It can be a bit misleading as basically aws_vpc_endpoint resource is supported. Would be good to either hide that from list of unsupported resources or add no cost details.

**Comment by alikhajeh1** [comment]
@dawidmalina good catch, we had identified the gateway type as a free resource but were returning the wrong value, I've fixed it in https://github.com/infracost/infracost/pull/343/files#diff-5c5fa8455d4a51483836d5fcaa87ff7ae4c6396d6e999d2047085055f0e61478R38 and it'll ship in the next release.

**Comment by dawidmalina** [comment]
Great job - thanks :)
