### ISSUE TITLE
Add support AWS Backup

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#344]
Terraform resources:
- aws_backup_plan
- aws_backup_selection
- aws_backup_vault
- aws_backup_vault_notifications
- aws_backup_vault_policy
- aws_backup_region_settings

AWS pricing page: https://aws.amazon.com/backup/pricing/

Service is free of charge but pricing is based on the amount of storage space your backup data consumes.

**Comment by alikhajeh1** [comment]
@dawidmalina have you tried [infracost-usage.yml](https://www.infracost.io/docs/usage_based_resources) as a way to provide usage estimates? I wonder if that would help with aws_backup* resources. We released it last week and are looking for feedback on that approach (we have ideas to auto-generate that file from sources like cloudwatch in the future but for now, the simplest is if the user adds rough usage estimates)

**Comment by dawidmalina** [comment]
ok I will try to test it.

**Comment by tim775** [comment]
It looks like we should add usage params for the different types of backup and restore to `aws_backup_vault`.  Except for EFS item-level restore the unit for each should be `GB`:

- `monthly_efs_warm_backup_gb` `EFS backup (warm)`
- `monthly_efs_cold_backup_gb` `EFS backup (cold)`
- `monthly_ebs_snapshot_gb` `EBS snapshot`
- `monthly_rds_snapshot_gb` `RDS snapshot`
- `monthly_aurora_snapshot_gb` `Aurora snapshot`
- `monthly_dynamodb_backup_gb` `DynamoDB backup`
- `monthly_storage_gateway_backup_gb` `Storage gateway backup`
- `monthly_fsx_windows_backup_gb` `FSx for windows backup`
- `monthly_fsx_lustre_backup_gb` `FSx for lustre backup`

- `monthly_efs_warm_restore_gb` `EFS restore (warm)`
- `monthly_efs_cold_restore_gb` `EFS restore (cold)`
- `monthly_efs_item_restore_requests` `EFS restore (item-level)` with unit 'requests'
- `monthly_dynamodb_restore_gb` `DynamoDB restore`

in addition Cross-Region data pricing params can be specified as:
- `monthly_efs_data_transfer_gb` `EFS data transfer to other regions`
- `monthly_ebs_data_transfer_gb` `EBS data transfer to other regions`
- `monthly_rds_data_transfer_gb` `RDS data transfer to other regions`
- `monthly_aurora_data_transfer_gb` `Aurora data transfer to other regions`
- `monthly_storage_gateway_data_transfer_gb` `Storage gateway data transfer to other regions`
- `monthly_fsx_data_transfer_gb` `FSx data transfer to other regions`

**Comment by ekifel** [comment]
@alikhajeh1 Hey, I want to work on it

**Comment by alikhajeh1** [comment]
@dawidmalina this was released in v0.9.2 today.
