### ISSUE TITLE
[AWS] Costs for Marketplace AMIs

### ISSUE THREAD

**Issue by ackbyte** [infracost/infracost#348]
Run infracost on one of my internal test projects and found the issue with Marketplace AMIs.
The AMIs, which are from the marketplace not in the cost overview.

Example:
`
resource "aws_instance" "kafka-endpoint" {  
ami                     = "ami-0034c84e4e9c557bd"
`

The AMI **0034c84e4e9c557bd** is an CentOS 8 and have additional costs.
The Output shows only the EC2 Costs:
_Linux/UNIX usage (on-demand, t3a.xlarge)          730  hours      0.1728       0.1728      126.1440_

**Comment by alikhajeh1** [comment]
@ackbyte thanks for reporting this. I believe you're referring to the extra charges for [this image](https://aws.amazon.com/marketplace/pp/B07YLV9Y8H?qid=1611178886493&sr=0-1&ref_=srh_res_product_title)?

As mentioned in [the supported resources page](https://www.infracost.io/docs/supported_resources/), costs associated with marketplace AMIs are not supported as AWS doesn't seem to have an API for these prices. Furthermore, from the terraform file itself, we can't tell what OS the AMI is using (we'd have to query AWS), so for now we only support [this option](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L51-L52) in the [infracost-usage.yml](https://www.infracost.io/docs/usage_based_resources#infracost-usage-file). I haven't checked how much work it is yet but we might be able to add a field to that file so users can specify an add-on hourly price for resources. Would you use that or too much manual work?

**Comment by ackbyte** [comment]
Hi @alikhajeh1, thank you for the quick response!

Yes, that's correct. The [CentoOS 8](https://aws.amazon.com/marketplace/pp/B07YLV9Y8H?qid=1611178886493&sr=0-1&ref_=srh_res_product_title) Marketplace images was used in my case. This one produce additional costs. 

I understand the issue with the API, which does't provide the required information for proper calculations. Usage of infracost file option is fine for me. Very sad at this point, that AWS does not provide the API functionality for that.

Thank you very much for pointing me to this option.

**Comment by alikhajeh1** [comment]
@ackbyte thanks, the infracost-usage.yml does not yet support add-on hourly price for resources, and if you use the existing `rhel` with a t3a.xlarge instance, it adds $0.2104/hr vs the centos8 $0.20. Is that close enough to unblock you for now? Also, do you use the hourly or annual pricing for paying for centos8? I guess if we add `hourly_price_addition` you can either use $0.20 or $0.1711 ($1499/365*24).

@aliscott what do you think about this feature?

**Comment by aliscott** [comment]
@ackbyte @alikhajeh1 yeah, this is something we can add an override for in the `infracost-usage.yml` file. Maybe `software_hourly_price` to make it consistent with the marketplace terminology.

Longer term, though, I think we do want to support this. AWS recently released an [API for private market places](https://aws.amazon.com/blogs/awsmarketplace/introducing-aws-marketplace-apis-private-marketplace-to-manage-software-subscriptions/) so hopefully one for for the public marketplace is coming soon. The other option would be scraping it somehow.

**Comment by alikhajeh1** [comment]
@ackbyte when you run `aws ec2 describe-images --image-ids ami-0034c84e4e9c557bd`, do you see a `UsageOperation` result for it? If so, can you plz paste that here? I'm searching the pricing DB to see if we can find additional costs for such AMIs based on that.

If that method works, would you want Infracost to automatically make AWS API calls, using the creds that Terraform has, so it can show any additional AMI costs?

**Comment by alikhajeh1** [comment]
@ackbyte just FYI that in the recently released [v0.9.9](https://www.infracost.io/docs/#1-install-infracost) version, we released a feature that attempts to detect the OS as one of `linux`, `windows`, `suse`, `rhel` based on the response of [EC2DescribeOS](https://github.com/infracost/infracost/pull/967/files#diff-f4c655b4695ecd87dfbe5622e121083f60c59c95c9a3c3d9117d87c64bb1dd67R10-R26). This works for the following Terraform resources: `aws_instance`, `aws_autoscaling_group` and `aws_eks_node_group`. Can you possibly try that and let us know if it works for your use-case as I'm not sure if marketplace AMIs are returned using the same codes.
