### ISSUE TITLE
Smaller version of table output

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#356]
Existing table might be quite long (especially when you are using modules or even nested modules), for example:
```
  NAME                                                                               MONTHLY QTY  UNIT         PRICE   HOURLY COST  MONTHLY COST
  module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]                                                               
  ├─ Transit gateway attachment                                                              730  hours        0.0600       0.0600       43.8000
  └─ Data processed                                                                            -  GB           0.0200            -             -
  Total                                                                                                                     0.0600       43.8000 

...

  OVERALL TOTAL (USD)                                                                                                       0.2040      148.9200
```

Ideally if I would use some additional argument which will omit (`MONTHLY QTY`, `UNIT`, `PRICE`) and produce simplified output like this: 
```
  NAME                                                                               HOURLY COST  MONTHLY COST
  module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]                               
  ├─ Transit gateway attachment                                                           0.0600       43.8000
  └─ Data processed                                                                            -             -
  Total                                                                                   0.0600       43.8000

...

  OVERALL TOTAL (USD)                                                                     0.2040      148.9200
```

Full report will still be required but it will be just an build (merge request) artifact which I can refer as link without putting all those details as merge request comment.

In this case flow would be like this:
1. `infracost report --output compact-table out*.json > compact.txt`
2. `infracost report --output html out*.json > report.html`

**Comment by alikhajeh1** [comment]
@dawidmalina great point, we've been trying to keep the cost component names (e.g. Transit gateway attachment) as short as possible without sacrificing clarity, but hadn't thought about modules and their nesting.

Thinking of other things we could do, what do you think about `module.emea.module.vpc_ft_vc01.x.vpc_vc01[0]` for the name, so the aws resource type is omitted? Or is the full name required so you can quickly/accurately map the output to terraform? also, what terminal width would you say is the max number of characters that works for you?

**Comment by dawidmalina** [comment]
Personally I would keep the original (full) name as it will allow me to quickly identify resource. For the quick diff (review) I would prefer those three columns: `NAME`, `HOURLY COST`, `MONTHLY COST` as a sane minimum.

Btw it is exactly like this: https://www.infracost.io/img/screenshots/pr-step-2.png

I would not go too far with calculating terminal width especially the the name can takeover a bit more spaces as this line does not contains any cost values.

```
  NAME                                                                               HOURLY COST  MONTHLY COST
  module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.this_name_can_be_even_more_bigger[0]
  ├─ Transit gateway attachment                                                           0.0600       43.8000
  └─ Data processed                                                                            -             -
  Total                                                                                   0.0600       43.8000

...

  OVERALL TOTAL (USD)                                                                     0.2040      148.9200
```

**Comment by alikhajeh1** [comment]
@dawidmalina makes sense, we're going to show some love to the GCP users - we'll get to this feature when we have bandwidth, I also briefly discussed the idea of having users select the columns they want in the output with @aliscott (similar to how `kubectl` has `custom-columns` option).

**Comment by dawidmalina** [comment]
Will this change be compatible with the `infracost diff` or at least with `infracost report`?

**Comment by aliscott** [comment]
@dawidmalina yes this will also be compatible with the functionality for diff and report.

**Comment by aliscott** [comment]
@dawidmalina just an update on this. We've now shipped the config file in the latest release, so this feature will be added to it in the next release. I'll update this ticket when it's done.

**Comment by aliscott** [comment]
@dawidmalina thanks for all the input here 🙏. I'm closing this in favour of https://github.com/infracost/infracost/issues/524 so we can keep speccing it out as part of that ticket.
