### ISSUE TITLE
Add AWS China pricing support

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#368]
AWS China is slightly different to other AWS regions, and have specific pricing in place: https://www.amazonaws.cn/en/ec2/pricing/

The ideal output of Infracost in terms of currency for now is that all outputs are in USD.

**Comment by aliscott** [comment]
Added in https://github.com/infracost/cloud-pricing-api/pull/32. Currently this converts the CNY to USD and caches it for a day.

Note: there's some options that aren't yet available in the bulk pricing API for China, such as AWS ECS with Fargate.

**Comment by dawidmalina** [comment]
Does it mean that it is already available on the public pricing endpoint?

**Comment by aliscott** [comment]
@dawidmalina yes this has now been released in the public pricing endpoint.
