### ISSUE TITLE
Add Google data transfer cost for Cloud Storage

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#385]
The #350 PR already had some of this so the aim of this ticket is to move those to a separate resource like we did with AWS data transfer and add the requires usage-file params too

**Comment by alikhajeh1** [comment]
You might need to look at things like https://cloud.google.com/sql/pricing#network-egress-pricing https://cloud.google.com/products/calculator#id= > Networking egress to the available prices

**Comment by sinabakh** [comment]
I took a quick look at the SQL pricing and compared it to storage pricing. It seems their egress pricing method is completely different. I think we can't have a general resource for it. Or am I missing something?

**Comment by aliscott** [comment]
This looks more complicated than I initially thought. The pricing page for Cloud SQL suggests that egress from us-central1-a to internet is always $0.19/GB. But the pricing API shows some destinations as $0.12/GB. In the pricing API they are listed as resourceGroup=PremiumInternetEgress, but the pricing is not entirely consistent with the Premium Internet Egress pricing here (https://cloud.google.com/vpc/network-pricing).

API Gateway (https://cloud.google.com/api-gateway/pricing) also has different pricing but says "Egress prices are consistent with Google Cloud Network Pricing - Premium Tier", which is also wrong 🤦 .

The Google Cloud cost calculator (https://cloud.google.com/products/calculator) seems to ignore these product specific rates and suggest that only the standard Premium Tier rates are used.

Not sure what to do with this at the moment. Will keep digging.

**Comment by alikhajeh1** [comment]
The GCP Cloud Storage service had data transfer pricing for `Service:    strPtr("Cloud Storage")`, and I saw the same when reviewing the Google Cloud Functions PR `Service:       strPtr("Cloud Functions")`. So maybe @sinabakh's approach in that PR was good: anytime data transfer prices are returned as part of that service's pricing data, we include them in that resource's cost components. What do you guys think?

**Comment by sinabakh** [comment]
I highly believe that's the more proper way of doing this even for AWS. I understand that they charge the transfer as a separate cost component but that's just a virtual thing. I can't really change it without changing other resources.
In my point of view(as an Infracost user, not a contributor), I want to know how much of that huge "data transfer" thing is related to a specific resource.
I think we should take a hybrid approach, If a data transfer is related to a resource we include it in the resource data and have a separate data transfer cost component for other cases.

**Comment by sinabakh** [comment]
So what's the final decision?

**Comment by alikhajeh1** [comment]
@sinabakh bring back the commented code and tests - your approach is better for GPC :)

**Comment by alikhajeh1** [comment]
@sinabakh I changed the title of this ticket so we can use to track adding back the stuff we commented-out during the Google Cloud Storage PR.
