### ISSUE TITLE
Add support for Google Cloud SQL

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#386]
Terraform resources:
google_sql_database_instance
google_sql_user
google_sql_database

Pricing details: https://cloud.google.com/sql/pricing

**Comment by sinabakh** [comment]
I'd like to work on it, it might take some time cause it needs to support 3 different dbs.

**Comment by sinabakh** [comment]
@alikhajeh1 If no one is working on it I will give it a try.

**Comment by alikhajeh1** [comment]
Thanks @sinabakh!

**Comment by ekifel** [comment]
@alikhajeh1 Hey! I want to finish it if nobody mind

**Comment by alikhajeh1** [comment]
Thanks @ekifel, @sinabakh mentioned https://github.com/infracost/infracost/pull/491#issuecomment-809711462 so feel free to fork his fork to finish it 🍴

**Comment by alikhajeh1** [comment]
@tobbbles, @wrighbr, @mercuriete just FYI that this was released today in v0.8.4.
