### ISSUE TITLE
Add support for AWS EventBridge

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#387]
Terraform resources:
aws_cloudwatch_event_bus
aws_cloudwatch_event_permission
aws_cloudwatch_event_rule
aws_cloudwatch_event_target

Pricing details:
https://aws.amazon.com/eventbridge/pricing/

**Comment by ekifel** [comment]
Good day. Can I pick this up if nobody minds?

**Comment by alikhajeh1** [comment]
Done in https://github.com/infracost/infracost/pull/415
