### ISSUE TITLE
Add diff functionality to table/HTML outputs

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#394]
Once [this issue](https://github.com/infracost/infracost/issues/99) is released, we'll want to add the diff functionality to the `--output table|html` outputs. That could then be used in [CI integrations](https://infracost.io/docs/integrations/).

**Comment by sinabakh** [comment]
I'm thinking about working on it, what ideas we have for it?

**Comment by aliscott** [comment]
@sinabakh I've got a work in progress branch for the CLI (https://github.com/infracost/infracost/tree/feat/diff-cli) that's almost ready. It's not really a table view, and there's no HTML view for it yet, so I think it will replace this ticket.

**Comment by sinabakh** [comment]
Seems promising 👍🏼

**Comment by alikhajeh1** [comment]
The diff functionality has been added in v0.8, see migration guide [here](https://www.infracost.io/docs/guides/v0.8_migration). The HTML format doesn't have diffs yet, it's not clear if it's needed in HTML as that's being used more as a report format (i.e. like breakdown). I'll leave it for the community to create an issue and explain their diff in HTML use-cases.
