### ISSUE TITLE
Show not yet supported resources in dedicated command

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#395]
Just a small improvement which I have in my mind.

Having unsupported resources as part of the diff is quite useless and noisy but I would still like to know which resources are not yet calculated. Maybe we could have small command which without any further calculation can print table or list with unsupported resources.

Such command will be executed in the background and I as a devops can from time to time take a look and provide you feedback with resources which I might be interested.

**Comment by alikhajeh1** [comment]
Thanks for sharing! Can you please try this and let me know if it does what you'd like?
```
infracost --format=json --log-level=warn --terraform-dir=. | jq ".resourceSummary.unsupportedCounts"
```

> Such command will be executed in the background and I as a devops can from time to time take a look and provide you feedback with resources which I might be interested.

This is interesting, am I right in assuming that you've deployed and look after Infracost, and there are other teams who consume the Infracost outputs/diffs, so you'd like to see the unsupported resources but the other teams won't find that useful? It would be great to learn more about how you're using Infracost :)

**Comment by dawidmalina** [comment]
Hi @alikhajeh1 - proposed trick do the job :) thanks for that.

```
{
  "aws_cloudformation_stack": 28,
  "aws_cloudwatch_event_rule": 28,
  "aws_cloudwatch_event_target": 28,
  "aws_config_config_rule": 28,
  "aws_config_configuration_recorder": 4,
  "aws_config_configuration_recorder_status": 4,
  "aws_config_delivery_channel": 4,
  "aws_dx_transit_virtual_interface": 4,
  "aws_ec2_tag": 8,
  "aws_ec2_transit_gateway_peering_attachment_accepter": 3,
  "aws_ram_principal_association": 44,
  "aws_ram_resource_association": 4,
  "aws_ram_resource_share": 4
}
```

Basically my use case is quite simple (i guess:D) I don't need to see them as a part of the report or diff added to the every merge request review. But from time to time I want to see what resources are missing to make sure i can create new issue on the github or vote for the exiting one.

**Comment by alikhajeh1** [comment]
Great - makes total sense! `--show-skipped` defaults to false so you shouldn't see them in the table or HTML reports by default, the CI integrations also don't show them by default. I [updated](https://github.com/infracost/docs/commit/853e0062a49e38420ecffc2e030ca03cd383871a) the docs to add that useful command :)
