### ISSUE TITLE
Support for running atlantis diff on newly created project

### ISSUE THREAD

**Issue by jayceebernardino** [infracost/infracost#403]
Atlantis diff fails to run infracost on a commit where the directory doesn't exists.

**Comment by alikhajeh1** [comment]
@jayceebernardino thanks for reporting this, can you possibly describe this in a little bit more detail? I'm not sure I understand, the terraform directory has no terraform files? If so, you'd expect Infracost to skip over that dir?

**Comment by jayceebernardino** [comment]
This happens when we add a new [project](https://www.runatlantis.io/docs/repo-level-atlantis-yaml.html#example-using-all-keys) in atlantis. 

[atlantis_diff.sh](https://github.com/infracost/infracost/blob/master/scripts/ci/atlantis_diff.sh) will run `infracost` on the current branch and the base branch. The base branch doesn't have these files available since they are new so infracost fails.

**Comment by alikhajeh1** [comment]
Fixed in https://github.com/infracost/infracost/pull/404
