### ISSUE TITLE
Add support and documentation for Jenkins CI

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#406]
A user would like to see how they can integrate Infracost into Jenkins CI/CD, they've had a few teams look at it but for one reason or another had issues integrating it into the pipeline.

**Comment by ashokalinux** [comment]
How can integrate Infracost into Jenkins CI/CD ?

**Comment by sinabakh** [comment]
I started working on adding support for Jenkins and writing some docs.

**Comment by sinabakh** [comment]
What would you expect from Jenkins provider? Here are my initial thoughts:

* Generate an HTML output and store it as an artifact.
* Setting thresholds so pipelines fail if they are violated

**Comment by alikhajeh1** [comment]
@simonmcc, @justinjtownsend and @ashokalinux just FYI that thanks to @sinabakh we released Jenkins support today in v0.8.6, see https://www.infracost.io/docs/integrations/cicd#jenkins.

It would be great to hear your feedback on how you found the integration.
