### ISSUE TITLE
AWS Resource Access Manager

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#408]
Terraform resources:
- aws_ram_principal_association
- aws_ram_resource_association
- aws_ram_resource_share
- aws_ram_resource_share_accepter

RAM is free of charge https://aws.amazon.com/ram/faqs/ so maybe we could make it supported.

> Q: Will I incur any charges for sharing my resources with other accounts?
> No. You can share resources at no additional cost.

**Comment by alikhajeh1** [comment]
Thanks @dawidmalina - putting that FAQ in the description helped me add this one quickly. Every little helps :)
