### ISSUE TITLE
AWS Resouces free of charge

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#409]
Terraform resources:
- aws_ec2_tag
- aws_ec2_transit_gateway_peering_attachment_accepter
- aws_vpc_peering_connection_accepter
- aws_dx_gateway_association_proposal

We can make it supported to remove the noise.

**Comment by alikhajeh1** [comment]
Thanks @dawidmalina! I added the missing ones in https://github.com/infracost/infracost/pull/422/files, the bottom two were already on the free list. This will be released in the next version (probably early next week).
