### ISSUE TITLE
AWS China VPC resources showing $0 prices.

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#417]
This is an issue in the AWS bulk pricing API. I've opened a support ticket with AWS (Case ID 7974374661).

**Comment by aliscott** [comment]
**Content of support ticket**

**--------**

I'm trying to get the pricing for the following services from the bulk pricing API:

https://www.amazonaws.cn/en/privatelink/pricing/ shows the following prices:

```
China (Ningxia) Region
  Price per VPC endpoint per AZ (¥/hour): 0.0875
  Price per GB data processed (¥): 0.0700
China (Beijing) Region
  Price per VPC endpoint per AZ (¥/hour): 0.1120
  Price per GB data processed (¥):0.0700
```

https://www.amazonaws.cn/en/transit-gateway/pricing/ shows the following prices

```
Price per AWS Transit Gateway attachment (CNY)	0.5
Price per GB of data processed (CNY)	0.143
```

There's no way of getting this pricing from the AWS China endpoint of the bulk pricing API. This route returns a bad request: https://pricing.us-east-1.amazonaws.com/offers/v1.0/cn/AmazonVPC/current/index.json.

Some pricing (only for the VPC endpoints, not the Transit Gateways) is available for the China regions in the us-east-1 endpoint of the bulk pricing API. The problem is it returns incorrect prices ($0 instead of ¥0.0875):

```
curl https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonVPC/current/index.json
...
      "4AHBH8ZS5M4PJ3WD" : {
        "4AHBH8ZS5M4PJ3WD.JRTCKXETXF" : {
          "offerTermCode" : "JRTCKXETXF",
          "sku" : "4AHBH8ZS5M4PJ3WD",
          "effectiveDate" : "2020-11-01T00:00:00Z",
          "priceDimensions" : {
            "4AHBH8ZS5M4PJ3WD.JRTCKXETXF.6YS6EN2CT7" : {
              "rateCode" : "4AHBH8ZS5M4PJ3WD.JRTCKXETXF.6YS6EN2CT7",
              "description" : "$0.0 per GB for VpcEndpoint-Bytes:VpcEndpoint in China (Beijing)",
              "beginRange" : "0",
              "endRange" : "Inf",
              "unit" : "GB",
              "pricePerUnit" : {
                "USD" : "0.0000000000"
              },
              "appliesTo" : [ ]
            }
          },
          "termAttributes" : { }
        }
      },
...
```

How can I get the correct pricing for these resources from the bulk pricing API?

**--------**

**Comment by dawidmalina** [comment]
@aliscott is there any reply from the aws support about this issue?

**Comment by aliscott** [comment]
@dawidmalina have just chased them up.

**Comment by alikhajeh1** [comment]
@dawidmalina in a previous startup, I use to tell users to ask their AWS account execs (if they had one) to chase-up the case (Case ID 7974374661 in this case) - sometimes it resulted in them to take the tickets more seriously.

**Comment by aliscott** [comment]
Update from AWS:

```
Hello Alistair,

Greetings for the day. 

I'm following up to inform you that the service team is already looking into this request and working on update to fix this issue. 

We will get back to you as soon as we hear back from the service team. 

Apologies for the delay involved. 

Have a nice day!
```

**Comment by PatMyron** [comment]
similar thread: https://github.com/vantage-sh/ec2instances.info/issues/330

**Comment by aliscott** [comment]
**Content of support ticket**

**--------**

Hello Alistair, 

Greetings for the day. 

I'm glad to inform you that our service team has provided us with an update, and we have been able to successfully resolve your issue. The Bulk Pricing API for China will now have Amazon VPC in the list. You will get the pricing for VPC Endpoints and Transit-Gateway in the BJS and ZHY regions.

I hope this helps. Please do let me know if you have any further requests or queries. 

Have a nice day!

**Comment by aliscott** [comment]
I've checked and can confirm that there is now pricing for VPC Endpoints and Transit-Gateways. @dawidmalina can you please confirm if this works for you now?

**Comment by dawidmalina** [comment]
I can see now prices for vpc endpoints :)

**Comment by alikhajeh1** [comment]
Can we close this ticket?
