### ISSUE TITLE
Add usage-file support for all existing resources

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#421]
[This docs page](https://www.infracost.io/docs/supported_resources) shows all of the resources Infracost supports. Since a few weeks ago, whenever we add a new resource, we also add support for it to the usage-file.

The aim of this ticket is to go through all of the supported resources, and check which ones need to be updated to add [usage-file](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml) support for them. Once this ticket is done, all resources that are supported by infracost should appear in the infracost-usage-example.yml file if they have usage-based resources. That means if someone uses a usage-file for their resources, they should not see any `-` in the hourly/monthly cost column.

Thanks to @ekifel for getting the list:
- [x] api_gatewayv2_api websockets
- [x] aws_docdb_cluster_instance
- [x] aws_ebs_snapshot
- [x] aws_ebs_volume
- [x] aws_eip
- [x] aws_elasticache_cluster, aws_elasticache_replication_group
- [x] aws_lb, aws_elb
- [x] aws_fsx_windows_file_system
- [x] aws_route53_record
- [x] aws_s3_bucket
- [x] google_compute_address

**Comment by sinabakh** [comment]
For starters, I think we can create a checklist of all resources we currently have as a snapshot. Then we can start checking and adding required usage data as needed gradually through different PRs. What do you think?

**Comment by ekifel** [comment]
@alikhajeh1 I want to do this if no one minds

**Comment by alikhajeh1** [comment]
@ekifel can this issue be closed? all done? 🚀

**Comment by ekifel** [comment]
@alikhajeh1 Yes, that's all! You can close it
