### ISSUE TITLE
Build/release arm64 binaries

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#428]
See https://github.com/infracost/infracost/pull/287 for a previous attempt

**Comment by ondrejsika** [comment]
Thank you guys!

**Comment by alikhajeh1** [comment]
@ondrejsika anytime :) it'll go live in today's release, we're finalizing the docs just now, will post a comment when it ships

**Comment by alikhajeh1** [comment]
@ondrejsika if you get 5mins, it would be good if you can test the brew and manual macOS [install](https://www.infracost.io/docs/#1-install-infracost) options and let us know if they have any issues. (`infracost --version` or something similar to test is fine)
