### ISSUE TITLE
[Regression] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost#434]
After updating from v0.7.18 to v0.7.19 I have this error:

```
An unexpected error occurred
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xa5b740, 0xf88470, 0x0)
        /opt/hostedtoolcache/go/1.15.8/x64/src/runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc00016a790, 0xc0001da4e0, 0xa84580, 0xf418c0)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:179 +0x1c5
main.main.func1(0xc0000a5f40, 0xc00016a790, 0xc0000a5ef8, 0xc000114300)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:50 +0xba
panic(0xa84580, 0xf418c0)
        /opt/hostedtoolcache/go/1.15.8/x64/src/runtime/panic.go:969 +0x1b9
github.com/infracost/infracost/internal/schema.diffResourcesByKey(0x0, 0x0, 0xc0000a5630, 0xc0000a5600, 0x0, 0xc000621180)
        /home/runner/work/infracost/infracost/internal/schema/diff.go:70 +0x174
github.com/infracost/infracost/internal/schema.calculateDiff(0xc0001b4800, 0x28, 0x40, 0xc0001b4400, 0x28, 0x40, 0x0, 0x1, 0x10000c00016a6e0)
        /home/runner/work/infracost/infracost/internal/schema/diff.go:35 +0x205
github.com/infracost/infracost/internal/schema.(*Project).CalculateDiff(...)
        /home/runner/work/infracost/infracost/internal/schema/project.go:29
main.defaultMain(0xc00016a790, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/default.go:300 +0x94b
main.defaultCmd.func1(0xc000229000, 0xc000264900, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/default.go:130 +0x105
github.com/urfave/cli/v2.(*App).RunContext(0xc0001da4e0, 0xbfd140, 0xc000138010, 0xc0001161b0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70d
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:122 +0x577

Environment:
Infracost v0.7.19
```

Please give me some advice to create a useful ticket.

**Comment by aliscott** [comment]
@mercuriete thanks, I'm looking into this now. When you run `terraform plan` in that directory is it showing resources being removed or added?

**Comment by sinabakh** [comment]
I reproduced it, I'm working on the fix.
@aliscott Here's the minimal code to reproduce it:
```
emptyRMap := make(map[string]*Resource)
diffResourcesByKey("random_resource", emptyRMap, emptyRMap)
```
If the `old` and `new` are both `nil`, it happens.

**Comment by mercuriete** [comment]
ok, thanks
if you need me for something please don't hesitate in asking me to do it.

**Comment by mercuriete** [comment]
@aliscott 
sometimes you do commits and there are no changes in the plan...
for example.... imagine that you do a commit only changing... ``` infracost-usage.yml```
the plan will be:

```
No changes. Infrastructure is up-to-date.
```

**Comment by aliscott** [comment]
@mercuriete thank you, can you run the following:

```
terraform plan -out plan.save
terraform show -json plan.save | jq |grep '\"planned_values\"\|\"prior_state\"\|\"address\"\|\"module_address\"\|\"configuration\"'
```

This requires `jq` to be installed and should give us the basic structure of your plan file.

**Comment by mercuriete** [comment]
I did that command but it includes sensible info about the names of our infrastructure...

Can you provideme another way to give useful information?

for example...
can you provide me a branch with some logs enabled and I will try to compile infracost?
or even a binary if you will...

Thanks for the support.

**Comment by aliscott** [comment]
@mercuriete no worries.

Can you try with the latest master and `INFRACOST_LOG_LEVEL=debug`? The log lines that will help us start with `diffResourcesByKey`.

**Comment by mercuriete** [comment]
master is not crashing but the logs is a little bit weird:

```
time="2021-02-17T12:34:25Z" level=debug msg="diffResourcesByKey nil current and past with key "
time="2021-02-17T12:34:25Z" level=debug msg="diffResourcesByKey nil current and past with key "
time="2021-02-17T12:34:25Z" level=debug msg="diffResourcesByKey nil current and past with key "
```

there are only 1 double quote but no closing quotes.

**Comment by mercuriete** [comment]
@aliscott it seems the key is empty?
I compiled using this commit: 29728a941ab2ee44064de3aece33ca0e73061da1

and using docker build and extracting the binary from the container to my workstation.

Can I do something for you?

**Comment by aliscott** [comment]
Thanks @mercuriete, this was super helpful. We've shipped a patch just now, can you test that v0.7.20 works okay for you?

**Comment by mercuriete** [comment]
I tested infracost v0.7.20 and it works for me.

thanks for your help.

you can close this ticket.

**Comment by aliscott** [comment]
Thanks for your help 😄
