### ISSUE TITLE
Add support for Google Memorystore Redis

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#439]
Terraform resource: [google_redis_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance)
Pricing: see [here](https://cloud.google.com/memorystore/docs/redis/pricing)

**Comment by aliscott** [comment]
This should have one cost component:
* name: `Redis instance (basic, M1)`. The metadata in brackets should have basic/standard and M1-M5.
* unit: `GB-hours`. This should be an hourly quantity with a value of the `memory_size_gb` field from Terraform

The price will depend on the storage tier for the `tier` field as well as the capacity tier for the given `memory_size_gb`.

**Comment by ekifel** [comment]
@alikhajeh1 I want to work on it
