### ISSUE TITLE
Add support for AWS Application Auto Scaling

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#440]
Terraform resource: aws_appautoscaling_* (3 resources)
Pricing: [Application Auto Scaling](https://aws.amazon.com/autoscaling/pricing/) is itself free but it's used to scale target resources, we could either show the resources as free or do what we did with aws_autoscaling_group and have a usage-file param. I suspect the latter requires a reverse lookup so from a resource, we can find any references to it from aws_appautoscaling_ resources?

**Comment by alikhajeh1** [comment]
@aliscott what do you think? We've seen a few resources that have needed reverse lookup so I wonder if we should create a GH issue for that and add this (and others) as examples in that ticket that we can use during development/testing?

**Comment by aliscott** [comment]
Agree, I've added https://github.com/infracost/infracost/issues/849 so we can start tracking them.

**Comment by aliscott** [comment]
There's a few approaches we could take here. Please add any more ideas.

### Option 1: Add manual usage params for each scalable dimension to the relevant resources

For example, the `aws_appautoscaling_target` might be defined as:

```hcl
resource "aws_appautoscaling_target" "dynamodb_table_read_target" {
  max_capacity       = 100
  min_capacity       = 5
  resource_id        = "table/${aws_dynamodb_table.example.name}"
  scalable_dimension = "dynamodb:table:ReadCapacityUnits"
  service_namespace  = "dynamodb"
}
```

To model this we could add a `read_capacity_units` usage param to the `aws_dynamodb_table` resource, which could be specified manually by the user. With this approach we're essentially ignoring the `aws_appautoscaling_target` resource but allowing the usage to be modelled manually.

We would have to do this for every possible option for the `scalable_dimension` argument.

### Option 2: Update the quantities of the target resource based on the values in the `aws_appautoscaling_target` resource

When we parse the `aws_appautoscaling_target`, we lookup the target resource and update the quantities of it.

* We would need to implement the 2-way references (https://github.com/infracost/infracost/issues/849)
* We would need to decide whether we use the `min_capacity` or `max_capacity` value or a range (https://github.com/infracost/infracost/pull/21)
* We would be unable to show the cost if the target resource cannot be found in the current Terraform code.

### Option 3: Add the costs for the affected cost components to the `aws_appautoscaling_target` resource

When we parse the `aws_appautoscaling_target` we add cost components directly to the `aws_appautoscaling_target` for the `scalable_dimension`. For the example in option 1 the output would look like:

```
aws_appautoscaling_target.dynamodb_table_read_target
└─ Read capacity                                      100 RCU $X
```

* We would need to decide whether we use the `min_capacity` or `max_capacity` value or a range (https://github.com/infracost/infracost/pull/21)
* We would need to work out what we do with the equivalent cost component on the target resource. It wouldn't make sense to show the cost twice, so we'd probably want to remove those cost components from the target resource which would require 2-way lookups.

**Comment by alikhajeh1** [comment]
There was also some discussion in https://github.com/infracost/infracost/issues/1294#issuecomment-1017337723

**Comment by tim775** [comment]
I've added support for app autoscaling with dynamo in #1401, I'll create additional PRs for other resource types.

**Comment by tim775** [comment]
Support for MSK has been added in #1408 and elasitcache replication groups in #1409

**Comment by tim775** [comment]
This is live in 0.9.19 with support for dynamo_db_tables, msk_cluster, and elasticache_replication groups.  We went with "Option 2: Update the quantities of the target resource based on the values in the aws_appautoscaling_target resource"
