### ISSUE TITLE
AWS Resource free of charge

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#444]
Terraform resources:
- aws_resourcegroups_group

We can make it supported to remove the noise.

**Comment by dawidmalina** [comment]
Hehe @alikhajeh1 you were quicker ;)

**Comment by alikhajeh1** [comment]
Done via https://github.com/infracost/infracost/pull/445/files (sharing the link in case you prefer to send a PR if it saves you time vs creating the issue first for adding free resources)

**Comment by alikhajeh1** [comment]
@dawidmalina doh! sorry about that - I didn't see the open PR, you added it in **exactly the right place**. As the community gets bigger maybe we should update the contributing guide to encourage people to add a comment on issues they're working on to avoid that woopsie 😹

**Comment by alikhajeh1** [comment]
Tweaked it [here](https://github.com/infracost/infracost/commit/efe69e72eaaae607278aa033b12a6bfee12833db)
