### ISSUE TITLE
docs: infracost usage yaml aws_s3_bucket

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost#460]
there are no documentation in this file: https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml

when I do infracost I see this:

```
 aws_s3_bucket.uploaded-files                                                                                                   
  └─ Standard                                                    
     ├─ Storage                                                            -  GB              0.0260            -             -  
     ├─ PUT, COPY, POST, LIST requests                                     -  1k requests     0.0055            -             -  
     ├─ GET, SELECT, and all other requests                                -  1k requests     0.0004            -             -  
     ├─ Select data scanned                                                -  GB              0.0023            -             -  
     └─ Select data returned                                               -  GB              0.0008            -             -  

```

If you need more information about the problem I can rewrite this ticket.

thanks.

PS: It would be nice to have a feature request where you can query the YAML schema for a given infracost version instead of reading outdated documentation.

**Comment by mercuriete** [comment]
I am not sure if the following idea is good or bad:

infracost --showKeys

a parameter that instead of see human readable report... see the usage keys that we need to put on a usage file. (or another column in the same report)

I don't know if that is very difficult to implement but it would be nice to have some functionality like that.

Anyways...
thanks for your product

PS: If you can point me where is the file on the source where you define the schema... I can read by myself and learn.
PS2: you can close this issue if you want.
:+1:

**Comment by alikhajeh1** [comment]
Good point! I just pushed [this](https://github.com/infracost/infracost/commit/25d0c6dd48f3cbc827cc61ff9c10b0c62ac2026c) to clarify it. In case it helps, the work involves updating [s3_bucket.go](infracost/internal/providers/terraform/aws/s3_bucket.go) to read params from the usage-file and use those in the `CostComponent`'s `monthlyQuantity` param. If you'd like to help, plz add a comment to #421 in case @ekifel is already working on it.

**Comment by aliscott** [comment]
Thanks @mercuriete. Will close this issue for just now 😄
