### ISSUE TITLE
Take output from infracost & reuse in TF / Terragrunt creating an AWS budget.

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#463]
It would be good if possible to take the infracost estimates and feed back into terraform / terragrunt in some way to then create an AWS budget. This way you can create an alerting mechanism from the original estimate, especially if you have usage based estimates i.e. a set of AWS resources being used for 35% of the time. You can then alert if the environment is being used beyond the initial 35% via a budget that was created from the initial infracost estimate.

**Comment by alikhajeh1** [comment]
Cool idea!

Have you used AWS Cost Anomaly Detection before? If so, what's good/bad about it? I'm wondering if [AWS budget alerts](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget) are still the main cost guardrails or if users are moving to the cost anomaly stuff.

**Comment by robh007** [comment]
Hi @alikhajeh1 we do have cost Anomaly detection but I see this as a slightly different use case. With budgets I see that different environments / workloads can have estimates generated and then a budget created. Within budgets you can also create actions i.e. Stop the workload or notify that a particular workload is breaching a threshold. 
 
With anomaly detection that's going to show something that perhaps was misconfigured or new and the bill is going to be larger than the previous bill or something isn't quite right. Which is good to catch things that create large costs i.e. application logging to cloud-watch excessively. But I think there's perhaps two different guardrails here.

**Comment by robh007** [comment]
I've created a working example workflow using ``terragrunt`` here https://github.com/robh007/infracost-budgets. I'm using terragrunt dependencies to drive the ordering. I don't think it's possible to achieve this directly in terraform.

**Comment by robh007** [comment]
> Very cool MVP! The "multiple guardrails" way of looking at this makes sense.
> 
> Did I understand it right that it [falls back](https://github.com/robh007/infracost-budgets/blob/main/main.tf#L6) to a user-defined variable if the infracost cost estimate is missing? that's neat.

Yea, that's correct.

**Comment by alikhajeh1** [comment]
@robh007 I re-read this thread 3 times today as we're [investigating cost policies](https://github.com/infracost/infracost/discussions/1177) by looking at OPA, Hashi's Sentinel and Pulumi's CrossGuard. I was just wondering if you've had any experience with these tools? It would be great to hear your take on which approach is worth exploring more first: "create alerts/notifications from inside TF" (i.e. your prototype) or Infracost integration with OPA?

Ultimately both approaches seem to be driving towards one use-case: tell me when some threshold or condition is breached.

**Comment by hassankhosseini** [comment]
Just doing some house cleaning :) This is a feature that we have now built directly into Infracost Cloud. Users can set budget thresholds, and alerts or approval workflows are kicked off. Please reach out to hello@infracost.io if you'd like a demo.
