### ISSUE TITLE
Add support for Google Monitoring

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#472]
Pricing page:
https://cloud.google.com/stackdriver/pricing

**Comment by ekifel** [comment]
@alikhajeh1 Hello, can I pick it?

**Comment by alikhajeh1** [comment]
Thanks @ekifel 🕺

**Comment by alikhajeh1** [comment]
@ekifel it might be good to look at the other 7 `google_monitoring_*` resources as part of this issue, we can still do 1 PR per resource but use the same GH issue.

**Comment by alikhajeh1** [comment]
Released v0.8.0
