### ISSUE TITLE
Add support for Google Container Registry

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#473]
Terraform reosurce:
`google_container_registry`

Pricing page:
https://cloud.google.com/container-registry/pricing

**Comment by aliscott** [comment]
This resource is just a wrapper around a `google_storage_bucket`. This should show exactly the same cost components as the [google_storage_bucket resource](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/storage_bucket.go).
* Storage (standard)
* Data retrieval
* Object adds, bucket/object list (class A)
* Object gets, retrieve bucket/object metadata (class B)
* Network egress
  * Data transfer in same continent
  * ...

It should re-use the functions we have for building those cost components and assume a storage class of `STANDARD`.

**Comment by sinabakh** [comment]
It might be a suitable issue for new contributors.

**Comment by Pauluson** [comment]
i want to do this

**Comment by alikhajeh1** [comment]
@guilhermerenew just FYI this was released today in v0.8.4. Thanks @Pauluson!
