### ISSUE TITLE
Add pricing support for AWS CloudFormation

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#49]
AWS Cloud Formation costs: https://aws.amazon.com/cloudformation/pricing/

`aws_cloudformation_stack` and `aws_cloudformation_stack_set` are the main resources. For each one, we can use this logic to show the cost components:
1. If `template_body` is set AND its "Resources.types" start with `AWS::*`, `Alexa::*`, or `Custom::*` then return `IsSkipped:    true, NoPrice: true,` as it's a free resource.
2. Else, show both of these:
  - "Handler operations", units "operations". Usage file param `monthly_handler_operations: 10000 # Monthly number of non-free handler operations (resources outside of the AWS::*, Alexa::*, and Custom::* namespaces).`
  - "Durations above 30s", units "seconds". Usage file param `monthly_duration_secs: 0 # Monthly duration of non-free handler operations that go above 30 seconds, in seconds.`

As normal, the cost components should show cost-depends-on-usage if the usage file param is not specified.

Free resources:
aws_cloudformation_stack_set_instance
aws_cloudformation_type

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@nocquidant, @miyurusankalpa, @guilhermerenew, @danielbayerlein and @RichardDRJ support for costs of CloudFormation used in Terraform projects was released in v0.9.1 today.

If you're interested in seeing Infracost process CloudFormation templates as input, please 👍 [this issue](https://github.com/infracost/infracost/issues/190)
