### ISSUE TITLE
Auto-discovery of all TF workspaces

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#490]
Infracost can use `terraform workspace list` to automatically discovery of all workspaces in a repo, and return a cost diff for all workspace when a component changes. For example, if I change a module or component to add an EBS volume, and that component is used in dev, stage and prod, what is the cost impact?

This can also help with onboarding new users if we could auto-generate a config file for them.

**Comment by tim775** [comment]
Ok so after some more digging I see that infracost can look at the state or plan json.  So here's how I'm thinking about this now:
When the user runs infracost with something like `infracost diff --terraform-workspace-all --path .` we should sequentially run and ouput infracost diff for each workspace (diff will automatically generate a tf plan for each workspace based on the shared config and the workspace specific state).

**Comment by aliscott** [comment]
The way I was thinking about it was that if the user runs `infracost diff --path <path>` or `infracost breakdown --path <path>`, we detect that the `<path>` has multiple Terraform workspaces and we treat each workspace as a separate Infracost project, so they would be looped through as separate projects here: https://github.com/infracost/infracost/blob/master/cmd/infracost/run.go#L39.

We could then use the existing `--terraform-workspace` flag to filter to a single workspace.

I know @alikhajeh1 had an alternative idea about generating a config file, so will see what he thinks.

**Comment by alikhajeh1** [comment]
I'm struggling to think of any downsides of going with what @aliscott suggested above. It seems simpler for users too vs having to specify another flag.

My only hesitation is that while Terraform Cloud has [a solution](https://www.terraform.io/docs/cloud/workspaces/variables.html#loading-variables-from-files) for [workspaces variable definition files](https://www.terraform.io/docs/language/values/variables.html#variable-definitions-tfvars-files), the Terraform CLI itself doesn't so I'm not sure how useful our auto-discovery will be if it can't handle workspace-specific vars. I suspect that's a common setup since many people will use different vars between prod and non-prod workspaces.

One way to handle that could be to detect any errors and output a basic [config file](https://www.infracost.io/docs/multi_project/config_file/) that the user can copy/edit with their `terraform_plan_flags`?

**Comment by alikhajeh1** [comment]
@JulienChampseix I noticed you liked this GH issue... are you using Terraform Cloud to manage multiple workspaces? If not, how do you store/load workspace-specific var files? any feedback is appreciated

**Comment by alikhajeh1** [comment]
Going to close this issue as it doesn't seem to be a big issue - happy to re-open it if users request it.
