### ISSUE TITLE
Update aws_api_gateway_rest_api to show no costs when the usage-file isn't used

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#494]
The resource currently outputs 0 costs. We could probably also refactor it to remove `calculateAPIRequests` and change it to use `CalculateTierBuckets` that's used by other resources.

**Comment by ekifel** [comment]
@alikhajeh1 Hey, I guess I can do it fast if no one is doing it

**Comment by alikhajeh1** [comment]
Released in v0.8.0.
