### ISSUE TITLE
Plaintext Output

### ISSUE THREAD

**Issue by calebtote** [infracost/infracost#496]
We're including your project in our GitLab CI pipelines, but it seems that the coloring codes aren't represented the same as they would be in GitHub?
![Screen Shot 2021-03-08 at 1 25 16 PM](https://user-images.githubusercontent.com/1459202/110370923-ec2b6b80-8011-11eb-8dcc-361f2d8226f4.png)

Is there an option for plaintext output? Or better, a way to get these color codes to show up properly in GitLab MRs?

**Comment by calebtote** [comment]
I'm not sure if this is helpful, but linking just in case: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/24167

**Comment by alikhajeh1** [comment]
@calebtote thanks for reporting this issue and sorry for the delay, I was waiting for v0.8.0 to be released as we've simplified the integration and changed the CI integrations to use the new `infracost diff` command. Can you please follow the [migration guide](https://www.infracost.io/docs/guides/v0.8_migration/), specifically the [GitLab section](https://www.infracost.io/docs/guides/v0.8_migration/#gitlab-ci), and let me know if that works ok for you?
