### ISSUE TITLE
Refactor AWS DocumentDB pricing

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#503]
Currently we support `aws_docdb_cluster_instance` but we could improve it if we:
- add `aws_docdb_cluster`: this should only have the `Backup storage` cost component, which should be removed from `aws_docdb_cluster_instance` and moved into this resource. This cost component should only apply if `aws_docdb_cluster.backup_retention_period` is more than 1 (the cost component has the `backup_storage_gb` usage file property too).
- add `aws_docdb_cluster_snapshot`, it only has 1 cost component, which is `Backup storage` (would be good to call the same method from the above resource to do this instead of copy/pasting the code).
- add `aws_docdb_subnet_group` to the list of free resources

**Comment by Pauluson** [comment]
@alikhajeh1 I want to do it

**Comment by alikhajeh1** [comment]
Released in v0.8.3
