### ISSUE TITLE
0.9.0 will be a breaking change and should be 1.0.0

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost#505]
today i updated infracost to 0.8.0 and I see this message:

```
infracost --usage-file infracost-usage.yml 
┌────────────────────────────────────────────────────────────────────────┐
│ Warning: The root command is deprecated and will be removed in v0.9.0. │
│ Please use infracost breakdown                                         │
│ Migration details: https://www.infracost.io/docs/guides/v0.8_migration │
└────────────────────────────────────────────────────────────────────────┘

```

according to semver (https://semver.org) a breaking change should not occur until a major version bump.

please change the message to:
```
┌────────────────────────────────────────────────────────────────────────┐
│ Warning: The root command is deprecated and will be removed in v1.0.0. │
│ Please use infracost breakdown                                         │
│ Migration details: https://www.infracost.io/docs/guides/v0.8_migration │
└────────────────────────────────────────────────────────────────────────┘
```

**Comment by aliscott** [comment]
@mercuriete thanks for the issue. We're still iterating on the interface and will remain in v0.* until we finalize the API (taking a [little inspiration from Hashicorp](https://www.hashicorp.com/resources/the-path-to-terraform-1-0)). Once that's done we will release v1.

Let us know if there's anything we can help with during the upgrade process.
