### ISSUE TITLE
Add support for Amazon EFS One zone 

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#508]
AWS released a new storage class within EFS, it will require TF support issue here - 

hashicorp/terraform-provider-aws#18016

AWS Blog post on the storage class. 
https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-lower-cost-storage-classes-for-amazon-elastic-file-system/

**Comment by alikhajeh1** [comment]
@robh007 this is great, thanks for keeping Infracost in-sync with cloud vendor and Terraform changes. It's the sort of thing we need to do across all cloud vendors and IaC tools longer term 🕺

**Comment by tim775** [comment]
It looks like we can use the presence of tf `availability_zone_name` param to determine if the EFS should use `Standard` or `One Zone` pricing.  We should update the display of the `storage_gb` and `infrequent_access_storage_gb` to differentiate between standard and one zone:
- `Storage (standard)` 
- `Storage (standard, infrequent access)` 
- `Storage (one zone)` 
- `Storage (one zone, infrequent access)`

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@robh007 just FYI this was released in v0.9.2 today.
