### ISSUE TITLE
infracost diff html format

### ISSUE THREAD

**Issue by sushant-pradhan** [infracost/infracost#509]
Hello team, I was wondering if we can enable html format for diff command. The console output looks good but if I have to send the diff output over email, the console output doesn't really go well. It will be better if we have a html equivalent like we have for breakdown command

infracost v0.8.1

**Comment by alikhajeh1** [comment]
@sushant-pradhan hah, funny you mention that as I posted [a comment](https://github.com/infracost/infracost/issues/394#issuecomment-795914531) a few hours ago asking for exactly this sort of feedback.

**Comment by alikhajeh1** [comment]
@sushant-pradhan who would you email the HTML reports to? fellow team mates? other teams? managers? clients? This context helps us as we think about how the output of Infracost can be shared with others

**Comment by sushant-pradhan** [comment]
@alikhajeh1 we plan to send to the team mates who can review the delta and approve the plan. It something similar to the PR comments we add from GH actions.

**Comment by alikhajeh1** [comment]
@sushant-pradhan we're working on a dashboard so team members can view run details, plz email me at ali.hosseini@infracost.io if this is something that might interest your team!

**Comment by alikhajeh1** [comment]
@sushant-pradhan as part of our [Terraform Cloud integration](https://www.infracost.io/docs/iac_tools/terraform_cloud_enterprise#terraform-cloud-run-tasks), we've developed a way to generate sharable, pre-authenticated, HTML reports (with both the breakdown and the diff format) that could be passed around teams. I've emailed you an example as we're thinking of developing that further so going to close this issue for now.
