### ISSUE TITLE
Use fixed cost component names

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#516]
I updated the contributing docs to say the following. The aim of this ticket is to find all cost component names that change based on other params, and refactor them. There shouldn't be many, but finding them might take some grep foo, or VS Code might have a better answer...

The cost component name should not change when the IaC resource params change; anything that can change should be put in brackets, so for example:
- `General Purpose SSD storage (gp2)` should be `Storage (gp2)` as the storage type can change.
- `Outbound data transfer to EqDC2` should be `Outbound data transfer (to EqDC2)` as the EqDC2 value changes based on the location.
- `Linux/UNIX (on-demand, m1.small)` should be `Instance usage (Linux/UNIX, on-demand, m1.small)`.

In the future, we plan to add a separate field to cost components to hold the metadata in brackets.

**Comment by Pauluson** [comment]
I want to do it
