### ISSUE TITLE
[docker] terraform latest version

### ISSUE THREAD

**Issue by uncodable** [infracost/infracost#519]
Hey,

Can we get the docker image built for the latest terraform build?

> Failed to read plan from plan file: plan file was created by Terraform 0.14.8, but this is 0.14.7; plan files cannot be transferred between different

Thanks in advance.

**Comment by uncodable** [comment]
ping @alikhajeh1 - thanks in advance

**Comment by alikhajeh1** [comment]
Thanks for reporting this! I sent [a PR](https://github.com/infracost/infracost/pull/520) to bump the version.

**Comment by aliscott** [comment]
@uncodable I've actually pushed this now to `infracost/infracost:latest`.
