### ISSUE TITLE
add shell-completion to infracost commands 🚀 

### ISSUE THREAD

**Issue by guilhermerenew** [infracost/infracost#525]
## About Issue 👋🏾 
@alikhajeh1 as we talked, follows the issue to add bash-completion to infracost commands! Such a feature can be compatible with the main bash `bashrc/zsh`! Looking at some examples that may help: [completion.go by Helm](https://github.com/helm/helm/blob/7b6dcfae98527c3ff7233fc16cbeac782dd82977/cmd/helm/completion.go)

**Comment by alikhajeh1** [comment]
We use https://github.com/spf13/cobra internally so we should be able to use the `Automatically generated shell autocomplete for your application (bash, zsh, fish, powershell)` feature it has to do the same thing as https://cli.github.com/manual/gh_completion and create a new command:

`infracost completion: Generate shell completion scripts`

**Comment by ekifel** [comment]
@alikhajeh1, I want to work on it!

**Comment by alikhajeh1** [comment]
@PatMyron and @guilhermerenew we released this in v0.9.1 today, please upgrade and run ` infracost completion --help` and add a comment if it works ok on your shells! We should have done this earlier, makes it much faster to run infracost commands 🕺

**Comment by guilhermerenew** [comment]
@alikhajeh1 I performed the autocomplete test following the help steps of the `infracost completion` command and it worked perfectly! This feature will be extremely welcome by the community, good job guys! 🎉
