### ISSUE TITLE
Support AWS EC2 RI prices

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#529]
Currently Infracost supports on-demand prices. We can add the following options to [aws_instance](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L118-L119) in the infracost usage-file to enable users to switch to see RI prices:
- reserved_instance_type: standard or convertible
- reserved_instance_term: 1_year or 3_year
- reserved_instance_payment_option: no_upfront, partial_upfront, all_upfront

The ability to define wildcards in the usage-file (e.g. `aws_instance.*` or `aws_instance.app1*`) would save users from having to define that for all instances. A similar thing could be applied to Azure instances that also have [RI prices](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/).

See [this reddit thread](https://www.reddit.com/r/Terraform/comments/m81h38/infracost_diff_git_diff_but_for_cloud_costs/grhzcpb/?utm_source=reddit&utm_medium=web2x&context=3) for background - thanks to u/sumthingcool for the discussion.

**Comment by alikhajeh1** [comment]
I think we can add the above usage file parameters to the following supported resources:
- aws_instance
- aws_eks_node_group
- aws_autoscaling_group (which has aws_launch_configuration as a sub-resource)

That would mean we support EC2 RI prices anywhere that uses them.

**Comment by ekifel** [comment]
@alikhajeh1 Good. Can I work on it?

**Comment by alikhajeh1** [comment]
This was released in v0.8.5
