### ISSUE TITLE
Support EC2 monitoring options

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#53]
EC2 monitoring price depends on the number of metrics for their instance types
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html#ec2-cloudwatch-metrics

Here are the one's we seem to be missing:
- aws_launch_configuration.*.enable_monitoring
- aws_instance.*.monitoring
- aws_launch_template.*.monitoring.enable

**Comment by aliscott** [comment]
Added in https://github.com/infracost/infracost/pull/129
