### ISSUE TITLE
Auto-generate usage-file from Terraform project

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#530]
Currently users have to write this out manually and everyone loves automation to help them.

**Comment by sinabakh** [comment]
I would like to work on it, here are my initial ideas:
* There will be a sub-command like: `infracost autogen -g usage_file -o ./usage_file.yml`. `-g` flag indicates what kind of file to generate so we can add more functionality to it later and `-o`.
* It will iterate over the resources of terraform project and will add 0 for all usage keys.

Here are some additional steps to make it more robust but will take more time so I don't know if we have to ship it in the first phase:
* If the file exists, do not override the existing values and just add missing ones.
* We can make the usage file thing more schema full so we won't have to parse our sample one first to know about all usage data for resources.

**Comment by aliscott** [comment]
Thanks @sinabakh! Here's some more thoughts on this:

> There will be a sub-command like: `infracost autogen -g usage_file -o ./usage_file.yml`

I like the separate command. It would need the same flags that are passed to breakdown (`--path, --terraform-plan-flags, etc`) so it can generate the plan JSON file.

Another option to think about is to add it as a flag to the existing breakdown command, e.g:
```
infracost breakdown --path=/path/to/code --usage-file=infracost-usage.yml --sync-usage-file
```

I don't have a strong preference yet, so can be convinced either way. Whichever way we pick I think we should mark it as experimental in the help text until we get some feedback from users.

> If the file exists, do not override the existing values and just add missing ones.

I think this should be in the first cut. However, not sure if we also want to remove values for resources that have been deleted initially.

> We can make the usage file thing more schema full so we won't have to parse our sample one first to know about all usage data for resources.

Agree, long term we should do this because it helps with validating the usage file as well. Initially, I think we should go with whatever is quickest.

**Comment by robh007** [comment]
I previously spoke about maybe supporting a variable map in terraform something like. This then can be part of the terraform input to the module.  In this example you could build usage support into the terraform modules & therefore not necessarily need the yaml file. Or the requirement to generate is done a usage file is within the internals of infracost. You're then not running multiple infracost commands. Just my thoughts. 

```hcl
variable "INFRACOST_USAGE" {
  type = map(map(string))
  default = {
    lambda_resource = {
      monthly_requests = 1000
      request_duration_ms = 100
    }
  }
}
```

Which ever way you think about this something as got to provide values to create a dataset. I think autogenerating the file is good, but also adding the correct usage values needs to be consider. i.e. how the values are set or retrieved.

**Comment by alikhajeh1** [comment]
@robh007 great feedback! I think this is the first of a few iterations we need to do on usage-based resources, the next iteration can be to fetch the last day/week/month values from CloudWatch as you pointed out at the bottom.

> You're then not running multiple infracost commands

Can you possibly expand on the benefits of having a `INFRACOST_USAGE` variable in TF as it feels like I'm missing something. Our old approach of using the terraform-provider-infracost felt a bit heavy/clunky but maybe a variable is lighter since it won't show-up in terraform apply outputs? You'd still want the variables to be auto-generated so you can fill-in the values?

**Comment by robh007** [comment]
@alikhajeh1 so the old approach was as you say `clunky`. It's definitely a lighter option, I'm more thinking around the terms of the actual values than the config file itself. Using cloudwatch is in an option if there's a valid metric to poll, there's also a cost associated with that and a separate authentication method outside of the terraform provider. This approach provides a native approach to include the specific request quantities within the TF code declaration(s). So maybe a better example would be. 

```hcl
module "workload-1" {
   source = "some-repo"

   function_name = "myfunction"
   s3_bucket_name = "mybucketname"

   // This is just to get the point across it doesn't define the naming convention. 
   infracost_usage = {
       lambda={
           monthly_requests = 100000
           request_duration_ms = 100
      },
       api_gateway_v2={
          monthly_requests = 100000
      }
   }
}
```

You could even look to set those values in a usage module then feed that map into subsequent other workloads. I think if you can support something in terraform either a var or even a local. You can then feed the quantities into the generated file. Or generate the file from the specified quantities. What do you do with the generated files & there quantities do you then store that away somewhere? Is this then starting to lean towards a second type of state file? Do you want to do that or lean on terraform to store those values for you with little effort.

**Comment by aliscott** [comment]
> Using cloudwatch is in an option if there's a valid metric to poll, there's also a cost associated with that and a separate authentication method outside of the terraform provider.

Yes this is a good point and something we need to think more about. I wonder if we could even calculate the potential cost of polling the metrics and display it!

One thing we have to consider is that we don't want this to be Terraform only, as we plan on supporting multiple IaC tools. This doesn't mean that we shouldn't provide a native Terraform way of specifying usage, but we should see it as additional alternative format. For this reason, I'd lean towards managing the state of the file ourselves.
