### ISSUE TITLE
Add support and documentation for Azure DevOps CICD

### ISSUE THREAD

**Issue by anmoel** [infracost/infracost#531]
Hi, 

we also use Azure DevOps for some Projects. Can you add an Azure DevOps extension to the marktplace (https://marketplace.visualstudio.com/) or document how to integrate it?

Thanks in advance
André

**Comment by alikhajeh1** [comment]
Hey @anmoel - thanks for creating this issue, it's something we should support.

I've not used Azure DevOps before and happy to learn. Do you know if it's possible to run docker tasks in Azure pipelines? That's how most of the current CI/CD integrations work, e.g. see the [GitLab one](https://gitlab.com/infracost/infracost-gitlab-ci/-/blob/master/infracost.yml). If so, then it should be fairly simple to get this working.

**Comment by alikhajeh1** [comment]
@anmoel we shipped initial support for Azure DevOps Pipelines, can you possibly review https://github.com/infracost/infracost-azure-devops/ and let me know if it works ok for you?
