### ISSUE TITLE
Support AWS CloudWatch costs

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#54]
Terraform cloud's cost estimation supports these:

- aws_cloudwatch_dashboard: should be $3 per dashboard per month ?
- aws_cloudwatch_metric_alarm: might be difficult with Anomaly detection and high-resolution

**Comment by robh007** [comment]
@alikhajeh1 I can take a look at this if you would like?

**Comment by alikhajeh1** [comment]
That would be great, thanks @robh007! heads-up that it won't be the simplest resource to add - happy to help :)
