### ISSUE TITLE
Update HTML output to be consistent with CLI output

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#548]
We should update the HTML output to be consistent with the new CLI table output

* Support multiple projects. We should update it so it doesn't use the following deprecated output fields: `resources`, `totalMonthlyCost`, `totalHourlyCost`, and instead uses the `projects` field.
* Remove the file grouping logic we have - this can now be done with the multiple project
* Support the `--fields` flag (when it's merged).  This should work the same way the `table` output format works
* Keep the existing tags functionality so we continue showing the tag list under each resource
* Add the `Cost depends on usage: XXX`

Here's a wireframe for what the output would look like:

<img width="840" alt="Screenshot 2021-04-26 at 11 54 39" src="https://user-images.githubusercontent.com/158824/116521804-581ca880-a8cc-11eb-96c7-3db96c9b6b18.png">

**Future**
1. How do we show both the breakdown and diff in the output? See: https://github.com/infracost/infracost/issues/509
2. Support dynamic columns (as per https://github.com/infracost/infracost/issues/524)

**Comment by alikhajeh1** [comment]
Initially let's just have the current HTML output format show a breakdown.

**Comment by ekifel** [comment]
@aliscott, I want to work on it!

**Comment by alikhajeh1** [comment]
Released in v0.9.0
