### ISSUE TITLE
AWS burstable instance credits calculations.

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#554]
Currently the way CPU credits for T2 / T3 & T4 instances are being calculated incorrectly. I'm just raising this as an issue here, it came to light when I was looking into #477. @alikhajeh1 If you can allocate this to me, I've got a WIP branch. It currently affects `EKS Node Groups` `Autoscaling Groups` & `EC2 Instances`.

**Comment by alikhajeh1** [comment]
@robh007 just wanted to check something: once this issue is resolved, would CPU credits on T2 / T3 & T4 instances show as "costs depend on usage: ..."?

**Comment by robh007** [comment]
Yes @alikhajeh1. I'm going to write some findings in the contributors channel.
