### ISSUE TITLE
Add CircleCI integration

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#56]
@sashman is already working on this, https://github.com/infracost/infracost-orb

**Comment by m-yosefpor** [comment]
Now that we have docker image on dockerhub, can we just use that instead of building it in the orb file? @sashman

**Comment by m-yosefpor** [comment]
I've created a PR for the above comment: https://github.com/infracost/infracost-orb/pull/2

**Comment by sashman** [comment]
I'll take this

**Comment by sashman** [comment]
Working on https://github.com/infracost/infracost-orb/issues/1 next

**Comment by amioranza** [comment]
Hi, this issue has any updates? I'm really interested to integrate infracost at circleci.

**Comment by alikhajeh1** [comment]
@amioranza yep! I've simplified the CI script so it can be re-used across GitHub, GitLab and CircleCI, the refactor will be merged today/tmrw and I'll update the orb to use it next right after that :)

**Comment by amioranza** [comment]
Awesome!!! Thanks.

**Comment by alikhajeh1** [comment]
@amioranza this is now released, please see https://github.com/infracost/infracost-orb 
1. I added support for GitHub and BitBucket and tested using their cloud offerings, are you using one of these? I also added 2 envs that can be useful for self-hosted ones but I haven't tested those.
2. If you're using BitBucket, please note that it does not show commit comments in the pull request page so you have to check the commit's comments page to see the Infracost output.

What's your take on infracost CI integrations storing the infracost output from the current branch as an artifact in the build, useful for future reference or is the diff comment enough?

I'll close the issue but feel free to comment to let me know how it goes.

**Comment by amioranza** [comment]
Hi @alikhajeh1:
First of all thanks for your works.

1. We use github cloud. I'll integrate the new orb and test it.
2. As bitbucket is not our current scenario, it is ok for me.

I think that infracost comment is enough, it we need to see the history we can go to the PR and look at the comments.
