### ISSUE TITLE
Add Azure App Service Plan and Environment

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#561]
The initial work has already been done by @DanielMabbett's here: https://github.com/infracost/infracost/pull/457/commits/c0d00adbac5a1bf89ac6984f5eae9db9fce0016e

Azure pricing page: https://azure.microsoft.com/en-gb/pricing/details/app-service/

Resources:

`azurerm_app_service_plan`

* Instance usage (S1) - unit is hours. Quantity is based on `capacity`. We should also allow the user to pass in a `instances` usage variable that overrides this capacity.

`azurerm_app_service_environment` - This is for the Isolated Service Plans.

* Stamp fee - unit is hour. This only applies to v1 instances.
* Instance usage (I1) - unit is hours

Not supported:

* Dev/test pricing - this doesn't seem to be supported by Terraform.

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
