### ISSUE TITLE
Add Azure managed disks

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#567]
* Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk
* Pricing page: https://azure.microsoft.com/en-gb/pricing/details/managed-disks/

Cost components and units:
* `Storage (S4)` - Azure disks are set sizes and have a name, so we can display the disk name in brackets. Unit should be `months`
* `Disk operations` - this is a usage-based component. Unit should be `10k operations`. This does not apply to PremiumSSD and UltraSSD disks
* `Provisioned IOPS` - only applicable to UltraSSD disks. Unit is IOPS-hours.
* `Provisioned throughput` - only applicable to UltraSSD disks. Unit is Mbps-hours.

Not supported:
* Bursting for PremiumSSD disks - this doesn't seem to be supported by Terraform.

**Comment by aliscott** [comment]
The price components for Standard HDD, Standard SSD and Premium SSD disks has already been done here: https://github.com/infracost/infracost/blob/feat/azure-pricing-changes/internal/providers/terraform/azure/virtual_machine.go#L100. This can be moved out of there and into helpers in the `azurerm_managed_disk` resource, so it can be used for both the `azurerm_*_virtual_machine` and `azurerm_managed_disk` resources.

**Comment by alikhajeh1** [comment]
Released in v0.8.4
