### ISSUE TITLE
[CI/CD] Docker releases should include app version and tf version

### ISSUE THREAD

**Issue by unfor19** [infracost/infracost#57]
For example-

`infracost/infracost:1.0.1-tf0.12.26, infracost/infracost:1.0.1-tf0.13.1`

**Comment by alikhajeh1** [comment]
This is partially done as we build/push released versions to dockerhub (all using Terraform v0.13.4).

**Comment by unfor19** [comment]
@alikhajeh1 feel free to close this issue if it's irrelevant

**Comment by alikhajeh1** [comment]
@unfor19 I think it might be needed long-term as more terraform versions (after the one that infracost supports) come out.

**Comment by alikhajeh1** [comment]
Going to close this issue as the infracost Dockerfile now has the latest patch versions that are supported and users can use [this env](https://www.infracost.io/docs/integrations/environment_variables#infracost_terraform_binary) to define which they'd like to use.
