### ISSUE TITLE
Add Azure App Service Certificate Order

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#570]
The Azure App Service Plan and Environment are included in https://github.com/infracost/infracost/issues/561.

Azure pricing page: https://azure.microsoft.com/en-gb/pricing/details/app-service/

Resource:

[`azurerm_app_service_certificate_order`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_certificate_order)
* `SSL certificate (standard) or SSL certificate (wildcard)` - unit is months. This is listed per year on the pricing page, but not sure how it's specified in the DB.

**Comment by alikhajeh1** [comment]
Released in v0.8.5
