### ISSUE TITLE
Add Azure MySQL Database

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#571]
Pricing page: https://azure.microsoft.com/en-gb/pricing/details/mysql/server/

`azurerm_mysql_database`

* `Compute (GP_Gen5_2)` - unit is hours.
  * The instance type can be taken from `sku_name`.
* `Storage` - unit is GB-months. The quantity should be based on `storage_mb`
* `Additional backup storage` - unit is GB-months. Price is based on `geo_redundant_backup_enabled`. Usage-based, usage key should be `additional_backup_storage_gb`.

Unsupported:
* Flexible server
* Threat detection

**Comment by ekifel** [comment]
@alikhajeh1, @aliscott, Hey, I want to work on it!

**Comment by aliscott** [comment]
Closed by https://github.com/infracost/infracost/pull/604.
