### ISSUE TITLE
Add Azure PostgreSQL Database

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#572]
Pricing page: https://azure.microsoft.com/en-gb/pricing/details/postgresql/server/

`azurerm_postgresql_server`

* `Compute (GP_Gen5_2)` - unit is hours.
  * The instance type can be taken from `sku_name`.
* `Storage` - unit is GB-months. The quantity should be based on `storage_mb`
* `Additional backup storage` - unit is GB-months. Price is based on `geo_redundant_backup_enabled`. Usage-based, usage key should be `additional_backup_storage_gb`.

Unsupported:
* Flexible server
* Hyperscale (Citus)
* Threat detection

**Comment by ekifel** [comment]
@alikhajeh1, @aliscott, Hey, I want to work on it!

**Comment by aliscott** [comment]
Closed by https://github.com/infracost/infracost/pull/603.

**Comment by aliscott** [comment]
@ekifel reopening this since I'm seeing these warnings in the test logs:
```
=== RUN   TestPostgreSQLServer
time="2021-04-23T17:26:34Z" level=warning msg="Multiple products found for azurerm_postgresql_server.gp_4core Additional backup storage, using the first product"
time="2021-04-23T17:26:34Z" level=warning msg="Multiple products found for azurerm_postgresql_server.basic_2core Additional backup storage, using the first product"
time="2021-04-23T17:26:34Z" level=warning msg="Multiple products found for azurerm_postgresql_server.mo_16core Additional backup storage, using the first product"
--- PASS: TestPostgreSQLServer (9.95s)
=== RUN   TestPostgreSQLServer_usage
time="2021-04-23T17:26:44Z" level=warning msg="Multiple products found for azurerm_postgresql_server.with_geo Additional backup storage, using the first product"
time="2021-04-23T17:26:44Z" level=warning msg="Multiple products found for azurerm_postgresql_server.without_geo Additional backup storage, using the first product"
--- PASS: TestPostgreSQLServer_usage (9.81s)
```
