### ISSUE TITLE
Add Azure Storage Account (block blob)

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#574]
Pricing page: https://azure.microsoft.com/en-gb/pricing/details/storage/blobs/

`azurerm_storage_account`

* Azure Storage Accounts can represent different types of storage. This ticket is for implementing the block blob storage prices. Initially we can return an unsupported resource if `account_kind` is not `BlockBlobStorage`.
* Capacity, operations and data prices are based on the following attributes:
  - `account_tier` - The Terraform docs say that only Premium is valid for BlockBlobStorage, but the Azure pricing pages say differently so we should check this.
  - `account_replication_type`
  - `access_tier`

Cost components:

* Capacity - unit is GB-months. Usage based, usage key should be `storage_gb`.
* Write operations - unit is 10k operations. Usage based, usage key should be `monthly_write_operations`.
* List and create container operations - unit is 10k operations. Usage based, usage key should be `monthly_list_and_create_container_operations`.
* Read operations - unit is 10k operations. Usage based, usage key should be `monthly_read_operations`.
* All other operations - unit is 10k operations. Usage based, usage key should be `monthly_other_operations`.
* Data retrieval - unit is GB. Usage based, usage key should be `monthly_data_retrieval_gb`.
* Data write - unit is GB. Usage based, usage key should be `monthly_data_write_gb`.
* Blob index - unit is 10k tags. Usage based, usage key should be `blob_index_tags`.

Unsupported:
* Change feed
* Encryption scopes

**Comment by tim775** [comment]
The details in initial comment seem pretty helpful.  It might be nice to also include a link to the terraform registry docs.

**Comment by ekifel** [comment]
Hey, I want to work on it!
