### ISSUE TITLE
Add Azure Storage Account (file)

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#575]
Pricing page: https://azure.microsoft.com/en-gb/pricing/details/storage/files/

`azurerm_storage_account`

* Azure Storage Accounts can represent different types of storage. This ticket is for implementing the file storage prices. The base resource will be implemented in https://github.com/infracost/infracost/issues/574 so this should be done after that.
* Capacity, operations and data prices are based on the following attributes:
  - `account_replication_type`
  - `access_tier` - Terraform docs say this can be `Hot` or `Cold` but file storage can also have `Premium` and `Transaction-optimized` so we should check if they are also supported.

Cost components:

* Data at rest - unit is GB-months. Usage based, usage key should be `data_at_rest_storage_gb`.
* Snapshots - unit is GB-months. Usage based, usage key should be `snapshots_storage_gb`.
* Metadata at rest - unit is GB-months. Usage based, usage key should be `metadata_at_rest_storage_gb`. This is free for Premium and Transaction-optimized tears.
* Write operations - unit is 10k operations. Usage based, usage key should be `monthly_write_operations`.
* List operations - unit is 10k operations. Usage based, usage key should be `monthly_list_and_create_container_operations`.
* Read operations - unit is 10k operations. Usage based, usage key should be `monthly_read_operations`.
* All other operations - unit is 10k operations. Usage based, usage key should be `monthly_other_operations`.
* Data retrieval - unit is GB. Usage based, usage key should be `monthly_data_retrieval_gb`.
* Early deletion - unit is GB. Usage based, usage key should be `early_deletion_gb`.

Unsupported:
* Sync servers

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
![yoda](https://user-images.githubusercontent.com/638577/118680165-66d4ec00-b7f6-11eb-8496-930685aade85.jpg)
