### ISSUE TITLE
Params for terraform init

### ISSUE THREAD

**Issue by ulm0** [infracost/infracost#576]
Hi guys, 
I have a workflow where terraform is initialized based on context from env vars, it uses params for that purpose (`terraform init --backend-config ...`) so no backend config is present in terraform files, and i can't seem to find a way to specify those params for infracost, is this currently supported? if not, anything i can do to help building this feature?

Thanks in advance

**Comment by alikhajeh1** [comment]
@ulm0 would [this method](https://www.infracost.io/docs/#terraform-plan-json) work? So you can generate the Terraform plan JSON before running Infracost, and point `--path` to it (instead of the Terraform project directory).

**Comment by ulm0** [comment]
That did the trick, thanks a lot @alikhajeh1

**Comment by alikhajeh1** [comment]
Awesome!
