### ISSUE TITLE
 index out of range error with --sync-usage-file

### ISSUE THREAD

**Issue by sergiorojodxc** [infracost/infracost#579]
infracost breakdown --sync-usage-file --usage-file env/dev/networking/vpc/resources-usage.yml --path env/dev/networking/vpc --terraform-plan-flags "-var-file=vars.tfvars -var-file=endpoint.tfvars"

Detected Terraform directory at env/dev/networking/vpc
  ✔ Running terraform plan
  ✔ Running terraform show

Error: An unexpected error occurred

runtime error: index out of range [-1]
goroutine 1 [running]:
runtime/debug.Stack(0xc0002c8800, 0x0, 0xc0001390f0)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc0001469a0, 0xaf6da0, 0xc000299470)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:220 +0x45
main.main.func1(0xc000139ec8, 0xc0001469a0, 0xc000024360)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:39 +0xa5
panic(0xaf6da0, 0xc000299470)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/usage.syncResourcesUsage(0xc000176400, 0x29, 0x40, 0xc00033d290, 0xc0001e3500, 0x16, 0x1, 0x0)
        /home/runner/work/infracost/infracost/internal/usage/usage_file.go:71 +0x59e
github.com/infracost/infracost/internal/usage.SyncUsageData(0xc000209c00, 0xc0001e3500, 0x7fffda3ce0cb, 0x2a, 0x1, 0xc00000e928)
        /home/runner/work/infracost/infracost/internal/usage/usage_file.go:47 +0x85
main.runMain(0xc00021e000, 0xc0001469a0, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/run.go:84 +0x4ff
main.breakdownCmd.func1(0xc00021e000, 0xc0002095e0, 0x0, 0x7, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:40 +0x106
github.com/spf13/cobra.(*Command).execute(0xc00021e000, 0xc000209570, 0x7, 0x7, 0xc00021e000, 0xc000209570)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e9680, 0x351, 0xc000139ee8, 0x7)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:171 +0xd3e

Environment:
Infracost v0.8.3

**Comment by aliscott** [comment]
Thanks @sergiorojodxc, looks like this is caused by the `--sync-usage-file` flag.

@sinabakh any ideas what could be causing this? Looks like a resource name isn't in the expected format.

**Comment by aliscott** [comment]
Thanks for reporting @sergiorojodxc, the fix will be in v0.8.4 which will be released tomorrow.

**Comment by alikhajeh1** [comment]
@sergiorojodxc this is released now.
