### ISSUE TITLE
[DOCS] Update README.md with Docker usage

### ISSUE THREAD

**Issue by unfor19** [infracost/infracost#58]
Add to the usage section-

## Docker

Replace the `--tf-dir` value with your infra's path, or git clone this repository to check the examples

```
docker run --rm -v $PWD/:/code/ infracost/infracost:latest --tf-dir /code/examples/small_terraform
```

**Comment by apreshagarwal** [comment]
Hi there, I am interested in taking up this task. Can you please assign it to me?

**Comment by apreshagarwal** [comment]
> Add to the usage section-
> 
> ## Docker
> Replace the `--tf-dir` value with your infra's path, or git clone this repository to check the examples
> 
> ```
> docker run --rm -v $PWD/:/code/ infracost/infracost:latest --tf-dir /code/examples/small_terraform
> ```

Hi there, I am interested in taking up this task. Can you please assign it to me?

**Comment by sashman** [comment]
@alikhajeh1 as per earlier, I'll pick this up
