### ISSUE TITLE
Add Gitlab-ci Integration

### ISSUE THREAD

**Issue by m-yosefpor** [infracost/infracost#59]

**Comment by m-yosefpor** [comment]
I've added a repository for it here :https://github.com/m-yosefpor/infracost-gitlab-ci

Please let me test it in a sample gitlab pipeline, and then we can create a repo here and move all the files. 

And about the repo name, which one is better?
- infracost-gitlab-ci
- infracost-gitlabci
- infracost-gitlab
- Any other alternative you suggest?

I prefer the first one. WDYT @aliscott @alikhajeh1 ?

**Comment by alikhajeh1** [comment]
thanks @m-yosefpor! So far we've been going with using words that resonate with users who use that CI system (hence infracost-gh-action, or infracost-orb) so I'd go with which ever matches best for gitlab users (probably the first one?)

**Comment by m-yosefpor** [comment]
Yeah `gitlab-ci` it is

**Comment by m-yosefpor** [comment]
A sample pipeline output:

![image](https://user-images.githubusercontent.com/47300215/92956619-6d97ac00-f47c-11ea-9115-a603b4063603.png)

Here is the mirrored repo: https://gitlab.com/myosefpor/infracost-gitlab-ci

I think the repo is ready for moving to infracost org.

**Comment by m-yosefpor** [comment]
This is done, and has been implemented in https://gitlab.com/infracost/infracost-gitlab-ci
