### ISSUE TITLE
Make units and quantities more understandable

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#593]
**Problem:**

The unit in the pricing API is not the same as the unit we want to display.

For example, for Azure Managed Disks we currently show:
```
 azurerm_managed_disk.ultra
 ├─ Storage (ultra, 8 GiB)                                  5,840  GiB-hours                  $0.96
 ├─ Provisioned IOPS                                      730,000  IOPS-hours                $49.64
 └─ Throughput                                              7,300  MB/s-hours                $10.00
```

It would be more understandable if we show:
```
 azurerm_managed_disk.ultra
 ├─ Storage (ultra, 8 GiB)                                      8  GiB                  $0.96
 ├─ Provisioned IOPS                                          100  IOPS                $49.64
 └─ Throughput                                                 10  MB/s                $10.00
```
But we still need the `-hours` values to calculate the cost from the price.

**Proposal:**

Have separate attributes to represent these:

* DisplayUnit: What we show in the Unit column
* DisplayQuantity: What we show in the Quantity column
* PriceQuantity: What the price is multiplied by to get the monthly or hourly cost
* PriceTimeUnit: Whether the price is an hourly, monthly, or one-off cost.

**Case 1: We want to display the same as the data in the pricing API**

Example: AWS EBS volume storage

Currently:

```
Unit:            "GB-months"
UnitMultiplier:  1
MonthlyQuantity: sizeGB
```

New:

```
DisplayUnit: "GB"
DisplayQuantity: sizeGB
PriceQuantity: sizeGB
PriceTimeUnit: TimeUnits.Month
```

**Case 2: We want to display a different multiple of the pricing API unit**

Example: We want to show AWS EBS volume I/O requests as "per 1M requests", but the pricing API has "per request" pricing.

Currently:

```
Unit:            "requests"
UnitMultiplier:  1000000
MonthlyQuantity: ioRequests
```

New:

```
DisplayUnit: "1M requests"
DisplayQuantity: ioRequests * 1000000
PriceQuantity: ioRequests
PriceTimeUnit: TimeUnits.OneOff
```

**Case 3: Pricing API has per-hour cost**

Example: Azure Managed Disks list the storage prices per hour, so for a 1 GiB disk we currently show the quantity and unit as "730 GiB hours" but we want the quantity to show "1 GiB".

Currently:

```
Unit:            "GiB-hours"
UnitMultiplier:  1
HourlyQuantity: sizeGB
```

New:

```
DisplayUnit: "GiB"
DisplayQuantity: sizeGB
PriceQuantity: sizeGB
PriceTimeUnit: TimeUnits.Hour
```

**Other changes**

Since the quantity is now no longer a monthly or hourly quantity, we should probably remove the `monthly_quantity` and `hourly_quantity` from the JSON format and replace it with `quantity`. This would be a breaking JSON change so we could release as part of v0.9.

We should also update the usage file to be consistent with this. For example we should update any key that is `*_per_hr` to be `hourly_*`, and any key that is `*_hrs` to `monthly_*_hrs`.

**Comment by tim775** [comment]
I"m going to work through it the way you propose but I'm wondering if we could achieve the same result without a breaking change by just adding DisplayQuantity and removing UnitMultiplier.

I had another thought (probably wrong due to inexperience 🙂 ): It seems like Hourly/Monthly Quantity and PriceTimeUnit are really used as arguments to a function that (along with a price) calculates the cost (CostComponent.CalculateCosts?).  

Instead could we just add a function field for CalculateCosts to CostComponent?  So the lambda requests resource would go from:
```
CostComponents: []*schema.CostComponent{
{
  Name:            "Requests",
  Unit:            "requests",
  UnitMultiplier:  1000000,
  MonthlyQuantity: monthlyRequests,
  ProductFilter: &schema.ProductFilter{
  ...
```
to something like
```
CostComponents: []*schema.CostComponent{
{
  Name:            "Requests",
  Unit:            "1M requests",
  Quantity: requests,
  CalculateCosts: func(price decimal) decimal {
            return requests / 1000000 * price; // or whatever this actual calculation should be :)
        },
  ProductFilter: &schema.ProductFilter{
  ...
```

**Comment by aliscott** [comment]
> I'm wondering if we could achieve the same result without a breaking change by just adding DisplayQuantity and removing UnitMultiplier.

Definitely open to better/quicker ways of doing this. What do you mean by "without a breaking change". Would that be not changing the JSON format?

I like the `CalculateCosts` function idea. We might want it to be `CalculateMonthlyCost` to make it clear what time frame the cost applies for.

There's also an edge case with Google instances we'll want to consider. For almost every resource `hourly_cost = monthly_cost / 730`. But for Google instances we use the sustained usage price for monthly, but not for hourly. This is currently applied with the `MonthlyDiscountPerc` field in the cost component.

**Comment by tim775** [comment]
> What do you mean by "without a breaking change". Would that be not changing the JSON format?
Clearly what I mean by that is "I'm not really sure what I'm talking about" 😀.  So... *maybe* this is where I'm headed: It seems like there are two parts to the proposal 1) Change Unit & UnitMultiplier -> DisplayUnit & DisplayQuantity, 2) Change HourlyQuantity & MonthlyQuantity -> PriceQuantity & PriceTimeUnit.  I guess it seems like we're trying to fix UnitMultiplier and I don't (yet) see why we need to muck with HourlyQuantity/MonthlyQuantity to do that.  Probably it will become clear when I get a bit further into the code.

> There's also an edge case with Google instances...
Ah I'd almost forgotten about sustained pricing discounts.  In that case would it make sense to have fields for CalculateMonthlyCost & CalculateHourlyCost?  I'm guessing that most resources would just use default implementations for both.  Doing it this way may be a cleaner way to handle MonthlyDiscountPerc and UnitMultiplier cases.

**Comment by aliscott** [comment]
> I guess it seems like we're trying to fix UnitMultiplier and I don't (yet) see why we need to muck with HourlyQuantity/MonthlyQuantity to do that. Probably it will become clear when I get a bit further into the code.

Ah ok. So the issue with the quantities is for cases like "Case 3" above. If someone creates an Azure Managed Disk with 2048GB storage, 4000 IOPS and 5000MB/s throughput, we currently show the below since the price is listed per hour.
```
 Name                                                            Quantity  Unit                Monthly Cost
 
 azurerm_managed_disk.ultra_disk
 ├─ Storage (ultra, 2048 GiB)                                   1,495,040  GiB-hours                $245.19
 ├─ Provisioned IOPS                                            2,920,000  IOPS-hours               $198.56
 └─ Throughput                                                  3,650,000  MB/s-hours             $5,000.50
 ```
 Ideally I think we want to show the quantities that match what the user entered in their Terraform code/usage file. These also match the inputs used by the AWS calculator (most of the time).
 ```
 Name                                                            Quantity  Unit                Monthly Cost
 
 azurerm_managed_disk.ultra_disk
 ├─ Storage (ultra, 2048 GiB)                                       2,048  GiB                      $245.19
 ├─ Provisioned IOPS                                                4,000  IOPS                     $198.56
 └─ Throughput                                                      5,000  MB/s                   $5,000.50
 ```
 So this is the idea between separating the display quantity from the hourly/monthly quantities we use to multiply the price by. I'm not sure if the term `DisplayQuantity` make sense to be honest.
 
 > In that case would it make sense to have fields for CalculateMonthlyCost & CalculateHourlyCost?
 
 Yeah I think that makes sense. For 90% of the cases I'm sure they will be defaults.
 
Just thinking out loud here, in the future I wonder if we'd want to show the user the logic of how the cost was calculated. So for these cases we could show the working like: `4000 IOPS * 730 (since it's an hourly price) * $0.000068`, although, I doubt that's going to be super important.

**Comment by tim775** [comment]
It looks like UnitMultiplier pretty much does what we want already so this seems to be a fairly simple change (no need to add or remove fields).  The trick is to remove the automatic calculation of UnitMultiplier quantities that's done in UnitWithMultiplier().  Once that's out of the way, we convert from GiB-hours by setting `Unit: "GiB"` and `UnitMultiplier: 730`.  https://github.com/infracost/infracost/compare/master...tim775:feat/make_units_and_quantities_understandable

I made the change for azure/managed-disk and table output changes from
```
  NAME                          MONTHLY QTY  UNIT        PRICE   HOURLY COST  MONTHLY COST  

  azurerm_managed_disk.ultra                                                                
  ├─ Storage (ultra, 2048 GiB)    1,495,040  GiB-hours   0.0002       0.3359      245.1866  
  ├─ Provisioned IOPS             2,920,000  IOPS-hours  0.0001       0.2720      198.5600  
  └─ Throughput                      14,600  MB/s-hours  0.0014       0.0274       20.0020  
  Total                                                               0.6353      463.7486  
                                                                                            
  OVERALL TOTAL (USD)                                                 0.6353      463.7486 
```
to 
```
  NAME                          MONTHLY QTY  UNIT  PRICE   HOURLY COST  MONTHLY COST  

  azurerm_managed_disk.ultra                                                          
  ├─ Storage (ultra, 2048 GiB)        2,048  GiB   0.1197       0.3359      245.1866  
  ├─ Provisioned IOPS                 4,000  IOPS  0.0496       0.2720      198.5600  
  └─ Throughput                          20  MB/s  1.0001       0.0274       20.0020  
  Total                                                         0.6353      463.7486  
                                                                                      
  OVERALL TOTAL (USD)                                           0.6353      463.7486 
```
the diff for JSON output is along the lines of
```
12,15c12,15
<           "unit": "GiB",
<           "hourlyQuantity": "2.8054794520547945",
<           "monthlyQuantity": "2048",
<           "price": "0.11972",
---
>           "unit": "GiB-hours",
>           "hourlyQuantity": "2048",
>           "monthlyQuantity": "1495040",
>           "price": "0.000164",
...
```

If that looks alright let me know and I'll update the rest of the "*-hour" units (I'm assuming we want to do this for all clouds, not just azure).

**Comment by aliscott** [comment]
👍 This makes a lot of sense.

Most non-monthly prices are shown monthly as well on pricing pages as well, so I think changing the price is okay.

We should update any cost component rows with no cost to show something like this: "Monthly cost depends on usage: $0.4745 per WCU" (Currently they show "Cost depends on usage: ...").

**Comment by tim775** [comment]
I've got two PRs for this.  First https://github.com/infracost/infracost/pull/619 adds the golden file tests.  Once that is merged the changes made in https://github.com/infracost/infracost/pull/622 should be easy to see in the golden file diffs.

**Comment by alikhajeh1** [comment]
This has been released
