### ISSUE TITLE
Add Azure App Service Certificate Binding

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#596]
The Azure App Service Plan and Environment are included in https://github.com/infracost/infracost/issues/561 and Certificate Order is included in https://github.com/infracost/infracost/issues/570

Azure pricing page: https://azure.microsoft.com/en-gb/pricing/details/app-service/

`azurerm_app_service_certificate_binding`
* IP SSL certificate - unit is months. only has a cost if `ssl_state` is `IpBasedEnabled`.

`azurerm_app_service_custom_hostname_binding`
* IP SSL certificate - unit is months. only has a cost if `ssl_state` is `IpBasedEnabled`.

Not supported:

* App Service Domain - this doesn't seem to be supported by Terraform.

**Comment by NissesSenap** [comment]
Started to look at this one.
I'm curios though.

It looks like **IP SSL** costs 39$ just as specified.
```
db.products.find({"vendorName": "azure", "service": "Azure App Service", "productFamily": "Compute", "region": "westeurope", "attributes.skuName": "IP SSL" }).pretty()
{
	"_id" : ObjectId("606c626038ebcb6d079a7d3c"),
	"productHash" : "33125878be2b0df7df979b4b76c976b1",
	"attributes" : {
		"effectiveStartDate" : "2013-06-03T00:00:00Z",
		"productId" : "DZH318Z0BP0S",
		"productName" : "Azure App Service SSL Connections",
		"serviceId" : "DZH317GT8G5N",
		"serviceFamily" : "Compute",
		"skuName" : "IP SSL",
		"armSkuName" : "",
		"meterId" : "94db869d-b0ed-486a-8995-ddff0eba7412",
		"meterName" : "IP SSL Connection"
	},
	"productFamily" : "Compute",
	"region" : "westeurope",
	"service" : "Azure App Service",
	"sku" : "DZH318Z0BP0S/001L/94db869d-b0ed-486a-8995-ddff0eba7412",
	"vendorName" : "azure",
	"prices" : [
		{
			"priceHash" : "33125878be2b0df7df979b4b76c976b1-e285791b6e6926c07354b58a33e7ecf4",
			"purchaseOption" : "Consumption",
			"unit" : "1/Month",
			"USD" : "39",
			"effectiveDateStart" : "2013-06-03T00:00:00Z",
			"startUsageAmount" : 0
		}
	]
}
```

But **SNI SSL** isn't free:
```
db.products.find({"vendorName": "azure", "service": "Azure App Service", "productFamily": "Compute", "region": "westeurope", "attributes.skuName": "SNI SSL" }).pretty()
{
	"_id" : ObjectId("606c625b38ebcb6d079a4fbb"),
	"productHash" : "bbe4dd4f5befd980f6edfb55affa61ce",
	"attributes" : {
		"effectiveStartDate" : "2013-06-03T00:00:00Z",
		"productId" : "DZH318Z0BP0S",
		"productName" : "Azure App Service SSL Connections",
		"serviceId" : "DZH317GT8G5N",
		"serviceFamily" : "Compute",
		"skuName" : "SNI SSL",
		"armSkuName" : "",
		"meterId" : "878bced4-6856-46c1-a3df-15641b31057a",
		"meterName" : "SNI SSL Connection"
	},
	"productFamily" : "Compute",
	"region" : "westeurope",
	"service" : "Azure App Service",
	"sku" : "DZH318Z0BP0S/001V/878bced4-6856-46c1-a3df-15641b31057a",
	"vendorName" : "azure",
	"prices" : [
		{
			"priceHash" : "bbe4dd4f5befd980f6edfb55affa61ce-e285791b6e6926c07354b58a33e7ecf4",
			"purchaseOption" : "Consumption",
			"unit" : "1/Month",
			"USD" : "9",
			"effectiveDateStart" : "2013-06-03T00:00:00Z",
			"startUsageAmount" : 0
		}
	]
}
``` 

So I guess I misunderstand the Azure docs or some pricing is wrong in your DB or in the azure pricing API.
If you have some pointer that would be great.

**Comment by alikhajeh1** [comment]
@NissesSenap awesome PR! Do you have a support contract with MS Azure? If so, maybe you can ask them that question? If not, I'll do that from our side. Their support teams usually escalate these detailed pricing questions to the right teams internally so we can get an answer.

Until then, I'd go with the Azure pricing page and skip the resource as free for SNI (see following example from the contributing guide). That's what users will be comparing Infracost outputs with so it feels safer to go with that till we know for sure.

```
free resources: if there are certain conditions that can be checked inside a resource Go file, which mean there are no cost components for the resource, return a `NoPrice: true` and `IsSkipped: true` response as shown below.

	if blah {
		return &schema.Resource{
			NoPrice:   true,
			IsSkipped: true,
		}
	}
```

**Comment by NissesSenap** [comment]
Glad to hear it :)
I don't have a easy way of creating tickets with them so it would be good if you can reach out.

I will update the PR with the NoPrice during this week.

**Comment by alikhajeh1** [comment]
Thanks @NissesSenap - sure will do, they usually take a while to get back to us so we can merge this PR once the outstanding issue is resolved and I'll create a new issue if required.
