### ISSUE TITLE
Request: Add Markdown as Output Option

### ISSUE THREAD

**Issue by ekristen** [infracost/infracost#605]
Markdown is practically supported everywhere in terms of parsing and displaying. I think markdown tables could work nicely.

You can use markdown lists for the tree affect as well.

I'm looking to want to generate outputs whenever it changes and store it along with my documentation which is all written in markdown already. Would be nice to run and redirect output to file to include in my docs.

**Comment by aliscott** [comment]
@ekristen thanks, I think this is a good idea. We also use markdown outputs for the CI/CD integrations.

Do you see the markdown output being similar to the `infracost breakdown` cli output or the `infracost diff` output?

**Comment by ekristen** [comment]
I was originally thinking the breakdown as a table?

**Comment by JamesWoolfenden** [comment]
If this could work to update a section Readme that would be ideal, well for me anyway.

**Comment by alikhajeh1** [comment]
@ekristen and @JamesWoolfenden any thoughts on the following output options? Markdown tables don't have cell-merge, and indentation isn't supported AFAIK :( 
BTW, there's also https://github.com/infracost/infracost/issues/43 if your use-case lends itself more to linking to a badge/shield in the readme?

# Option 1: markdown list

Monthly cost estimate from Infracost.io: **$742.64**
- aws_instance.web_app
  - Instance usage (Linux/UNIX, on-demand, m5.4xlarge), 730  hours, $560.64
  - root_block_device
    - Storage (general purpose SSD, gp2),                             50  GB-months,                    $5.00
  - ebs_block_device[0]
    - Storage (provisioned IOPS SSD, io1),                         1,000  GB-months,                  $125.00
    - Provisioned IOPS,                                              800  IOPS-months,                 $52.00
- aws_lambda_function.hello_world
  - Requests,                                            Cost depends on usage: $0.20 per 1M requests
  - Duration,                                            Cost depends on usage: $0.0000166667 per GB-seconds

# Option 2: markdown table

Monthly cost estimate from Infracost.io: **$742.64**

| Name |                                                       Monthly Qty | Unit |                 Monthly Cost |
| --- | --- | --- | ---|
| aws_instance.web_app |
| - Instance usage (Linux/UNIX, on-demand, m5.4xlarge)           |    730  | hours    |                  $560.64 |
| - root_block_device |
| -- Storage (general purpose SSD, gp2)                          |   50 | GB-months |                   $5.00 |
| - ebs_block_device[0] |
|  -- Storage (provisioned IOPS SSD, io1)                        | 1,000 | GB-months          |        $125.00 |
|  -- Provisioned IOPS                                           |  800  | IOPS-months       |          $52.00 |
| aws_lambda_function.hello_world |
| - Requests             |                               Cost depends on usage: $0.20 per 1M requests |
| - Duration              |                              Cost depends on usage: $0.0000166667 per GB-seconds|
| **PROJECT TOTAL**                                                              |||                         **$742.64** |

# Option 3: current table format wrapped in a markdown code block

```
Monthly cost estimate from Infracost.io: $742.64

 Name                                                        Monthly Qty  Unit                  Monthly Cost

 aws_instance.web_app
 ├─ Instance usage (Linux/UNIX, on-demand, m5.4xlarge)               730  hours                      $560.64
 ├─ root_block_device
 │  └─ Storage (general purpose SSD, gp2)                             50  GB-months                    $5.00
 └─ ebs_block_device[0]
    ├─ Storage (provisioned IOPS SSD, io1)                         1,000  GB-months                  $125.00
    └─ Provisioned IOPS                                              800  IOPS-months                 $52.00

 aws_lambda_function.hello_world
 ├─ Requests                                            Cost depends on usage: $0.20 per 1M requests
 └─ Duration                                            Cost depends on usage: $0.0000166667 per GB-seconds

 PROJECT TOTAL                                                                                       $742.64
```

**Comment by sinabakh** [comment]
I might be biased but I think option 3 seems more readable.

**Comment by JamesWoolfenden** [comment]
I like the third option, I was  manually copying in the output and using codeblocks and that seems to give the best layout.

**Comment by alikhajeh1** [comment]
I'm going to close this issue as Option 3 above seems the most readable, which doesn't require any changes since the text output can be wrapped in ```code``` blocks in markdown. Feel free to comment with better suggestions and we can revisit it.

**Comment by benniemosher** [comment]
I personally would love to see a markdown table like option #2 as well as a command that will update my Readme for me like terraform-docs does. How can we get something like this going?

**Comment by jeacott1** [comment]
I ended up just wrapping the standard infracost breakdown text in markdown codefences. Quick and dirty but better than any of the other options.
