### ISSUE TITLE
Git removed from Docker image which breaks remote modules

### ISSUE THREAD

**Issue by keslerm** [infracost/infracost#607]
In the PR #585 Git was removed from the list of installed packages but it is required by Terraform to pull remote modules

```
   Terraform command failed with:
    Error: Failed to download module
    Could not download module "private" (main.tf:1) source code from
    "git@github.com:private/repo": error
    downloading
    'ssh://git@github.com/private/repo': git
    must be available and on the PATH
```
I think maybe removing git was unintentional without realizing Terraform depended on it

**Comment by aliscott** [comment]
Thanks @keslerm 🙌, sorry for missing that!

**Comment by aliscott** [comment]
@keslerm this fix is now in the infracost/infracost:latest Docker image.
