### ISSUE TITLE
Add support for Azure Functions

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#627]
Pricing web page: https://azure.microsoft.com/en-gb/pricing/details/functions/
Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app

The `app_service_plan_id` can be followed to see what type of pricing applies:
1. If the `app_service_plan.kind=elastic` OR `app_service_plan.sku.tier=ElasticPremium` then `Premium plan` pricing applies so the following cost components should be shown. The instance type can be fetched from `azurerm_app_service_plan.sku.size` and the supported values are [EP1, 2 and 3](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-premium-plan?tabs=portal#available-instance-skus), we can have a hard-coded map of the CPU/Memory of those 3 types. The `instances` usage file value can be used to calculate the cost.
- Name "vCPU", units "vCPU-hours"
- Name "Memory", units "GB-hours"

2. If the app_service_plan.kind is FunctionApp then `Consumption` pricing applies so the following cost components should be shown. The monthly_executions, execution_duration_ms, and memory_mb usage file values can be used to calculate the cost. 
- Name "Execution time", units "GB-seconds"
- Name "Executions", units "requests"

The usage file should have these params, the top 3 can be used in Consumption and the bottom 2 can be used in Premium plan pricing:
```
    monthly_executions: 100000 # Monthly executions to the function. Only applicable for Consumption plan.
    execution_duration_ms: 500 # Average duration of each execution in milliseconds. Only applicable for Consumption plan.
    memory_mb: 128 # Average amount of memory consumed by function in MB. Only applicable for Consumption plan.
    instances: 2 # Number of instances. Only applicable for Premium plan.
```

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
