### ISSUE TITLE
Gone from 0.8.5 -> 8.5.6, release should be 0.8.6

### ISSUE THREAD

**Issue by 06kellyjac** [infracost/infracost#630]
The latest release is `8.5.6`. I'm guessing it was meant to be `0.8.6`

**Comment by alikhajeh1** [comment]
@06kellyjac thanks for reporting this! I've messed up :( fixing things now...

**Comment by alikhajeh1** [comment]
@06kellyjac fixed https://github.com/infracost/infracost/releases/tag/v0.8.6 😅
