### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by Tjstretchalot** [infracost/infracost#631]
Hello! A minor annoyance I have with this CLI is it doesn't respect `-v`, `--version` or the command `version`. It does print the version out when you just run e.g. `infracost help` when using an out of date version, but it's nice to see the correct version number for peace of mind after updating infracost.

**Comment by alikhajeh1** [comment]
@Tjstretchalot thanks for reporting this! We added `infracost --version` a while ago (can't remember the date but it feels like a few months ago), perhaps you're using an old version when we didn't have that?

**Comment by Tjstretchalot** [comment]
I must be insane but I see it now; thank you!
