### ISSUE TITLE
Convert integration tests to golden files.

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#637]
We should convert existing infrastructure tests in `internal/providers/terraform/` to use `tftest.GoldenFileResourceTests`.  

Please comment on this issue when you begin a conversion so we can avoid conflicts.  

The basic steps to do this are:

1. Create a new sub directory of testdata for the resrourceL `mkdir internal/providers/terraform/aws/testdata/my_resource_test`
2.  Create `my_resource_test.tf` and `my_resource_test.usage.yml` in that directory.
3.  Populate those files with the tf and usage info in the existing `internal/providers/terraform/aws/my_resource_test.go`.  You may need to rename resources so they do not conflict since they will now all be in a single tf project.
4. Replace the existing test cases with a single golden file test case reference the testdata director:
```go
func TestMyResourceGoldenFile(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping test in short mode")
	}

	tftest.GoldenFileResourceTests(t, "my_resource_test")
}
```
5. Run the test with the `-update` flag to create `testdata/my_resource_test.golden`:
```sh
go test ./internal/providers/terraform/aws/my_resource_test.go -v -update
```
Take a look at `aws/dynamodb_table_test.go` for an example.

### Pro tip:
I made a little `copycreate.sh` shell script in my local testdata directory to speed up some of the drudgery of copy + paste:
```sh
mkdir ${NEW_RESOURCE_NAME}_test
cp dynamodb_table_test/dynamodb_table_test.tf ${NEW_RESOURCE_NAME}_test/${NEW_RESOURCE_NAME}_test.tf
cp dynamodb_table_test/dynamodb_table_test.usage.yml ${NEW_RESOURCE_NAME}_test/${NEW_RESOURCE_NAME}_test.usage.yml
echo -e "\nfunc GoldenFile(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip(\"skipping test in short mode\")
	}

	tftest.GoldenFileResourceTests(t, \"${NEW_RESOURCE_NAME}_test\")
}"
echo -e "\ngo test -v ../${NEW_RESOURCE_NAME}_test.go -run GoldenFile -update\n"
```
which would be run as `NEW_RESOURCE_NAME=my_resource ./copycreate.sh`

**Comment by aliscott** [comment]
I'm taking the following:

- [ ] acm_certificate
- [ ] acmpca_certificate_authority
- [ ] api_gateway_stage
- [ ] autoscaling_group
- [ ] cloudwatch_dashboard

**Comment by tim775** [comment]
I'll take:
- [ ] aws/secretsmanager_secret_test.go
- [ ] aws/sns_topic_subscription_test.go
- [ ] aws/sns_topic_test.go
- [ ] aws/sqs_queue_test.go
- [ ] aws/ssm_activation_test.go
- [ ] aws/ssm_parameter_test.go
- [ ] aws/vpc_endpoint_test.go
- [ ] aws/vpn_connection_test.go

**Comment by aliscott** [comment]
Next up I'll do:
- [ ] aws_cloudwatch_event_bus
- [ ] aws_cloudwatch_log_group
- [ ] aws_cloudwatch_metric_alarm
- [ ] aws_codebuild_project
- [ ] aws_config_config_rule

**Comment by ekifel** [comment]
I'll take Azure resources: 

- [ ] azurerm_app_service_certificate_binding
- [ ] azurerm_app_service_certificate_order
- [ ] azurerm_app_service_environment
- [ ] azurerm_app_service_plan
- [ ] azurerm_mariadb_server
- [ ] azurerm_mssql_database
- [ ] azurerm_mysql_server
- [ ] azurerm_postgresql_server

**Comment by sinabakh** [comment]
I'll work on:
- [ ] aws/config_configuration_recorder
- [ ] aws/config_organization_custom_rule
- [ ] aws/config_organization_managed_rule
- [ ] aws/dms
- [ ] aws/dx_connection

**Comment by ekifel** [comment]
I'll take: 

- [ ] aws_efs_file_system
- [ ] aws_eip
- [ ] aws_elasticache_cluster
- [ ] aws_elasticache_replication_group
- [ ] aws_elasticsearch_domain
- [ ] aws_elb
- [ ] aws_fsx_windows_file_system
- [ ] aws_kms_key

**Comment by sinabakh** [comment]
I'll take:

- [ ] aws/db_instance
- [ ] aws/docdb_cluster_snapshot
- [ ] aws/docdc_cluster
- [ ] aws/dx_gateway_assosiaction
- [ ] ebs_snappshot_copy

**Comment by ekifel** [comment]
I'll take:
Google: 

- [ ] google_cloudfunctions_function
- [ ] google_compute_address
- [ ] google_compute_disk
- [ ] google_compute_image
- [ ] google_compute_instance
- [ ] google_compute_machine_image
- [ ] google_compute_router_nat
- [ ] google_compute_snapshot

**Comment by tim775** [comment]
Taking:

- [ ] aws/ebs_volume_test.go
- [ ] aws/kms_key_external_test.go

**Comment by tim775** [comment]
Taking:

- [ ] google/container_cluster_test.go
- [ ] google/container_node_pool_test.go
- [ ] google/container_registry_test.go
- [ ] google/dns_managed_zone_test.go
- [ ] google/dns_record_set_test.go
- [ ] google/google_test.go
- [ ] google/kms_crypto_key_test.go

**Comment by ekifel** [comment]
I'll take: 

- [ ] google_monitoring_metric_descriptor
- [ ] google_pubsub_subscription
- [ ] google_pubsub_topic
- [ ] google_redis_instance
- [ ] google_sql_database_instance
- [ ] google_storage_bucket

**Comment by tim775** [comment]
> I'll take:
> 
> * [ ]  aws/eks_node_group
> * [ ]  aws/eks_cluster
 
It looks like eks_node_group is done.  It still has the old style test for the spot pricing case since those prices change too frequently to use golden files.
