### ISSUE TITLE
Add support for Kinesis Data Analytics

### ISSUE THREAD

**Issue by avst-dmartino** [infracost/infracost#639]
Terraform Resources:

aws_kinesis_analytics_application
aws_kinesisanalyticsv2_application

Pricing details:

https://aws.amazon.com/kinesis/data-analytics/pricing/?nc=sn&loc=3

**Comment by tim775** [comment]
`aws_kinesisanalyticsv2_application` should have:
- A `kinesis_processing_units` usage param displayed as `Processing (stream)` with unit `KPU`.
- A `Processing (orchestration)` cost with unit `KPU` determined based on the resources `runtime_environment`.  This should be 1 KPU for FLINK, and 2 KPU for Studio (when it is supported by terrfaform).  This should not be displayed for SQL runtimes.
- A `Running storage` cost with unit `GB` which is present for FLINK and Studio `runtime_environment`s.  The quantity is calculated as 50GB * the `kinesis_processing_units` usage param.
- A `durable_application_backup_gb` usage param displayed as `Backup` with unit `GB`, only present for FLINK and Studio `runtime_environment`s.

`aws_kinesisanalytics_application` only supports SQL so it should have:
- A `kinesis_processing_units` usage param displayed as `Processing (stream)` with unit `KPU`

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by tim775** [comment]
Note that `Processing (stream)` and `Processing (orchestration)` can both use the same cloud price (e.g. `"$0.11 per Kinesis Processing Unit-hour for Java applications"`).  The difference is that `Processing (stream)` is strictly a usage param, while `Processing (orchestration)` is an automatic charge that depends on `runtime_environment`.

**Comment by alikhajeh1** [comment]
@avst-dmartino just FYI this was released in v0.9.2 today.
