### ISSUE TITLE
Add support for Azure Container Registry

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#648]
Resources: azurerm_container_registry as the paid resource with these free resources: azurerm_container_registry_scope_map, azurerm_container_registry_token, azurerm_container_registry_webhook

Pricing: https://azure.microsoft.com/en-us/pricing/details/container-registry/

Cost components:
1. "Registry usage (sku_here)", units "days", set MonthlyQuantity to 30 so we assume a 30 day month. sku defaults to Classic according to the terraform-provider-azurerm code (which is the same as Basic).

2. For Premium sku, if there is are georeplication_locations or georeplications, then add a "Geo replication (X locations)" cost component where X is the number of locations (use the word "location" if there is only 1), units "days", set MonthlyQuantity to 30 so we assume a 30 day month.

3. "Storage (over XGB)", units "GB-months", with the following entry in the usage file. X should be the included storage for that sku. If the usage file value is above the "Included storage" then apply the Additional storage cost, otherwise this should show as a usage-based cost component.
`storage_gb: 150 # Total size of registry in GB.`

4. "Build vCPU", units "seconds" (in the pricing API, they have `"meterName" : "Task vCPU Duration"`), with the following entry in the usage file, convert the hrs to seconds for the calculation.
`monthly_build_vcpu_hrs: 150 # Monthly container build hours across all vCPUs.`

Terraform doesn't seem to support Dedicated agent pool yet so no need to include that.

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
