### ISSUE TITLE
Packing your windows file executable without .exe extension

### ISSUE THREAD

**Issue by JamesWoolfenden** [infracost/infracost#652]
Your release 0.8.6 for windows is packaged with no extension. Should be .exe

**Comment by alikhajeh1** [comment]
Thanks @JamesWoolfenden! I added the issue to our [main board](https://github.com/infracost/infracost/projects/2#card-60947485)

**Comment by alikhajeh1** [comment]
@JamesWoolfenden this'll be fixed in the next version

**Comment by alikhajeh1** [comment]
Shipped in v0.8.7, @JamesWoolfenden feel free to comment on https://github.com/infracost/infracost/issues/737 if there are other Windows output issues.
