### ISSUE TITLE
Add support for Azure IP address

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#665]
Pricing: https://azure.microsoft.com/en-us/pricing/details/ip-addresses/, ignore the "Basic (Classic)" column as Terraform only works with ARM (Azure Resource Manager)

Terraform resource: [azurerm_public_ip](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip) has 1 cost component: "IP address (type_here)" where type is "dynamic" or "static", units is "hours". The sku and allocation_method Terraform parameters can be used to detect which price applies.

Terraform resource: [azurerm_public_ip_prefix](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip_prefix) has 1 cost component, "IP prefix", units "hours".

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
