### ISSUE TITLE
Add support for Azure Load Balancer

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#666]
Pricing page: https://azure.microsoft.com/en-us/pricing/details/load-balancer/ (also available in the [Azure pricing calculator](https://azure.microsoft.com/en-gb/pricing/calculator/))

Terraform resources:

1. `azurerm_lb`:
if `sku` is Basic (the default), then this is a free resource (search contributing guide for "free resources:" to see how to handle that). Else show one cost component "Data processed", units "GB", with the following usage file parameter (meaning if the usage file param is not defined it should show "cost depends on usage"):
`monthly_data_processed_gb: 100 # Monthly inbound and outbound data processed in GB.`

2. For `azurerm_lb_rule` and `azurerm_lb_outbound_rule`, we don't have the ability to count the resources that are part of the same LB (we need to 2-way lookup, cc @aliscott for another instance of this use-case). So for now, show one cost component "Rule usage", units "hours" and use the "Additional rules" pricing (e.g. $0.01).

You can use the `ReferenceAttributes` feature (from contributing guide) and the `loadbalancer_id ` to get the location from that parent resource. If that's nil, then use the references feature with `resource_group_name` to get the location from that parent resource (search the code for `roup := d.References("resource_group_name")` for an example of this in the `azurerm_app_service_environment` resource).

3. free resources (add to registry.go for azure):
azurerm_lb_backend_address_pool
azurerm_lb_backend_address_pool_address
azurerm_lb_nat_pool
azurerm_lb_nat_rule
azurerm_lb_probe

**Comment by sbalajisivaram** [comment]
Thanks @alikhajeh1 for the details will take it up and keep you updated...

**Comment by sbalajisivaram** [comment]
@alikhajeh1, one quick question, when I look at the available regions for Load balancer services in mongo from cloud pricing api it shows three regions(Global, China & US Gov) but the actual pricing page(https://azure.microsoft.com/en-us/pricing/details/load-balancer/) does not show china region.

**Comment by alikhajeh1** [comment]
@sbalajisivaram Azure China has different pricing that we don't fully yet (we have to fetch the pricing from different endpoints vs the other regions). For now, you can use [this logic](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/nat_gateway.go#L23-L31), so we can try to future-proof it.

**Comment by aliscott** [comment]
@sbalajisivaram Looks like Azure China pricing is listed differently. I found this: https://www.azure.cn/en-us/pricing/details/load-balancer/.

**Comment by alikhajeh1** [comment]
@sbalajisivaram any update on this?

**Comment by NeverovDS** [comment]
If it’s ok with @sbalajisivaram, I can work on this

**Comment by alikhajeh1** [comment]
Thanks @NeverovDS! @sbalajisivaram there are plenty of more resources we want to add support for in the future :)

**Comment by alikhajeh1** [comment]
This was released in v0.9.2 today.
