### ISSUE TITLE
Add support for Azure Cosmos DB

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#669]
Terraform resources: azurerm_cosmosdb* (there are around 12 resources) but they all have the same pricing model mentioned in https://azure.microsoft.com/en-us/pricing/details/cosmos-db/#pricing so we can probably use the same logic between those resources

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@ekifel the master branch test logs are showing this, can you please check?
```
time="2021-05-26T17:14:14Z" level=warning msg="Multiple products found for azurerm_cosmosdb_cassandra_keyspace.serverless Provisioned throughput (serverless), using the first product"

```
