### ISSUE TITLE
Add support for Azure Databricks

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#671]
Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace
Pricing details: https://azure.microsoft.com/en-us/pricing/details/databricks/

We can support the Pay as you go pricing for DBUs only initially (not the VM or storage costs as those require other non-Azure terraform resources to be processed). Use the Terraform `sku` field to find which pricing applies, return `NoPrice=true,IsSkipped=true` if the sku is trial as those are free. There should be three cost components, with the following usage file params:
- "All-purpose compute DBUs", units "DBU-hours"
- "Jobs compute DBUs", units "DBU-hours"
- "Jobs light compute DBUs", units "DBU-hours"

Usage file should have (if any are not set, show usage depends on costs...):
```
monthly_all_purpose_compute_dbu: 500 # Monthly number of All-purpose Compute Databricks Units (DBUs).
monthly_jobs_compute_dbu: 1000 # Monthly number of Jobs Compute Databricks Units (DBUs).
monthly_jobs_light_compute_dbu: 2000 # Monthly number of Jobs Light Compute Databricks Units (DBUs).
```

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!
