### ISSUE TITLE
Add support for Azure Firewall

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#672]
Terraform resources: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall. The other 5 azurerm_firewall* resources should be added as free resources
Pricing details: https://azure.microsoft.com/en-us/pricing/details/azure-firewall/

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it! :)

**Comment by alikhajeh1** [comment]
@ekifel I noticed that the `attributes.skuName` mongo field has "Secured Virtual Hub" and "Premium Secured Virtual Hub" options. Can you please send a new PR that checks if `azurerm_firewall.virtual_hub` is set? if so, then these two options can be used instead of the existing ones. That should cover the "Azure Firewall with Secured Virtual Hub" [pricing section](https://azure.microsoft.com/en-us/pricing/details/azure-firewall/#pricing) - the prices are all the same just now but this new logic would ensure that if the prices change, the code works as expected
