### ISSUE TITLE
Add support for Azure NAT Gateway

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#673]
Terrafom resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/nat_gateway
Pricing details: https://azure.microsoft.com/en-us/pricing/details/virtual-network/#pricing > NAT Gateway

Cost components:
- "NAT gateway", unit "hours".
- "Data processed", unit "GB", usage file parameter: `monthly_data_processed_gb: 10 # Monthly data processed by the NAT Gateway in GB.`

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@NeverovDS the master branch test logs are showing this, can you please check?
```
time="2021-05-26T17:15:22Z" level=warning msg="Multiple products found for azurerm_nat_gateway.my_gateway NAT gateway, using the first product"
time="2021-05-26T17:15:22Z" level=warning msg="Multiple products found for azurerm_nat_gateway.my_gateway Data processed, using the first product"
time="2021-05-26T17:15:22Z" level=warning msg="Multiple products found for azurerm_nat_gateway.my_gateway2 NAT gateway, using the first product"
time="2021-05-26T17:15:22Z" level=warning msg="Multiple products found for azurerm_nat_gateway.my_gateway2 Data processed, using the first product"
```

**Comment by alikhajeh1** [comment]
Fixed warnings in https://github.com/infracost/infracost/commit/e40eb392757a9e47c6844424a9265ddb07c42444
