### ISSUE TITLE
Add support for Azure Logic App Integration Service Environments

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#674]
Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/integration_service_environment
Pricing page: https://azure.microsoft.com/en-us/pricing/details/logic-apps/ > Integration Service Environment

Cost components:
Split the terraform "sku_name" property on `_` to find out if the type is Developer or Premium and multiply the scale number (also known as capacity) by the price where applicable. Defaults to `Developer_0`.
- "Base units", units "hours"
- "Scale units", units "hours", should only show for premium

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
