### ISSUE TITLE
Add Azure App Service Certificate Binding (for hostname)

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#682]
This ticket has 2 parts:

1. the existing `azurerm_app_service_certificate_binding` resource needs to be updated to use the location from its `certificate_id` reference (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_certificate, which has location as required). Current it's using region=Global (the prices look to be the same so it's best to use the location-specific one in case prices change).

2. a new `azurerm_app_service_custom_hostname_binding` [resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding) should be added. You can copy the code from the above resource (one cost component "IP SSL certificate", unit is "months" - only show if `ssl_state=IpBasedEnabled`). However, the code should be changed a little so:
a) resource_group_name reference is used to get the location.
b) if ssl_state is not set, then assume it's free and return "NoPrice=true, IsSkipped=true"

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!
