### ISSUE TITLE
Add support for AWS Step functions.

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#702]
Terraform providers a resource `aws_sfn_state_machine` for AWS Step functions. Infracost should be able to take the workflow type & then calculate the cost based on the state machine definition. 

Link to pricing page.
https://aws.amazon.com/step-functions/pricing/

**Comment by praveenghuge** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
Thanks @praveenghuge, https://calculator.aws/#/createCalculator/StepFunctions has clues as to what our usage file params could be, the `type` terraform field can tell us which pricing applies.

**Comment by alikhajeh1** [comment]
> then calculate the cost based on the state machine definition.

@robh007 do you mean we can parse the aws_sfn_state_machine.definition JSON to calculate something? I haven't used the resource but I see that @praveenghuge has added a usage file param (which is the same thing that the AWS calculator does).

**Comment by robh007** [comment]
> > then calculate the cost based on the state machine definition.
> 
> @robh007 do you mean we can parse the aws_sfn_state_machine.definition JSON to calculate something? I haven't used the resource but I see that @praveenghuge has added a usage file param (which is the same thing that the AWS calculator does).

Yes - not sure how complex it would be. But I think you can take the state definition & the workflow type and work out how many transitions occur, you're billed based on these calculations. I'm happy to help if required.

**Comment by alikhajeh1** [comment]
The basic form of this was merged as part of https://github.com/infracost/infracost/pull/704 / https://github.com/infracost/infracost/pull/720. Going to close this ticket, feel free to create another ticket with the advanced version details to calculate the transitions (I think there was some Slack discussion on it too that might be useful in the new ticket).

**Comment by alikhajeh1** [comment]
Shipped in v0.8.7
