### ISSUE TITLE
Add support for Azure API Management

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#705]
Pricing: https://azure.microsoft.com/en-us/pricing/details/api-management/
Terraform resources: azurerm_api_management* (there's a lot of resources but most are free)

**Comment by tim775** [comment]
Terraform resource `azurerm_api_management` should have

- For all but the 'Consumption' tier: `API management (<tier>)` with unit `units` where tier is determined from the first part of the `sku_name`  and the quanity of units from the second part of the `sku_name` (see the terraform docs).
- Add a `monthly_api_calls` usage parameter displayed as `API management (consumption over 1M)` with unit `1M calls`.  When tier is not Consumption, this key should be hidden.  If the key is not provided, we should display 'Monthly cost depends on usage'.  Nothing should be shown if the key is provided and their is no charge

I don't see how to determine if there is a 'self hosted gateway' from the .tf, so I guess we should add a 'monthly_self_hosted_gateway_count` usage paramter displayed as `Self hosted gateway` with unit `gateways`

Other `azurerm_api_management*` resources should be free.

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!
