### ISSUE TITLE
Add support for Azure Automation

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#707]
Pricing details: https://azure.microsoft.com/en-us/pricing/details/automation/
Terraform resources: azurerm_automation* (there's quite a lot of resources but most are free)

**Comment by tim775** [comment]
@alikhajeh1 I had trouble wrapping my head around this, but I think the best option is:

For `azurerm_automation_account `:
- A `monthly_job_run_ mins` usage parameter displayed as `Job run time (over 500 mins)` with unit `minutes`.
- A `monthly_watcher_hours` usage parameter displayed as `Watchers (over 744 hours)` with unit `hours`.
- A `monthly_non_azure_configuration_node_count` usage parameter displayed as `Non-azure configuration nodes (over 5)` with unit `nodes`.

All other resources would be free.

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@NeverovDS maybe go for #709 until we finalize the details on this one? I've not had a chance to look into Tim's comments

**Comment by NeverovDS** [comment]
@alikhajeh1 Sure!

**Comment by alikhajeh1** [comment]
@tim775 how about this?

1. `azurerm_automation_job_schedule` (since a runbook by itself doesn't seem to run):
    - Cost component "Job run time" with unit "minutes", usage file param `monthly_job_run_mins: 0 # Monthly number of job run minutes.`.
    - Cost component "Watchers" with unit "hours", usage file param `monthly_watcher_hours: 0 # Monthly number of watcher hours.`

2. `azurerm_automation_dsc_configuration` and `azurerm_automation_dsc_nodeconfiguration` each have:
    - Cost component "Non-azure config nodes" with unit "nodes", and usage file param `non_azure_config_node_count: 0 # Number of non-Azure configuration nodes.`

3. `azurerm_automation_account` would have all 3 of the above cost components and their usage file params to show users that the account itself has these prices. But by default since the usage file params are 0, it doesn't show costs.

All other resources would be free.

**Comment by tim775** [comment]
That seems good except I can't say if a 'watcher' makes sense on a job schedule or not.  

I guess I wasn't sure how a "one-time" run of a runbook would be represented in tf but I think have the ability to put `monthly_job_run_mins` on `azurerm_automation_account` is sufficient to handle that.

**Comment by alikhajeh1** [comment]
Good point, I can't tell from https://docs.microsoft.com/en-us/azure/automation/automation-scenario-using-watcher-task either, maybe it's not possible to create watcher in TF yet as I don't see anything in their docs for it. So we can do this:

1. `azurerm_automation_job_schedule` (since a runbook by itself doesn't seem to run):
    - Cost component "Job run time" with unit "minutes", usage file param `monthly_job_run_mins: 0 # Monthly number of job run minutes.`

2. `azurerm_automation_dsc_configuration` and `azurerm_automation_dsc_nodeconfiguration` each have:
    - Cost component "Non-azure config nodes" with unit "nodes", and usage file param `non_azure_config_node_count: 0 # Number of non-Azure configuration nodes.`

3. `azurerm_automation_account` would have the above 2 cost components and their usage file params to show users that the account itself has these prices. But by default since the usage file params are 0, it doesn't show costs.
It should also have this 3rd one:
    - Cost component "Watchers" with unit "hours", usage file param `monthly_watcher_hours: 0 # Monthly number of watcher hours.`

All other resources would be free.

**Comment by alikhajeh1** [comment]
@NeverovDS this is ready

**Comment by NeverovDS** [comment]
@alikhajeh1 Strarting work on it!)

**Comment by alikhajeh1** [comment]
Released in v0.9.1
