### ISSUE TITLE
Add support for Azure Kubernetes Load Balancer and HTTP Application Routing

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#710]
The [azurerm_kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster), which Infracost supports, has a `load_balancer_sku` param. Once we support the [Azure LB resource](https://github.com/infracost/infracost/issues/666) is merged, we can update the AKS resource to include costs of the LB if that param is used.

**Comment by aliscott** [comment]
I've added some details for the load balancer and DNS pricing for AKS here: https://github.com/infracost/infracost/issues/591#issuecomment-829163605.

The DNS pricing applies if `http_application_routing.enabled == true`. [This page](https://docs.microsoft.com/en-us/azure/aks/http-application-routing) contains a bit more detail, but basically when this option creates a new DNS Zone, so any pricing we have for DNS Zones should apply here.

**Comment by NeverovDS** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
Released in v0.9.2 today.
