### ISSUE TITLE
Add support for Azure Postgres Flexible Server

### ISSUE THREAD

**Issue by JanCallewaert-TomTom** [infracost/infracost#722]
Terraform has recently added support: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server.

Pricing details: https://azure.microsoft.com/en-us/pricing/details/postgresql/flexible-server/#pricing

**Comment by alikhajeh1** [comment]
Thanks @JanCallewaert-TomTom! Seems like `create_mode` can be:
- `default`, which [requires](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/postgres/postgresql_flexible_server_resource.go#L224-L232) `sku_name` and `storage_mb` params to be set (which we can use for cost calcs). 
- `PointInTimeRestore`, which means we can use the `source_server_id` to find the above params from that source resource.

What's confusing is that there is no default value for `create_mode` itself (per the docs or the code). I guess we should just assume "default" is the default value for `create_mode`? Maybe it's something they'll change as that resource seems to be in preview?

**Comment by JanCallewaert-TomTom** [comment]
Do you require some more information or support from me with regards to this?

**Comment by alikhajeh1** [comment]
@JanCallewaert-TomTom if you created this resource on Azure with TF, can you possibly check if a new DB was created when create_mode was left undefined?

**Comment by JanCallewaert-TomTom** [comment]
I checked with my colleagues. We didn't specify a value for `create_mode` and a new database was created. Is this what you need?

**Comment by alikhajeh1** [comment]
Yep - thanks! I've updated my previous description

**Comment by aliscott** [comment]
Here are the details for the cost components we should add. This is very similar to the [`azurerm_postgresql_server`](https://github.com/infracost/infracost/issues/572) resource.

* Compute (GP_Standard_D2s_v3) - unit is hours. The instance type can be taken from `sku_name`
* Storage - unit is GB-months. The quantity should be based on `storage_mb`. The price is based on the tier part of the `sku_name`.
* Additional backup storage - unit is GB-months. Usage-based, usage key should be `additional_backup_storage_gb`. The price is based on the tier part of the `sku_name`.

**Comment by ekifel** [comment]
@alikhajeh1, I want to work on it

**Comment by alikhajeh1** [comment]
This has been merged and will be released in the next version (this week).

**Comment by alikhajeh1** [comment]
@JanCallewaert-TomTom this was released in v0.9.0 (released just now) - let us know if you notice any issues with it!

**Comment by JanCallewaert-TomTom** [comment]
Thanks @alikhajeh1, I will check it out next week when my colleagues are back.

**Comment by JanCallewaert-TomTom** [comment]
This works perfectly. Great job!
