### ISSUE TITLE
Review/fix case sensitive Terraform inputs

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#729]
- [x] Google
- [x] Azure
- [x] AWS

Terraform ignores case sensitivity in most cases for AWS, GCP and Azure (I haven't checked other providers). The aim of this GH issue is to review and update all existing cloud resources to ensure that:

1. case-insensitive string comparison are used, e.g.:
Bad: `input == "large"`
Good: `strings.ToLower(input) == "large"`
We might be able to grep for something like `== "` to review/fix them all.

2. case-insensitive `Value` or `ValueRegex` price filters are used for any user input, e.g.:
Bad: `{Key: "virtualInterfaceType", ValueRegex: strPtr(fmt.Sprintf("/%s/", virtualInterfaceType))},`
Good: `{Key: "virtualInterfaceType", ValueRegex: strPtr(fmt.Sprintf("/%s/i", virtualInterfaceType))},  # notice the `/i` in the regex`
We might be able to grep for something like `, Value` to review/fix them all.

As part of this issue, we should also update the contributing guide.

**Comment by krishnaindani** [comment]
Is this issue open to take? I am new and would like to learn and contribute since it is tagged as the good first issue.

**Comment by alikhajeh1** [comment]
@krishnaindani sure! Thanks for offering to help.

**Comment by krishnaindani** [comment]
> @krishnaindani sure! Thanks for offering to help.

My pleasure and thank you for giving me a chance to work on it. I will go through a bit and may ask some questions before getting started.

**Comment by krishnaindani** [comment]
While going through code I see there is a lot of comparisons in the internal/providers directory where it is something like let's say `input == "LARGE"`.  Do we need to fix them all with strings.ToLower(input) == "large" to convert everything to lower case for comparison

**Comment by alikhajeh1** [comment]
@krishnaindani yep, the `internal/providers/terraform` contains the files that need to be reviewed and fixed. I think the tests should not need to be changed and they should continue to pass, but feel free to post here if you find a test that looks like it needs to be changed.

**Comment by krishnaindani** [comment]
> @krishnaindani yep, the `internal/providers/terraform` contains the files that need to be reviewed and fixed. I think the tests should not need to be changed and they should continue to pass, but feel free to post here if you find a test that looks like it needs to be changed.

Thanks. Yeah from the few changes with the aws I don't see the changes are required for the tests. But will continue to check more on AWS and on GCP and azure as well.

**Comment by krishnaindani** [comment]
@alikhajeh1 I have pr in which I have updated the code for the first which is string comparison. But while going through the second one which is `Value` or `ValueRegex` filters, I have few questions. From what I see in the regex package and what I understand, adding `i` will do case insensitive comparison, correct? For example, if I take this `{Key: "usagetype", ValueRegex: strPtr("/PaidPrivateCA/")}` and update to `{Key: "usagetype", ValueRegex: strPtr("/paidprivateca/i")}`, will it be correct comparison? Would you be able to provide an example when using `Value` instead of `ValueRegex`? Thank you.

**Comment by alikhajeh1** [comment]
> From what I see in the regex package and what I understand, adding i will do case insensitive comparison, correct? For example, if I take this {Key: "usagetype", ValueRegex: strPtr("/PaidPrivateCA/")} and update to {Key: "usagetype", ValueRegex: strPtr("/paidprivateca/i")}, will it be correct comparison?

Correct! However, in your example above, no variables are being used, thus there is no need to add the `/i`. If it was `{Key: "usagetype", ValueRegex: strPtr(fmt.Sprintf("/%s-PaidPrivateCA/", userVariable))}` then the `/i` would be needed as we do not know if `userVariable` will have lower or upper case letters.

> Would you be able to provide an example when using Value instead of ValueRegex? Thank you.

Sure, here are two examples:

1. In [this example](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/storage_bucket.go#L243), no changes are needed since the filter is a hard-coded string so we are sure that the case-sensitivity is ok.

2. In [this example](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/compute_instance.go#L88), a change is required since `machineType` is a variable that users control. The fix would be to change that line to `{Key: "machineType", ValueRegex: strPtr(fmt.Sprintf("/%s/i", machineType))}` (notice the `/i`).

**Comment by krishnaindani** [comment]
> > From what I see in the regex package and what I understand, adding i will do case insensitive comparison, correct? For example, if I take this {Key: "usagetype", ValueRegex: strPtr("/PaidPrivateCA/")} and update to {Key: "usagetype", ValueRegex: strPtr("/paidprivateca/i")}, will it be correct comparison?
> 
> Correct! However, in your example above, no variables are being used, thus there is no need to add the `/i`. If it was `{Key: "usagetype", ValueRegex: strPtr(fmt.Sprintf("/%s-PaidPrivateCA/", userVariable))}` then the `/i` would be needed as we do not know if `userVariable` will have lower or upper case letters.
> 
> > Would you be able to provide an example when using Value instead of ValueRegex? Thank you.
> 
> Sure, here are two examples:
> 
> 1. In [this example](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/storage_bucket.go#L243), no changes are needed since the filter is a hard-coded string so we are sure that the case-sensitivity is ok.
> 2. In [this example](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/compute_instance.go#L88), a change is required since `machineType` is a variable that users control. The fix would be to change that line to `{Key: "machineType", ValueRegex: strPtr(fmt.Sprintf("/%s/i", machineType))}` (notice the `/i`).

That makes sense. Thanks.

**Comment by alikhajeh1** [comment]
@krishnaindani any update on this? We can take the old PR and run with it as it looked pretty close - or maybe a send a partial PR that fixes some of them and we can do the rest.

**Comment by krishnaindani** [comment]
> @krishnaindani any update on this? We can take the old PR and run with it as it looked pretty close - or maybe a send a partial PR that fixes some of them and we can do the rest.

My apologies, I got caught up with something past sometime. I am planning to get ready with the changes by the EOW, does that works?

**Comment by alikhajeh1** [comment]
Thanks @krishnaindani - that would be awesome! It can go into next week's release.

**Comment by krishnaindani** [comment]
Great, Thanks for waiting!!

**Comment by krishnaindani** [comment]
@alikhajeh1 should I split in three different PR's one for azure, google, and aws each. That way it would be easier for the review and testing as well. What are your thoughts?

**Comment by alikhajeh1** [comment]
@krishnaindani good idea - smaller PRs are easier to review/test

**Comment by krishnaindani** [comment]
Thank you for updating the task list, will make azure next. Last time you were mentioning you can provide me some temporary credentials for Azure, would you still be able to do that?

**Comment by alikhajeh1** [comment]
@krishnaindani thanks for that! Since this is a one-off, I can just run the tests against the Azure PR and paste in any issues if that's ok with you?

**Comment by krishnaindani** [comment]
> @krishnaindani thanks for that! Since this is a one-off, I can just run the tests against the Azure PR and paste in any issues if that's ok with you?

Sounds good, that works.

**Comment by krishnaindani** [comment]
I have noticed this while running lint stage. 
```
➜ make lint
golangci-lint run
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
```

Do you plan to migrate to revive? I can work on this next if you plan to. @alikhajeh1

**Comment by alikhajeh1** [comment]
@krishnaindani thanks for sticking with this issue through completion! 

Re golint, @aliscott WDYT?

**Comment by krishnaindani** [comment]
> @krishnaindani thanks for sticking with this issue through completion!

Thank you so much for your patience and for letting me work on this. Looking forward to contributing more to this project. Let me know if there is any other work I can pick up. I will keep eye on board though.
