### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by chenrui333** [infracost/infracost#73]
FYI, I have filed a pending PR for adding this utility into homebrew-core, https://github.com/Homebrew/homebrew-core/pull/60777

Thanks!

**Comment by alikhajeh1** [comment]
That's awesome! Thank you :) We can update the README and https://www.infracost.io/docs/#installation when it's available on homebrew. Just FYI that I left a few comments on https://github.com/Homebrew/homebrew-core/pull/60777 to see if we can bump that to the latest version (v0.5.1).
