### ISSUE TITLE
Rename JSON format's projects to projectResults

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#735]
We have internal concepts of:
1. runs: each time the CLI runs. This is similar to what Terraform Cloud call runs.
2. projects: a project contains the infra-as-code and any [configs](https://www.infracost.io/docs/multi_project/config_file/) (e.g. the terraform_binary version to be used) that are needed to run that project through Infracost.
3. project results: the JSON output of a project run. We currently include these in the `projects` array in our JSON format but it should be renamed to something like `projectResults` so it's clear that this is the results of a project run, not the project itself.

**Comment by aliscott** [comment]
@alikhajeh1 should we also update any of the following for v0.9?
* Rename `metadata` to `projectMetadata`
* Move `path` into `projectMetadata`
* Add `name` that creates a name from the repo URL/path?

**Comment by aliscott** [comment]
In the end we decided to do this only for v0.9. We weren't sure about the `projectResults` change so thought it was best to leave it as is just now.

* Move path into metadata
* Add name that creates a name from the repo URL/path?
