### ISSUE TITLE
Check/fix Windows color output

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#737]
https://www.infracost.io/docs/ > Windows tab asks users to run with `--no-color`. The aim of this ticket is to investigate and fix terminal color issues we have with Windows. We can provide access to a Windows remote desktop to enable the debugging/testing of this. We can check what the `gh` CLI tool does on Windows.

If it's not easy to fix the color/animations looking odd in Windows, we can disable those (the same as what we tell users).

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by ekifel** [comment]
@alikhajeh1 it looks like color output works fine, only special symbols is broken

**Comment by alikhajeh1** [comment]
Thanks for checking @ekifel, @aliscott would a work-around be not show the symbols in windows?

**Comment by aliscott** [comment]
Yes, but @ekifel can you check if https://github.com/infracost/infracost/pull/749 fixed it? It fixed this issue: https://github.com/briandowns/spinner/issues/110

**Comment by ekifel** [comment]
@aliscott, I checked this again, CMD and PowerShell have the same results, but in VSCode's terminal everything is fine.
![image](https://user-images.githubusercontent.com/62132367/120621178-15279500-c477-11eb-98de-d34db5521e6a.png)
![image](https://user-images.githubusercontent.com/62132367/120621255-283a6500-c477-11eb-9dc9-eb074b329d7d.png)

**Comment by aliscott** [comment]
Can we detect if the shell is CMD or PowerShell using `echo $0`? If not then I think we should just disable the spinners for windows.

**Comment by alikhajeh1** [comment]
@ekifel any update on this?
