### ISSUE TITLE
Error parsing terraform locals

### ISSUE THREAD

**Issue by karancode** [infracost/infracost#75]
I am trying to run `infrascost` for some of my terraform resources and I am getting below error : 
```
➜ infracost --tfdir terraform/
⠋ Calculating costs… ERROR There are some problems with the configuration, described below.
ERROR
ERROR The Terraform configuration must be valid before initialization so that
ERROR Terraform can determine which modules and providers need to be installed.
ERROR
ERROR Error: Error parsing /karan/Desktop/terraform/data.tf: At 85:25: unexpected token while parsing list: IDENT
ERROR
ERROR
exit status 1
➜
```

The code in `data.tf` at line 85 is `locals` defining some subnet id, etc. shown below:  
```hcl
locals {
  private_subnets    = [data.aws_subnet.private-1a-prod, data.aws_subnet.private-1c-prod, data.aws_subnet.private-1d-prod]
  private_subnet_ids = local.private_subnets.*.id
  private_subnet_azs = local.private_subnets.*.availability_zone
}
```

I am using terraform version `0.12.16` & aws provider version `2.51.0`

Could you please help with this issue?

**Comment by aliscott** [comment]
@karancode thank you! This error is from the terraform binary when it runs `terraform init`. I'm not able to reproduce this with terraform v0.12.16. The error looks the same as the error you would get using terraform v0.11 with the new list syntax that was introduced in v0.12.

Infracost will use the default terraform binary in your path, but you can override it by specifying the `TERRAFORM_BINARY` env var, e.g.:
```
TERRAFORM_BINARY=/path/to/terraform_0.12.6 infracost --tfdir terraform/
```

Can you make sure that `terraform init` is working correctly for you and that the correct binary 0.12.16 is being used?

**Comment by karancode** [comment]
hi @aliscott thank you so much for the reply. I was using alias for the my terraform binary.. setting up `TERRAFORM_BINARY` works well. 
Thanks again!
