### ISSUE TITLE
Azure MSSQL database should show license cost by default

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#758]
When launching a `azurerm_mssql_database` with Terraform the SQL license is included by default.

Infracost currently only includes the SQL license cost if `license_type == LicenseIncluded`, but we should update this to be the default and only exclude it if `license_type == BasePrice`.

Relevant code: https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/mssql_database.go#L110-L115

**Comment by ekifel** [comment]
@alikhajeh1, I want to do it
