### ISSUE TITLE
Use multiple methods to find Azure region (including a default)

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#763]
The aim of this ticket is to review/update all Azure resources to set a default region and use 4 ways to override that default. The default ensures that we never panic/crash. Since cloud prices different in small way between regions, and we show cost estimates (not 100% accurate costs), it seems better to use a default region price if none of the 4 methods work, vs showing nothing and skipping the resource.

If possible, it would be great to have this logic in a function that all Azure resources can re-use.

---

Set the following as as the first line in the resource function, this sets the `region` variable to the default we have set for Azure (currently it's "eastus" defined in `defaultProviderRegions`, but we might enable users to define this default in the usage file).
```
region := d.Get("region").String()
```

After that, use this logic to set the region:
1. if resource has a `location` TF param, set the `region` variable to that. Use the word "region" so it's consistent with what we call it in AWS/GCP and the pricing filters (Azure also sometimes call it region).
2. else if the resource has a parent Terraform resource that has location,  set `region` to that. E.g. `azurerm_mssql_database` points to `azurerm_mssql_server`, which has location.
3. else if resource has a resource group, set `region` to that.
4. else `log.Warnf("Using %s for resource %s as its 'location' property could not be found.", region, d.Address)` and continue.

**Comment by alikhajeh1** [comment]
I updated the contributing docs:
https://github.com/infracost/infracost/commit/6582db38c193e0a978c68deba3755a630e4ec3b1

**Comment by PatMyron** [comment]
https://github.com/infracost/infracost/blob/6ccdc06ce0c89ca55a4927396898f168e0d033bb/internal/providers/terraform/parser.go#L19-L23

Interested to know how the current default regions were chosen, tried looking into the best default regions / instance types a couple years ago here:

https://github.com/patmyron/cloud

**Comment by alikhajeh1** [comment]
Good question! @aliscott picked those; I think we picked the region that had the most number of services. The list is a fall-back mechanism; if there is no other way to find the region from the resource, we use this and log a warning since it's an assumption we make.

The link you posted does bring-up another question: what if the default region doesn't have prices for the resource being estimated? In that case, the CLI logs a warning showing that no prices could be found.

Our hope is that users report these warnings to us so we can investigate them, however, currently that requires the user to run with `--log-level=warn` so we could do a better job of highlighting our assumption in the actual CLI output.

**Comment by aliscott** [comment]
@PatMyron what did you find and do you have any recommendations?

One way we could do it by using what the cloud vendors use as the default for their pricing pages/calculators. So that would be:
AWS: us-east-2
Azure: westus
Google: us-central1
