### ISSUE TITLE
How should Infracost CI/CD integrations be versioned?

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#777]
## Background
Users should consider 3 versions when using Infracost:
1. Infracost CLI version: `infracost --version` shows this. We follow semantic versioning. Our current thinking is influenced by [the HashiCorp Requirements for a 1.0 Release](https://www.hashicorp.com/resources/the-path-to-terraform-1-0), thus we've had many minor and patch versions but no major versions yet.
2. Infracost CI/CD integration version: the version of the integration scripts or CI template being used. Depends on the integration being used.
3. Terraform/Terragrunt CLI version: only considered when running Infracost with a non-plan-json option, since that requires Infracost to run Terraform/Terragrunt internally.

The Infracost JSON format, usage file, and config file are also versioned, but those are outside the scope of this discussion.

## Status quo
There are currently 7 CI/CD integrations:
1. GitHub Action, GitLab CI Template, CircleCI Orb, BitBucket Pipeline, Jenkins: by default, these point to the `infracost/infracost:latest` Docker tag, which uses the latest released version of the Infracost CLI. Users can change the integration yaml to point to another tag. This image comes with [versions](https://www.infracost.io/docs/integrations/environment_variables#cicd-integrations) of Terraform and Terragrunt too, since without that the image can only be used with plan-json option.
2. Atlantis: the `infracost/infracost-atlantis:latest` Docker tag is used in our docs, and that uses the latest released version of Infracost and Atlantis. Since this image is built from the latest release of the Atlantis image, it comes with the Terraform version that Atlantis includes. This image also uses the [master-branch version](https://github.com/infracost/infracost/blob/master/scripts/ci/atlantis_diff.sh) of the `atlantis_diff.sh` script.
3. Azure DevOps: this installs the latest release of the Infracost CLI and the [master-branch version](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh) of the `diff.sh` script. This is because I couldn't find an easy way to use the `infracost/infracost:latest` Docker images with this integration.

## What should we do next?
The status quo's key benefit is that users automatically get the latest version of Infracost, which is important as it usually has more resource coverage. Upgrading CI/CD pipelines can be time-consuming given that companies often have many pipelines.

Its key weakness of the status quo is that we risk breaking CI/CD pipelines when: a) we bump-up the minor version of the Infracost CLI, **and** b) we can't find a way to keep backward compatibility. This has happened once so far, in which case we showed deprecation warnings for a few versions, then removed the deprecated features with the minor version bump.

Another weakness of the status quo for the Docker-based CI/CD integrations is that the image size keeps increasing as we add more Terraform versions, which can slow down runs due to the image pull time. Most CI/CD platforms heavily cache things so perhaps this is not a significant issue yet - we're already up to a few hundred MBs.

### Over to you

We'd appreciate feedback from anyone, specially if you have used one of the integrations or ran into issues during upgrades.

**Comment by sushant-pradhan** [comment]
@alikhajeh1 I exactly had the same problem outlined above. Every time there is a upgrade, I have to upgrade my pipeline executors and run a regression test. A bit of a hassle. 
I have one thought: can we keep the cli and core rules/engine separate? cli will just be a shell to call the core engine (default point to latest rules/engine but can be downgraded/pinned if required).

Inspired from [gitleaks ](https://github.com/zricethezav/gitleaks)implementation where the secret rules can be externalized and loaded at runtime (without having to upgrade the cli)

**Comment by alikhajeh1** [comment]
@sushant-pradhan great idea! This is also similar to how Terraform has split the providers from the CLI itself.

**Comment by alikhajeh1** [comment]
In the new [Infracost GitHub Actions](https://github.com/infracost/actions) repo (which we'll release/announce soon) we've changed the way the CI/CD integrations work to address three issues mentioned in this GitHub issue:
1. **Reduce Docker image size**: The Infracost CLI setup has been split out from the Terraform/Terragrunt setup. This solves the Docker image size increasing over time and enables other GitHub Actions (such as the official [terraform-setup](https://github.com/hashicorp/setup-terraform) action) to be used to install required versions of Terraform/Terragrunt.
2. **Safe version upgrades**: the Infracost [setup action](https://github.com/infracost/actions/tree/master/setup) has a `version` field for the CLI, which supports [Semver Ranges](https://www.npmjs.com/package/semver#ranges). So instead of a [full version](https://github.com/infracost/infracost/releases) string, you can use `0.9.x`. This enables you to automatically get the latest backward compatible changes in the 0.9 release (e.g. new resources or bug fixes) without worrying about CI/CD pipelines breaking.
3. **Versioning for the integration itself**: the integration has a version, `infracost/action@v1`, which also supports Semver. So users can use v1 to get backward compatible updates for the integration (e.g. bug fixes).

@sushant-pradhan the provider model (where resource mappings are split from the CLI core) is still in the back of our minds, I'm not sure when we'll get bandwidth to work on it but the above changes should make upgrades less painful whilst enabling us to move fast to experiment with new things.

Closing the issue but looking forward to hearing the community's feedback!
