### ISSUE TITLE
Add support for Azure Cognitive Search Service

### ISSUE THREAD

**Issue by bgrainger** [infracost/infracost#790]
Pricing: https://azure.microsoft.com/en-us/pricing/details/search/#pricing
Terraform: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service

**Comment by tim775** [comment]
Terraform resource azurerm_search_service should have

- An hourly charge based on the sku and number of units, displayed as `Search usage (<sku (capitalized)>, <number of units> unit)` with unit `hours` where the number of units is calculated based as `replica_count` * `partition_count` with a default of 1. The number of hours should be 730 * number of units.  
- A `monthly_images_extracted` usage param displayed as `Image extraction (<tier>)` with unit `1000 images` where `tier` is `first 1M`, `next 4M`, or `over 5M`.  As usual, if the usage parameter is not set the first tier should be displayed with the `Monthly cost  depends on usage:...` message.  If it is set, only tiers incurring a charge should be displayed.

Semantic Search looks like it's still in preview and Cognitive Search seems to be billed under Cognitive Services, so it seems like we can leave these out for now.

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
Released in v0.9.1 released today
