### ISSUE TITLE
Add support for Azure Redis Cache

### ISSUE THREAD

**Issue by bgrainger** [infracost/infracost#791]
Pricing: https://azure.microsoft.com/en-us/pricing/details/cache/#pricing
Terraform: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache

**Comment by tim775** [comment]
Terraform resource azurerm_redis_cache should have
- An hourly charge based on the sku_name and capacity, displayed as `Cache usage (<sku_name>_<family><capacity>, <number of nodes> node)` and unit `hours` where the quantity is 730 * number of nodes.  For sku_name `Basic` `<number of nodes>` is `.  For Standard it is 2.  For Premium number of nodes defaults to 2.  If `replica count` is set number of nodes is 1 + replica count.  If `shard_count` is set it is 2 * shard_count.

It doesn't look like terraform supports Enterprise or Enterprise Flash yet, so I guess we can leave them out for now.

azurerm_redis_firewall_rule and azurerm_redis_linked_server should be free resources.

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@bgrainger thanks for creating this issue and https://github.com/infracost/infracost/issues/790 - these resource were added in v0.9.1 released today - plz add a comment if you notice any issues with them!
