### ISSUE TITLE
Add support for Azure Database for MySQL Flexible Server

### ISSUE THREAD

**Issue by bgrainger** [infracost/infracost#792]
Resource information: https://docs.microsoft.com/en-gb/azure/mysql/flexible-server/
Pricing information: https://azure.microsoft.com/en-gb/pricing/details/mysql/flexible-server/

### Paid resource

`azurerm_mysql_flexible_server`

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server

Cost components:

| Name | Unit | Usage param | Notes|
| -- | -- | -- | -- |
| `Compute (<sku name>)` | `hours` | | ex. `Compute (B_Standard_B1ms)` |
| `Storage` | `GB` | | If not specified, defaults to 20GB minimum |
| `Additional IOPS` | `IOPS` | | Comes from TF resource, https://docs.microsoft.com/en-us/azure/mysql/flexible-server/concepts-compute-storage#iops. If not specified, defaults to 360 minimum. Also, first 360 IOPS are free, show only  the additional value `IOPS - 360` |
| `Additional backup storage` | `GB` | `monthly_additional_backup_storage_gb` | |

### Free resources

- `azurerm_mysql_flexible_database`
- `azurerm_mysql_flexible_server_configuration`
- `azurerm_mysql_flexible_server_firewall_rule`

**Comment by alikhajeh1** [comment]
@bgrainger infracost already supports azurerm_mysql_server, so unless I'm missing something we can update the title/description of this ticket to be focused on terraform-providers/terraform-provider-azurerm#8884 ?

**Comment by bgrainger** [comment]
Sorry, my mistake; for some reason I thought I wasn't getting cost information for `azurerm_mysql_server`. I'll update the issue to just cover Flexible Server.

**Comment by alikhajeh1** [comment]
No problems - thanks! I've subscribed to the Terraform ticket you mentioned to get a reminder when that ships so we can unblock this :)

**Comment by vdmgolub** [comment]
@bgrainger This resource is finally merged to master! :) It should go live with the next release.
