### ISSUE TITLE
Markup/discount on prices based on Region, Services, etc

### ISSUE THREAD

**Issue by FredTiercin** [infracost/infracost#796]
Large companies often use an internal markup to apply teams costs to resources. For example 1000$ on demand EC2 will cost $1000$ + 20% for the project. The 20% are used to pay the company devops teams that handle the work on the instance.

It would be great to have a global way to add markup configuration to be able to say for example EC2 in Asia will cost %20 more, in Europe 15%, etc ...

**Comment by alikhajeh1** [comment]
Interesting use-case! How are you handling this just now?

**Comment by FredTiercin** [comment]
At the moment we use JS in Bigquery to calculate the markup based on region found in the CUR (aws and gcp). We automate this using Dataform. We also filter Oracle license fees where markup doesn't apply.

**Comment by alikhajeh1** [comment]
Thanks for sharing the details! If I understand it correctly, you use that process to apply the markup for post-bill chargeback, and would like the same markup to apply to cost estimates, so the end users have the correct expectations set? vs seeing a lower cost estimate in Infracost, then the markup "surprising" them somewhat in the chargeback step?

**Comment by FredTiercin** [comment]
That's exactly right. We have a markup that can goes up to 100% which double the "on demand" price for certain services/regions. So we don't want bad surprises for project leaders :)

**Comment by alikhajeh1** [comment]
Assuming we design a good way for such markups to be modeled, a new line-item could be output in `infracost breakdown` to show the cost component, DevOps services, in this case. How does that sound?

```
 Name                                                           Monthly Qty  Unit                        Monthly Cost

 aws_instance.web_app
 ├─ Instance usage (Linux/UNIX, on-demand, m5.4xlarge)                  730  hours                            $560.64
 ├─ root_block_device
 │  └─ Storage (general purpose SSD, gp2)                                50  GB                                 $5.00
 └─ ebs_block_device[0]
    ├─ Storage (provisioned IOPS SSD, io1)                            1,000  GB                               $125.00
    └─ Provisioned IOPS                                                 800  IOPS                              $52.00
 └─ DevOps services                                                     730  hours                            $700.00
```

I'm not quite sure what we'd do for the `infracost diff` output, probably omit this cost component since it doesn't change between runs.

**Comment by FredTiercin** [comment]
That would be great !

**Comment by alikhajeh1** [comment]
Thanks for the input @FredTiercin! We'll keep this issue open so we can get 👍 or more input from the community, in July we're focusing on improving the self-hosting experience for our Cloud Pricing API

**Comment by alikhajeh1** [comment]
@FredTiercin one of our users had an interesting workaround to apply a fixed % discount to all prices/costs that I'm sharing here in case it's useful:

1. Get the Infracost JSON output for the Terraform project:
    ```
    infracost breakdown --path . --format json > pre-markup.json
    ```
2. Use `jq` (version 1.6 and above) to add a discount/markup to all price/cost fields in the JSON file:

    ```
    discountFactor='1.1' # For a 10% markup, could be `.90` for a 10% discount

    cat pre-markup.json | jq --argjson df "$discountFactor" '
    walk(if type == "object" and has("monthlyCost") and .monthlyCost != null
        then .monthlyCost = ((.monthlyCost | tonumber) * $df | tostring)
        elif type == "object" and has("totalMonthlyCost") and .totalMonthlyCost != null
        then .totalMonthlyCost = ((.totalMonthlyCost | tonumber) * $df | tostring)
        else .
        end) |
    walk(if type == "object" and has("hourlyCost") and .hourlyCost != null
        then .hourlyCost = ((.hourlyCost | tonumber) * $df | tostring)
        elif type == "object" and has("totalHourlyCost") and .totalHourlyCost != null
        then .totalHourlyCost = ((.totalHourlyCost | tonumber) * $df | tostring)
        else .
        end) |
    walk(if type == "object" and has("price") and .price != null
        then .price = ((.price | tonumber) * $df | tostring)
        else .
        end)' > post-markup.json
    ```

3. Use `infracost output` to render the post-markup.json:
    ```
    infracost output --path post-markup.json --fields all
    ```
