### ISSUE TITLE
add package manager support for windows - chocolatey

### ISSUE THREAD

**Issue by JamesWoolfenden** [infracost/infracost#798]
- [ ] Add package manager support for windoz users with chocolatey: like here: https://github.com/bridgecrewio/yor-choco
- [ ] use zip format for the [Windows release](https://github.com/infracost/infracost/releases) so users can just unzip it without a separate tool.

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
See our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) if you'd like to help with this issue!

**Comment by saltperfect** [comment]
I would like to work on this.

**Comment by saltperfect** [comment]
@JamesWoolfenden @aliscott I have done some changes but apparently choco pack is creating .nupkg file for me in the directory.

I will raise a PR for this can you take a look as to what I might be missing?

**Comment by hugorut** [comment]
Hi @JamesWoolfenden I'm closing this as I'm happy to say that we now have chocolatey support for Infracost. You can install Infracost using:

```
choco install infracost
```

check out our chocolatey community page [here](https://community.chocolatey.org/packages/infracost) and the choco package [scripts here](https://github.com/infracost/chocolatey-packages). Thanks pushing us to do this ❤️
