### ISSUE TITLE
Create-or-update PR comments

### ISSUE THREAD

**Issue by soulshake** [infracost/infracost#809]
Infracost seems great so far!

I've noticed it has the potential to get a bit noisy on busy PRs.
Would it be a possibility to make it so only a single comment is created? Subsequent commits would then update the existing comment instead of creating a new one (and previous versions would still be available in the comment history, at least on Github).

If so, I could give this a shot if needed.

P.S. Feel free to move this to https://github.com/infracost/infracost-gh-action or let me know if it would be more appropriate over there.

**Comment by alikhajeh1** [comment]
Good idea! @aliscott mentioned something similar last week.

We could change [this code](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L147-L152) such that:
1. if there's a pull request, create-or-update the [PR comment](https://docs.github.com/en/rest/guides/working-with-comments#pull-request-comments-on-a-line). 
2. else keep the current behavior (i.e. post a commit comments).

I wonder if an even better option could be to compare the new comment's content with the previous one, and only post **commit comments** if they're different. This might be better as I'm not sure if people notice old edited comments, and the original comment might have had discussions underneath it that were related to older versions. What do you think?

Are there are GH integrations that we could take inspiration from?

**Comment by soulshake** [comment]
The Codecov PR comment behavior seems ideal, especially because it handles posting multiple updates per commit. I can't find the source code that handles this, though (I did reach out and will update if I hear back).

On a related note, we have multiple Terraform directories in our repo and run infracost against each of those plans. It would be awesome if infracost could add one comment per PR, and handle multiple plans per commit!

**Comment by alikhajeh1** [comment]
Thanks @soulshake! I've added this ticket to the project board so we or the community can get to it when there's bandwidth.

> On a related note, we have multiple Terraform directories in our repo and run infracost against each of those plans. It would be awesome if infracost could add one comment per PR, and handle multiple plans per commit!

Are you using a [config file](https://www.infracost.io/docs/multi_project/config_file) for that? It can be specified in GH Actions like [this](https://github.com/infracost/infracost-gh-action#config_file). If so, the [diff.sh](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L289-L291) should be combining those into 1 comment. I'm probably missing something though 😅

**Comment by soulshake** [comment]
> I've added this ticket to the project board

Awesome! :tada: 

> Are you using a [config file](https://www.infracost.io/docs/multi_project/config_file) for that? It can be specified in GH Actions like [this](https://github.com/infracost/infracost-gh-action#config_file). If so, the [diff.sh](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L289-L291) should be combining those into 1 comment. I'm probably missing something though

Unfortunately I don't think this would work, because they are running in a parallel job matrix (and therefore there's no shared filesystem).

**Comment by tim775** [comment]
Just a heads up, I've been working on #980 to address this and I've started discussion #1016 to talk about future improvements.

**Comment by alikhajeh1** [comment]
@soulshake, @PatMyron, @1mamute and @simon-jt just FYI that a new `post_condition='{"update": true}'` has been added to all GitHub-based integrations: [GitHub Actions](https://github.com/infracost/infracost-gh-action#post_condition ), [Azure DevOps with GitHub repos](https://github.com/infracost/infracost-azure-devops#post_condition) and [CircleCI with GitHub repos](https://github.com/infracost/infracost-orb#post_condition). It would be great if you can try it and let us know if that helps.

https://github.com/infracost/infracost/discussions/1016 is there to continue the discussion, specially to do with merging multiple run outputs into 1 PR comment.
