### ISSUE TITLE
Report output to CSV

### ISSUE THREAD

**Issue by 1mamute** [infracost/infracost#816]
# The problem
As mentioned in https://github.com/infracost/infracost/issues/811#issuecomment-861522629 I use `infracost breakdown` in a daily scheduled pipeline that generate a daily report about our infrastructure total approximated cost. For the moment, we have three state files that generates a uniform report in JSON. I send this uniform report via cURL to our Discord Channel (slack would work as well) and Google Sheets using [Pipedream](https://pipedream.com/).

For the Discord webhook, this methods works fine, it's easy to parse a Discord message using nodeJS but inserting this JSON report in Google Sheets is very difficult.

# My proposal
A CSV `--format` option for `diff` `breakdown` and `output` to make easier to insert these informations in a datasheet.

**Comment by alikhajeh1** [comment]
Awesome! This would probably work nicely with `--fields` too so you can select the CSV fields.
Any suggestions on what the CSV output could like for the breakdown and the diff? The diff might be challenging

**Comment by 1mamute** [comment]
Maybe something like this could work: [simple example](https://docs.google.com/spreadsheets/d/1oU4o-K-LZqjE6y5G3ToH7Bq3ZsjdL0MBhXpjqm75jmM/edit?usp=sharing).

**Comment by alikhajeh1** [comment]
The `output` command's format is making me wonder if there's a need to split between format and report type, e.g. we have a breakdown and diff report types, and those can be in text, HTML or CSV format (so you have csv_diff, or html_breakdown). JSON has been our machine format so it has all the data required to create either of those report types. 

Can you possibly share what roles in the company use the Google Sheets output, and what they do with it?

**Comment by aliscott** [comment]
> making me wonder if there's a need to split between format and report type

Yeah this is a very good point, but I wonder if we need different formats for the CSV diff and breakdown. We handle both already in the JSON, so maybe one CSV format that has both would work. For each resource we could show the current, projected and diff cost in a single row. Maybe something like this:

|project   |resource                |costComponent |price|unit|monthlyQuantity|hourlyQuantity|monthlyCost|hourlyCost|pastMonthlyCost|pastHourlyCost|diffMonthlyCost|diffHourlyCost|
|----------|------------------------|--------------|-----|----|---------------|--------------|-----------|----------|---------------|--------------|---------------|--------------|
|my/tf/code|                        |              |     |    |               |              |742.64     |1.0173    |0              |0             |742.64         |1.0173        |
|my/tf/code|aws_instance.my_instance|              |     |    |               |              |742.64     |1.0173    |604.64         |0.8283        |138.00         |0.1890        |
|my/tf/code|aws_instance.my_instance|Instance usage|0.77 |hours|730            |1             |560.64     |0.768     |422.64         |0.5789        |138.00         |0.1890        |


Similar for the HTML output, maybe. It could show the diff and then an option of expanding that to show the full breakdown.

**Comment by alikhajeh1** [comment]
Hah, you're right, we already have the fields in JSON so we can use the same in CSV. For HTML, do you mean an HTML tab for each project inside the HTML page? We can default to the breakdown tab being visible.

**Comment by aliscott** [comment]
> do you mean an HTML tab for each project inside the HTML page? We can default to the breakdown tab being visible.

Yeah something like that could work. Or showing the diff as a summary at the top and then a bit you can expand to view the whole details.

**Comment by 1mamute** [comment]
> Can you possibly share what roles in the company use the Google Sheets output, and what they do with it?

I explain my two use-cases in this comment here: https://github.com/infracost/infracost/issues/811#issuecomment-861522629

In this case, i'm planning to append our costs daily into to a Google Sheets using [this pipedream integration](https://pipedream.com/apps/google-sheets) and handle this sheet to our non-profit financial people so they can keep a history of the expected costs of the 3 environments we have as we create the resources (the project is in early stages). 

Here's an example from the top of my head to what I'm expecting this sheet from finances to look like:

| Date | Global $/h | Global $/month | Dev $/h | Dev $/month | Main $/h | Main $/month | Total $/h | Total $/month
| ------ | -------------- | -------------------- | ----------- | ----------------- | ----------- | ------------------ | ------------ | -----------------
| 18/06/2021  | $0.5 | $360 | $0.5 | $360 | $0.5 | $360 | $1.5 | $1080
| 19/06/2021  | $0.6 | $432 | $0.5 | $360 | $0.5 | $360 | $1.6 | $1152
| 20/06/2021  | $0.6 | $432 | $0.55 | $396 | $0.5 | $360 | $1.65 | $1188

**Comment by alikhajeh1** [comment]
@1mamute awesome - thanks! I've added this to the project board so we/community can get to it when there's bandwidth.
