### ISSUE TITLE
Support currency conversions as a setting

### ISSUE THREAD

**Issue by Terryromeu** [infracost/infracost#819]
Hello, 
How can i change the currency USD to EUR ?
![image](https://user-images.githubusercontent.com/22493255/122374394-a2ccaf80-cf62-11eb-9617-6aea3757ed34.png)

**Comment by aliscott** [comment]
Thanks @Terryromeu! Unfortunately multiple currencies are not supported yet. I think the different cloud vendors all handle them slightly differently when listing prices and billing. Which cloud vendors are you using and would a straight up conversion using the current exchange rate work for you or are you looking for it to pull in listed prices in EUR from somewhere?

**Comment by hassankhosseini** [comment]
@AErmie - one you requested too, just in case you wanted to follow it 👍

**Comment by AErmie** [comment]
@aliscott  / @hassankhosseini, if we changed the "USD" manually to something else (ie. "CAD"), would that work? Or would that break anything in the code somewhere else? 

To weigh in on the questions posed...
1. Azure (though other customers use AWS)
2. How would straight conversion compare to what the Cloud Provider API's own conversion mechanisms differ? Usually, you get your cloud bill monthly, but, we would be using InfraCost on PRs, etc. which happen daily, etc. So in my opinion, I think a straight conversion with the disclaimer of "this may not be 100% accurate" should suffice. After all, it's more of a spot-check to see how significantly your bill will increase. 
3. Not sure I follow the question. If we're using InfraCost, then we'd expect the output from that (ie. as a gate/control, or at least a PR comment). It wouldn't be directly checking against the Cloud Provider's pricing API.

**Comment by craigthackerx** [comment]
Hey, me and my team love the tool.  We were also wondering about getting USD converted to GBP in Azure.

My thoughts are I'd like just a straight up conversion of USD to GBP at the time of running, and as @AErmie says, a notice that "This is not 100% accurate" would suffice, for us at least.

I'm not completely familiar with the operation of the code, so apologies if this is a dumb question - Is it possible to perform a basic math function on the returned result of the API based on a flag? E.g. 1$ = £0.72 at the time of writing, so if we get a returned total value of $100, from the API with the `--convert gbp` flag, all we would need to do is multiply it by 0.72 to get a rough estimate.

Its not really manageable with my suggestion as currencies fluctuate daily, but it gives the basic functionality conceptually. 

If anyone is feeling brave, I dare you to try and do it as a USD to Bitcoin conversion and see how many commits you need to make in a week....

**Comment by alikhajeh1** [comment]
+1 on straight up conversion of USD to GBP (or other currencies) at the time of the CLI running. That's the simplest thing we could do just now and it seems to be good enough for estimation purposes.

**Comment by VasseurLaurent** [comment]
+1 I would also be interested by conversion from USD to Euro at the time of the CLI running. It would be great to be able to specify the currency within infracost command or with an environment variable.

**Comment by tim775** [comment]
@Terryromeu @craigthackerx @gareda @VasseurLaurent @PatMyron @AErmie @VasseurLaurent 
We released this today, thanks for your input!  Try running 0.9.6 with `INFRACOST_CURRENCY=XAG` env variable to see how much silver you're sending to the cloud 🙂
