### ISSUE TITLE
Add support for EKS clusters

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#82]

**Comment by hassankhosseini** [comment]
Is this ticket only for aws_eks_node_group, or any other of the eks resources:

<img width="193" alt="Screen Shot 2020-09-16 at 8 44 29 AM" src="https://user-images.githubusercontent.com/1238825/93307546-01f56c00-f7f9-11ea-9aa6-f8848f9b106c.png">

**Comment by sashman** [comment]
> Is this ticket only for aws_eks_node_group, or any other of the eks resources:
> 
> <img alt="Screen Shot 2020-09-16 at 8 44 29 AM" width="193" src="https://user-images.githubusercontent.com/1238825/93307546-01f56c00-f7f9-11ea-9aa6-f8848f9b106c.png">

@hassankhosseini I shall pick this up in multiple PRs per resources if that's cool?

**Comment by alikhajeh1** [comment]
@sashman thanks! Having 1 PR with multiple resources (e.g. aws_eks_*) is fine

**Comment by sashman** [comment]
🥳
