### ISSUE TITLE
Add support for Azure Key Vault azurerm_key_vault_secret resource

### ISSUE THREAD

**Issue by vagonas** [infracost/infracost#829]
Hi there, At the moment there is only support for `azurerm_key_vault_certificate`  and `azurerm_key_vault_key` as per https://github.com/infracost/infracost/pull/657 

We need support for `azurerm_key_vault_secret` otherwise, how can we estimate secrets operations? 

https://azure.microsoft.com/en-us/pricing/details/key-vault/
<img width="1378" alt="Screenshot 2021-06-25 at 11 03 50" src="https://user-images.githubusercontent.com/13677203/123399577-1430e180-d5a5-11eb-81fa-5e804b5441ea.png">

**Comment by alikhajeh1** [comment]
👋 hey @vagonas, great question! We modeled that price as part of the `azurerm_key_vault_key` resource as we thought that users would have a key that is used for secret operations (alongside other operations), so the output below is generated: 

```
 Name                                          Monthly Qty  Unit                      Monthly Cost                                                                                                    
 azurerm_key_vault_key.my_key                                                                    
 ├─ Secrets operations                  Monthly cost depends on usage: $0.03 per 10K transactions  
 ├─ Storage key rotations               Monthly cost depends on usage: $1.00 per renewals          
 └─ Software-protected keys             Monthly cost depends on usage: $0.15 per 10K transactions  
```

If you use the Infracost [usage file](https://www.infracost.io/docs/usage_based_resources), and add something like this:
```
version: 0.1
resource_usage:
  azurerm_key_vault_key.my_key:
    monthly_secrets_operations: 30000          # Monthly number of secrets transactions.
```

Then the output would show the costs:
```
 Name                                          Monthly Qty  Unit                      Monthly Cost                                                                                                    
 azurerm_key_vault_key.my_key                                                                       
 ├─ Secrets operations                                   3  10K transactions                 $0.09 
 ├─ Storage key rotations                               30  renewals                        $30.00 
 └─ Software-protected keys                            300  10K transactions                $45.00 
```

Does that make sense? I'm not an Azure expert so I'm happy to move prices or also show them in other TF resources if you think that makes more sense? (in which case, I'd really appreciate a short explanation of why)

Also, you might be interested in watching/commenting on [this ticket](https://github.com/infracost/infracost/issues/819), which is about currency.

**Comment by alikhajeh1** [comment]
Going to close this issue, feel free to comment if the above doesn't address the issue
