### ISSUE TITLE
Add support for Azure Application Insights

### ISSUE THREAD

**Issue by vagonas** [infracost/infracost#830]
Pricing page: https://azure.microsoft.com/en-us/pricing/details/monitor/  (also available in the Azure pricing calculator)

Terraform resources is [`azurerm_application_insights`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights).

**Comment by tim775** [comment]
`azurerm_application_insights` should have:
- A usage param `monthly_data_ingested_gb` with unit `GB` displayed as `Data ingested`
-`Data retention (<days> days)` with unit `GB` where `days` is determined by the `azurerm_application_insights.retention_in_days`.  The cost is calculated by multiplying `monthly_data_ingested_gb` by the number of retention days over 90.  This should only be displayed if the cost is > 0.

`azurerm_application_insights_web_test` should have:
- `Multi-step web test` with unit `test` where quantity is 1 if `kind` == `multistep` and `enabled`=`true`

**Comment by ekifel** [comment]
@alikhajeh1, I want to work on it!

**Comment by alikhajeh1** [comment]
Thanks @ekifel!

**Comment by tim775** [comment]
> The cost is calculated by multiplying monthly_data_ingested_gb by the number of retention days over 90.
The charge for data retention is GB-month, so I think this should actually be `monthly_data_ingested_gb * number_of_months_over_3_months` (where a month == 30 days).  

So if ingested == 1000, and retention == 120, then `((120-90) / 30) == 1` so the cost would be `1000 * 1 * $0.12 per GB per month == $120`.
If retention == 550, then `(550-90) / 30 == 15.3` so cost would be `1000 * 15.3 * $0.12 per GB per month == $1836`

**Comment by alikhajeh1** [comment]
Released in v0.9.2 today.
