### ISSUE TITLE
Output message showing number of resources that we don't support

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#84]
e.g. "2 out of 26 resources could not be estimated because they don't have a price or Infracost does not yet support them (https://www.infracost.io/docs/supported_resources)"

Debug level logging could show the resource addresses.

**Comment by alikhajeh1** [comment]
It might be helpful to distinguish these two cases:
1. a free resource is being used in Terraform: we've reviewed that it's free when we added the resource to Infracost but the user doesn't know.
2. a free or paid resource that infracost doesn't support.

Maybe an output like this:
"Out of the 26 resources, 8 are free, and 18 aren't supported in Infracost yet (https://www.infracost.io/docs/supported_resources), re-run with FLAG_HERE to see the list."

**Comment by sinabakh** [comment]
I think I can work on it, I have to review the core codes again to get some solid ideas on how to manage it.
I just have some questions:
**1.** The simple way is to show users that we don't support the resource but how can we show him the exact reason? As far as I know, there are multiple reasons:
**A.** We simple does not support the resource
**B.** User specified some wrong attributes in its usage data such as setting `monthly_write_request_units` for `PROVISIONED` DynamoDB
**C.** We don't support part of resources like when we support provisioned resources but not their on_demand version.
2. What are examples of free resources? @alikhajeh1 

To handle the first situations we might have to generate some messages and return them back as an error or part of resource data so we can generate more meaningful messages.

**Comment by alikhajeh1** [comment]
Thanks @sinabakh! 

Regarding 1, my guess is that most users don't care about the reason, they just want to know why some of their terraform resources aren't showing up in the output, and we can ask them to rerun with `--verbose` or some flag to see the details (they could send us that list so we can work on it too).

Regarding 1B, I'd leave that out of the scope of this ticket, we're still gathering feedback about the terraform provider. 

Regarding 1C, see "Level 1 support" in https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md, my idea going forward is that all pricing components of a resource should be supported. We need to re-check/change the existing supported resources to add pricing for all of their components.

Regarding 2, see `docker_volume_configuration` and `proxy_configuration` in the PR description of https://github.com/infracost/infracost/pull/36#issue-475764082 I'm not sure if it's going to be easy to handle those but it would be good to discuss the options here even if we decide to implement them via another GH issue.

**Comment by aliscott** [comment]
I can still see 1C being an issue. For example, we only support ECS+Fargate and not ECS+EC2. ECS+EC2 is a lot more complicated to add, so I don't think we should block the Fargate support for that.

But, for this case if we come across an option we don't yet support, I think we can just treat it the same way as 1A and list it as a resource we don't support. Thoughts?

**Comment by sinabakh** [comment]
Thanks, yeah I agree with you. So we just need to handle 1A. For cases like what @aliscott mentioned, the easiest way is to treat them like 1A since we will have support sooner or later for all kinds of resources. But the other option is to let the resource function generate a more meaningful message for its verbose mode.
What do you think?

**Comment by alikhajeh1** [comment]
If the resource function is optional and the output can remain sane then that can work nicely. A user pinged me today with 1K+ terraform resources...

One other semi-related, verbose-type output, topic, we need to think about is how the resource file can include the "notes" that we have in https://www.infracost.io/docs/supported_resources, so we can auto-generate that docs page. Should those go into the verbose output at the bottom so users don't need to read docs? I doubt users would compare 1K+ resources in their terraform against a markdown file manually...

**Comment by sinabakh** [comment]
Sure, we need to discuss them.
For now, I will stick to 1A`We simple does not support the resource`. We can get more feedbacks and think about more complicated handlers in the future.
