### ISSUE TITLE
Query: Is there a possibility to include enterprise discounts offered by the cloud provider in calculating the individual resource cost or the overall cost? 

### ISSUE THREAD

**Issue by SarmaKHCL** [infracost/infracost#843]
Query: Is there a possibility to include enterprise discounts offered by the cloud provider in calculating the individual resource cost or the overall cost?

**Comment by alikhajeh1** [comment]
@SarmaKHCL I'd love to learn more about your use-case and which of the various enterprise discount programs you're more interested in, if you like we can have a quick call as it'll be faster than many back-n-forth detailed comments here, my email is ali.hosseini@infracost.io

**Comment by alikhajeh1** [comment]
Closing this ticket as I believe you're discussing this with @hassankhosseini over email. Other users can add comments here or create new issues so we can understand their use-case.

**Comment by alikhajeh1** [comment]
@SarmaKHCL out of interest, which of [these options](https://github.com/infracost/infracost/issues/1725#issuecomment-1147817410) would work for your use-case to handle discounts from the cloud providers?
