### ISSUE TITLE
Update `infracost register` to let users know upfront if they already have an API key

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#858]
I've seen many users with multiple keys soon after they register. I wonder if it's because when they run `infracost register`, it creates the API key then checks/informs them if one already exists. We should change this so the first step in register is to check for an existing key, and tell them that it's saved in `~/.config/infracost/credentials.yml`, then ask if they'd like to create a new key.

**Comment by krishnaindani** [comment]
Hey @alikhajeh1, is this open for work, I would like to try if that's okay?

**Comment by alikhajeh1** [comment]
Yep, go for it, @aliscott will review it - not sure if he has any pointers before the work begins

**Comment by aliscott** [comment]
@alikhajeh1 only question I have for this is: If the user has an API key and still wants to generate a new one, should it always overwrite the one they have saved in `~/.config/infracost/credentials.yml` or should they still get the option to overwrite it or not?

**Comment by alikhajeh1** [comment]
It's probably better to give them a choice as if they overwrite it, there's no going back.

**Comment by krishnaindani** [comment]
I have skimmed the code for the register command yesterday, will go through it so that I have a clear understanding, and ask questions if I get any. And then I can start the work. Thank you so much @alikhajeh1 and @aliscott.

**Comment by krishnaindani** [comment]
> It's probably better to give them a choice as to if they overwrite it, there's no going back.

For this issue, are we addressing it by giving the user the option to provide a different path if they want? I have a bunch of questions if we are going to implement it that way.

**Comment by alikhajeh1** [comment]
@krishnaindani I'd keep it simple and not worry about changing paths. The aim is to ensure users are aware that a key already exists before the existing flow kicks-in.

**Comment by krishnaindani** [comment]
That means we are good with giving the warning here https://github.com/infracost/infracost/blob/master/cmd/infracost/register.go#L60 and overwriting it, right? We just need to change the flow to 

1. check if the key exists
2. If the key exists, ask the user if he still wants to generate. 
3. If yes to 2, overwrite the key that is saved in `config/infracost/credentials.yml`. 
4. If no to 2, will exit. 
 
Does that sound, correct?

**Comment by alikhajeh1** [comment]
Almost...
1. Check if the key exists
2. If it exists, output `You already have an API key saved in %s, would you like to generate a new one?`
3. If yes to 2, ask for Name and Email, show the new API key, and ask `Would you like to overwrite your existing saved API key` then overwrite if they say yes, otherwise just show the API key and exit (current behavior).
4. If no to 2, exit.

**Comment by krishnaindani** [comment]
oh got it. WIll need to change the prompt order from what I thought. Thanks, that makes sense. Also, do we have a way to delete the keys, because while I was testing I see a user can only have 5 keys and after that, it throws an error?

**Comment by alikhajeh1** [comment]
I emailed you about it :)

**Comment by krishnaindani** [comment]
Thank you. Haven't received it yet. Will wait.

**Comment by krishnaindani** [comment]
Looks like the AWS test is failing even though I have no changes there.  Would someone correct me what's wrong here, I only have changes in the `register` command file. https://github.com/infracost/infracost/runs/3053394850?check_suite_focus=true

**Comment by alikhajeh1** [comment]
@krishnaindani yep, looks like something changed in the AWS pricing that caused the integration test to fail for that resource. I'll look at it later tonight but it's not related to your PR :)

**Comment by krishnaindani** [comment]
sounds good. Thank. I have my pr mostly ready will be testing again and will add a description and move to review later. I don't see tests for the command, do we plan to have that?

**Comment by krishnaindani** [comment]
@alikhajeh1 @aliscott I have PR ready for review, have tested this locally. Looking forward to the review and what do you think. https://github.com/infracost/infracost/pull/864

**Comment by aliscott** [comment]
Fixed in #864, thanks @krishnaindani! 🚀
