### ISSUE TITLE
Unsupported Terraform Core version

### ISSUE THREAD

**Issue by tovbinm** [infracost/infracost#866]
When running Infracost with Terraform 1.0.2

```
  Terraform command failed with:
    Error: Unsupported Terraform Core version
      on versions.tf line 2, in terraform:
       2:   required_version = ">= 1.0"
    This configuration does not support Terraform version 0.15.4. To proceed,
    either choose another supported Terraform version or update this version
    constraint. Version constraints are normally set for good reason, so updating
    the constraint may lead to other errors or unexpected behavior.

Error: Error running terraform init: exit status 1
```

**Comment by alikhajeh1** [comment]
Hey @tovbinm! Infracost calls out to `terraform plan` to get the plan JSON, and that error suggests that `which terraform` is pointing to the terraform 0.15.4 version on that system.

Can you please try setting `INFRACOST_TERRAFORM_BINARY=/path/to/new_terraform_binary infracost breakdown --path /path/to/code` and see if that works?

**Comment by tovbinm** [comment]
Where can set Terraform version for Infracost to use?

**Comment by alikhajeh1** [comment]
That can be set by either:
1. `export INFRACOST_TERRAFORM_BINARY=/path/to/new_terraform_binary_on_your_machine`, then run infracost as normal
2. if you're using a [config-file](https://www.infracost.io/docs/multi_project/config_file), the `terraform_binary` param

**Comment by tovbinm** [comment]
I updated the `infracost.yml`:
```
version: 0.1

projects:
  - path: .
    terraform_workspace: dev
    terraform_binary: 1.0.2
```

And now I get:

```
Error: Terraform binary "1.0.2" could not be found.
```

**Comment by tovbinm** [comment]
Oh, it has to be a local binary. I see.

**Comment by tovbinm** [comment]
Can I just set up the Terraform with https://github.com/marketplace/actions/hashicorp-setup-terraform ?

**Comment by alikhajeh1** [comment]
@tovbinm ah you're using the GH Action, sorry I should have checked that. I've sent a PR to add the latest TF version to our Dockerfile. After that's released you can set the infracost config file `terraform_binary: terraform_1.0` (that way it'll use the latest patch version of 1.0).

We'll aim for a release tmrw.

**Comment by tovbinm** [comment]
Got it. Thank you!
