### ISSUE TITLE
Improve performance of integration tests

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#87]
Currently the integrations tests take ~10 seconds each to run. This is because they are running `terraform init`, `terraform plan` and hitting the pricing.infracost.io service for each test.

There's various options to improve the performance. Some initial ideas:
 * Parallelise the tests
 * Cache the pricing API responses
 * Cache the `terraform plan` outputs
 * Only run `terraform init` and `terraform plan` once when the tests run by somehow merging the tests into a single Terraform project.

**Comment by aliscott** [comment]
I've improved the integration test performance by about a third by caching the Terraform providers (https://github.com/infracost/infracost/commit/005d9b8f19a3b870711665d898d6ab4da5c108b7#diff-336978a5a517930d99e40a473468326e).

**Comment by alikhajeh1** [comment]
Going to close this as the tests run in ~5mins on GH just now (down from ~17mins), some of the ideas in this ticket were implemented in https://github.com/infracost/infracost/issues/637
