### ISSUE TITLE
new feature (azure): azurerm_private_endpoint 

### ISSUE THREAD

**Issue by dgcaron** [infracost/infracost#870]
I was looking at some components that we add regularly that aren't too complex and should be a good first try. we rely heavily on networking features and therefore azurerm_private_endpoint looks like an ideal candidate. 

the resource has an hourly rate and two usage parameters outbound and inbound data processed. 

*** Note ***
the docs mention something about bandwidth pricing (https://azure.microsoft.com/en-us/pricing/details/bandwidth/) and i am unsure where this should land in the resource costs?

**Comment by alikhajeh1** [comment]
@dgcaron thanks for creating this ticket! That looks like an ideal first resource to add, here are some details that might help:

Cost components:
- "Private endpoint", unit "hours".
- "Inbound data processed", unit "GB", usage file parameter: `monthly_inbound_data_processed_gb: 100 # Monthly inbound data processed in GB.`
- "Outbound data processed", unit "GB", usage file parameter: `monthly_outbound_data_processed_gb: 100 # Monthly outbound data processed in GB.`

For the data processed params, if the usage file is not defined, they should show the usual cost depends on usage params. Regarding the data transfer, I wouldn't handle it as part of this resource. For AWS, we did it as [a separate resource](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L107-L112).

Free resource that could be added to `internal/providers/terraform/azure/registry.go`:
- azurerm_private_link_service

**Comment by dgcaron** [comment]
i can't seem to find the private endpoint / link service in the cloud costs database? 
i tried these two calls: 

```
db.products.distinct("service", {"vendorName": "azure", "service": {$regex: "private", $options: "i"} });
[ "Private Mobile Network" ]
> db.products.distinct("service", {"vendorName": "azure", "service": {$regex: "endpoint", $options: "i"} });
[ ]
```

checking the networking family, it also isn't showing
```
> db.products.distinct("service", {"vendorName": "azure",  "productFamily": "Networking" });
[
        "Application Gateway",
        "Azure Bastion",
        "Azure DDOS Protection",
        "Azure DNS",
        "Azure Firewall",
        "Azure Firewall Manager",
        "Azure Front Door Service",
        "Azure Orbital",
        "Azure Route Server",
        "Bandwidth",
        "Content Delivery Network",
        "ExpressRoute",
        "Load Balancer",
        "Microsoft Azure Peering Service",
        "NAT Gateway",
        "Network Watcher",
        "Private Mobile Network",
        "Traffic Manager",
        "VPN Gateway",
        "Virtual Network",
        "Virtual WAN"
]
``` any pointers in what I am doing wrong here?

**Comment by alikhajeh1** [comment]
Azure sure don't make it easy... I found them with the following:
```
db.products.distinct("attributes.meterName", {"vendorName": "azure", "service": "Virtual Network", "attributes.productName":"Virtual Network Private Link"})
```

Notice how each of the above meterNames has 3 prices (Global, US Gov and China). This is common for these global resources and the following methods can help you convert the region:
```
	region := lookupRegion(d, []string{}) // finds the location property from the resource
	region = convertRegion(region) // converts it to the format needed by the price filters
```

For the `AttributeFilters`, it looks like `meterName` and `productName` is all that's needed. You can also add the `PriceFilter` so if Azure add non-consumption prices, this code still matches these prices.

**Comment by dgcaron** [comment]
i created this devcontainer for setting up a GO development env, run the make deps and preload a mongodb in a container. do I need to add the .devcontainer folder to the .gitignore or is it something that would be helpful for other contributors? 

my initial stab -> https://github.com/dgcaron/infracost/tree/feat/vscode_devcontainer/.devcontainer 

details on dev containers -> https://code.visualstudio.com/docs/remote/containers

**Comment by alikhajeh1** [comment]
that's awesome! these tooling improvements help other contributors (I use vscode too). Can you possibly create an issue with the above comment so it can be worked-on separately? I suggest that as there's a [big change](https://github.com/infracost/cloud-pricing-api/issues/52#issuecomment-881225486) going on in the Cloud Pricing API and we're removing the mongo dependency in favor of postgres so it's probably best to do this after that's released in the week or two.

**Comment by dgcaron** [comment]
i am trying  to run the integration tests as described in the contributing.MD but I am getting an Go error indicating decimalPtr and strPtr don't exist. however, when I run make build everything compiles. is there a way to run a single integration test?
this fails for me
```bash
INFRACOST_LOG_LEVEL=warn go test ./internal/providers/terraform/aws/private_endpoint.go -v -update
```

**Comment by alikhajeh1** [comment]
hmm what was the failure error message? That's how we run individual integration tests locally. Note that Azure integration tests requires creds since Azure Terraform provider needs them: https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#azure

Edits to the contribution docs are also welcome!

**Comment by dgcaron** [comment]
it's probably just me, sorry.

**Comment by alikhajeh1** [comment]
Closed by https://github.com/infracost/infracost/pull/878

**Comment by alikhajeh1** [comment]
@dgcaron just FYI that Infracost CLI v0.9.6 that released just now has this - thank you!
