### ISSUE TITLE
Add support for GCP instance groups

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#871]
We already support google_compute_instance costs.

We can add support for [compute_instance_group_manager](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager) and [compute_region_instance_group_manager](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager) as they have a `target_size` param.

**Comment by kevinkengne** [comment]
:wave:, what would be the cost component for these resources?

**Comment by alikhajeh1** [comment]
I think they should be the same as `google_compute_instance`. So we can refactor the cost components in that resource to put them in functions and call them from the new `compute_instance_group_manager` and `compute_region_instance_group_manager` resources but also use the `target_size` param to set the quantity.
Does that make sense?

**Comment by kevinkengne** [comment]
Yess, that makes perfect sense. I can pick this up then, if that's ok.

**Comment by alikhajeh1** [comment]
Thanks @kevinkengne!

**Comment by kevinkengne** [comment]
One more question: How do I get the correct machine type for the managed instance groups? It looks like that would be defined in the `instance_template` and the `instance_template` argument for both resources (`compute_instance_group_manager` and `compute_region_instance_group_manager`) seems to be a URL.

**Comment by tim775** [comment]
You should be able to access the `compute_instance_group_manager` using `ReferenceAttributes`.  As an example take a look at how `compute_snapshot` figures out its size:
It identifies `source_disk` as a reference attribute: https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/compute_snapshot.go#L14
Then it uses `d.References('source_disk')` to access the attributes of the associated `google_compute_disk`.

https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/compute_snapshot.go#L55-L57

One thing to watch out for:  I'm not sure of is if `google_compute_instance_template` needs to be added to the registry (maybe as a free resource) for the references to work properly.  https://github.com/infracost/infracost/blob/master/internal/providers/terraform/google/registry.go#L53

**Comment by tim775** [comment]
Thanks for sticking with it!  We do support `google-beta` in a few places but I think it would be ok to defer handling multiple `versions` to a new issue if that simplifies things.  We could log a warning now if we detect multiple versions.

**Comment by tim775** [comment]
@njculver This is merged to master in #944.  Thanks @kevinkengne!
