### ISSUE TITLE
add devcontainer for setting up a GO development env, run the make deps and install other dependencies

### ISSUE THREAD

**Issue by dgcaron** [infracost/infracost#872]
i created this devcontainer for setting up a GO development env, run the make deps and preload a mongodb in a container. do I need to add the .devcontainer folder to the .gitignore or is it something that would be helpful for other contributors? 

my initial stab -> https://github.com/dgcaron/infracost/tree/feat/vscode_devcontainer/.devcontainer 

details on dev containers -> https://code.visualstudio.com/docs/remote/containers

 
![image](https://user-images.githubusercontent.com/9764640/126640656-2c6030c3-7c87-4737-bf44-1fa331811035.png)

_Originally posted by @dgcaron in https://github.com/infracost/infracost/issues/870#issuecomment-884878747_

**Comment by dgcaron** [comment]
Yeah, no I think it is not a big thing right now.

**Comment by alikhajeh1** [comment]
Awesome - thanks @dgcaron! btw, if you used the [azure devops extension](https://marketplace.visualstudio.com/items?itemName=Infracost.infracost-tasks), we'd appreciate a review/star rating :)
