### ISSUE TITLE
Bug: --sync-usage-file flag is destructive when used with wildcard resource usage

### ISSUE THREAD

**Issue by m-yosefpor** [infracost/infracost#875]
When using `--sync-usage-file` flag with [wildcard resource usage](https://www.infracost.io/docs/usage_based_resources#resource-arrays) such as:

```
aws_cloudwatch_log_group.my_group[*]:
  storage_gb: 1000
  monthly_data_ingested_gb: 1000
  monthly_data_scanned_gb: 200
```

the values are removed and replaced with each index/key specific resources with default `0` usage value:

```
aws_cloudwatch_log_group.my_group[0]:
  storage_gb: 0
  monthly_data_ingested_gb: 0
  monthly_data_scanned_gb: 0
aws_cloudwatch_log_group.my_group[1]:
  storage_gb: 0
  monthly_data_ingested_gb: 0
  monthly_data_scanned_gb: 0
```

This is also true for resource maps with `for_each`.

**Expected behavior**:

`--sync-usage-file` flag
1. should not delete the wildcard usages for resources with count and for_each
2. should delete the wildcard usages for resources if they got removed or count/for_each argument is removed.
3. should not add any element to resource usage file if a wildcard exists for that (since element values will override the wildcard).
4. should delete any out of range index / non-existing keys if resource array/map is updated.

**Comment by krishnaindani** [comment]
Hey @alikhajeh1 , is this the bug in the breakdown command? Can I try to attempt this issue if not time crunch? I might have to go through the breakdown command code though to understand before starting to work.

**Comment by alikhajeh1** [comment]
I suspect it's a bug in the `SyncUsageData` function, no time crunch yet (if it does become time-sensitive then I'll comment here)

**Comment by krishnaindani** [comment]
sounds good, I will start looking into this. Does that work?

**Comment by alikhajeh1** [comment]
@krishnaindani sure, I assigned it to you, and maybe @m-yosefpor can review the PR later on since his GH issue descriptions is nicely detailed :)

**Comment by alikhajeh1** [comment]
@krishnaindani just wondered if there were any updates to this?

**Comment by aliscott** [comment]
@ajoulie awesome! Heads up that there's some big changes going into that part of the code that might affect this in #1036. I'll be merging it today.

**Comment by alikhajeh1** [comment]
Thanks @ajoulie and @aliscott - I added https://github.com/infracost/docs/pull/99/commits/2c463e157a45a2d952cbfd450a12a0386ce536c4#diff-127ccf771949de22c36f72306c28f3f448853733f173a2f658d4d6f5464de803R106-R108, feel free to tweak https://github.com/infracost/docs/pull/99 if needed
