### ISSUE TITLE
Proposal: Adding an option which cause the output to contain all the fields

### ISSUE THREAD

**Issue by m-yosefpor** [infracost/infracost#876]
Having an option such as `--fields=all` which caused the output to contain all the supported fileds: price, monthlyQuantity, unit, hourlyCost, monthlyCost.

**Comment by alikhajeh1** [comment]
Good idea! This'll place nice with breakdown, diff and output

**Comment by kevinkengne** [comment]
👋, may I start working on this issue? this should be fairly straightforward.

**Comment by alikhajeh1** [comment]
Thanks @kevinkengne! Sure, let us know if you run into any issues

**Comment by kevinkengne** [comment]
Thanks. In my opinion, it would be worth having unit tests for the CLI command to give people modifying arguments/options the confidence that they haven't introduced any regressions.

**Comment by tim775** [comment]
> Thanks. In my opinion, it would be worth having unit tests for the CLI command to give people modifying arguments/options the confidence that they haven't introduced any regressions.

I agree that's a good idea.  Would something like the golden file tests we have for resources work or do you have something different in mind?

**Comment by kevinkengne** [comment]
Something like the existing golden file tests for resources would be perfect.

**Comment by alikhajeh1** [comment]
This was released in Infracost CLI v0.9.6 just now, thanks to @m-yosefpor and @kevinkengne for your input! It looks like we forgot to update the help text for the --fields flag, I'll open a PR in a bit.
