### ISSUE TITLE
Add support for Azure Sentinel

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#889]
Microsoft Sentinel (former name Azure Sentinel) is a security analytics service that uses analytics log data ingested via Azure Monitor Log Analytics platform (TF resource `azurerm_log_analytics_workspace`). It's enabled on a workspace and it supports different data connectors. The billing is based on the amount of log
data.

There are several Terraform data connector resources that depend on `azurerm_log_analytics_workspace`. However they are not billed individually thus we can't add cost components for them. But we can detect if they are defined and show a dedicated cost on Log Analytics Workspace resource.

1. Add the following resources:
  - `azurerm_sentinel_data_connector_aws_cloud_trail`
  - `azurerm_sentinel_data_connector_azure_active_directory`
  - `azurerm_sentinel_data_connector_azure_advanced_threat_protection`
  - `azurerm_sentinel_data_connector_azure_security_center`
  - `azurerm_sentinel_data_connector_microsoft_cloud_app_security`
  - `azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection`
  - `azurerm_sentinel_data_connector_office_365`
  - `azurerm_sentinel_data_connector_threat_intelligence`

Each resource should be free and do not have any cost components, but it should reference `log_analytics_workspace_id` to support [reverse references](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md#reverse-references).

Here's an example how it can look like:

```go
func (r *SentinelDataConnectorAwsCloudTrail) BuildResource() *schema.Resource {
	return &schema.Resource{
		Name:        r.Address,
		IsSkipped:   true,
		NoPrice:     true,
		UsageSchema: SentinelDataConnectorAwsCloudTrailUsageSchema,
	}
}
```

2. Update `log_analytics_workspace` resource:
  - Add reverse references for the data connector resources.
  - Having at least one data connector means that the Sentinel is enabled.
  - If Sentinel is enabled add the following cost component:
    - Name: `Sentinel data ingestion`
    - Unit: `GB`
    - Mimic Log Analytics Workspace's logic for `Log data ingestion` cost component:
      - if sku is `PerGB2018` - use Pay-as-You-Go pricing
      - if sku is `CapacityReservation` and usage param is > 0 - use tiered pricing
    - Usage key: `monthly_sentinel_data_ingestion_gb`

More details on pricing:
- Pricing page: https://azure.microsoft.com/en-us/pricing/details/monitor/
- Billing: https://docs.microsoft.com/en-us/azure/sentinel/billing
- How to reduce costs: https://docs.microsoft.com/en-us/azure/sentinel/billing-reduce-costs#set-or-change-pricing-tier
- Enable data connectors: https://docs.microsoft.com/en-us/azure/sentinel/connect-data-sources
- Pricing calculator: https://azure.com/e/8a92a412178147b081d19c771f43fca8
- Discussion in [this PR comment](https://github.com/infracost/infracost/pull/886#discussion_r679384833)

**Comment by praveenghuge** [comment]
hey @alikhajeh1 I would like to work on this

**Comment by alikhajeh1** [comment]
🎉 Thanks @praveenghuge!

**Comment by alikhajeh1** [comment]
@praveenghuge thanks for helping so far! For now, I've unassigned this issue and moved it back in the Todo list in case someone else wants to work on it.

**Comment by vdmgolub** [comment]
Hi @acald-creator! 👋 Thank you! I've assigned the issue to you. We'll add cost components soon 👍

**Comment by vdmgolub** [comment]
@acald-creator Hey! Sorry for the delay with details, as the old issue description mentioned, the Sentinel pricing is weird :) I've updated the description, so it should be good to go. You may discover more details along the way, so if you see that the description is not 100% accurate, that's okay to adjust. Feel free to contact us here or in Slack. Together we'll make it work! 💪

**Comment by acald-creator** [comment]
@vdmgolub Thank you! Sorry for the delay but I will work on it and ask in Slack if I have any questions.

**Comment by acald-creator** [comment]
Friendly bump, I'm nearly done, I may have a PR by end of week.

**Comment by vdmgolub** [comment]
Awesome! Thanks for the heads up! Hope it is not too complex :)

**Comment by vdmgolub** [comment]
This is merged to master and will go out with the next release.

**Comment by hugorut** [comment]
Thanks @acald-creator for your contribution 🚀 . This is now live in the v0.9.24 release
