### ISSUE TITLE
Add support for Azure Active Directory Domain Services

### ISSUE THREAD

**Issue by Theragus** [infracost/infracost#898]
Terraform Resource:

```terraform 
azurerm_active_directory_domain_service
```

Pricing Information:

https://azure.microsoft.com/en-us/pricing/details/active-directory-ds/

Different prizes for directory size

**Comment by kevinkengne** [comment]
Hi :wave:, may I start working on this issue?

**Comment by alikhajeh1** [comment]
Sure! @tim775 if you get the chance, it might be nice to add details of the cost components to this.

**Comment by tim775** [comment]
Looks like this should be fairly straightforward: 
For `azurerm_active_directory_domain_service` we'll need a line item for `Active directory domain service (<type>)` with unit `hours` where <type> is one of 'standard', 'enterprise', or 'premium' and is determined by the `sku` argument.

`azurerm_active_directory_domain_service_replica_set` should have an identical line item where type is determined by the `sku` argument of the referenced `azurerm_active_directory_domain_service`.

**Comment by kevinkengne** [comment]
Thanks for the description. In the sentence for the first resource "where is one of 'standard', 'enterprise', or 'premium'", after where did the word you mean to write is type? That's my intuition but I'm not 100% sure

**Comment by tim775** [comment]
> Thanks for the description. In the sentence for the first resource "where is one of 'standard', 'enterprise', or 'premium'", after "where" is the word you meant to write "type"? That's my intuition but I'm not 100% sure

Your intuition was correct, I've corrected it.

**Comment by kevinkengne** [comment]
Thanks, I've raised a PR for the `azurerm_active_directory_domain_service` to get some early feedback. I have a question concerning the `azurerm_active_directory_domain_service_replica_set` resource: basically since it will reference a `azurerm_active_directory_domain_service`, how do I make sure that a file containing both resources only takes into consideration one of them when calculating the price?

Example:

```
resource "azurerm_active_directory_domain_service" "example" {
  name                = "example-aadds_3"
  location            = "australiaeast"
  resource_group_name = "aadds-rg"

  domain_name           = "widgetslogin.net"
  sku                   = "Premium"
  filtered_sync_enabled = false

  initial_replica_set {
    subnet_id = azurerm_subnet.deploy.id
  }
}

resource "azurerm_active_directory_domain_service_replica_set" "replica" {
  domain_service_id = azurerm_active_directory_domain_service.example.id
  location          = "australiaeast"
  subnet_id         = azurerm_subnet.deploy.id
}
```

Here the `replica` resource references the `example` resource. I'd assume the expected calculation should total to the price of one resource and not both. 

**Actual calculation:**

```

 Name                                                         Monthly Qty  Unit   Monthly Cost 
                                                                                               
 azurerm_active_directory_domain_service.example                                               
 └─ Active directory domain service (Premium)                         730  hours     $1,168.00 
                                                                                               
 azurerm_active_directory_domain_service_replica_set.replica                                   
 └─ Active directory domain service replica set (Premium)             730  hours     $1,168.00 
                                                                                               
 OVERALL TOTAL                                                                       $2,336.00 
```

**Expected calculation (In my opinion):**

```
 azurerm_active_directory_domain_service_replica_set.replica                                   
 └─ Active directory domain service replica set (Premium)             730  hours     $1,168.00 
                                                                                               
 OVERALL TOTAL                                                                       $1,168.00 
```

**Comment by tim775** [comment]
> Here the replica resource references the example resource. I'd assume the expected calculation should total to the price of one resource and not both.

My reading of the TF docs was a little different:  I was thinking that since `azurerm_active_directory_domain_service` requires an `initial_replicate_set_id` that would count as the first set and be charged.  Each `azurerm_active_directory_domain_service_replica_set` would be an additional set and also be charged.

Like I said though, that's just from reading TF and I don't actual experience with this service.

@Theragus Do you know how the pricing for replica sets works?

**Comment by Theragus** [comment]
Hi,

I already had some interaction with HashiCorp and MS on this resource type.
The pricing for AAD Domain Services is the rate for the SKU (Standard, Enterprise, or Premium) multiplied by the number of replica sets.
So @tim775 assumption on this one is correct.

SKU x Number of replica sets = Charged Price (see also here https://docs.microsoft.com/en-us/azure/active-directory-domain-services/concepts-replica-sets#deployment-considerations)

The first Replica Set is always created when creating the AAD Domain Services and is charged by default. So we only need to take into account replica set billing when we have more than 1 replica set. With only one replica set it is basically included in the ` azurerm_active_directory_domain_service resource ` resource. There was already some confusion on the replica sets in another issue i opened with HC -> https://github.com/hashicorp/terraform-provider-azurerm/issues/12728

Side Note: Azure AD Domain Services have the added constriction that only one can be deployed per tenant.

**Comment by tim775** [comment]
@kevinkengne @Theragus Thanks for your help!  We pushed this out today in 0.9.6.
