### ISSUE TITLE
Enable running infracost against a terraform.tfstate file

### ISSUE THREAD

**Issue by digitalronin** [infracost/infracost#90]
To get costs of an existing infrastructure setup, we need to run something like:

```
terraform init
infracost --tfdir .
```

So infracost does a terraform plan internally, and then uses the output of that to generate a report. Alternatively, we can do the `terraform plan` manually, and then supply the output to infracost.

Either way is quite slow.

All of the information required to report on existing infrastructure will be in the `terraform.tfstate` JSON file for the project, so if it were possible to run something like:

```
infracost --terraform-statefile=/path/to/my/project/terraform.tfstate
```

This could enable cost reports to be generated much more quickly - I'd guess a few seconds rather than several minutes, since it shouldn't be necessary to run `terraform init` beforehand either.

For many use-cases, this may not be an issue, but in my particular case, with 200+ terraform projects to analyse, it makes a big difference, and I imagine some others will be in a similar situation.

**Comment by ctrlaltdev** [comment]
Bump for that issue - I'm using TerraGrunt and split my infra in a lot of modules and the work around needed are quite painful. Using the tfstate would really help.

**Comment by enribd** [comment]
It could be nice if I could use a set of tfstates instead of just one. Maybe read them from cloud object storages like S3 buckets.

**Comment by aliscott** [comment]
#203 adds a `--use-tfstate` flag, which might solve this use case.

So in master you can run it with
```
# if running dev:
make run ARGS="--tfdir=/path/to/code --use-tfstate"

# if running binary:
infracost --tfdir=/path/to/code --use-tfstate
```

This still needs the `terraform` binary to run `terraform show` internally instead of directly reading the state file, which is the recommended way of interacting with the state (https://www.terraform.io/docs/state/index.html#format) and has the added benefit of working with both local and remote states.

From my testing, this is a lot faster than running `terraform plan` each time 😄 

Let me know if this helps.

**Comment by ayr-ton** [comment]
I've created a new related issue here:

https://gitlab.com/infracost/infracost-gitlab-ci/-/issues/1

**Comment by alikhajeh1** [comment]
@ctrlaltdev / @enribd can you possibly try v0.7.2 (available on brew too), and see if the `infracost --tfdir=/path/to/code --use-tfstate` option is good enough to close this issue? It works with remote state. I haven't used TerraGrunt much so it would be great if you can create issues with any difficulties you hit with that.

**Comment by ctrlaltdev** [comment]
@alikhajeh1 It works fine!
Just used on a couple of modules and I get a nice output back!

Regarding terragrunt, I'll open an issue for that.

**Comment by alikhajeh1** [comment]
@ctrlaltdev thanks for creating https://github.com/infracost/infracost/issues/224, given the interest in that, I've put it at the top of the todo pile in https://github.com/infracost/infracost/projects/2

Closing this issue, new issues can be created for leftovers.
