### ISSUE TITLE
Add Support for Azure VPN Gateway S2S Connections

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#906]
This is a follow up for #887.

azurerm_virtual_network_gateway_connection

Pricing Information:

https://azure.microsoft.com/en-us/pricing/details/vpn-gateway/

VPN Gateway has an hourly charge for S2S Tunnels over some limit.  In TF these are represented as azurerm_virtual_network_gateway_connection with type "IPsec".  We can add a usage charge `VPN gateway S2S tunnel (<type>)` with unit `hours` where `<type>` is determined from the sku of the associated `azurerm_virtual_network_gateway`.

**Comment by praveenghuge** [comment]
Hi Tim, will work on this 🙂

**Comment by tim775** [comment]
Thanks!

**Comment by praveenghuge** [comment]
https://github.com/infracost/infracost/pull/908

**Comment by alikhajeh1** [comment]
Can this be closed?

**Comment by tim775** [comment]
Yes this was fixed by #908.  Thanks @praveenghuge!
