### ISSUE TITLE
Missing Azure Storage Accounts, SQL Databases and Bastion Hosts

### ISSUE THREAD

**Issue by tiernano** [infracost/infracost#925]
Opening this as a tracking item, and i might chance my arm at trying to fix this as a learning excersize, but when i ran Infracost on my Azure Terraform scripts, i got messages that the following were missing:

* azurerm_storage_account
* azurerm_bastion_host
* azurerm_sql_database

There were a couple of other ones, but i think that 1: the ones above are more important, and 2, most of the others are either Free or cheap enough...

**Comment by alikhajeh1** [comment]
@tiernano thanks for creating this issue! 

1. `azurerm_storage_account`: Infracost [only supports](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/storage_account.go#L32-L35) BlockBlobStorage and FileStorage just now, can you please provide details of the TF resource block so we can see which storage type is needed?

2. `azurerm_bastion_host`: do you know how we could determine if the resource is "Azure Bastion" or "Azure Bastion Standard"? Could the `azurerm_bastion_host.public_ip_address_id.sku` (Basic vs Standard) be used to tell that? It doesn't look like that as the [Bastion service supports the SKU directly](https://docs.microsoft.com/en-us/azure/bastion/upgrade-sku) but TF doesn't seem to support that?

3. `azurerm_sql_database`: we added `azurerm_mssql_database` add TF says [`azurerm_sql_database` is deprecated](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database). Do you know if the pricing is the same? If so, the new resource could be added fairly easily by reusing the same logic.

For free resources, you can send a quick PR to add them [here](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/registry.go#L93) :)

**Comment by tiernano** [comment]
1: looks like the storage accounts we are creating are just the accounts without any of the "containers" so thats probably why they got skipped... I may have missed something here...
2: The bastion host we are using is standard "Azure Bastion". The newer "standard" sku is still in preview, so we havent played with that just yet..
3: Whoops... I missed that message on the portal... Pricing should be the same... I will tweak my scripts and swap to azurerm_mssql_database and see what happens.

Thanks. And i will try my hand at a PR in the next few days!

--Tiernan

**Comment by alikhajeh1** [comment]
1. what is the `account_kind` of those `azurerm_storage_account` terraform resources?
2. Great, I added https://github.com/infracost/infracost/issues/939 to track that.
3. awesome - let us know if that works ok.

Once I know the answer to #1, I'll create a new issue and close this one.

**Comment by tiernano** [comment]
1: looks like if you dont enter anything by default, it uses StorageV2 as the account type... and account_tier is set to "Standard"
2: cool. thanks.
3: yea, changed from azurerm_sql_XXX to azurerm_mssql_XXX and that gives proper info now.

Thanks again.

--Tiernan

**Comment by alikhajeh1** [comment]
1. thanks for checking, plz subscribe/upvote https://github.com/infracost/infracost/issues/951 for updates

Closing this issue
