### ISSUE TITLE
Apply `--sync-usage` results to current run of Infracost

### ISSUE THREAD

**Issue by xeger** [infracost/infracost#928]
When I ask Infracost to sync usage, it writes a fresh usage file but does not apply the usage to the `breakdown` or `diff` command that I am running. In order to see the fresh usage-based costs, I need to run the tool again so it will use the latest YML file.

Instead, I would like it to retain the fresh usage in memory and use it immediately, giving me instant feedback on the cost associated with my synced usage.

One solution is to ask the provider to load the resources a second time after syncing usage:

```
		if runCtx.Config.SyncUsageFile {
			err = usage.SyncUsageData(project, u, projectCfg.UsageFile)
			if err != nil {
				return err
			}
			// BEGIN NEW CODE - applies fresh usage to project
			err = provider.LoadResources(project, u)
			if err != nil {
				return err
			}	
			// END NEW CODE
		}
```

There might be a more elegant solution that takes less time, but this would be a good start. (If I am asking for `--sync-usage` then presumably I don't mind waiting a moment to see the fresh output.)

**Comment by aliscott** [comment]
@xeger can this please closed now?
