### ISSUE TITLE
Add support for Azure Bastion

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#939]
Terraform resource: [`azurerm_bastion_host`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host)
Pricing page: https://azure.microsoft.com/en-us/pricing/details/azure-bastion/
Whilst Azure allows upgrades [via their UI/CLI](https://docs.microsoft.com/en-us/azure/bastion/upgrade-sku), Terraform only supports "Azure Bastion", not "Azure Bastion Standard".

Cost components:
- "Bastion instance", units "hours"
- "Outbound data transfer", tiered using the `CalculateTierBuckets` method we use elsewhere, ignore the free tier, use the following usage file param. If no usage param is defined, show "first 10TB", otherwise show applicable tiers. Hard-code the region-to-zone map in `internal/providers/terraform/azure/util.go` and use the `location` Terraform param to find the zone.
  - `monthly_outbound_data_gb: 100          # Monthly data transferred out in GB.`

### Note for community:
Please 👍 if you'd like to upvote this or receive updates.

**Comment by kevinkengne** [comment]
👋  
may I start working on this issue?

**Comment by alikhajeh1** [comment]
sure! - thanks @kevinkengne

**Comment by tim775** [comment]
@tiernano just a heads up that this will go out in the next release.

**Comment by tiernano** [comment]
Cool. Thanks. I will check it out when the next release is out.

--Tiernan
