### ISSUE TITLE
Customise AWS EBS snapshot "Fast snapshot restore"

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#940]
It does not look like we can detect "Fast snapshot restore" from the [Terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_snapshot). Reading the [AWS pricing page](https://aws.amazon.com/ebs/pricing/) > "EBS Fast Snapshot Restore" example, I think we should hide that cost component by default and instead add a "fast_snapshot_restore_hours: 2 # Number of monthly hours when Fast Snapshot Restore is enabled" usage file param for it. The units should also be updated to "DSU-hours".

```
 aws_ebs_snapshot.gp2                                                                                                  
 ├─ EBS snapshot storage                                                  10  GB                                 $0.50 
 ├─ Fast snapshot restore                                                  1  DSU                              $547.50 
 ├─ ListChangedBlocks & ListSnapshotBlocks API requests  Monthly cost depends on usage: $0.0006 per 1k requests        
 ├─ GetSnapshotBlock API requests                        Monthly cost depends on usage: $0.003 per 1k SnapshotAPIUnits 
 └─ PutSnapshotBlock API requests                        Monthly cost depends on usage: $0.006 per 1k SnapshotAPIUnits 
```

### Notes for community
Please 👍 if you'd like to upvote this or receive updates.
Read the [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) if you'd like to work on this issue - we're happy to help you!

**Comment by saltperfect** [comment]
I would like to work on this issue.

> Read the contributing guide if you'd like to work on this issue - we're happy to help you!

Going through it.

**Comment by saltperfect** [comment]
I am trying to replicate the issue by changing the /examples/terraform/main.tf
```tf
resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"
  size              = 40

  tags = {
    Name = "HelloWorld"
  }
}

resource "aws_ebs_snapshot" "example_snapshot" {
  volume_id = aws_ebs_volume.example.id

  tags = {
    Name = "HelloWorld_snap"
  }
}
```
and running 
```bash
make run ARGS="breakdown --path examples/terraform --usage-file=examples/terraform/infracost-usage.yml"
```

I am getting region not set by terraform
```
Detected Terraform directory at examples/terraform
  ✖ Running terraform plan 

  Terraform command failed with:  Error: Missing required argument  The argument "region" is required, but was not set.

Error: Error running terraform plan: exit status 1
exit status 1
make: *** [Makefile:19: run] Error 1
```

Any inputs as to where I can set aws region. I checked in /examples/terraform/plan.json and can see aws region entry present there.

**Comment by alikhajeh1** [comment]
@saltperfect thanks! Try the following main.tf file:

```
provider "aws" {
  region                      = "us-west-2" # <<<<< Here's where you can set the region
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"
  size              = 40

  tags = {
    Name = "HelloWorld"
  }
}

resource "aws_ebs_snapshot" "example_snapshot" {
  volume_id = aws_ebs_volume.example.id

  tags = {
    Name = "HelloWorld_snap"
  }
}
```

**Comment by saltperfect** [comment]
Got it!! Thanks.
