### ISSUE TITLE
Add support for Azure Standard (GPv2) storage 

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#951]
Terraform resource: [azurerm_storage_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account) (which we already support but not fully). This GH issue is to add the default "StorageV2" as the account_kind ("Standard" as the account_tier, but there's also Premium) 
Pricing page: https://azure.microsoft.com/en-us/pricing/details/storage/blobs/ 

Other resources to check as part of this issue:
`azurerm_storage_account_network_rules`

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
See our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) if you'd like to help with this issue!

**Comment by tim775** [comment]
@tiernano, @ealdaon, @Theragus, @PatMyron, @dsfrederic:  This has been released in v0.9.14.  Thanks @vdmgolub!
