### ISSUE TITLE
BUG - `infracost diff` showing prices for data objects

### ISSUE THREAD

**Issue by nomeelnoj** [infracost/infracost#960]
Hey Infracost Team!

Recently upgraded to 0.9.6 (tested with 0.9.7 and the same issue is present) and when running `infracost diff` with `data` objects for EC2 instances, infracost shows the price difference as if the instances are getting destroyed.

Here is some example code and output:

```
# example.tf
locals {
  instances = [
    "instance-1",
    "instance-2",
    "instance-3",
    "instance-4",
    "instance-5",
    "instance-6"
  ]
}

data "aws_instance" "default" {
  for_each = toset(local.instances)
  filter {
    name   = "tag:Name"
    values = [each.value]
  }
}

resource "aws_lb_target_group_attachment" "default" {
  for_each         = toset(local.instances)
  target_group_arn = "<my-target-group-arn>"
  target_id        = data.aws_instance.instance[each.key].id
  port             = 80
}
```
Based on the code above, I would expect to see a cost of 0, which is what I get when i run `infracost breakdown`.  However, when I run `infracost diff`, I get Infracost telling me that my costs are going to decrease by thousands of dollars per month based on the costs of these instances:
```

╰─ infracost diff --path .
Detected Terraform directory at .
  ✔ Running terraform plan
  ✔ Running terraform show

✔ Calculating monthly cost estimate

Project: infracost-data-bug

- data.aws_instance.default["instance-1"]
  -$295

    - Instance usage (Linux/UNIX, on-demand, c4.2xlarge)
      -$291

    - EBS-optimized usage
      $0.00

    - root_block_device

        - Storage (magnetic)
          -$4.80

        - I/O requests
          Monthly cost depends on usage
            -$0.05 per 1M request

- data.aws_instance.default["instance-2"]
  -$300

    - Instance usage (Linux/UNIX, on-demand, c4.2xlarge)
      -$291

    - root_block_device

        - Storage (general purpose SSD, gp2)
          -$9.60

- data.aws_instance.default["instance-3"]
  -$347

    - Instance usage (Linux/UNIX, on-demand, c4.2xlarge)
      -$291

    - EBS-optimized usage
      $0.00

    - root_block_device

        - Storage (general purpose SSD, gp2)
          -$6.40

    - ebs_block_device[0]

        - Storage (general purpose SSD, gp2)
          -$50.00

- data.aws_instance.default["instance-4"]
  -$833

    - Instance usage (Linux/UNIX, on-demand, r4.4xlarge)
      -$777

    - root_block_device

        - Storage (general purpose SSD, gp2)
          -$6.40

    - ebs_block_device[0]

        - Storage (general purpose SSD, gp2)
          -$50.00

- data.aws_instance.default["instance-5"]
  -$347

    - Instance usage (Linux/UNIX, on-demand, c4.2xlarge)
      -$291

    - EBS-optimized usage
      $0.00

    - root_block_device

        - Storage (general purpose SSD, gp2)
          -$6.40

    - ebs_block_device[0]

        - Storage (general purpose SSD, gp2)
          -$50.00

- data.aws_instance.default["instance-6"]
  -$637

    - Instance usage (Linux/UNIX, on-demand, c4.4xlarge)
      -$581

    - EBS-optimized usage
      $0.00

    - root_block_device

        - Storage (general purpose SSD, gp2)
          -$6.40

    - ebs_block_device[0]

        - Storage (general purpose SSD, gp2)
          -$50.00

Monthly cost change for infracost-data-bug
Amount:  -$2,760 ($2,760 -> $0.00)

----------------------------------
Key: ~ changed, + added, - removed

To estimate usage-based resources use --usage-file, see https://infracost.io/usage-file
```

Not sure how to go about debugging this any further, but hoping we can get a release soon that helps with this.  We have a lot of existing infrastructure that we are slowly getting into terraform, so we often use data blocks to look up many of our resources (normal for terraform usage) and having these costs incorrectly shown is turning a lot of heads incorrectly.

Thanks in advance for your help!

**Comment by aliscott** [comment]
Thanks @nomeelnoj. These details should help me track down the issue, but will update here if we need anything else.

**Comment by aliscott** [comment]
I think the bug must be in the [stripDataResources](https://github.com/infracost/infracost/blob/c510e169e99599a26ecac54a2a524ddd712ca0db/internal/providers/terraform/parser.go#L318-L324) function, probably in `addressResourcePart`.

I'm unable to reproduce this so far with your example. I launched some instances in our test AWS account to try it. Will keep digging in further. Is your Terraform code structured in modules?

**Comment by aliscott** [comment]
I've found an issue for resources that have a `.` in the index part, e.g. `aws_instance.my_instance["index.1"]` and added a fix in https://github.com/infracost/infracost/pull/968.

**Comment by nomeelnoj** [comment]
@aliscott yes, these instances have a `.` in the name.  Interesting bug, nice find!

**Comment by nomeelnoj** [comment]
Wonderful! Thanks so much!

**Comment by alikhajeh1** [comment]
@nomeelnoj just FYI that Infracost CLI v0.9.8 has been released and has a fix in it - plz let us know if that helps. Thanks for the awesome level of details in the GH issue.
