### ISSUE TITLE
Support for BitBucket Server/DataCenter PRs and how to handle other notification channels

### ISSUE THREAD

**Issue by sbibow** [infracost/infracost#962]
# Where I am coming from

The organization I am working with (or for 🤷‍♂️) uses BitBucket Server as a code repository and Jenkins as their CI and CD system.

I was trying to integrate infracost into this setup. Unfortunately the current CI scripts are not much help:

- jenkins_diff.sh
  This script creates an HTML file that can be uploaded via the publishHTML plugin (See https://github.com/infracost/jenkins-demo/blob/master/Jenkinsfile) and it optionally posts a message to slack (https://github.com/infracost/infracost/blob/v0.9.7/scripts/ci/jenkins_diff.sh#L123)
- diff.sh
  It does support posting to BitBucket Cloud (not BitBucket Server nor BitBucket DataCenter) and it assumes that it was run in a BitBucket Pipeline. 
  In general the script is optimized to run from a build-system that is provided by the same product as the code repository (GitLabCI and GitLab, GitHub Actions and GitHub, BitBucket Pipelines and BitBucket)
  The only exception here are circle_ci and azure_devops who check how they were triggered (https://github.com/infracost/infracost/blob/v0.9.7/scripts/ci/diff.sh#L180 or https://github.com/infracost/infracost/blob/v0.9.7/scripts/ci/diff.sh#L216)

So, with that in mind, I created my own script to handle the combination of Jenkins and BitBucket Server. See https://gist.github.com/sbibow/8a6358945dbd189be45274b08c3fca0f

All in all, not too difficult to work with the BitBucket Server API; writing the whole thing was just a few hours.
The question is *why* did I create an issue for this? Well, that what is coming now:

# The bigger picture

The way the ci scripts are set up currently is not scalable. The Infracost CI scripts support 6 notification channels (1 Slack and 5 repositories) and is almost 380 lines long.

There needs to be a better way to integrate new notification channels. There are Git Repository systems that do not come with built-in CI (like Gerrit, Gitea, Gogs, ...) and there might also be a demand for Teams messages, Email notifications, etc. in the future.

I am certain that we need to have a discussion how we move forward with the CI scripts before we tackle #809, because the shell scripts would only get uglier.

# Options for the future

1. Have a new repository and put shell script in there
2. Have a new repository and write a real programming language (preferably with SDKs to the notification channels we want to support)
3. Keep the scripts in the current repository but separate them by notification channel
4. Do nothing

With the first two option there is going to be the problem of keeping the releases in sync (maybe that isn't a problem: #777).
The second option makes it easier to add and maintain existing channels, but the docker container to run infracost in CI will be even bigger.
The third option is just like the first one, without the release sync problem.
And the last option is just for the sake of completeness.

---

If you have any ideas or opinions, please leave a comment below :)

**Comment by alikhajeh1** [comment]
Thanks for sharing the details @sbibow! There's a lot to unpack and think about here. For https://github.com/infracost/infracost/issues/809, @tim775 is experimenting with the bash script for GitHub Actions.

I suppose another option for the future could be to configure the integrations/notifications in a dashboard so creds/settings don't need to be replicated to each CI/CD pipeline or repo for the org?

**Comment by sbibow** [comment]
I am a bit confused about which dashboard you mean.
Do you mean the Enterprise offering, the dashboard.api.infracost.io or something else entirely?

The need to persist the setting seems in my eyes like a non issue. Nice for convenience, but mostly irrelevant because most CI systems support some kind of templating (GitLab CI with the [include](https://docs.gitlab.com/ee/ci/yaml/#include) and [extends](https://docs.gitlab.com/ee/ci/yaml/#extends) keyword, Jenkins with [shared libraries](https://www.jenkins.io/doc/book/pipeline/shared-libraries/) or the [load function](https://www.jenkins.io/doc/pipeline/steps/workflow-cps/#load-evaluate-a-groovy-source-file-into-the-pipeline-script), GH Actions with [reusable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows), ...).
And most of the sensitive values come via environment variables anyway (which infracost cli and the ci scripts understand). If the same secret values should be used there are ways in most CI systems again: GitLab with groups that contain multiple projects, Jenkins with folders that contain multiple pipelines, etc.

I would rather image something in the direction of having a subcommand in the infracost cli that can be invoked:
```bash
infracost report <options>

# support for multiple notification channels
infracost report --channels=slack,gh \
  --slack-token=XXXXXXX --slack-channel=12345 \
  --github-project=infracost/cloud-pricing-api --github-token=XXXXX \
  --path=infracost_diff.json # eg. after running "infracost diff --path=. > infracost_diff.json"
```

That way you can add first-class support for all APIs. Configure them via infracost config, use SDKs for (some) notification channels.
The only downside that I see is the potential size increase and complexity added to the infracost cli. If that is a concern, a new project could be the answer, though then you would need to package it into the docker container for ci...

I would try to move away from BASH scripts because at a certain complexity they do not scale well (no type checking, no SDKs available, ...).

**Comment by alikhajeh1** [comment]
Yep, I meant https://dashboard.infracost.io (which for now only supports [Terraform Cloud Run Tasks](https://www.infracost.io/docs/iac_tools/terraform_cloud_enterprise#terraform-cloud-run-tasks)).

We did think about having notification channels and other CI/CD logic in the CLI but we kept them out for two reasons for now:
1. users have a variety of workflows and we're still learning/prototyping; many times users have taken the bash scripts and customized them to work with their workflows (or support new permutations, e.g. as you did for Jenkins/BB). Having that logic in bash makes it easy to prototype/customize without worrying about release versions and upstream CLI versions. But once the use-cases are matured, we should probably move to a non-bash-based approach as you say.
2. authentication, auditing and building visibility-features around the workflow might be simpler to do server-side.

None of this is baked in stone though! We're still experimenting/learning, some CI/CD-based products develop custom apps for the integrations, e.g. GitHub Apps (vs Actions) so that might be another approach.

**Comment by sbibow** [comment]
I am not a fan of using https://dashboard.infracost.io for something like that, unless there is a self-hosted version available. Trusting a third-party with API keys is often difficult in enterprises - mostly due to protection of Intellectual Property.

With your point in mind it makes sense to wait.
For now we should refactor the bash scripts because I find them difficult to work with. Maybe they could be sliced based on the notification channel and still have the diff.sh as central entry point, that glues it together.

**Comment by alikhajeh1** [comment]
@sbibow thanks for your input so far - it influenced the features we [shipped in November](https://www.infracost.io/blog/nov-2021-update/) 😄

We'd like to add support for [Bitbucket comments to Infracost](https://github.com/infracost/infracost/issues/1173), and update [Compost](https://github.com/infracost/compost) (our new open source project) to work with Bitbucket too. I suppose some next steps are, to investigate:
1. How can the Infracost CLI be installed in Jenkins using SemVer ranges? The idea being that every run checks and gets a backward-compatible CLI version (so users get new resources and bug fixes without worrying about breaking CI/CD pipelines). Is that even possible/desired with Jenkins? Would a Docker image (e.g. `infracost-v0.9`) help?
2. Once we have `infracost output --format bitbucket-comment` and compost supports Bitbucket, I think users can achieve the same [workflows](https://github.com/infracost/actions/#examples) as GitHub Actions enables?

**Comment by sbibow** [comment]
### Ad 1

There are basically two ways that **I** use to install tooling (just as a reminder: Jenkins can be (ab)used in soo many ways and there is no [universal standard](https://xkcd.com/927/)):
1. Download tools during a stage called "Prepare". Here I execute shell commands that downloads software and print out their version Eg:
   
   ```groovy
   [...]
   stage("Prepare") {
     environment {
       PATH = "${env.PATH}:bin"
     }
     steps {
       // Install terraform
       sh("curl -L -o terraform.zip
       https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip")
       sh("unzip terraform.zip")
       sh("mv terraform bin/")
       // Install Infracost
       sh("curl -sL https://github.com/infracost/infracost/releases/download/v0.9.14/infracost-linux-amd64.tar.gz | tar xz -C tmp")
       sh("mv tmp/infracost-linux-amd64 bin/infracost")

       sh("chmod +x bin/*")

       sh("terraform --version")
       sh("infracost --version")
     }
   }
   [...]
   ```
2. Using docker images. With this example there is no "Prepare" stage needed, as the tools are installed and available in the docker containers. Eg:
   ```groovy
   [...]
   stage("Cost Estimation") {
     agent {
       docker {
         image 'infracost/infracost:0.9'
         args  '--entrypoint=\'\''
       }
     }
     environment {
       INFRACOST_API_KEY = "MYAPIKEY"
       IAC_PATH          = "plan.json"
     }
     steps {
       // Unstash previously stashed terraform plan
       // was generated via `terraform show -json tf.plan > plan.json`
       unstash(name: "terraform-plan-json")
       sh("infracost breakdown --no-color --format json > infracost_breakdown.json")
       [...] // Do rest of the analysis and uploads to Jenkins, Code Repository, etc.
     }
   }
   [...]
   ```

As I see it for docker you are already updating the `0.9` tag to point to the latest version (currently `0.9.14`). It'd be great to have a similar functionality with option 1 that downloads the pre-compiled package from GitHub Releases. But I think there is no way to do it in GitHub and would require some weird workaround.

From an infracost perspective I do not see any action required here, because code example 2 works already that way and in code example 1 no other tool has yet come up with a way to standardize the backwards-compatible updates; so why should you?


### Next steps

Yes, We should close this issue. It was pretty broad and seems to be "fixed" with the release of compost, that now formalizes the APIs and creates an abstraction between build tool and VCS.

Concretely I see also the action that you have outlined in your point 2:

- Add output format `bitbucket-comment` to infracost cli
- Add support for BitBucket in compost

If you need help with testing (or some minor implementations), feel free to reach out 😊

**Comment by alikhajeh1** [comment]
XKCD 🤣 
Thanks! Feel free to subscribe to https://github.com/infracost/infracost/issues/1173 for updates as it includes both of those action items. Helping with testing would be greatly appreciated - I'm not sure when we'll get to this but CI/CD integrations are important for us so probably not too far

**Comment by alikhajeh1** [comment]
@sbibow I just wanted to circle back and thank you for the feedback+discussion here. This issue plus other feedback and earlier prototypes with [Compost](https://github.com/infracost/compost) lead us to create [`infracost comment`](https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests).

That new command can be used to post comments to GitHub, GitLab, Azure Repos and Bitbucket, and can be used in any CI/CD system. We're going to migrate our existing CI/CD integrations to use that command too and have added examples of how that can be used with various CI/CD system env vars (e.g. an example of which CircleCI env vars, such as the PR number, that are needed to post a comment). Our hope is that this enables any CI/CD system to be supported with those 4 main version control systems.

Keep the feedback coming 🙇
