### ISSUE TITLE
Terraform v0.13 - resources in nested child modules always show in diff

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#969]
I can only reproduce this in Terraform v0.13.X.

When a resource exists in a nested child module, e.g. `module.my_module.module.my_submodule.aws_instance.my_instance`, `infracost diff` will always show that resource as being created.

**Comment by aliscott** [comment]
Looks like this is fixed in Terraform in https://github.com/hashicorp/terraform/pull/27352.

I've submitted a backport PR in the here: https://github.com/hashicorp/terraform/pull/29626.

**Comment by alikhajeh1** [comment]
We should probably close this issue as Terraform are basically asking users to upgrade if they want a fix. Agreed?

**Comment by alikhajeh1** [comment]
Going to keep this open for a few more months in case users search for it.
