### ISSUE TITLE
Crash: slice bounds out of range [:2] with length 0 in NewAzureRMAppServiceCustomHostnameBinding (Infracost v0.9.8)

### ISSUE THREAD

**Issue by jnobile** [infracost/infracost#982]
Detected Terraform directory at .
  ✔ Running terraform plan
  ✔ Running terraform show

Error: An unexpected error occurred

runtime error: slice bounds out of range [:2] with length 0
goroutine 1 [running]:
runtime/debug.Stack(0x40e078, 0xa8, 0x1315a40)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc0001e3380, 0x11494a0, 0xc00011c3a8)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:180 +0x45
main.main.func1(0xc0000d9f48, 0xc0001e3380, 0xc00009e120)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:42 +0xa5
panic(0x11494a0, 0xc00011c3a8)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/providers/terraform/azure.NewAzureRMAppServiceCustomHostnameBinding(0xc0003807e0, 0x0, 0xc00046a584)
        /home/runner/work/infracost/infracost/internal/providers/terraform/azure/app_service_custom_hostname_binding.go:40 +0xa5e
github.com/infracost/infracost/internal/providers/terraform.(*Parser).createResource(0xc0000d9678, 0xc0003807e0, 0x0, 0x0)
        /home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:68 +0x166
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSONResources(0xc0000d9678, 0x84901, 0x1bbca20, 0x0, 0x0, 0xc000274f60, 0x5, 0xc000400000, 0x8497f, 0x0, ...)
        /home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:123 +0x4dd
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSON(0xc0000d9678, 0xc000690000, 0x8497f, 0xf8000, 0xc000274f60, 0x0, 0x0, 0xc0000d9600, 0x40e078, 0x30, ...)
        /home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:145 +0x79f
github.com/infracost/infracost/internal/providers/terraform.(*DirProvider).LoadResources(0xc0000f83c0, 0xc000274f60, 0xc0000d9900, 0xc000274f60, 0x0, 0x0, 0x0)
        /home/runner/work/infracost/infracost/internal/providers/terraform/dir_provider.go:153 +0x2d6
main.runMain(0xc00028c780, 0xc0001e3380, 0xc000249900, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/run.go:92 +0x528
main.breakdownCmd.func1(0xc00028c780, 0xc000294160, 0x0, 0x1, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:41 +0x1c5
github.com/spf13/cobra.(*Command).execute(0xc00028c780, 0xc000294150, 0x1, 0x1, 0xc00028c780, 0xc000294150)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025d680, 0xc00025d680, 0xc0001e3380, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:55 +0x105

Environment:
Infracost v0.9.8

Please copy the above output and create a new issue at https://github.com/infracost/infracost/issues/new

Here's one of the bindings which is missing expected `ssl_state`:

```
{
    "address": "module.service_name_test_app.azurerm_app_service_custom_hostname_binding.app_service",
    "mode": "managed",
    "type": "azurerm_app_service_custom_hostname_binding",
    "name": "app_service",
    "provider_name": "registry.terraform.io/hashicorp/azurerm",
    "schema_version": 0,
    "values": {
        "app_service-name": "fltest-service-name-wus2-app",
        "hostname": "test.service-name.example.com",
        "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/sites/fltest-service-name-wus2-app/hostNameBindings/test.service-name.example.com",
        "resource_group_name": "<redacted>",
        "ssl_state": "",
        "thumbprint": "",
        "timeouts": null,
        "virtual_ip": ""
    },
    "sensitive_values": {}
}
```

**Comment by tim775** [comment]
@jnobile Thanks for the report!  It looks like since ssl_state is empty this resource should have no charge.  Is that right?

**Comment by jnobile** [comment]
@tim775 *probably*? Though the resource is in an error state due to external reasons, so it is unclear what the cost should be anyway. 

I mostly opened this case because it shouldn't have crashed the app.

**Comment by alikhajeh1** [comment]
@jnobile thanks for reporting it, the fix has been merged and will be released in the next version (probably early next week).

What do you think about how [CodeCov prevents CI failures](https://github.com/codecov/codecov-bash#prevent-build-failures)? would you use that or do you prefer to know about issues so you can report them and we can fix them?

**Comment by jnobile** [comment]
If the team is proactive fixing bugs like in this case (*thanks!!*), then I prefer the tool crash right away, so errors don't propagate.

**Comment by alikhajeh1** [comment]
@jnobile thanks - that makes sense.
