### ISSUE TITLE
Adding diff functionality to JSON output

### ISSUE THREAD

**Issue by m-yosefpor** [infracost/infracost#99]
### Current aim
The aim of this ticket is to update the Infracost JSON output so it includes the following fields, which can then be used in the future to build table/HTML outputs that show the diff of what's about to be applied.

```
existingState:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

plannedState:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

diff:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

timeGenerated
resourceSummary
``` 

### Original ticket description

Options to support:
- tfplan
- tfjson
- tfdirs
- tfstate (after #90)

So it would be 4*4=16 possible combinations to invoke it.

User can invoke it like
```
infracost diff --tfdir first/path --tfdir second/path
infracost diff --tfdir first/path --tfplan second/plan
...
```

So the flag presence order would be important. What other kind of implementations would work better??

**Comment by alikhajeh1** [comment]
Another option is for infracost to use the output from the `terraform apply` as the diff of the infrastructure about to be created, and show the cost for that. I haven't thought much about the implications of this yet, Atlantis's [Checkout Strategy](https://www.runatlantis.io/docs/checkout-strategy.html#merge) might be relevant to consider.

**Comment by sinabakh** [comment]
I was thinking about working on it, but did not get a general idea and what is needed. Could you please elaborate more?

**Comment by aliscott** [comment]
Notes from discussion

Update JSON output to have the following top level fields:
- existing_resources
- planned_resources
- resource_changes

All these keys have the same field structure as our existing `resources` field.

Cases to think about:
1. Cost component doesn't change -> existingMonthlyCost == plannedMonthlyCost
2. Existing cost component does change, e.g. instance type is changed.
3. New cost component gets added to existing resource
4. Cost component gets removed from existing resource
5. New resource is added
6. Resource gets removed
7. If only the state is used (--use-tfstate)

**Comment by sinabakh** [comment]
For starters, I will try to change the JSON output and then add the original functionality in a separate MR.
@aliscott Are we ok with these fields names? Or it needs more investigation?

**Comment by aliscott** [comment]
As a reference:

Terraform uses:
```
prior_state (when it's a plan file) / values (when it's a state file)
planned_values
resource_changes
```

Pulumi uses:
```
oldState
newState
detailedDiff
```

Options:

Currently I'm thinking this hierarchy:

```
existingState:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

plannedState:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

diff:
  resources:
    ...
  totalHourlyCost
  totalMonthlyCost

timeGenerated
resourceSummary
```

@sinabakh @alikhajeh1 any thoughts?

**Comment by alikhajeh1** [comment]
@aliscott +1 on those names

**Comment by sinabakh** [comment]
It looks good to me, will start working on it.

**Comment by alikhajeh1** [comment]
@sinabakh it would be good to have the current top-level JSON keys in the JSON file for the next release `0.7.17`, and ensure that `infracost report` still continues to work (terragrunt users rely on that, I can help you test that if needed), then in `0.8.0` we'll remove the old keys and put in the usual "breaking change" release note.

**Comment by sinabakh** [comment]
@alikhajeh1 So if I understand correctly, we will first add new keys alongside the current ones and then will remove the current ones right? I just started working on this task, thanks for heads up.

**Comment by alikhajeh1** [comment]
@sinabakh correct! Users might appreciate the heads-up and have a little more time to switch.
