### ISSUE TITLE
Debug logs should show free resources

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#993]
I was debugging a user issue who asked about why they're not seeing costs for `azurerm_key_vault` as they had seen these logs:
```
time="2021-09-30T13:40:51+01:00" level=debug msg="Falling back to default region (eastus) for azurerm_key_vault"
time="2021-09-30T13:40:51+01:00" level=debug msg="Falling back to default region (eastus) for azurerm_key_vault_access_policy"
time="2021-09-30T13:40:51+01:00" level=debug msg="Falling back to default region (eastus) for azurerm_key_vault_access_policy"
```

It took me a while to figure out that `azurerm_key_vault_certificate`, `azurerm_key_vault_key` and `azurerm_key_vault_managed_hardware_security_module` are paid resources but we've marked `azurerm_key_vault` as a free resource.

I think `--log-level=debug` or maybe even `info`, should output the free resource types that were skipped so users can debug such issues themselves. Having to search for them in https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/registry.go#L94 isn't ideal.

**Comment by amoghrajesh** [comment]
@alikhajeh1 I don't completely understand the purpose of this issue, could the aim be made a little more clearer? Is this repository a part of Hactoberfest 2021? If yes, I would like to learn more about this issue and help to fix it.

**Comment by tim775** [comment]
@alikhajeh1 @sbalajisivaram this will go out with the next release!
